### ISSUE TITLE
Popup Window Invisible with Vulkan Beta

### ISSUE THREAD

**Issue by Reithan** [SnosMe/awakened-poe-trade#100]
As title says, if you Ctrl+D on an item with the new Vulkan beta renderer enabled, the popup window is invisible until you mouse over it.

**Comment by Reithan** [comment]
FYI, it also isn't a problem in actual windowed mode - just fullscreen windowed.

**Comment by eris667** [comment]
Thank you @Reithan windowed mode (vs my default fullscreen windowed mode) fixed the problem for me in the interim

**Comment by SnosMe** [comment]
This bug must be fixed by GGG.
For now you can fix it yourself by googling program that turns window into borderless mode (eg https://github.com/Codeusa/Borderless-Gaming/releases)

**Comment by SnosMe** [comment]
Fixed by GGG
