### ISSUE TITLE
Item Highlighting Gets Toggled When Pressing Auto-Hide Hotkey

### ISSUE THREAD

**Issue by Nicholas-Ingram** [SnosMe/awakened-poe-trade#1008]
Whenever I hit the "Auto-Hide Mode" hotkey it acts as if I also press the "Toggle Highlighting" input. I have tried uninstalling and reinstalling the plugin many times even going as far as finding all associated files from the plugin and deleting them after uninstalling. This hasn't fixed the issue.

**Comment by SnosMe** [comment]
I remember that GGG has recently split highlight items and mods into separate hotkeys. You can change them to distinct keys in the game if it crashes when you try to price check with too much loot in map. But the other key to show mods will always be pressed by the tool because it's required.

**Comment by Nicholas-Ingram** [comment]
Yup that did it. I had mods as ALT, highlight as CTRL+ALT, and price check as CTRL+D
