### ISSUE TITLE
Wrong search with "Reduced raising of alert level from opening chests" on Heist Cloaks

### ISSUE THREAD

**Issue by kristianskouv** [SnosMe/awakened-poe-trade#1010]
How to reproduce:
Use awakened poe to price check A heist cloak with the "Reduced raising of alert level from opening chests"

Actual behavior:
Since the mod is called "#% increased raising of Alert Level from opening Chests" on the trade site, it logically puts for a 12% reduced cloak "-12" in the minimum value. You would expect this to work, however the trade site will show every cloak.

How to fix
By putting "-12" (in this case) as the "max" value instead of "min" does it work on the trade site.

**Comment by SnosMe** [comment]
Yeah I maintain list of flipped stats. If you find more let me know :)

![image](https://github.com/SnosMe/awakened-poe-trade/assets/4292308/837c78cd-6317-4fb8-8f04-c19bb23091f6)
