### ISSUE TITLE
Spacebar not working when awaken trade is open

### ISSUE THREAD

**Issue by joshhooper99** [SnosMe/awakened-poe-trade#1015]
Spacebar doesn't work in the chat in POE when I have awaken trade open

**Comment by joshhooper99** [comment]
also doesn't work in stash tabs

**Comment by SnosMe** [comment]
Check your hotkeys, one of them is using Spacebar

**Comment by joshhooper99** [comment]
in poe the default is set for keybinds and the issue is only when awaken trade is open

**Comment by joshhooper99** [comment]
still having this issue
