### ISSUE TITLE
ctrl + scroll wheel interaction

### ISSUE THREAD

**Issue by shanks1578** [SnosMe/awakened-poe-trade#1016]
in previous versions ctrl + scroll wheel only moved stash tabs while hovering over the stash tab
in latest version the ctrl + scroll wheel moves the stash tab even when it's not over the stash tabs, thus interfering with other scripts such as x-mouse

**Comment by SnosMe** [comment]
Nothing has changed, you can disable scrolling in the tool settings.

![image](https://github.com/SnosMe/awakened-poe-trade/assets/4292308/9a790746-3eb6-4876-98d7-e9aa0d0a8021)
