### ISSUE TITLE
Awakened poe trade forces poe to use inefficient presentation model

### ISSUE THREAD

**Issue by RustyShark** [SnosMe/awakened-poe-trade#1017]
Awakened PoE Trade forces PoE to use "Composed: Flip" as its presentation model. This causes a loss in performance and a substantial latency penalty. This should not be the case while the overlay is not on the screen.

Additional information on presentation models can be found here:
https://wiki.special-k.info/en/Presentation_Model
https://learn.microsoft.com/en-us/windows/win32/direct3ddxgi/dxgi-flip-model.

**Comment by SnosMe** [comment]
Duplicate of #709
