### ISSUE TITLE
Bug, when trying to see the price of an item

### ISSUE THREAD

**Issue by CatShredengera** [SnosMe/awakened-poe-trade#1020]
I installed the program and waited for it to update, and I get this error, what can this be due to?
![image](https://github.com/SnosMe/awakened-poe-trade/assets/46873856/8f4aa5d7-9b8a-4ff4-8867-ce898b5e7dae)

**Comment by SnosMe** [comment]
You forgot to change the language in the app.

**Comment by CatShredengera** [comment]
Yeah thx
