### ISSUE TITLE
You cannot view the price of an item after the update 3.21.10003 

### ISSUE THREAD

**Issue by venlight** [SnosMe/awakened-poe-trade#1021]
![image](https://github.com/SnosMe/awakened-poe-trade/assets/139842076/ab39fcd0-7026-4ff8-b869-7433a7c394fe)

**Comment by SnosMe** [comment]
you've used app in RU, and then switched the game to EN. So, don't forget to change language in the tool too :)

**Comment by venlight** [comment]
а спасибо не знал просто

**Comment by Klonoa3000** [comment]
And for Spanish people @SnosMe ? I  have the same bug but this program don't have spanish

**Comment by SnosMe** [comment]
@Klonoa3000 it has never supported Spanish, so nothing changed for you with this release.

**Comment by Klonoa3000** [comment]
So i need to have the game in english no?
Never put spanish in the program? Maybe one day? Spanish comunity it's really big

**Comment by SnosMe** [comment]
@Klonoa3000 yes, you need to switch game to English (as I guess you did before).
