### ISSUE TITLE
Price Checking does not work on ROG Ally

### ISSUE THREAD

**Issue by f111fei** [SnosMe/awakened-poe-trade#1025]
All settings are default.

When I press Ctrl+D or Ctrl+Alt+D, it opens Armoury Crate Settings Panel instead of Price Checking.

I always end up opening the Armoury Crate Settings Panel no matter how I change the hotkey for Price Checking.

The error log is `warn [ClipboardPoller] No item text found.`

But Shift+Space to open the overlay window and Ctrl+C to copy text work fine!

I've read https://snosme.github.io/awakened-poe-trade/nothing-happens. 

Price Checking works fine when I close Armoury Crate Panel, so I'm sure Armoury Crate Panel and APE conflict. 

But I can't keep closing Armoury Crate Panel because once I close this system programme, ROG Ally will have more problems. 

So is there a solution to the conflict? I can't live without APT.

**Comment by f111fei** [comment]
Sorry, I solved the conflict after reading the documentation and source code carefully. 

Setting the `Show Advanced Item Descriptions` hotkey in the game to something other than Alt (like `) fixed the problem.

**Comment by ZeroGTLord** [comment]
sorry, I tryed like you did, but nothing solved the problem... No matter the binding it always opened the command center.

**Comment by f111fei** [comment]
> 

See https://github.com/SnosMe/awakened-poe-trade/pull/1026

There are a bug that read default config. You can temporarily set the configuration file path manually

**Comment by f111fei** [comment]
Now overlay-window has some problems in windows 11 tablet mode, it is recommended to disable tablet mode using the following registry command

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\PriorityControl]
"ConvertibleSlateMode"=dword:00000001
```

**Comment by ZeroGTLord** [comment]
hey, thank you for the quick answer.

At first, do you speak German? ;)

I'll try the reg command today. yesterday all I see was a white screen....thank you, I hope it works.

**Comment by f111fei** [comment]
> 

Is it still a white screen?  Win11 will adapt the window when using the touch screen, just like Win10's tablet mode, this reg is to disable this default behavior.

**Comment by ZeroGTLord** [comment]
it's still a white screen. cause when I copy and paste the command in the reg editor, nothing but an error warning happens. so I can't change anything.

**Comment by f111fei** [comment]
> it's still a white screen. cause when I copy and paste the command in the reg editor, nothing but an error warning happens. so I can't change anything.

1. Copy the code and save as `.reg` file
2. Open the file

**Comment by ZeroGTLord** [comment]
Do you have any advices for me for the path question?
please!!

**Comment by f111fei** [comment]
> 



> Do you have any advices for me for the path question? please!!

![image](https://github.com/SnosMe/awakened-poe-trade/assets/7069719/f53e3957-abdd-4914-a2ef-b7fdb7fbd176)

That's the POE config.

`C:\Users\Your_Name\Documents\My Games\Path of Exile\production_Config.ini`

**Comment by ZeroGTLord** [comment]
I changed the config path, but the ally still opened the armoury crate.

Now I try to close the 4  armoury crate files via the task manager and APT works correctly. I allways have to do this when put on the ally, but once it's set, it's OK for the session.

Thanks again for you effort and your patience!!!
