### ISSUE TITLE
Using hotkeys cause to paste "ć" in Polish system language

### ISSUE THREAD

**Issue by Jugg3rPL** [SnosMe/awakened-poe-trade#1028]
ć on Polish keyboard by default is "right alt + c"

How ever using any hotkey with awakened poe trade cause to paste "ć" in stash tab search box or chat if they are active.
It's really frustrating to constantly delete "ć" or close and reopen chat after each price check.

Video of this happening: https://youtu.be/Bbh5GnYtXn8

**Comment by SnosMe** [comment]
Thank you for taking time to capture a video, not a lot of people do this.
It does press LeftAlt+C to copy item as explained here https://snosme.github.io/awakened-poe-trade/nothing-happens.html
Try changing Alt **in the game** to other key.
