### ISSUE TITLE
Cannot Price Check Item or Change League

### ISSUE THREAD

**Issue by yulechemist** [SnosMe/awakened-poe-trade#1029]
![image](https://github.com/SnosMe/awakened-poe-trade/assets/128137204/79136915-f234-42ea-9dc2-8ea766e20f0e)

Steps I've taken to try to fix this:
Completely removed it from my computer and attempted reinstalling
Cleared config folder
Tried installer and standalone
Tried previous version from April

**Comment by SnosMe** [comment]
You might be blocked by CLoudflare, click "Browser" button.

**Comment by yulechemist** [comment]
Thank you, that solved my issue.

**Comment by yesmenoop** [comment]
i have the same problem but whenever i click browser, it price check for me once, then completly crashed, i have open an issue but got no reply nor can't find it now please help
