### ISSUE TITLE
Failed to get price prediction error.

### ISSUE THREAD

**Issue by Bassen87** [SnosMe/awakened-poe-trade#1036]
Hey I'm getting this error when pressing CTRL + D to get a pricecheck on an item.

Failed to get price prediction
ERROR: LEAGUE IS NOT ACTIVE. PRIVATE LEAGUES ARE NOT SUPPORTED NOW.
[https://i.imgur.com/VghW6ov.png](url)

But I have chosen Ancestor league in the Shift + Space Settings.
[https://i.imgur.com/wbqUhYf.png](url)

I have pressed refresh and chosen "Ancestor".

I have deleted the config.json under APPDATA and I have uninstalled and reinstalled awakened poe trade program twice now.
But still get the same error.

When I press CTRL + ALT + D and press search I do get a list over prices but I still get the same error on top.

[https://i.imgur.com/55kCyOd.png](url)

Is there something that I am missing?
It used to work for the crucible league but not for this league.

**Comment by SnosMe** [comment]
Price predictions are from https://poeprices.info/
Probably they have not updated league list yet.

**Comment by Bassen87** [comment]
> Price predictions are from https://poeprices.info/ Probably they have not updated league list yet.

But none of my friends has this issue at the moment?

**Comment by SnosMe** [comment]
They do :)
Don't confuse it with poe.ninja price that appears in the exact same spot

**Comment by Bassen87** [comment]
Which poe.ninja price? Can I change it to poe.ninja instead of using poeprices.info or what do you mean?

**Comment by SnosMe** [comment]
rare items are predicted by https://poeprices.info/
all other items are by poe.ninja, it's auto-switched based on item rarirty.
If error atm annoys you, then disable 
![image](https://github.com/SnosMe/awakened-poe-trade/assets/4292308/92e38c7a-5ae5-4241-b7b3-335fd9082df8)

**Comment by Bassen87** [comment]
Ah ok, ye but it's the price prediction that I am after. I'll just wait until poeprices.info has updated it on their side.
Thank you.

**Comment by Bassen87** [comment]
I went to the poeprices.info webpage, and when I choose the scrolldown under "Standard" the name is written "Ancestors" and not "Ancestor" like it's named in the PoE config files and awakened poe trade files.

Could it be a spelling error on poeprices.info's part?

**Comment by Bassen87** [comment]
What I mean is, can't I just change the config.json file ----> "leagueId":"Ancestor" into "leagueId":"Ancestors" instead and it should work?

**Comment by Bassen87** [comment]
No I guess I was wrong, leagueId:Ancestor only checks the value inside the production_Config PoE file, I just have to wait until poeprices.info changes it from Ancestors into Ancestor then?

**Comment by Bassen87** [comment]
Update: I contacted the owner of poeprices.info and got confirmation that it was a typo and that the owner has fixed it now, you can mark this thread as resolved.
