### ISSUE TITLE
Prevents iCUE from working

### ISSUE THREAD

**Issue by Noshei** [SnosMe/awakened-poe-trade#105]
I have a Corsair keyboard and use their iCUE software to change the keybinds for custom keys on my keyboard based on the game I am playing.  When using awakened poe trade this does not work as iCUE does not recognize PoE as the active window.

**Comment by nowx-gh** [comment]
I have the same problem with logitech software (not testet v2 yet).

**Comment by SnosMe** [comment]
With v2 being released can you confirm that issue no longer affects you?

**Comment by nowx-gh** [comment]
confirmed. works.
