### ISSUE TITLE
 The program doesn't show me a price no matter which item I choose

### ISSUE THREAD

**Issue by saufmalwas** [SnosMe/awakened-poe-trade#1065]
I've tried everything now and this is the last chance to get this working, please know who is progressing like me, I'm desperate.
English language, program started as admin.

And then hover over items and press ctrl d and then the window pops up with information. It just doesn't show what I need. The price apparently there are problems and I'm not able to solve the problem on my own and I can't find a simple explanation or solution anywhere

PS I'm German and my English sucks. So I googled it, got it translated. If there are any errors in the translation that are offensive or hurtful, I am sincerely sorry

**Comment by SnosMe** [comment]
So what does it show? Also the app doesn't support German selected in the game

**Comment by saufmalwas** [comment]
It seems that the problem for me is on the trading side, even if I try to find something there, Manuel shows me that he can't find anything or only 1-2 offers
who changed the trade page to German but does it reflect Funs?

**Comment by SnosMe** [comment]
Don't you find it stupid to say you dont speak English well, and yet don't attach any screenshot to help me understand

**Comment by saufmalwas** [comment]
problem found and solved
I had the wrong liger
It hurts because I've looked it up before, but I didn't question the setting because it didn't stand up. sorry for the inconvenience and thanks for your help
