### ISSUE TITLE
POE not recognized after sleep - Failed to register low level windows hook

### ISSUE THREAD

**Issue by Zellustrious** [SnosMe/awakened-poe-trade#1069]
Awakened POE trade usually works fine on my computer, I have a .bat that loads all of my tools along with POE and everything is fine and dandy. 

Awakened POE trade will sometimes stop working after I have closed POE/tools, and put my computer to sleep. I restart the program(even manually via double click on the shortcut) and it fails to recognize PoE as my active window so shift+space does nothing. 

Things I have tried that I found from other issues:

- running from admin command prompt/right click run as administrator on shortcut
- --listen=0.0.0.0 
- I have created an exception in windows firewall, even tried with firewall and defender disabled, same behavior. 
- set ELECTRON_NO_ATTACH_CONSOLE=true
- Updated to latest version of awakened poe trade, and upgraded graphics drivers.

![image](https://github.com/SnosMe/awakened-poe-trade/assets/112378058/ecc8f691-e627-4f07-8a25-f55767b48343)

If I right click the icon in the taskbar and click open in browser this is what I see:
![image](https://github.com/SnosMe/awakened-poe-trade/assets/112378058/703b52db-578c-4b4f-b3cd-8a3b9941e021)

References
https://github.com/SnosMe/awakened-poe-trade/issues/854
https://github.com/SnosMe/awakened-poe-trade/issues/114
https://github.com/SnosMe/awakened-poe-trade/issues/525

Thank you for any input/suggestions.

**Comment by SnosMe** [comment]
This is not normal and has to do something with your customized windows. Without clear steps to reproduce this is the best I can say

**Comment by Zellustrious** [comment]
Alrighty.. I kinda figured that would be the case :[ a restart usually fixes it for me so I guess I can just do that whenever the issue comes up. 

Thank you very much for taking the time to review/respond! This tool makes playing PoE so much better, ty.
