### ISSUE TITLE
Price check overlay closes on hover

### ISSUE THREAD

**Issue by DigohD** [SnosMe/awakened-poe-trade#1071]
When checking prices using Ctrl + D the overlay shows up in game as expected. But as soon as I hover the price check window, Poe is minimized so that I end up in the Desktop, and the Awakened overlay window is not visible. When I move the mouse out of the window area which is now invisible, Poe is maximized again and the overlay becomes visible. If I am fast and click the overlay window as soon as I hover it, PoE still is minimized but the overlay remains visible.

The issue started appearing after I opened settings with Shift + Space the first time.

I tried reinstalling Awakened as well as deleting the config folder,

**Comment by SnosMe** [comment]
The issue is you having PoE in fullscreen

**Comment by DigohD** [comment]
I feel a bit silly not trying this first.

Thanks!
