### ISSUE TITLE
Urgent orders cannot be found via "heist target: skill gem" search

### ISSUE THREAD

**Issue by Slolwhat** [SnosMe/awakened-poe-trade#1079]
![image](https://github.com/SnosMe/awakened-poe-trade/assets/13590992/d782fa5c-385f-41de-926e-bbfd72a8e8a9)

**Comment by SnosMe** [comment]
Will be fixed, for now you can just type "orders".

**Comment by Slolwhat** [comment]
seems to be the case for Rage Support as well
