### ISSUE TITLE
[Feature Request] Alchemy Orb as option for items in the bulk exchange category 

### ISSUE THREAD

**Issue by meve90** [SnosMe/awakened-poe-trade#1080]
Currently for items on the bulk exchange category like currencies, fragments, tatoo etc there is only an option to see prices for chaos and divine orbs, would it be possible to add Alchemy Orbs as an options as well?

As you may guess this is a feature mostly for Ruthless mode where alchemy orbs are the main currency there.
As Ruthless is a very unpopular mode I uderstand if you have no time to add but some of us would appreciate it very well.

**Comment by SnosMe** [comment]
I don't agree with GGG on the idea of Ruthless. People who decided to play it for real, should follow GGG spirit and not use any third party tools, sites, wikis, guides, and PoB especially.

**Comment by poroburu** [comment]
Can we get bulk exchange for non-meta currency pairs? Why does it only have to be Chaos and Divine?

**Comment by poroburu** [comment]
> I don't agree with GGG on the idea of Ruthless. People who decided to play it for real, should follow GGG spirit and not use any third party tools, sites, wikis, guides, and PoB especially.

GGG could disable the API for Ruthless. But it works as expected.

PoB, Filterblade supporting the ".ruthlessfilter" file extension, poeplanner, the wiki hosted by GGG, all supports Ruthless. Obviously not first class feature support. 

How about an opt-in option to enable 'ruthless options' that shows a copy pasted button that gets bulk trade pairing for non-meta currencies.

`https://www.pathofexile.com/trade/exchange/Ruthless%20Necropolis?q=%7B%22exchange%22:%7B%22have%22:[%22chaos%22],%22want%22:[%22harbinger-scarab%22],%22status%22:%7B%22option%22:%22online%22%7D%7D%7D`

Change `chaos` to `alch` and it will show the alch pairing.

`https://www.pathofexile.com/trade/exchange/Ruthless%20Necropolis?q=%7B%22exchange%22:%7B%22have%22:[%22alch%22],%22want%22:[%22harbinger-scarab%22],%22status%22:%7B%22option%22:%22online%22%7D%7D%7D`
