### ISSUE TITLE
Updates brick the entire macro

### ISSUE THREAD

**Issue by PhantomzoneTV** [SnosMe/awakened-poe-trade#1083]
Second update now where I've closed out of the macro for an update and it'll sit on my taskbar for a little bit, I mouse over it and it disappears, I relaunch it and I can no longer interact with it at all. LMB, RMB does literally nothing to it on the taskbar and it does nothing in-game. Have to force close it via task manger. Tried to reinstall it for the sixth time this league and it just doesn't launch anymore at all.

No idea what's going on but this league has been terrible with the updates, they just do nothing but brick the trade macro, every single time. Last time this happened it just randomly started working again after four or five hours of trying to figure out what was wrong with it and waiting for a reply in my last issue post which I removed once the issue was solved.

**Comment by SnosMe** [comment]
Sorry to hear, but I can't do anything about it. Auto-updater is not under my control, it doesn't have any knobs for me to tweak.
