### ISSUE TITLE
UI on the wrong display and unmovable

### ISSUE THREAD

**Issue by noraj** [SnosMe/awakened-poe-trade#1090]
I play PoE on both Windows 11 (GGG client) and ArchLinux (with Steam + Proton) in Windowed Fullscreen.

APT works well on Windows. APT also works on Linux with the AppImage.

The issue is that I have 3 screens/displays, PoE displayed on screen 2 (middle) while APT opens on screen 1 (left). There is no option to tell on which screen to appear and the Window is not movable/draggable.

Note: I'm using wayland (not X).

**Comment by SnosMe** [comment]
https://snosme.github.io/awakened-poe-trade/cmd-flags.html

> --no-overlay
> Disables the creation of the Overlay Window completely. Can be useful for Linux users using APT in the browser.

**Comment by noraj** [comment]
I already tried that, it only makes APT running on a web browser (so on another screen). I would like the overlay to run on the same screen as the game.

**Comment by SnosMe** [comment]
I would like the linux desktop to agree on some kind of stable api. Don't see this coming soon.

**Comment by noraj** [comment]
There are 2 kinds of display server:

- Xorg (legacy): https://www.x.org/wiki/Documentation/
- Wayland (modern): https://wayland.freedesktop.org/docs/html/

The API is absolutely standard and the same across distributions or desktop environments.

From the CLI some tools allow listing the displays but that would be possible to do from the library directly.

```
# for X
➜ xrandr --listmonitors 
Monitors: 3
 0: +*DP-4 1920/540x1080/300+1920+0  DP-4
 1: +DP-3 1920/540x1080/300+0+0  DP-3
 2: +DP-5 1920/540x1080/300+3840+0  DP-5

# for wayland (see wl_output on the lib)
➜ wayland-info
```

In fact at a low level all video adapters are listed under `/sys/class/drm`.

What would you need? Listing all monitors available, knowing on which screen PoE is running and then tell APT to run on the same screen (and not on the first one necessarily)?

**Comment by SnosMe** [comment]
> What would you need?

Events when the foreground window has changed, the title of foreground window, its dimensions/position. I'm not interested in monitors at all.

**Comment by noraj** [comment]
It should be possible to that with the X lib (C) but you are maybe looking for a higher level API in another language:

- I believe for python https://github.com/python-xlib/python-xlib could do that
- For nodejs I heard of https://github.com/sidorares/node-x11

For the title of foreground window many people use xdotool (cf. https://unix.stackexchange.com/questions/38867/is-it-possible-to-retrieve-the-active-window-process-title-in-gnome) but it seems there is a cross-platform lib doing this for people using electron: https://github.com/sindresorhus/active-win.

**Comment by SnosMe** [comment]
I have no problems with X11 (except fullscreen on some distributions) and have my own library for all of this...
https://github.com/SnosMe/electron-overlay-window/blob/master/src/lib/x11.c

**Comment by noraj** [comment]
> I have no problems with X11 (except fullscreen on some distributions)

When I switch from Wayland to X11 I have the same issue.  What can I do to help? Could I provide some debug data?

> have my own library for all of this...

Oh nice!

**Comment by SnosMe** [comment]
> When I switch from Wayland to X11 I have the same issue

As I said some distros have weird behaviour for fullscreen windows. I don't need any debug data, I need distros to be consistent so I can develop on one and it works everywhere.
But using in normal window should work without issues.

**Comment by noraj** [comment]
You're right, on Windowed mode it's working properly.

**Comment by keyboardsquid** [comment]
Bumping an old thread, because this is the first result in the Search engine. 
On Wayland, i found a workaround by swapping the ports my monitors were plugged into. 
Seems to launch on whichever monitor is "first" according to your GPU.

**Comment by lebster** [comment]
I had this issue and fixed it by doing the following:

1. Launch **Awakened PoE Trade**  
2. Launch **Path of Exile**  
3. Change the display mode from **Windowed Fullscreen** to **Fullscreen** *(but **do not** click "Accept Changes")*  
4. Press the **Super** key to minimize Path of Exile  
5. Click back into Path of Exile  
6. Click **Revert**

I have to repeat this process every time I start the game.

**Comment by Jtramey** [comment]
> I had this issue and fixed it by doing the following:
> 
>     1. Launch **Awakened PoE Trade**
> 
>     2. Launch **Path of Exile**
> 
>     3. Change the display mode from **Windowed Fullscreen** to **Fullscreen** _(but **do not** click "Accept Changes")_
> 
>     4. Press the **Super** key to minimize Path of Exile
> 
>     5. Click back into Path of Exile
> 
>     6. Click **Revert**
> 
> 
> I have to repeat this process every time I start the game.

This worked perfectly, thank you! (kde plasma, wayland)

**Comment by Eispala** [comment]
> I had this issue and fixed it by doing the following:
> 
>     1. Launch **Awakened PoE Trade**
> 
>     2. Launch **Path of Exile**
> 
>     3. Change the display mode from **Windowed Fullscreen** to **Fullscreen** _(but **do not** click "Accept Changes")_
> 
>     4. Press the **Super** key to minimize Path of Exile
> 
>     5. Click back into Path of Exile
> 
>     6. Click **Revert**
> 
> 
> I have to repeat this process every time I start the game.

Nice find, works for me aswell (kde/wayland)

**Comment by notpentadactyl** [comment]
> I had this issue and fixed it by doing the following:
> 
>     1. Launch **Awakened PoE Trade**
> 
>     2. Launch **Path of Exile**
> 
>     3. Change the display mode from **Windowed Fullscreen** to **Fullscreen** _(but **do not** click "Accept Changes")_
> 
>     4. Press the **Super** key to minimize Path of Exile
> 
>     5. Click back into Path of Exile
> 
>     6. Click **Revert**
> 
> 
> I have to repeat this process every time I start the game.

Thank you for this hint!

FYI for me the only thing I actually need to do now is to launch **Awakened PoE Trade** before **Path of Exile**. 

KDE Plasma Wayland.

**Comment by almighty-atlas** [comment]
> I had this issue and fixed it by doing the following:
> 
> 1. Launch **Awakened PoE Trade**
> 2. Launch **Path of Exile**
> 3. Change the display mode from **Windowed Fullscreen** to **Fullscreen** _(but **do not** click "Accept Changes")_
> 4. Press the **Super** key to minimize Path of Exile
> 5. Click back into Path of Exile
> 6. Click **Revert**
> 
> I have to repeat this process every time I start the game.

Thank you some much, this works like a charm!

KDE (Wayland) aswell.
