### ISSUE TITLE
[Feature Request] Price-check map on map tab hover

### ISSUE THREAD

**Issue by davechurchill** [SnosMe/awakened-poe-trade#1091]
Being able to hit CTRL+D when hovering a map I need would be pretty sweet if it's possible to do within the current API

![image](https://github.com/SnosMe/awakened-poe-trade/assets/1189032/b4faab9d-46f3-4913-a032-3ca52ce461ff)

**Comment by SnosMe** [comment]
It's not possible because the game doesn't copy anything when your cursor is placed threre.

**Comment by davechurchill** [comment]
You don't have to re-open this, but when you said "doesn't copy anything" what exactly do you mean?

A new popup title window is formed with the name of the hovered map. Or is there another form of copying you mean? Apologies I'm new to the program

**Comment by SnosMe** [comment]
I'm not scanning the screen, it would be very inefficient and brittle. 
PoE only copies real items you own in inventory to the clipboard.
https://snosme.github.io/awakened-poe-trade/nothing-happens.html

**Comment by davechurchill** [comment]
Thank you for the explanation! I thought you may have been reading game memory, but now I understand what you meant by copy.
