### ISSUE TITLE
Checking the price of the "Voices" Cluster Jewel should have it's "nothing" passive skills in the "MAX", not "MIN" field by default.

### ISSUE THREAD

**Issue by grallbring** [SnosMe/awakened-poe-trade#1098]
Hello, when price checking a "Voices" the amount of "nothing" passive skills it has goes into the "MIN" field by default, so even a 3 or 1 "nothing" passive "Voices" would show the price of  the listed 7 "nothing" passive skills "Voices".

![image](https://github.com/SnosMe/awakened-poe-trade/assets/134601573/7f6c4bda-d901-4828-97ba-c1ff71cfefca)

**Comment by SnosMe** [comment]
hmmm, weird. "variant" stats should fill min&max as for example on Legion jewels.
I'll check this.
