### ISSUE TITLE
Invite chat command is invalid when using the controller

### ISSUE THREAD

**Issue by f111fei** [SnosMe/awakened-poe-trade#1100]
My chat settings is
```
/invite @last
```
The current workflow is
1. `Ctrl + Enter`
2. `Home`
3. `Delete`
4. `Ctrl + V`

But unlike with a keyboard and mouse when using a controller, the input box in the `Ctrl + Enter` chat bar doesn't get the focus and you need to press the OK button on the controller as in the picture below.

![image](https://github.com/SnosMe/awakened-poe-trade/assets/7069719/989c351c-6074-4e08-8fff-dc0b207f9d28)

So when you press `Home` the cursor doesn't move to the top of the input box and then the bug occurs.

I think the solution is to press `Ctrl + Enter` and then press `Backspace` or `ArrowLeft` once to get the focus on the input box before pressing `Home` when using a controller, or just roughly press `Home` twice.

**Comment by SnosMe** [comment]
Sorry I don't have controller, so I won't be able to test this

**Comment by f111fei** [comment]
> Sorry I don't have controller, so I won't be able to test this

https://github.com/SnosMe/awakened-poe-trade/blob/b446c617cc1d4970067c209cf172a5dd93fcf72a/main/src/shortcuts/text-box.ts#L25

Just press `Home` twice. I've changed the code and then compiled and tested it to pass. Can I create a pr to fix this?
