### ISSUE TITLE
Journey Tattoo of Makanui

### ISSUE THREAD

**Issue by potato404** [SnosMe/awakened-poe-trade#1104]
![image](https://github.com/SnosMe/awakened-poe-trade/assets/23662853/1518a3ae-21de-473d-9649-7844da060be3)

**Comment by potato404** [comment]
this still hasn't been fixed

**Comment by SnosMe** [comment]
Yes, so the issue is open, looks pretty logical to me 🙂

**Comment by SnosMe** [comment]
Added
