### ISSUE TITLE
Trying to Lookup an Item Immediately Closes ALL Open Windows

### ISSUE THREAD

**Issue by Ruebs** [SnosMe/awakened-poe-trade#1106]
When I press CTRL+D on an item, the game and all of my open windows immediately close (including browser, PoB, Discord, etc.)

Cant check the logs because it quits Awakened PoE trade so next time I open it there is only one log line.

Didn't see anything in common issues or requirements about this. (Running PoE in Fullscreen Windowed).

Let me know if there is anything I can try, thanks!

**Comment by SnosMe** [comment]
Other than you having a shortcut to close everything idk

**Comment by Ruebs** [comment]
I changed the shortcut to something else and it still does it.

Without awakened trade running or if I press CTRL+D without the mouse being over an item, it does nothing.

:(

**Comment by Chronikz** [comment]
I have the exact same problem. It closes EVERY application thats currently open when I try to use the auto price-check function. Doesn't matter which Hotkey I assign to it. Same happens with Lailloken UI for me whenever I use it "Magic Button". This is driving me nuts.

**Comment by Ruebs** [comment]
For me it ended up being caused by WinSplit Revolution. It has a hotkey to close all windows which seems bugged because it was set to a completely different key combo. I disabled that option entirely and that fixed it. Try closing any other utilities/apps and only have PoE and Awakened PoE running and see if it works then.

**Comment by Chronikz** [comment]
OH. MY. GOD. I love you so much! This has been the fix. It would have taken me ages to find that out! Thank you so much!!!
