### ISSUE TITLE
Overlay displaying presumably CSS

### ISSUE THREAD

**Issue by ShiroTsuma-github** [SnosMe/awakened-poe-trade#1109]
![image](https://github.com/SnosMe/awakened-poe-trade/assets/57981416/4b1bab13-34d6-40d0-9281-93aa5d3b8d86)
![image](https://github.com/SnosMe/awakened-poe-trade/assets/57981416/9875d72d-c44c-415d-add9-fe700ca66322)

Can't pinpoint the reason, but sometimes POE trade instead of opening overlay or anything displays what i presume it's style. 

Restarting POE trade often doesn't help, same with POE. 
During this time you can't get prices or anything and often it doesn't want to go away with shortcuts

**Comment by SnosMe** [comment]
lol, seeing this for the first time. 
as you can guess, low-level stuff of injecting css is handled by framework, so idk what this can be
