### ISSUE TITLE
(2.0.0 beta) two small issues found during the test

### ISSUE THREAD

**Issue by Xebtria** [SnosMe/awakened-poe-trade#111]
- APT is friendly to other windows and 3rd party tools, so run all the tools you usually use
► no problems. I run it in vulkan mode, using the poe autoborderless ahk macro so I can use windowed mode and still be borderless (because actual fullscreen windowed via settings in reality is just true fullscreen with vulkan) and also poe.lurker, both seem to work just fine with it.
- APT has the red test-border that must exactly match PoE sizes
► red border is there.
  - move PoE window;
► works
  - resize PoE window;
► works
  - switch between "windowed fullscreen", and "windowed" mode;
► works, excvept for than the vulkan issue I mentioned above, which causes the red border only to appear when poe actually is not in focus, but that is not an issue of APT I believe. works just fine with Dx11.
  - change "Display" (if have 2 monitors);
► works
  - open two PoE clients and resize them so that they are not the same size, when switching between them, the overlay should automatically move and resize.
► works
- APT shows "Game window is not active" in bottom-right corner (when PoE window is not focused)
  - Alt+Tab;
► works
  - click on the Desktop and again on the game;
► works
  - go to windowed fullscreen and toggle Windows Start menu;
► works (only tested with dx11 because of the vulkan issue)
- APT shows as transparent window
  - quit APT & PoE. Open PoE, open APT and click on PoE window
► red border shows, indicating it is active
  - quit APT & PoE. Now in reverse order. First launch APT, and wait till tray icon is shown, then start PoE client
► tray icon was active, then I started poe, poe had the focus but APT/red border was not shown. had to click outside of the game client (browser, desktop) and back into the game to make it show up. Minor inconvenience at worst I'd say, but technically not 100% working
- APT correctly focuses and defocuses
  - press Shift+Space to activate overlay, press Esc to bring focus back to the game
► works
  - do a price check in auto-hide mode, move mouse slowly (holding Ctrl) to the window, it must become active
► works
  - do a price check in auto-hide mode, move mouse very-very quickly (holding Ctrl) to the opposite side of the screen, price-check window must close
► price check window does not close. what happens is the following: When I move the mouse slowly (previous test basically), the price check window becomes active as soon as the mouse cursor enters the price check window, and it disappears as soon as the curse leaves the price check window again. I believe this is the intended behavior. but when I move the mouse very very quickly, the window becomes active and remains active even though the mouse left the price check window again. when I THEN move the cursor back to the price check window it still remains active and if it THEN leaves the window, the price check window disappears. This second time is irrelevant whether I do it slowly or very very quickly, it always disappears when I "travel" over the window with the mouse the second time (and it leaves the window during that "travel").
  - do a price check in locked mode
► works

**Comment by SnosMe** [comment]
Thank you for detailed feedback.
Hope you want to install beta again and test the second (and last) time.

> quit APT & PoE. Now in reverse order. First launch APT, and wait till tray icon is shown, then start PoE client
> ► tray icon was active, then I started poe, poe had the focus but APT/red border was not shown. had to click outside of the game client (browser, desktop) and back into the game to make it show up.

How often this happens to you. For me it is like 1 out of 30 times.

> do a price check in auto-hide mode, move mouse very-very quickly (holding Ctrl) to the opposite side of the screen, price-check window must close
> window becomes active and remains active even though the mouse left the price check window again

Record a 60fps video with PoE in windowed mode, so I can see the PoE window titlebar.

**Comment by Xebtria** [comment]
> Thank you for detailed feedback.
> Hope you want to install beta again and test the second (and last) time.

Sure, no problem. Software testing is actually my job as well, so I mind even less :) 
> > quit APT & PoE. Now in reverse order. First launch APT, and wait till tray icon is shown, then start PoE client
> > ► tray icon was active, then I started poe, poe had the focus but APT/red border was not shown. had to click outside of the game client (browser, desktop) and back into the game to make it show up.
> 
> How often this happens to you. For me it is like 1 out of 30 times. (Steam or Standalone client?)

100% every single time. it can also be observed that if for example an explorer window is open on the same screen where poe opens, this explorer window remains on top even though poe is starting up. and even then, if I click in the poe window, APT does not show up (no red border). only if  something else gets the focus again at that point (clicking the desktop, alt-tab, whatever), and then I get back to poe, then APT and the red border shows up. The behavior is identical if I close poe and re-open poe without closing APT in between.
This is with standalone client
I also tried with steam client (I have both installed) and there it work (red border shows up immediately). Also the other described behavior (any window remains on top when starting poe) is not applicable for steam, there steam directly is completely on top when it starts, so there is an actual difference between the clients here.
Both tried with windowed mode in this case
> > do a price check in auto-hide mode, move mouse very-very quickly (holding Ctrl) to the opposite side of the screen, price-check window must close
> > window becomes active and remains active even though the mouse left the price check window again
> 
> Record a 60fps video (if OS is Windows) with PoE in windowed mode, so I can see the PoE window titlebar.
OS is win10 1909
https://gofile.io/d/DYh9VO here is the video, hope it helps. first time was slow/slow, then fast/slow, and then twice fast/fast. The fps spikes in the poe display at the top are because I have my foreground locked to 100fps and the background locked to 60fps, and whenever any tool is becoming active, poe considers being in the background. usually I have it with 15fps to save computing power (and prevent my gpu fans going haywire), but I changed it to 60 for the purpose of this video, as requested :) 
oh and I have alt for the temp window, ctrl is my lock window shortcut. but I also tried earlier with ctrl for the temp window, it doesn't make a difference.
Out of curiosity I tried this also with both clients, but here is no behavior difference, behaves the same for steam and standalone.

**Comment by SnosMe** [comment]
1. Can confirm

2. I am actually have no idea why, watched frame-by-frame and maybe repainting background on large resolution takes huge chunk of time, so Chromium miss mouse move events. Try resizing to FullHD window, no need to record video, dont forget to uncap 15fps again  ;)

**Comment by Xebtria** [comment]
Tried with a window in the 13xx x 7xx range of just randomly made it smaller, same behavior, although significantly "harder" to reproduce, in about every half of the attempts (very rough estimate) the window disappeared when moving the mouse quickly, the other half it stayed just as shown in the video.

**Comment by Xebtria** [comment]
btw: I happen to run into the same problem with the focus thing (1.) when using poe lurker. after I finish a trade, APT shows that client is not in focus anymore and I have to click outside / alt+tab somewhere and back into poe before it gains the focus again.
