### ISSUE TITLE
Game Limited to 60 FPS when APT is running and overlay is off.

### ISSUE THREAD

**Issue by DamnMyEyes1** [SnosMe/awakened-poe-trade#1111]
My primary monitor is 60hz, but my 2nd display is a 120hz TV.  I play on the 2nd display.  When I **don't** have APT running, I get 120 FPS.  When APT **is** running, I get 60 fps in game, but if I open the overlay, price check, or move focus to primary, my FPS jumps back to 120.

**Comment by llam722** [comment]
Just a possible suggestion - you think the Background FPS Cap in your Graphics settings is enabled? That might be limiting it.

**Comment by DamnMyEyes1** [comment]
Nope, I don't have any FPS cap enabled (aside from Nvidia control panel).  I should also note that I've done a DDU driver uninstall and NVCleanstall with the latest driver.

**Comment by SnosMe** [comment]
https://github.com/SnosMe/awakened-poe-trade/issues/709#issuecomment-1224129297

**Comment by DamnMyEyes1** [comment]
@SnosMe Thank you.  Disabling G-sync does fix the issue.  I can't play the game without your tool, and I thank you.

**Comment by DamnMyEyes1** [comment]
I thought it was just the G-sync being enabled.  Turns out that it's more about the VSync setting in game.  Adaptive caps my FPS at 60 regardless of G-sync being enabled or not.  Fast setting gives me 120 fps even with G-sync on and APT running.
