### ISSUE TITLE
Bug when Price Checking

### ISSUE THREAD

**Issue by derKriig** [SnosMe/awakened-poe-trade#1117]
So this has been happening for around 2 days and I have no clue what's causing it.

![awakenedpoebug](https://github.com/SnosMe/awakened-poe-trade/assets/66647170/557a29c8-29ab-4786-8982-c6396a422fbd)

This is with default configs, using CTRL+D. When using CTRL+ALT+D, I am able to interact with the overlay and close it with a click.\

Only way to exit what's shown in the gif is to ALT+TAB

**Comment by SnosMe** [comment]
> So this has been happening for around 2 days

I assume it was working before. Since there were no recent updates to the app, the only reason it would broke is something has changed on your PC.
