### ISSUE TITLE
Price check

### ISSUE THREAD

**Issue by Berlima** [SnosMe/awakened-poe-trade#1118]
hello everything is fine?
I'm a newbie and I know little about the game, I was visiting various temples and researching items in different ways, until this message appeared in the app...See photo below
![imagem_2023-09-23_144212314](https://github.com/SnosMe/awakened-poe-trade/assets/145865460/02864b52-cfaf-4473-be91-c8db0d465bce)

**Comment by SnosMe** [comment]
Just click on this button again. 
![image](https://github.com/SnosMe/awakened-poe-trade/assets/4292308/4da61862-c5a7-44ab-a750-1ae182b3197f)

**Comment by SnosMe** [comment]
It just shows you the search limits that GGG impose on their trade servers, so players don't overload the site with searches.

**Comment by Berlima** [comment]
Thanks for the response and sorry for the inconvenience... but in short, didn't that get me banned?

**Comment by SnosMe** [comment]
Why should you be banned? It's just a temp suspension ONLY for you to not being able to do searches on trade website. Depending on which rule you've hit it cant last for 5-30 minutes
