### ISSUE TITLE
Multi language support

### ISSUE THREAD

**Issue by gnibeda** [SnosMe/awakened-poe-trade#112]
Official api supports different languages. What the main issue with implementation on APT side?

**Comment by SnosMe** [comment]
Thanks to my prior work I am able to add this, the main issue is time, multilang will be added on 2-3 week of league I think.

**Comment by gnibeda** [comment]
Maybe I can help(or somebody else)? Can you describe what to do or any info about multi language implementation?

**Comment by SnosMe** [comment]
https://en.wikipedia.org/wiki/Brooks%27s_law

League starts soon, I'll have to adapt APT for new content, new people will come to discord and ask more questions, important 2.0 update is also pushing me. And now imagine me involving someone to dev process ;) 

As a dev Im pretty sure you are understand what I'm talking about.

And not least important, I really want to continue development only by myself, but, of course, accepting the suggestions. Also, I'm the only one responsible for the codebase, so everyone knows who to blame ;)

**Comment by gnibeda** [comment]
Ok, got it. Also I've breafly looked through the code and now I understand that this task is not so trivial because there are a lot of enums with i18n strings, so changing it will lead into big code changings.

**Comment by xXDarkNovaXx** [comment]
If awakened poe trade gets support for other languages how will the pricing work since poeprices.info only supports English?

I use a translator^^

**Comment by SnosMe** [comment]
poeprices.info block will be disabled and hidden for non-English. I might be able to translate item Ctrl+C to English, but don't promise it.

**Comment by xXDarkNovaXx** [comment]
You mean that if someone uses e.g. German that the item is translated into English and then passed on to poeprices.Info?
Not being able to price items that are not yet available on the market would be bad if you are not familiar with the value of individual stats

**Comment by SnosMe** [comment]
#174
