### ISSUE TITLE
Price check does not work in Russian version

### ISSUE THREAD

**Issue by PepeAuraliano** [SnosMe/awakened-poe-trade#1124]
The League is Ancestor in the settings, but the price check does not work in the Russian version, language in settings switched to Russian (price check works fine in the English version), it writes “unknown item” for any item. What to do?
![photo_2023-09-25_21-28-42](https://github.com/SnosMe/awakened-poe-trade/assets/79316778/86aa62a5-3427-4bba-883e-c85ae1302e2c)

**Comment by SnosMe** [comment]
> price check works fine in the English version

Nope, it doesn't work fine in English for you either, because you need to resolve issue with keybinds, details here:
https://snosme.github.io/awakened-poe-trade/no-item-mods.html

**Comment by PepeAuraliano** [comment]
Thanks, I changed the key for extended descriptions to Alt and it worked!
