### ISSUE TITLE
localhost:0

### ISSUE THREAD

**Issue by jidambo** [SnosMe/awakened-poe-trade#1125]
Hey, thanks for the lib! I forked it and made some updates for me. After build I run the .exe file and when I press "Open in Browser" it redirects me to localhost:0. But when I build your package locally it opens random port, how do you run renderer and set the port when run .exe file?

**Comment by SnosMe** [comment]
Honestly, I don't know what's happening on your machine.
Having renderer and electron can be confusing 😄 

A 0 is passed to Operating System, which then returns the allocated random port.
https://github.com/SnosMe/awakened-poe-trade/blob/b446c617cc1d4970067c209cf172a5dd93fcf72a/main/src/server.ts#L130

**Comment by jidambo** [comment]
My bad, I've broke fastify. Thanks for your time
