### ISSUE TITLE
Don't apply search range to almost top rolled mods

### ISSUE THREAD

**Issue by SnosMe** [SnosMe/awakened-poe-trade#1128]

**Comment by IvanHucko** [comment]
@SnosMe Hi, I am looking for an issue to solve and this looks like interesting one to work on. Could you assign me? I would also welcome some information about the source code, maybe a hint where to look to find implementation of search range. Thanks

**Comment by SnosMe** [comment]
https://github.com/SnosMe/awakened-poe-trade/blob/b446c617cc1d4970067c209cf172a5dd93fcf72a/renderer/src/web/price-check/filters/create-stat-filters.ts#L163-L167


Basically if perfect roll then need to ignore `percent` argument, for filters created inside: 
- createExactStatFilters: all types of items
- initUiModFilters: only for unique items

**Comment by SnosMe** [comment]
`yarn dev` in /renderer and /main, also before that `yarn make-index-files` in renderer

**Comment by IvanHucko** [comment]
Hi, I am getting stuck on error trying to build the project. I am on Win11. I want to check if you have encountered something similar.

![image](https://github.com/SnosMe/awakened-poe-trade/assets/56114531/4abee15a-bf0b-47e0-8e24-5c82943a91c8)

**Comment by SnosMe** [comment]
Run this command after installing dependencies 😅

**Comment by IvanHucko** [comment]
Hi, I think I managed to complete this issue. If stat on item is max rolled, percentage argument in filter will be replaced by 0. This is implemented in `util.ts` -> `checkMaxedStatsPercent`. I would suggest making an indicator that the stat is max rolled, simmilar to indicator that item has improved quality. I left a little comment in `filterModifier.vue`. Here is the pull request: SnosMe/awakened-poe-trade/pull/1143
