### ISSUE TITLE
How do I make the overlay window clickable when the focus is on the poe window?

### ISSUE THREAD

**Issue by Traveller-hongchen** [SnosMe/awakened-poe-trade#1138]
I'm trying to add the ability to display a button for quick activity when a trade request is accepted, which is the poeoverlay feature。
However, I found that I couldn't get the overlaywindow to get mouse activity while also having mouse events pass through the overlaywindow

I looked at the files that handle overlayWindow.ts and poeWindow.ts and still can't find a workaround。
QwQ

**Comment by SnosMe** [comment]
It's not possible, at least without injecting into process like poeoverlay does
