### ISSUE TITLE
F5

### ISSUE THREAD

**Issue by grish333** [SnosMe/awakened-poe-trade#1139]
It is clear that the F5 function (to teleport to the our hideout) is essential for our game experience. It solves issues and saves time.

Unfortunately, this would cause a problem when a player would press F5 within a graphic stutter period (whether it's right after a loading screen or simply within a generic stutter while in someone else's hideout); and recently, due to the unnecessary graphic updates of Path of Exile, these stutters have become a lot more common.

**The actual problem is that, during graphic stutter, the game will open the chat in order to input the " /hideout " command but instead it will input the last entry of your clipboard from your computer.
This is a very serious matter and I can't describe how bad it can turn out since players are exposed to non-voluntarily post very sensitive information from their computer's clipboard.**

On behalf of all players, I appeal for this to be discussed thoroughly by the creators so that the F5 function is rather optimized so it does not cause this issue.

Thank you.

**Comment by SnosMe** [comment]
> F5 function is rather optimized

There is nothing to "optimize" there.

I disabled the root cause by default for new installations year ago https://github.com/SnosMe/awakened-poe-trade/issues/742#issuecomment-1245345219 , but existing players like your need to go to settings.

**Comment by grish333** [comment]
Can you please explain what was the "brilliant" idea of using anything from the clipboard?
Thanks for the suggestion but I'll take my leave with mixed feelings about you and your software.

**Comment by grish333** [comment]
@SnosMe 
I'd like to inform you that this setting does not work. I checked it and tried. I unchecked it and tried - it still continues to use the clipboard when the game interface is not active for a split second (as mentioned before - either while in someone else's hideout or right after the game loads a town, etc.)

I highly recommend that you:

1. Fix the it in a way that this issue won't possibly ever happen again.
2. Explain to me and in public why would it use the clipboard in any way?
I have read the topic you linked but it wasn't a solution for the issue, let alone an explanation why you're using the user's clipboard for this function.
Please excuse my hard tone but the situation is of a serious legal matter.

**Comment by SnosMe** [comment]
> why would it use the clipboard in any way?

This is the only available way for me to type text in game chat quickly and reliably across multiple platforms. And because I overwrite your clipboard content I provide an option to restore it after the command (hopefuly) executes. But as you see PoE can lag which would restore clipboard before PoE unlags, so that PoE proceses inputs from OS queue later and actually pastes whatever I've restored back. This feature has been disabled for all new installations.

**Comment by grish333** [comment]
@SnosMe 

Thank you for your honest reply.
