### ISSUE TITLE
Issues opening with batch file.

### ISSUE THREAD

**Issue by gotex007** [SnosMe/awakened-poe-trade#114]
This is using the stable version v1.2.0.

I use a batch file to open up all my PoE tools rather than having to open them one at a time before a session. I run into this error in the command prompt and then it hangs. Closing the command prompt closes Awakened PoE Trade and closing Awakened PoE Trade closes the command prompt.

hook_run [719]: SetWindowsHookEx() failed! (0X7E)
(node:12384) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:12384) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:12384) UnhandledPromiseRejectionWarning: Error: Failed to register low level windows hook.
    at UiohookNapi.start (C:\Users\username\AppData\Local\Programs\Awakened PoE Trade\resources\app.asar\node_modules\uiohook-napi\dist\index.js:156:13)
    at App.<anonymous> (C:\Users\username\AppData\Local\Programs\Awakened PoE Trade\resources\app.asar\background.js:2:4478322)
(node:12384) UnhandledPromiseRejectionWarning: Error: Failed to register low level windows hook.
    at UiohookNapi.start (C:\Users\username\AppData\Local\Programs\Awakened PoE Trade\resources\app.asar\node_modules\uiohook-napi\dist\index.js:156:13)
    at App.<anonymous> (C:\Users\username\AppData\Local\Programs\Awakened PoE Trade\resources\app.asar\background.js:2:4478322)
(node:12384) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12384) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12384) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:12384) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

___
The batch file is really simple. Awakened.lnk is the shortcut renamed to remove spaces.

@echo off
cd "C:\Users\username\Desktop\PoE Tools"
start acquisition.lnk
start Custom_Macros.ahk
start YoloMouse.lnk
start Trade_Companion.lnk
start Awakened.lnk
start CurrencyCop.lnk

**Comment by SnosMe** [comment]
`start "" "Awakened PoE Trade.lnk"`

in your case

`start "" "Awakened.lnk"`
