### ISSUE TITLE
Unable to check prices for all sanctum items

### ISSUE THREAD

**Issue by YunBeee** [SnosMe/awakened-poe-trade#1146]
![image](https://github.com/SnosMe/awakened-poe-trade/assets/151738898/cc23779f-c867-4539-8045-afe6aeb8f740)

Item Class: Sanctum Research
Rarity: Currency
Forbidden Tome
--------
Area Level: 83
--------
Item Level: 85
--------
Mundus noster cecidit. Daemones ubique sunt. Librum
hunc in sacrarium conicio, ut forte alius viam inveniat...
--------
Take this item to the Relic Altar in the Forbidden Sanctum to enter.

**Comment by SnosMe** [comment]
![image](https://github.com/SnosMe/awakened-poe-trade/assets/4292308/989207fb-c29b-4b13-ad2f-e1fefe56e2f8)
