### ISSUE TITLE
Ruthless Options

### ISSUE THREAD

**Issue by Neehwahs** [SnosMe/awakened-poe-trade#1155]
It looks like Ruthless options are missing from the Price Check in Awakened POE Trade. Was this intended? 

https://i.imgur.com/BEvydTe.png

**Comment by SnosMe** [comment]
Yes, removed from the list to clearly indicate that I don't have intention to support it.
APT is a bit strict for HC, and definitely is for Ruthless.

If you think it is usable enough on Ruthless, then type league name manually.
![image](https://github.com/SnosMe/awakened-poe-trade/assets/4292308/8aa721fc-f9ec-45b6-9b58-890b21c45ffb)

**Comment by goldmango** [comment]
@SnosMe after each software restart needed to type ruthless or private league again. Can you please make it saved?

**Comment by goldmango** [comment]
> I think he said he doesnt really care about Ruthless so he wont be doing any updates that will increase quality of life for it

but it is not about ruthless. It is about make saveable the option which grants the availability to choose the league name.

**Comment by test544** [comment]
Just checked: private league name is saved fine, but ruthless is reset on restart. Sad bug if it is, lame decision if it's intentional.

**Comment by SkySniper** [comment]
> Just checked: private league name is saved fine, but ruthless is reset on restart. I really hope it's a bug and not intentional decision. +1 that's need fixing

https://github.com/SnosMe/awakened-poe-trade/issues/1344

**Comment by test544** [comment]
> This is something they decided to do intentionally it is not a bug

Message above only says about "not supporting". And "not supporting" is not the reason to intentionally break the feature when it still works fine. Especially when solution for the only inconvenience in question was already proposed and takes like 5 minutes to implement\\integrate
