### ISSUE TITLE
Using the shortcut to search for an item creates a clip of the past 30 seconds

### ISSUE THREAD

**Issue by XaDesako** [SnosMe/awakened-poe-trade#1158]
every time i search vor an item using the shortcut it creats also a clip of the past 30 seconds.
it shows a popup on the top left corne 
![image](https://github.com/SnosMe/awakened-poe-trade/assets/153369350/1c5d2ed2-6dc5-46dc-8b2b-cf0f237b21b4)
this happens even though i changed the short cut from default ctrl + D to F10 for example. it also happens on ctrl + alt + d

Awakened PoE Trade
Version 3.22.10005

**Comment by XaDesako** [comment]
seems like the problem is "ctrl + alt + c"
thank you

**Comment by Engineer6Ta** [comment]
I am also having this issue just now, how did you fix it?

**Comment by XaDesako** [comment]
The problem was actually discord.
Discord released a beta-feature wich record the past 30 seconds when you press "alt + c" 
Hope that helps you!

**Comment by mr-september** [comment]
Both ctrl d and ctrl alt c are triggering this for me and I can't find any mention of either hotkeys in Discord - Keybinds.
