### ISSUE TITLE
Stash Tab Scrolling

### ISSUE THREAD

**Issue by TheNeolix** [SnosMe/awakened-poe-trade#1161]
Hi, I have set stash tab scrolling to disabled, also checked in the config.json file to make sure it's set to false, but when I press ctrl and start scrolling it keeps scrolling my stash tabs...
How to fix this issue? It's annoying I have to click every item now...

**Comment by SnosMe** [comment]
PoE has builtin scrolling by itself (but only when mouse inside stash tabs)

**Comment by TheNeolix** [comment]
My mouse is inside my inventory and it's scrolling it, in game I should have it disabled since harvest league

**Comment by SnosMe** [comment]
All I can say is this setting is working and you can close APT to be sure, that it is not caused by it :)

**Comment by TheNeolix** [comment]
It was actually the AHK macro I have, LutTools, disabled it and it works fine now.
