### ISSUE TITLE
Add support for Corpse Items from the league mechanic

### ISSUE THREAD

**Issue by Medivha** [SnosMe/awakened-poe-trade#1166]
these are items you can buy from the 1 of the 3 vendors(charms, Tincture are the others) in the league mechanic and can be traded

https://poedb.tw/us/Corpses

I’m on version 3.23.10001

thx <3

**Comment by Medivha** [comment]
There are different tiers "imperfect" "normal name" "perfect" and a lot of the perfect ones have auras they provide. As an example, the Perfect Forest Tiger gives you Haste as an Aura and is super rare to find, so worth a lot.
https://www.pathofexile.com/trade/search/Affliction/zeXeWjqh4 around 4 div
so with these spectres you can run more auras than normal. And no, you don't need to rebuy them. You don't lose spectre on death. And on removing the gem they drop as corpses again in your current area and you can recast them.

**Comment by SnosMe** [comment]
Ok, i'll add them. Just wanted to be sure they won't become a cheap commodity very quickly once people farm them enough.
