### ISSUE TITLE
Entire screen grey when game is in foreground

### ISSUE THREAD

**Issue by TheSofas** [SnosMe/awakened-poe-trade#1169]
With this tool open, the entire screen is grey. When Alt-Tabbed, the game shows like normal. Game is still interactable behind the grey screen. All other programs are disabled/closed. Opening settings with Shift+Space works, but it seems like transparency is broken. Tried running with flags --enable-transparent-visuals --disable-gpu but this did not work either. Debug Log is blank other than windows/app version.

Game Settings:
Windowed Fullscreen
Vulkan (DX11 doesn't work either)

OS: Win 11
App Version: Latest

**Comment by SnosMe** [comment]
Check mica for everyone

![image](https://github.com/SnosMe/awakened-poe-trade/assets/4292308/90071063-e444-4ed2-b4a0-9779c98d93db)

**Comment by TheSofas** [comment]
That is indeed the issue. I had tried closing Mica for Everyone, but forgot that the settings are still active even when it is not active itself. Will close this, thanks.
