### ISSUE TITLE
[Feature Request] Show Hidden Mods Option

### ISSUE THREAD

**Issue by HPoEGH** [SnosMe/awakened-poe-trade#1171]
Please add an option under price check settings for showing hidden mods by default.

Some mods that only show under hidden options **(Fractured mods)**, I would like the option of this behavior to be shown by default.
There are also some mods that only show up under hidden modifiers, that are not present under the regular mod section, and for this reason would also like the option to toggle them.

**Comment by SnosMe** [comment]
no, if you constantly need an access to hidden mods you're price checking wrong
