### ISSUE TITLE
Chaos damage not included in Total DPS calculation

### ISSUE THREAD

**Issue by wubbles90** [SnosMe/awakened-poe-trade#1172]
For this bow, the added chaos damage is not included in the "Total DPS" calculation when I use Ctrl+D.  The "Total DPS" shown by Awakened PoE Trade is 526 but it should be 812.

```
Item Class: Bows
Rarity: Rare
Armageddon Guide
Thicket Bow
--------
Bow
Quality: +20% (augmented)
Physical Damage: 38-115 (augmented)
Elemental Damage: 58-106 (augmented), 134-203 (augmented)
Chaos Damage: 103-252 (augmented)
Critical Strike Chance: 5.00%
Attacks per Second: 1.61 (augmented)
--------
Requirements:
Level: 66
Str: 113
Dex: 146 (augmented)
Int: 92
--------
Sockets: B-R-G-G 
--------
Item Level: 84
--------
18% reduced Attribute Requirements
Adds 58 to 106 Fire Damage
Adds 134 to 203 Cold Damage
Adds 103 to 252 Chaos Damage
7% increased Attack Speed
19% increased Projectile Speed
```

**Comment by SnosMe** [comment]
Elemental dmg synergizes badly with DOT. Therefore, I don't include it in total. You're the first one to ask for a change in 3 years :) Maybe you can try to convince me why I should make this change

**Comment by Tadiian** [comment]
Not OP but: Tinctures.
The one that makes "All damage can poison".
Ele+Chaos are the best mods for a good poison bow.

**Comment by wubbles90** [comment]
Yes, that is the reason. The Poisonberry tincture has the mod "All damage can poison". So I am looking at bows to see the total DPS including all of physical, elemental, and chaos. I see that outside of this, it might not be much use.

**Comment by SnosMe** [comment]
Didn't go into core.
