### ISSUE TITLE
Weapon DPS

### ISSUE THREAD

**Issue by tgavankar** [SnosMe/awakened-poe-trade#118]
poe-iteminfo (what poe-trademacro was forked from) had a feature where if you ctrl+c on a weapon, it would show you calculated stats like weapon DPS split into total/phys/ele and both 0% and 20% quality. It'd be nice to have that here too, as I don't think there's any way to cleanly get that info today.

**Comment by Hillgrove** [comment]
yes please! This would be a welcome edition :)

**Comment by SnosMe** [comment]
Planned, however in most cases you already can see it in price check window (it might fall under toggle switch also)

**Comment by TechTrooper** [comment]
Has this been implemented yet? Any update?
It was very easy to evaluate weapons with trade macro since we could compare pDPS and eDPS directly instead of specific mods.

**Comment by BD9a** [comment]
> Has this been implemented yet? Any update?
> It was very easy to evaluate weapons with trade macro since we could compare pDPS and eDPS directly instead of specific mods.

Yes, it's implemented. Sometimes U have to switch "hidden" to see weapons dps.

**Comment by goldern** [comment]
Back on this issue, it not always show Full DPS + Phys DPS + Elemental DPS, even in Hidden mode
![Awakened_PoE_Trade_8x5cOa5pOT](https://user-images.githubusercontent.com/5741155/188279885-ebc8ae60-dc53-416b-aefa-ac9fd826f3ea.png)
![Awakened_PoE_Trade_LAOgcWzfkd](https://user-images.githubusercontent.com/5741155/188279915-920a3866-b0c2-4127-97c2-5325b025de6d.png)
