### ISSUE TITLE
Getting price prediction stuck sometimes

### ISSUE THREAD

**Issue by ggarcia00** [SnosMe/awakened-poe-trade#1181]
When I check an item from the overlay sometimes it takes about 1-2 seconds for the prediction from poeprice to show up, while most times, it keep stuck in "Getting price prediction".

While if I go directly to poeprices.info and paste the item, I get the result instantly almost every time.

Should this be happening or there is something wrong with my install?

**Comment by SnosMe** [comment]
yep random 1-2seconds is usual for poeprices, especially on league launch.
