### ISSUE TITLE
The "Fill Stat Values" option doesn't work correctly

### ISSUE THREAD

**Issue by braseidon** [SnosMe/awakened-poe-trade#1184]
If a modifier has the maximum roll within its tier, Awakened will pre-fill that ceiling number for any modifier while price checking. This is far from optimal when price checking.

**Comment by SnosMe** [comment]
> This is far from optimal 

Why?

**Comment by braseidon** [comment]
If a mod's tier can roll from 14 to 18, in my opinion, you wouldn't only search trade for 18 and up. Obviously this can differ per item. In general, I think people would rather be checking the minimum of the tier, or a variable amount based on the 'Fill stat values' option. This was the way price checking worked with Awakened before this league.. so I'm not sure if the change was intentional.

Let me know if I need to elaborate xD

**Comment by SnosMe** [comment]
> change was intentional

one change in that area was adding "perfect rolls", but I don't see it affecting anything else other than these perfect rolled mods. The only thing I might need to tweak is to apply it only to fractured mods.

Can you show example item where you consider this behaviour unwanted, maybe i'm missing something.

**Comment by braseidon** [comment]
It's just a bit awkward checking prices on some items where tier 1 is the only tier for a mod. First examples I can think of are base jewels, or attack speed suffix on rings, or some flask mods. Another example would be perfect t1 resistance on an armor piece. In my opinion, searching perfect rolled t1 res isn't important as just searching the same tier. Buyers could immediately harvest swap the res to another, or a perhaps few percent won't break their build. For a lot of mods, I feel like it's more likely to not matter if it's a perfect t1 roll, vs just being in the t1 range.

On the other hand, this wouldn't be the case for checking +1-2 all spell skill gems on a staff, or # of targets that projectiles pierce on Shaper boots, etc. I could get you a list of mods I feel like should be specific if you need it

These thoughts are preferential and will surely differ from person to person, so I'm just giving my two cents. I appreciate all the work you do on amazing tool!
