### ISSUE TITLE
CTRL + W disabled on windows 11

### ISSUE THREAD

**Issue by oosnyt** [SnosMe/awakened-poe-trade#1187]
Awekened trade disables CTRL + W key shortcut for everything on windows 11.

**Comment by SnosMe** [comment]
i'm on win11 and nothing it's not disabled

**Comment by oosnyt** [comment]
Yup was bit hasty, problem was fixed by updating samsung 990 pro firmware, but also it was only poe awekned trade that caused this behaviour.
