### ISSUE TITLE
Doesn't work with virtual desktop 

### ISSUE THREAD

**Issue by Conusoid** [SnosMe/awakened-poe-trade#119]
Hi! I'm using Ubuntu 18.04.4 LTS and Lutris to play POE. In order to solve some minor problems with the game I've been playing with "Virtual desktop" feature. Recently I was using POE Trade Macro (for windows) and it worked fine but today I found out about APT and its Linux version. For some reason it doesn't work with virtual desktop at all (even F* shortcuts). With vdesktop turned off it works fine. Just so you know.
I really hope most of the problems was solved by implementing Vulkan and will try to just play it without vdesktop =)

**Comment by SnosMe** [comment]
What is a Virtual desktop?

**Comment by Conusoid** [comment]
Virtual desktop is a wine setting. With it enebled, created windows are confined to a single window (the "virtual" desktop window). Windows within a virtual desktop are not decorated or managed by window manager. Very useful in some cases :)
Nontheless all the problems that were solved by the virtual desktop disappeared when using the vulkan renderer. So if no one else doesnt doesn't experience such problem, you can close this issue. Thanks for ur reply!
