### ISSUE TITLE
Changing key of " price checking without closing" to middle mouse or shift

### ISSUE THREAD

**Issue by duncandutchgame** [SnosMe/awakened-poe-trade#1191]
I've noticed that you cannot bind it to shift or middle mouse button for example, is there a reason for it? I've been using CAPS for a while but I really want to swap out of it cause even if i turned off capslock, it will still typ in caps unless i tab out of the game

**Comment by SnosMe** [comment]
I can't add support for mouse buttons. Standalone modifer key (Shift) can't be supported too.
