### ISSUE TITLE
Window with settings

### ISSUE THREAD

**Issue by Conusoid** [SnosMe/awakened-poe-trade#120]
Hi! I'm using Ubuntu 18.04.4 LTS with Regolith DE (some kind of i3wm) and currently don't have any "tray" at all. So when I'm starting APT nothing really happens on the screen. I'm steel able to do some configuration through the ~/.config/...config.json, but I wonder if there any possibility to get some kind of window on the start of APT in future releases?

**Comment by SnosMe** [comment]
Look for solutions in #70 and #106

**Comment by Conusoid** [comment]
There's some kind of misunderstanding :D With GNOME I have tray icon but I'm not using gnome. When I said that I don't have any "tray" on my i3wm I meant that - not using tray. So I just asked about possibility of getting some separate window :)
