### ISSUE TITLE
Harvest league not available?

### ISSUE THREAD

**Issue by FyuriusRyage** [SnosMe/awakened-poe-trade#121]
OK maybe I am missing something simple, but this isn't working for me in Harvest league.  When I check the league setting, it shows Delirium (options Std/HC/Delirium/HC Delirium).

Not sure what to do?

**Comment by SnosMe** [comment]
Restart awakened.

![image](https://user-images.githubusercontent.com/4292308/85204763-6189cb80-b31f-11ea-9a27-09b0b204132c.png)

**Comment by FyuriusRyage** [comment]
Thank you!!! appreciate your work, looking forward to trying this out now.

    On Saturday, June 20, 2020, 8:56:50 AM MDT, Alexander Drozdov <notifications@github.com> wrote:  
 
 


Restart awakened.
