### ISSUE TITLE
[Windows 11] Key mapping: set and display incorrect when using non-qwerty layout

### ISSUE THREAD

**Issue by umbravi** [SnosMe/awakened-poe-trade#1213]
Given a non-qwerty layout on Win11, 
When setting a key-bind,
the UI uses the qwerty key location.

This only impacts setting key-binds.
Key-bind use is correct.

Ex:
To set `ctrl+x` using Dvorak, `ctrl+q` must be pressed.

**Comment by SnosMe** [comment]
Duplicate of #447
