### ISSUE TITLE
Awaken POE Trade Starting but not working and showing nothing. 

### ISSUE THREAD

**Issue by UnseenScythe** [SnosMe/awakened-poe-trade#1218]
Hello, I downloaded this and it worked perfectly. I wanted to change the hotkey to search items to I edited the config file, the one that pops up when you click the icon in your tray.

After I edited the config the app stopped working, I was also not able to revert it back. 

When I say stop working I want to clarify that the app runs in the background still, but none of the hotkeys work and when I click "Open in browser" it just takes me to a page with nothing on it. 

Things I have tried:
- Uninstall / Reinstall
- Hard delete the file out the AppData and Install location, emptied recycling bin, restarted computer and reinstalled
- Copied a working config file from a friend and replaced mine with the working one

Unfortunately I still cannot get it to work anymore. Any help would be greatly appreciated.

**Comment by UnseenScythe** [comment]
I would also like to add that the overlay is not working as well, so I can't use shift + space in POE to check the logs like in your issues guide.

**Comment by SnosMe** [comment]
check your pc for ghosts :) removing config literally resets APT, if it didn't work I have nothing to say

**Comment by UnseenScythe** [comment]
Hello, it's crazy how reading the issues page will help.

Hard deleting the folder out of AppData and clearing the %appdata%  and then re-installing solved this issue. That is my bad for assuming AppData and %appdata% were the same thing. 

I appreciate you taking the time to reply!
