### ISSUE TITLE
Can't change league and no explanation of how to exit app so that update will occur.

### ISSUE THREAD

**Issue by tyler13ho** [SnosMe/awakened-poe-trade#122]
Is there a way to change the league in which prices are pulled from? Also, I received a prompt for an update saying that it would update upon exiting the app, but there is no hotkey for exiting the app that I am aware of and force closing the app does not cause it to update upon reopening.

**Comment by SnosMe** [comment]
Icon in tray.

![image](https://user-images.githubusercontent.com/4292308/85220273-c80bf980-b3b2-11ea-8fde-46ee50abbfa1.png)

**Comment by tyler13ho** [comment]
Oh wow, didn't even realize there was an icon in the tray! Thank you!
