### ISSUE TITLE
Awakened poe trade quit unexpectedly

### ISSUE THREAD

**Issue by bankinobi** [SnosMe/awakened-poe-trade#1222]
Hello
Trying to run latest version 3.23.10002 on m1
Both from release page and locally build
<img width="490" alt="image" src="https://github.com/SnosMe/awakened-poe-trade/assets/28591219/fedf0fe4-f7af-411c-b32c-62637a24b284">
<img width="846" alt="image" src="https://github.com/SnosMe/awakened-poe-trade/assets/28591219/84f8be61-2209-43a0-ac78-347ddbd206a6">
<img width="225" alt="image" src="https://github.com/SnosMe/awakened-poe-trade/assets/28591219/51016326-7289-4c01-b983-6eff4f136c5a">

**Comment by Ineigo** [comment]
Hello, I have the same problem

**Comment by bankinobi** [comment]
This works for me
https://github.com/SnosMe/awakened-poe-trade/issues/1153#issuecomment-1848320380
