### ISSUE TITLE
Pop up disappears instantly when I move the mouse.  

### ISSUE THREAD

**Issue by ost3g0** [SnosMe/awakened-poe-trade#123]
1.30 - poe in DX11 or Vulkan - borderless full screen win 10.  the second i move my mouse after control+D it disappears.

**Comment by askanymark** [comment]
@ost3g0 Use Ctrl + Alt + D

**Comment by SnosMe** [comment]
@ost3g0 It is intended. Please carefully read README

![image](https://user-images.githubusercontent.com/4292308/85220298-03a6c380-b3b3-11ea-8255-b30c22bdbda5.png)

**Comment by BunnyTheLifeguard** [comment]
I don't even touch the mouse and it disappears after a second or so :D

**Comment by SnosMe** [comment]
@BunnyTheLifeguard #172

**Comment by BunnyTheLifeguard** [comment]
> @BunnyTheLifeguard #172

My bad, I had fullscreen, not windowed which was causing the problem for me.
