### ISSUE TITLE
Awakened Poe Trade quit unexpectedly

### ISSUE THREAD

**Issue by dinfyru** [SnosMe/awakened-poe-trade#1232]
Apple M1 Max 32GB
14.2.1 (23C71)
Awakened-PoE-Trade-3.23.10002-universal.dmg
[Poe Trade log.txt](https://github.com/SnosMe/awakened-poe-trade/files/13797426/Poe.Trade.log.txt)
![image](https://github.com/SnosMe/awakened-poe-trade/assets/10163112/e07e2cfb-1344-478e-83ef-5d08f97cca4b)

**Comment by jakuzure** [comment]
did you find a fix for this? I'm having the same problem
