### ISSUE TITLE
Relevance of Magic Jewels

### ISSUE THREAD

**Issue by urzbs** [SnosMe/awakened-poe-trade#1233]
Hey, 

Case 1: Fractured Bases

Issue: Currently, identifying hundreds of fractured bases can be time-consuming. It would be incredibly helpful to have a feature setting that, by default, includes the fractured mod in search. Alternatively, the option to toggle hidden mods through a setting (as a new default) would streamline the process.

Case 2: Relevance of Magic Jewels

Issue: With the introduction of the "Adorned" Jewel, magic jewels have become more relevant than rares. To address this shift, it would be beneficial to have an option that automatically sets the correct rarity when conducting price checks. Many rare jewels that were previously considered Best in Slot (BIS) are no longer optimal, requiring users to manually adjust the rarity on trade websites.

If any of these settings already exist and I've overlooked them, kindly let me know.

Thanks

**Comment by SnosMe** [comment]
Agree with Magic Jewels.

Don't see the issue with fractured items, you identify them in inventory and watch the mod tier  in the game, it's quite rare to see T1 mod. What I can probably help is to select BaseItem tab by default for fractured items?

**Comment by urzbs** [comment]
Thank you for answering. 

I know that mostly looking for T1 fractured mods is profit. 
The base Item Tab helps here a lot (did not know that it would automatically also include the fracture).

Im currently pricechecking fractured stuff for my guildies, they are new players they know nothing about the game.
Now it is a bit easier for them by just using the tool and looking into BaseItem Tab.
