### ISSUE TITLE
Fracture Check Needed

### ISSUE THREAD

**Issue by TwoStonedBrilliance** [SnosMe/awakened-poe-trade#1238]
Situation that lead me to discover this issue - 

Dropped 12 passive bow large cluster jewel ilvl84 

Used Awakened trade to p/c - This is the trade link it generates - https://www.pathofexile.com/trade/search/Affliction/QbvjB7wTw

But this is incorrect because the one I dropped is not fractured = bricked

Correct search setting = fractured item set to no - https://www.pathofexile.com/trade/search/Affliction/0d5Ma8gcg

Fracture check is needed for items to avoid comparing to bricked items where people have tried to fracture 35% effect etc

Thanks

**Comment by SnosMe** [comment]
I agree with this one.

**Comment by SnosMe** [comment]
Added, but keep in mind that this filter will only apply if you have BaseItem tab active.

![image](https://github.com/SnosMe/awakened-poe-trade/assets/4292308/e4f87a0a-a56d-4041-9cba-18dfe2362a0c)
