### ISSUE TITLE
Changing keybind for "Show Advanced Item Descriptions" bricks pricecheck feature

### ISSUE THREAD

**Issue by Spazz** [SnosMe/awakened-poe-trade#1239]
If you change the keybind for "Show Advanced Item Descriptions" away from "Alt" to a mouse button then Pricecheck is no longer able to identify the stats on an item. Reviewing the debug, this is because it is not tracking mouse buttons so it is not able to simulate the advanced tooltip.

Can you update this so it also reads mouse buttons?

**Comment by SnosMe** [comment]
nope, mouse buttons can't be integrated

**Comment by Spazz** [comment]
Unfortunate, thanks for the reply!
