### ISSUE TITLE
Copy item when price check item

### ISSUE THREAD

**Issue by SayPauPau** [SnosMe/awakened-poe-trade#1240]
When i press key for price check programm automatically presses buttons for copy item that I don't press. Its work wtich any keys
![изображение_2024-01-01_180239057](https://github.com/SnosMe/awakened-poe-trade/assets/155371571/9dd063e0-01eb-41c9-a52c-01ad9dd7f680)

**Comment by SnosMe** [comment]
Look at the image here https://snosme.github.io/awakened-poe-trade/nothing-happens.html
