### ISSUE TITLE
Logo for POE Discord broken in Settings -> About

### ISSUE THREAD

**Issue by ealmen** [SnosMe/awakened-poe-trade#1241]
![](https://i.imgur.com/fktGQ5x.jpg)

Looks like POE Discord changed it's logo. The old URL givs me a http 404 error.
New URL should be:
https://cdn.discordapp.com/icons/174993814845521922/c8d02f8ad79b006dabfd27a026f102dc.webp?size=32
Right?

**Comment by SnosMe** [comment]
Yeah, relying on discord was not the best idea, will copy them here ;)
