### ISSUE TITLE
Error after 3.23.10004 installed

### ISSUE THREAD

**Issue by Scuun** [SnosMe/awakened-poe-trade#1261]
I am getting this error after i installed 3.23.10004
And this pops off every 10 minutes when awakener trade is running or i wanna search for a item

<img width="394" alt="error" src="https://github.com/SnosMe/awakened-poe-trade/assets/156623457/1cdf9320-993c-46d5-95ed-b7cfe5e08b7a">

**Comment by SnosMe** [comment]
not very descriptive error :(
let me guess, you also don't have prices loaded from poe.ninja?

**Comment by Scuun** [comment]
I installed it yesterday 3-4 times and everytime the same problem.
When i was searching it poped the error window and no price was shown.

Today i installed all again (3.23.10002 to 3.23.10004) and the problem seems gone for now.
Idk what it was. I never had a problem with it for years

**Comment by Scuun** [comment]
Still same problem.
When i start the tool, error
When i search something, error

I never had any problems. Version 3.23.10002 and 3 work fine

<img width="392" alt="error2" src="https://github.com/SnosMe/awakened-poe-trade/assets/156623457/a97e6b8e-3b2f-4387-a8ea-2513e95c6a5b">

**Comment by SnosMe** [comment]
Do you have divine price from poe.ninja in these older versions?
![image](https://github.com/SnosMe/awakened-poe-trade/assets/4292308/3c97cc2b-c101-4fa7-9fd0-be428c60cbb8)

**Comment by Scuun** [comment]
In 3.23.10003 it was shown normal everytime i checked price. But in 3.23.10002 it sometimes was empty or not shown like on the pic. But 10002 had no error. It was only empty sometimes.

**Comment by SnosMe** [comment]
https://github.com/SnosMe/awakened-poe-trade/releases/tag/v3.23.10003
you will need to disable updates in settings tho

**Comment by SassyBeard** [comment]
Same thing is happening to me, I'm rolling back.
updates lately have been super sketchy, I wonder what's going on.

**Comment by 20of** [comment]
Had this too, had to go back to .10003
It will almost brick your windows, since APT is always on top, and it stays there when error comes. could not even kill it from task manager since its on top of it. after some time I realized that i could alt tab into error and press enter, unbricking it.

**Comment by JinY07** [comment]
I kept getting errors all day after updating to .10004 and then found this thread and rolled back to .10003, which fixed it for me :)
Can someone tell me how to disable the auto-update in settings?  I looked in the overlay cog but can't seem to find it??

**Comment by IrmatDen** [comment]
To anyone stuck there and accepting to revert to .10003 and disable auto-updates, we can see in the sourcecode ([link](https://github.com/SnosMe/awakened-poe-trade/blob/master/main/src/AppUpdater.ts))  that it seems there are a few ways:

- run the app on mac os (system named 'darwin')
- run the app as a portable app: for this one, I'm not sure if the non-setup exe in the releases is a portable app or not; it might be worth trying
- or use the command line argument "--no-updates" when running Awakened POE trade

I chose to use the command line argument, so the basic rundown for this is:

1. uninstall .10004
2. install the .10003 BUT DON'T RUN IT AT THE END (=> **you must uncheck the option!**)
3. edit the start menu shortcut (or whatever shortcut you're using), and add " --no-updates" to the target (please keep the space between the exe and the argument)

![image](https://github.com/SnosMe/awakened-poe-trade/assets/4919540/04bd72dd-17c9-445e-ad50-8029709c897e)

**Comment by 20of** [comment]
Or just download the non-setup version from https://github.com/SnosMe/awakened-poe-trade/releases/tag/v3.23.10003

**Comment by IrmatDen** [comment]
Yes, it seems to be the "portable" build. But with this approach, you can't restore automatic updates once this .10004 bug has been solved, you'll have to keep updating manually.

**Comment by Bhlynd** [comment]
Posting this link here as this issue seems relevant to 1269.

The problems seems to be with price prediction.

https://github.com/SnosMe/awakened-poe-trade/issues/1269#issuecomment-1907028193

**Comment by SnosMe** [comment]
The error is now logged rather than thrown in your face.

**Comment by IrmatDen** [comment]
Thank you!
