### ISSUE TITLE
Remember Buyout Currency Not Working?

### ISSUE THREAD

**Issue by FeralRage7** [SnosMe/awakened-poe-trade#1264]
I may have the features mixed up but when I search for things for specific things (scarabs, harvest juice for two examples), they usually come back in Divine prices and I click over to chaos. Jewelers and essences seem to return value in chaos orbs.

I checked the "Remember Buyout Currency" under Price Check options and clicked save. I restarted the app and the selection persisted. However, still when I search for things, divine comes up as the first value. I understand this is probably preferred for bulk selling.

Can I pick chaos orb as default value for all currency searches?

![image](https://github.com/SnosMe/awakened-poe-trade/assets/61394919/6632aea2-1a3d-4bba-950a-ae8ed7fb04de)
![image](https://github.com/SnosMe/awakened-poe-trade/assets/61394919/79d234fc-f074-4a54-bd29-8ff1b992e292)

v3.23.100004

**Comment by SnosMe** [comment]
Duplicate of #1225
