### ISSUE TITLE
After launch awakened poe trade appear an error java script

### ISSUE THREAD

**Issue by ShunRei71** [SnosMe/awakened-poe-trade#1269]
![error java script](https://github.com/SnosMe/awakened-poe-trade/assets/157188002/ac38b851-0784-49a4-a31f-88f96d66f079)

Windows 10 Pro 64-bit (10.0, Build 19045) (19041.vb_release.191206-1406)

 Application Error 
 
  - EventID 1000 

   [ Qualifiers]  0 
 
   Version 0 
 
   Level 2 
 
   Task 100 
 
   Opcode 0 
 
   Keywords 0x80000000000000 
 
  - TimeCreated 

   [ SystemTime]  2024-01-20T03:40:21.3381558Z 
 
   EventRecordID 12933 
 
   Correlation 
 
  - Execution 

   [ ProcessID]  0 
   [ ThreadID]  0 
 
   Channel Application 
 
   Computer DESKTOP-M2VI62O 
 
   Security 
 

- EventData 

   Awakened PoE Trade.exe 
   3.23.10004.0 
   64da7847 
   KERNELBASE.dll 
   10.0.19041.3930 
   9141f979 
   c0000602 
   000000000012db22 
   26b4 
   01da4b4ce310b4dd 
   C:\Program Files\Awakened PoE Trade\Awakened PoE Trade.exe 
   C:\Windows\System32\KERNELBASE.dll 
   c8fe2bb5-7b05-49c4-833d-71da54e7a5d9

**Comment by deadlyeye79** [comment]
i do have the same issue
Version 3.23.10004, Win11 Pro v.23H2

**Comment by SnosMe** [comment]
https://test-ipv6.com/

**Comment by ShunRei71** [comment]
seems like ipv6 is not active at all but it's active

**Comment by SnosMe** [comment]
ok, so you have ipv4 but app for some reason want to connect using ipv6, that's bad

**Comment by ShunRei71** [comment]
no,
i ve ipv6 , by the test seems like is not active but by checking the router it's active

**Comment by ShunRei71** [comment]
fixed by brought the router back to the factory settings, and make ipv6 active again.

thank you very much.

**Comment by 20of** [comment]
I think this might be same issue as with #1261
I got multiple error messages, including this one, and I do not have ipv6

**Comment by BomarM** [comment]
same as me, had to roll back

**Comment by BomarM** [comment]
any idea of when a fix will come?

**Comment by Aphotic** [comment]
> ok, so you have ipv4 but app for some reason want to connect using ipv6, that's bad

![image](https://github.com/SnosMe/awakened-poe-trade/assets/30921064/fd0f2936-c086-4885-9517-5aa32950dc9d)
I am having the same issue and i have disabled ipv6 totally(its useless here in my place) from my connection settings in the control panel network and sharing Windows 10
![image](https://github.com/SnosMe/awakened-poe-trade/assets/30921064/f9aa5047-972a-4c79-bbbf-01d34a567a52)

**Comment by Juts2** [comment]
Same issue, no IPV6 either.

**Comment by Bhlynd** [comment]
After investigating this same issue I have, I have found that poeprices.info is being blocked as phishing/malicious. This is used to price check.

https://www.virustotal.com/gui/url/a945173f364a26e202f1b2a2d397adc89a01ed539a8bfaff879976dac6a1ec12?nocache=1

**Comment by Juts2** [comment]
> After investigating this same issue, I have found that poeprices.info is being blocked as phishing/malicious. This is used for price prediction.
> 
> https://www.virustotal.com/gui/url/a945173f364a26e202f1b2a2d397adc89a01ed539a8bfaff879976dac6a1ec12?nocache=1
> 
> Disabling it in the config resolves the issue for me. ![image](https://private-user-images.githubusercontent.com/33144881/299123476-fb4a1e57-922b-4ba5-a3ad-4eddffdbc427.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNjMzMjgsIm5iZiI6MTcwNjA2MzAyOCwicGF0aCI6Ii8zMzE0NDg4MS8yOTkxMjM0NzYtZmI0YTFlNTctOTIyYi00YmE1LWEzYWQtNGVkZGZmZGJjNDI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDAyMjM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjNjA4Njc3ODZkYjQ4N2U3YTBiYzE0YzBkNzY3MzMxYjRhMTEwMDA3N2ZhOGJhNGQ1ZDg3Y2Q3NDEyOGYyMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uPNOAfitbrOYb-_C6oHpt7lyq6kmaWepbPE1w7JLOPc)

I do not have that box ticked and have had the issue for a few days.

**Comment by Bhlynd** [comment]
> > After investigating this same issue, I have found that poeprices.info is being blocked as phishing/malicious. This is used for price prediction.
> > https://www.virustotal.com/gui/url/a945173f364a26e202f1b2a2d397adc89a01ed539a8bfaff879976dac6a1ec12?nocache=1
> > Disabling it in the config resolves the issue for me. ![image](https://private-user-images.githubusercontent.com/33144881/299123476-fb4a1e57-922b-4ba5-a3ad-4eddffdbc427.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNjMzMjgsIm5iZiI6MTcwNjA2MzAyOCwicGF0aCI6Ii8zMzE0NDg4MS8yOTkxMjM0NzYtZmI0YTFlNTctOTIyYi00YmE1LWEzYWQtNGVkZGZmZGJjNDI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDAyMjM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjNjA4Njc3ODZkYjQ4N2U3YTBiYzE0YzBkNzY3MzMxYjRhMTEwMDA3N2ZhOGJhNGQ1ZDg3Y2Q3NDEyOGYyMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uPNOAfitbrOYb-_C6oHpt7lyq6kmaWepbPE1w7JLOPc)
> 
> I do not have that box ticked and have had the issue for a few days.

It is possible that the resolution i gave is more related to the issue in #1261. Happy for it to be moved there not to confuse.

**Comment by SnosMe** [comment]
The error is now logged rather than thrown in your face.
