### ISSUE TITLE
3.23.10004

### ISSUE THREAD

**Issue by Lonely1599** [SnosMe/awakened-poe-trade#1270]
3.23.10004 version stop working when i enable vpn with smart route, previous version works fine with smart route

**Comment by SnosMe** [comment]
no, previous versions didn't work fine. they were just silent about any network error.

**Comment by Lonely1599** [comment]
okay, version 3.23.10003 works fine for me:) can i somehow disable auto update?

**Comment by SnosMe** [comment]
yes https://snosme.github.io/awakened-poe-trade/cmd-flags.html

**Comment by Lonely1599** [comment]
thank you
