### ISSUE TITLE
Trade Overlay inputting wrong value during price check

### ISSUE THREAD

**Issue by Integratores** [SnosMe/awakened-poe-trade#1271]
So I was buying some Ursine Charms with Elemental Res penetration and saw that every now and again people where selling 4% ones for the price of 3% ones. When i was checking one of the ones i bought with Awakened POE i saw that the input for what it was showing was 3% instead of 4%.

![image](https://github.com/SnosMe/awakened-poe-trade/assets/129285342/cd146f9a-7b8c-472d-a76e-561661c69f15)

im not sure if it just defaults to the lowest value for that tier or something, but its a difference of 100% for this charm.

**Comment by SnosMe** [comment]
not applying % to unmodifiable magic items seems ok, will change that
