### ISSUE TITLE
Windows closing automatically, sometimes they don't open at all. 

### ISSUE THREAD

**Issue by Oddwin** [SnosMe/awakened-poe-trade#1272]
Hi there, 

Been using this program for leagues upon leagues now. This morning when I got up I had a strange issue. 

**When I hit CTRL+D the window flashes up, however, as soon as I move my mouse it closes.** 

Things I have tried:

-Holding CTRL while moving the mouse
-Toggling Autoclose
-Computer restart
-Changing the hotkeys
-Uninstalling and deleting %appdata%
-Reinstall
-Launching ONLY POE and APOET
-Searching Google/Reddit for 30 mins to see if anyone has a similar problem
-Attempting to figure out how to navigate Discord to find anyone to talk to about his issue with no luck. (Tried through TFT and POE)
-Followed this twice https://snosme.github.io/awakened-poe-trade/issues

It worked fine before bed last night... 

Thank you for taking the time to read this, and thank you in advance for any help/suggestions you may have. 

***FIX***

I managed to somehow tag the settings button after spamming SHIFT+SPACE for what felt like 10 mins. I completely disabled Autohide and now it works with CTRL+D

I don't know how or why this worked suddenly...

**Comment by SnosMe** [comment]
The issue is in whatever system changes were made on your end.
