### ISSUE TITLE
Linux KDE screenblur constant and won't close

### ISSUE THREAD

**Issue by PhantomStryk** [SnosMe/awakened-poe-trade#1273]
I am playing POE on Garuda Linux with KDE as my GUI. When I launch awakened Poe along side POE blurs my game as long as Poe is my active tab. My clicks go through the blur to the game but not able to see anything.

**Comment by SnosMe** [comment]
You should look into compositor settings and disable any blurry backgorund effects for APT window/enable transparency. This is as much I can provide help.
