### ISSUE TITLE
Ruthless as private league name not saved

### ISSUE THREAD

**Issue by SnosMe** [SnosMe/awakened-poe-trade#1275]
@SnosMe after each software restart needed to type ruthless or private league again. Can you please make it saved?

_Originally posted by @goldmango in https://github.com/SnosMe/awakened-poe-trade/issues/1155#issuecomment-1905193638_

**Comment by Sykh** [comment]
Adding ruthless as permanent checkbox would be nice aswell :)

It gets listed at
https://api.pathofexile.com/league

**Comment by SkySniper** [comment]
Need change function
function isPrivateLeague (id: string) {
  return /\(PL\d+\)$/.test(id)
}
https://github.com/SnosMe/awakened-poe-trade/issues/1344
