### ISSUE TITLE
ETIMEDOUT poe.ninja

### ISSUE THREAD

**Issue by lelo1480** [SnosMe/awakened-poe-trade#1276]
My friend have decimals on divine ratio for example 0,5div is 100c and i dont have it, Reinstalled app , used mobile version , deleted poe awakened folder in appdata.
How to add such feature or turn it on ?
left is my friend , right is mine
![issue](https://github.com/SnosMe/awakened-poe-trade/assets/157624289/1995ea39-0cae-4655-bbeb-497aded1abb8)

**Comment by SnosMe** [comment]
if you have the latest 3.23.10005 then look into logs (in settings -> debug)

**Comment by lelo1480** [comment]
![obraz](https://github.com/SnosMe/awakened-poe-trade/assets/157624289/849f0a49-10f4-4b7d-895b-337fa451146c)

**Comment by SnosMe** [comment]
Here another option just become available because I updated Electron,
https://www.electronjs.org/docs/latest/api/command-line-switches#--dns-result-orderorder

**Comment by lelo1480** [comment]
Disabled Ipv6 - i dont use shortcuts from desktop but from downline . Dunno where to put this nds thingi .
Thanks for help :)
