### ISSUE TITLE
Bug: Evasion not being shown correctly

### ISSUE THREAD

**Issue by Reithan** [SnosMe/awakened-poe-trade#128]
![image](https://user-images.githubusercontent.com/7475701/85372053-1c63c600-b4e6-11ea-9ddf-e7bcca777b6e.png)

This armor has 788 evasion, but overlay is showing it as having 945

**Comment by SnosMe** [comment]
945 is (788 + 20% of item quality).
850 is (945 - 10% that is configurable in settings).

You may not know, but trade site treats items < 20%q as 20%q, it is indeed correct behavior.

![image](https://user-images.githubusercontent.com/4292308/85378678-8bbbd300-b543-11ea-8146-19efa3149927.png)
