### ISSUE TITLE
can't develop the procedure

### ISSUE THREAD

**Issue by Traveller-hongchen** [SnosMe/awakened-poe-trade#1284]
I can‘t use “yarn dev” to develop the procedure after 10004
vite ： connect ECONNREFUSED 127.0.0.1:8584

**Comment by SnosMe** [comment]
Nothing changed, you just forgot to yarn dev in /main folder

**Comment by SnosMe** [comment]
well, one more line was changed, but I doubt it's the reason https://github.com/SnosMe/awakened-poe-trade/commit/59e3302387214d85c9feba075f0deed0d5b3bc53

![image](https://github.com/SnosMe/awakened-poe-trade/assets/4292308/97c30ab9-c6bf-4b9f-8a86-cf32421de2a9)

**Comment by Traveller-hongchen** [comment]
I seem to understand why，It seems that I didn't close the app that I had already opened
