### ISSUE TITLE
not loading some info

### ISSUE THREAD

**Issue by belph93** [SnosMe/awakened-poe-trade#1287]
hi, when i press Alt+D to check a price the divine orb price on top left corner is not showing it keeps like loading and never shows up same for the recomended price of an item.. any idea why this might be happening ? the prices of the items listed by ppl are the only ones showing 

PD: same problem with every single item

**Comment by belph93** [comment]
![image](https://github.com/SnosMe/awakened-poe-trade/assets/61531909/a5bacdbd-4257-4ded-b161-3352782b7092)

**Comment by SnosMe** [comment]
check logs and #1276
