### ISSUE TITLE
Keybinds broken for macOS

### ISSUE THREAD

**Issue by emilnissa** [SnosMe/awakened-poe-trade#1289]
In order to use Awakened PoE Trade as an app, instead of running from Terminal, which is crashing right on start, do the following in Terminal:

`sudo xattr -r -d com.apple.quarantine /Applications/Awakened\ PoE\ Trade.app`
and
`codesign --force --deep --sign - /Applications/Awakened\ PoE\ Trade.app`

Then, make sure Awakened PoE Trade is added in the list in `Settings -> Privacy and Security -> Accessibility`. If it is added automatically via running the app, remove it from the list and add it manually.

_Originally posted by @tiltshiftfocus in https://github.com/SnosMe/awakened-poe-trade/issues/1153#issuecomment-1951861701_

This original issue tracked several things, creating a new issue for what bugs me at the moment.

I get the application to run and respond (shift+space while in PoE) but the keybind for price-check doesn't do anything. I've tried changing the keybind but it doesn't do anything.

**Comment by SnosMe** [comment]
https://snosme.github.io/awakened-poe-trade/nothing-happens.html
