### ISSUE TITLE
Cannot use space when editing text in widgets

### ISSUE THREAD

**Issue by dcgaines** [SnosMe/awakened-poe-trade#129]
With the overlay in the new 2.0 update, when naming a widget space still closes the overlay, which prevents you from using a space in the name of a widget. Not a huge issue but thought I'd mention it.

**Comment by SnosMe** [comment]
Thank you, it is super important bug actually. The only way to fix is remove a way to close using Space.

**Comment by dcgaines** [comment]
Is there a way to do that manually or only in development?

**Comment by SnosMe** [comment]
Hardcoded, so wait for update/hotfix

**Comment by SnosMe** [comment]
Fixed in v2.1
