### ISSUE TITLE
No Keyboard inputs Accepted after Map Mod Search

### ISSUE THREAD

**Issue by defekT1312** [SnosMe/awakened-poe-trade#1299]
I'm Looking for Map Mods via Shortcut and afterwards poe doesn't accept any Keayboard input anymore but closing the Game with Alt + F4 works.

Please tell me how I can help troubleshooting this.

I'm on OpenSUSE Tumbleweed and newest awa Trade version

**Comment by SnosMe** [comment]
linux is in complicated state, if it doesn't work easier just to give up

**Comment by sfinseth** [comment]
> linux is in complicated state, if it doesn't work easier just to give up

I wish you'd reconsider this statement and at least try to look into it.. I have no keyboard input at all on arch linux with as soon as I open awakened poe trade :frowning_face:
