### ISSUE TITLE
Add POE SSID setting

### ISSUE THREAD

**Issue by vadash** [SnosMe/awakened-poe-trade#13]
So we wont get limited on search requests

**Comment by SnosMe** [comment]
GGG allows you to make 12 requests in the interval of 6 seconds. This is insane speed for human action.

Therefore, the only reason for implementing POESESSID if you share an IP address with other people. And they also play POE, and at the same time (seconds) also check prices. It is difficult to imagine such a situation. Game club?

**Comment by vadash** [comment]
That was probably poe prices ML lagging. Nothing can be done here
