### ISSUE TITLE
Cant use awakened poe trade version 3.23.10003 and up

### ISSUE THREAD

**Issue by J3muzu** [SnosMe/awakened-poe-trade#1306]
After the 3.23.10003 version I cant mange to make it work. If I use the 3.23.10002 it works fine. Anyone has the same problem as me. Please help. If I open the browser, "This site can’t be reached, localhost refused to connect." http://localhost:51669/

**Comment by SnosMe** [comment]
looking at the changes made in 3.23.10003, I don't find any connection to this issue.
so far I think only VPNs prevented connecting to localhost

**Comment by micheilsgrey** [comment]
Same problem for me. I having this issue on the version since 3.23.10004. And I just installed last version 3.24. Poe trade not working for me. Same error in browser "This site can’t be reached, localhost refused to connect."  3.23.10003 working fine.

**Comment by micheilsgrey** [comment]
> Looking at the changes made in 3.23.10003, I don't find any connection to this issue. so far I think only VPNs prevented connecting to localhost

I use a VPN. But now, the question. Why 3.23.10003 working fine with VPN, and all other versions up to the latest are not?

**Comment by J3muzu** [comment]
> looking at the changes made in 3.23.10003, I don't find any connection to this issue. so far I think only VPNs prevented connecting to localhost

Thank you is works now. I remember using a blocker on my VPN, maybe it affected the app since I set it up to block all app except POE. I have this problem since last league. Thank you again sir!
