### ISSUE TITLE
Overlay enables on any window named "Path of Exile" including windows file explorer

### ISSUE THREAD

**Issue by skillrax** [SnosMe/awakened-poe-trade#1311]
![Issue_evidence](https://github.com/SnosMe/awakened-poe-trade/assets/35474631/8aef5287-7451-487b-869b-8f1925a4bcf8)

Seen here, the overlay announced itself when I opened the root directory of the POE install. I pressed the overlay settings hotkey and it worked to bring up the menu. 

Doesnt seem harmful, but clearly not intended.

**Comment by pitoriex** [comment]
Haha, the lowkey IDA shortcut icons 😂

**Comment by SnosMe** [comment]
Duplicate of #776
