### ISSUE TITLE
Alflame ember error parsing

### ISSUE THREAD

**Issue by KostiantynBoiar** [SnosMe/awakened-poe-trade#1318]
When I'm trying to see how much any Alframe ember is on the market I get an error message about parsing the item

![image](https://github.com/SnosMe/awakened-poe-trade/assets/97537403/8ecc396a-bff3-4538-b2f1-ac46d537f48e)

**Comment by SnosMe** [comment]
Maybe because you should pay attention about the update at the top.

**Comment by KostiantynBoiar** [comment]
Yeah, that makes sense 😸
