### ISSUE TITLE
Assess empty affix slot(s) in eval tool

### ISSUE THREAD

**Issue by CloudTekSystems** [SnosMe/awakened-poe-trade#1319]
It'd be nice if APT recognized there are open affixes (or have the option for you to select open pre/suff and qty) when performing an evaluation using the overlay.

**Comment by SnosMe** [comment]
It's available for a long time under hidden toggle.

![image](https://github.com/SnosMe/awakened-poe-trade/assets/4292308/ba8ac8ec-2538-4ab2-a6a0-4e771e9fb63d)
