### ISSUE TITLE
Map danger mods

### ISSUE THREAD

**Issue by AncientD** [SnosMe/awakened-poe-trade#133]
I suggest, add the ability to check the map for dangerous modifiers, such as "reflection" or "no regen"

For example, Press "Ctrl + Q" and see a window with modifiers that are dangerous on top, somehow highlight dangerous, by color or column.

In the settings, add a list of dangerous mods and let the user select them himself. 
1) Check box list 
2) two vertical list, 1st active "dangerous" mods, 2th all probably dangerous mods.

**Comment by SnosMe** [comment]
Available in v2.2
