### ISSUE TITLE
An error occurred while parsing the item

### ISSUE THREAD

**Issue by Khaael29** [SnosMe/awakened-poe-trade#1336]
Hi, i have this erro message : 

An error occurred while parsing the item
This is probably a bug and you can report it on GitHub.

When i use ctrl+D on a items

**Comment by Devalock** [comment]
![image](https://github.com/user-attachments/assets/cd5a0304-7ab2-4f6b-838d-df3fff63d063)
I'm having the same problem. Each item I'm querying is just like this. I've upgraded the software to the latest version(v.3.25.102) but it doesn't works. Could you please teel me how did you solved this problem?

**Comment by btaglitch** [comment]
Does anyone have any information on how to solve this problem?

**Comment by x4everyung** [comment]
change language
