### ISSUE TITLE
App crashing on mac

### ISSUE THREAD

**Issue by carbonefederico** [SnosMe/awakened-poe-trade#1342]
Crash report attached
[Crash report.txt](https://github.com/SnosMe/awakened-poe-trade/files/15052955/Crash.report.txt)

**Comment by TurboTodd2000** [comment]
Another crash log, hope this helps.
[crash log.txt](https://github.com/SnosMe/awakened-poe-trade/files/15110367/crash.log.txt)

**Comment by niemesrw** [comment]
Similar behavior. I get a message asking for me to allow it access to control my computer using accessibility features & then it crashes.

I granted it permissions to use Accessibility features, toggled it off and back on-browsing to the app in /Applications folder.


[Awakened PoE Trade-2024-04-27-111219.ips.zip](https://github.com/SnosMe/awakened-poe-trade/files/15138570/Awakened.PoE.Trade-2024-04-27-111219.ips.zip)

**Comment by SnosMe** [comment]
#1153
