### ISSUE TITLE
Restore clipboard after price checking item

### ISSUE THREAD

**Issue by moxaj** [SnosMe/awakened-poe-trade#1343]
Pressing CTRL-D while hovering an item copies the item stats to the clipboard. After the search is done, the previous clipboard entry should be restored.

Usecase: when crafting with rog, I always have a regex on my clipboard, but after price checking an item, I always have to win-v and find the regex again.

**Comment by SnosMe** [comment]
![image](https://github.com/SnosMe/awakened-poe-trade/assets/4292308/b68a9631-a07e-4e1b-b1a0-838263cf76e4)

**Comment by moxaj** [comment]
My bad! Closing.
