### ISSUE TITLE
Magic jewels not using 'Exact Value' when filling out stats

### ISSUE THREAD

**Issue by SyrupBuccaneer** [SnosMe/awakened-poe-trade#1345]
![image](https://github.com/SnosMe/awakened-poe-trade/assets/72714858/5bc0dc2d-a076-47fa-b2e0-88d9abbafdff)

![image](https://github.com/SnosMe/awakened-poe-trade/assets/72714858/e6922968-852f-4eb2-8527-c514dab9bb2b)

I checked that it is at the correct setting and this still occurs

**Comment by SnosMe** [comment]
Looks like a leftover from days before Div/Ex swap where you would spent two divs to get perfect rolls on magic item :)
