### ISSUE TITLE
Transparent overlay is not fully transparent

### ISSUE THREAD

**Issue by Murdoc84** [SnosMe/awakened-poe-trade#135]
Transparent window (Shift+Space) it is not fully transparent, adding screenshot with ON and OFF, also overlay is not clickable thruge
![overlay](https://user-images.githubusercontent.com/22428605/85682230-60182480-b6cc-11ea-987e-62abbb683b7c.jpg)

**Comment by SnosMe** [comment]
It is supposed to have white background when active. It's a complex system, saying something is not clickable very helpful for me, would be nice if you specify is and record a video

**Comment by Murdoc84** [comment]
Same with new overlay when i Ctrl+Alt+D on item to check price, new circle show around checked item and overlay whole screen show much brighter (probably white overlay not set to 255 but 240 :)) and that overlay is not clickable thruge.

**Comment by SnosMe** [comment]
No changes to background planned, as well as click through behavior
![S00625-132517](https://user-images.githubusercontent.com/4292308/85702764-649e0680-b6e7-11ea-8dca-94b095524c7a.jpg)
