### ISSUE TITLE
Building fails on arch

### ISSUE THREAD

**Issue by Shoxx98** [SnosMe/awakened-poe-trade#1355]
[awakPoeTradeBuildError.txt](https://github.com/SnosMe/awakened-poe-trade/files/15179628/awakPoeTradeBuildError.txt)

Complete build process is in file
tldr: it shoots itself in the foot by trying to download node 16 and expects >18.
I don't know if this is a PKBUILD problem or a package problem.
Build process happens on cachyOS.
I tried having nodejs installed and uninstalled, both resulted in an error because in the build process it actively makes sure its downloading AND using the wrong version.

**Comment by SnosMe** [comment]
i have no relation with arch package
