### ISSUE TITLE
Overlay Causing Coil Whine

### ISSUE THREAD

**Issue by ArticulatedDrunk** [SnosMe/awakened-poe-trade#1359]
Your overlay runs at thousands of fps in the background of the game whenever active and gives me nasty coil whine on a 6900xt with the latest amd graphics drivers. I can provide more info as needed as long as I can get an explanation of how to capture the info.

**Comment by SnosMe** [comment]
https://github.com/SnosMe/awakened-poe-trade/issues/415#issuecomment-864084650

**Comment by SnosMe** [comment]
It can't run at "thousands of fps" because it uses Electron=Chromium.

**Comment by ArticulatedDrunk** [comment]
The only other situation I get coil whine is when old or light games mess up and spike their fps to 400+. I can record it if you want but I don't think that will help to find a solution? Main point so far is that the game is fine without your app and then now has the coil whine with your app running whether its visible or not.

**Comment by ArticulatedDrunk** [comment]
Given you referenced performance issues, I realized you might not know what coil whine is.
Basically just the gpu makes an annoying high pitched noise when its current or load are too high. With mine in particular it only seems to happen at 400+ fps and when I lock games to a lower fps like 165 or 200 its completely gone.
video for example, but its way quieter in this video than irl for me
https://youtu.be/HP73edpQwgc

**Comment by SnosMe** [comment]
i still don't know how it can cause it, can you show Task Manager.

**Comment by SnosMe** [comment]
1. Locking game to custom fps instead of vsync is dumb.
2. Closing, no screenshot has been provided.
