### ISSUE TITLE
cannot use only ctrl+d to check

### ISSUE THREAD

**Issue by solituker** [SnosMe/awakened-poe-trade#1360]
must first press ctrl+d and then press ctrl +c to check price,either single press ctrl+d or ctrl+c is not working.and my setting is ctrl+d to check price.

**Comment by SnosMe** [comment]
enable key logging, and check what's going on
https://snosme.github.io/awakened-poe-trade/nothing-happens.html

**Comment by solituker** [comment]
> enable key logging, and check what's going on https://snosme.github.io/awakened-poe-trade/nothing-happens.html

solved, thanks
