### ISSUE TITLE
Unable to exit app (gracefully)

### ISSUE THREAD

**Issue by hatani** [SnosMe/awakened-poe-trade#137]
I play in Gnome (Linux) thus I have no taskbar where could I interact with the program.  I only start it (it starts silently) and then interaction keys work.  App says 'Update available: 2.0.0 It will be installed automatically on exit'.  I, however, have no means to quit app cleanly (there is no button for it, upper 'x' just removes GUI from sight but program keeps running).  Would be good to either give us a way to exit gracefully or to do updating on startup.

**Comment by SnosMe** [comment]
Take a look at #70

**Comment by hatani** [comment]
Thanks that solved the issue for me.  Would still prefer that exit option though, honestly :).  PS: thanks for great working trade macro for Linux players, much appreciated!
