### ISSUE TITLE
Key Combination for Map Mods/Search is Extremely Irritating

### ISSUE THREAD

**Issue by VeloxDevelopment** [SnosMe/awakened-poe-trade#139]
The key combination for map mods is extremely irritating, i would like to use shift+space while trying to type and do multiple actions at once, it is continually getting in the way,,,

The feature is excellent but the end use does not fit the active need, given the current key combinations.

Thank you very much for this program

**Comment by VeloxDevelopment** [comment]
Also would like to add the overlay is also annoying in my perception, more buffer, i believe if someone is able to use the tool, they dont need brighter colors on one rectangle

**Comment by VeloxDevelopment** [comment]
moving to poe-overlay until this is more smooth, thank you

**Comment by JasderoFox** [comment]
+100500
Overlay don't need, how to off it? And how to off mods search? I every time to open it when i am chatting ......

**Comment by JasderoFox** [comment]
> moving to poe-overlay until this is more smooth, thank you

lol, I also decided to use poe-overlay until the function to turn off the gray background and search mods through shift+space

**Comment by VeloxDevelopment** [comment]
=) this happens often with programmers, they think it's a feature and creative but don't ask for ideas of the end user =))

**Comment by VeloxDevelopment** [comment]
SDLCs help with this issue

**Comment by VeloxDevelopment** [comment]
Use the previous version =) solves all problems

**Comment by SnosMe** [comment]
this happens often with end user, the think they know better than developer and often miss technical details.
Im working on update and always give the current state of things in Discord #news channel.

**Comment by VeloxDevelopment** [comment]
Likely I do know better than you

**Comment by VeloxDevelopment** [comment]
which technical detail is there to miss? the one you added that people don't like? how are we missing it?

**Comment by VeloxDevelopment** [comment]
it's not an attack  on your ego it's a proposal for change, respond like an idiot, get treated like one

**Comment by VeloxDevelopment** [comment]
I don't see the sentence "which ideas do you think would be great to add?" in this repository

**Comment by VeloxDevelopment** [comment]
Please Delete This Issue
and your ego

**Comment by gdoublev** [comment]
While I agree that the keybind for this feature is annoying and I keep triggering it unintentionally, you really need an attitude adjustment @VeloxDevelopment. This is a free, open source tool. If something bothers you, don't use it, or fork this repo, fix it, and create a pull request. Spamming whiny comments on here is rather unproductive. 👎

**Comment by SnosMe** [comment]
v2.1:
- You can change Overlay hotkey
