### ISSUE TITLE
cannot price check "base" item types

### ISSUE THREAD

**Issue by nandotech** [SnosMe/awakened-poe-trade#14]
Get the "item cannot be recognized" when attempting to check just the value of a base item + implicits (whether it's magic or normal). 

If it is rare, it does not seem to take any base item info into account. See screenshot/item below for example.

```
Rarity: Normal
Spike-Point Arrow Quiver
--------
Requirements:
Level: 45
--------
Item Level: 83
--------
24% increased Global Critical Strike Chance (implicit)
--------
Crusader Item
```

**Comment by nandotech** [comment]
![PathOfExile_x64_DKWCMpf7iJ](https://user-images.githubusercontent.com/2347606/72184010-697f3000-33bd-11ea-8e89-651b135613f1.jpg)

**Comment by SnosMe** [comment]
![image](https://user-images.githubusercontent.com/4292308/72229399-fccf8580-35b6-11ea-8ca8-9efd69bb5186.png)
