### ISSUE TITLE
How to turn off full-screen white overlay? Activates at random [Version 2.0]

### ISSUE THREAD

**Issue by scottmudge** [SnosMe/awakened-poe-trade#140]
There is a new full-screen overlay that is white w/ ~30-50% transparency in Version 2.0. It doesn't show up all the time. It appears to show up when Ctrl+D (price check) is initiated, and then when the mouse moves over the price-check window. It also appears unconditionally when Ctrl+Alt+D are pressed (price check w/ persistent window). 

It also appears to show up randomly with other key combinations, but I haven't kept track of which. It just seems to show up randomly during the game. 

Here is a screenshot of what I'm referring to:

![image](https://user-images.githubusercontent.com/19617165/85779190-5b199c00-b6f1-11ea-9713-223e5a3dfa99.png)

You can see there is a circle/target kind of thing that shows up at the mouse coordinates where the cursor was when the price check was initiated (at the scarab in this case). 

Is there a way to disable this?

I understand the purpose of this feature (to help visually isolate the price check window), but it seems to show up randomly and can interfere with the game or other on-screen elements, as the partially transparent overlay is **not** click-through.

**Comment by scottmudge** [comment]
After further investigation it seems to be a feature which isolates the overlay window and indicates which item is being checked.

Which is a nice feature if Ctrl+Alt+D is pressed (to keep the overlay window open). I guess my issue is that I would like to disable this feature UNLESS Ctrl+Alt+D is pressed. It seems to show up randomly even when the price check feature is not activated.

**Comment by ErueWoad** [comment]
I'd like to turn this off as well as it interferes with another addon I use called PoE Lurker (I really like the trade UI). So the option to disable this fullscreen thing or a UI similar or better to PoE lurker would be nice

**Comment by VeloxDevelopment** [comment]
+1000

**Comment by VeloxDevelopment** [comment]
we can go back to 1.3 =)

**Comment by scottmudge** [comment]
Yes I will do that for the time being. I'll just disable auto-updates.

**Comment by JasderoFox** [comment]
> Yes I will do that for the time being. I'll just disable auto-updates.

Disable? How?! I want too

**Comment by SnosMe** [comment]
"Fixed" in v2.1 #139
