### ISSUE TITLE
Add buyout currency filter to remove price fixers from search.

### ISSUE THREAD

**Issue by beaverrrr** [SnosMe/awakened-poe-trade#1422]
Few days into the league, every price check for any map-like item of any value returns entire table full of chisels listings. Those are not real listings by real people, those are price-fixing bots drowning out legitimate trades, and the purpose of this script becomes completely defeated. The solution would be to have a choice of currency to search listings in, like pathofexile.com/trade does (buyout price: chaos or divine orbs).
Current situation, price checking T17 map: 
![Awakened_PoE_Trade_ADE5MeidWD](https://github.com/user-attachments/assets/c7eb4942-ea2a-42f8-aaa0-80022f3729d7)
Listings on POE trade without proper currency filter: 
![brave_23yrsSODou](https://github.com/user-attachments/assets/ab8d8ac0-9401-4834-a280-e33079bab415)
Real listings by real people: 
![brave_1IRwfVNAlB](https://github.com/user-attachments/assets/afbc3d96-65b6-4e04-9176-2e4f15a1fd28)

**Comment by SnosMe** [comment]
You already can do this, hover over "Online". There is also a setting to not reset this option if you want such behaviour.

**Comment by beaverrrr** [comment]
Thank you, I'm blind.
