### ISSUE TITLE
Doesn't work on Kubuntu 20.04

### ISSUE THREAD

**Issue by gcamuzea** [SnosMe/awakened-poe-trade#143]
Program starts, but makes the game window black. Errors during execution :

(node:8752) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:8752) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
hook_thread_proc [101]: Could not set thread priority 49 for thread 0x7F8AB291E700!

**Comment by SnosMe** [comment]
Enable window compositing

**Comment by gcamuzea** [comment]
It worked :) Cheers, and good job !
