### ISSUE TITLE
Auto-hide mode doesnt work and currency price check suggestion.

### ISSUE THREAD

**Issue by kilpsz** [SnosMe/awakened-poe-trade#144]
1.Auto-hide mode doesn't work for me no matter what i try.

2.When price checking currency they should have a default stock amount, either configurable or not, for example if price checking exalts it should set stock to 10 to get a more accurate price check, fuse something like 200 etc.

**Comment by SnosMe** [comment]
1. Update Nvidia drivers

2. Already suggested, in queue for implementation...

**Comment by QUEWEX** [comment]
Re: autohide, I was also having this problem - or rather it is a bit schizophrenic whether it displays, hides, or re-displays itself based on whether and where I move the mouse cursor, or press keys with POE focused. If I alt tab to the Awakened window and keep my mouse cursor on it, it will stay up, but if I move my mouse cursor off the window and move it back onto the window, it will hide again.

I updated to latest nvidia this morning - 451.48, nvidia site said it released 24 JUN 2020 - but I am still having the issue.

Could it be an issue with Win7/DX11? I know support for Win7 isn't common anymore (I will understand if you won't support an issue that only exists in Win7), but I'm just looking to figure out if it is a problem with a solution or just something I will have to deal with.

**Comment by SnosMe** [comment]
1. #176 
2. -
