### ISSUE TITLE
% to elemental resistances.

### ISSUE THREAD

**Issue by KingJevy12** [SnosMe/awakened-poe-trade#1458]
Everytime I price check an item, the app keeps thinking that % to all elemental resistances is a pseudo stat that isn't actually on the item. It won't go away, I uninstalled and reinstalled and it messes with the price of everything I check. 

![image](https://github.com/user-attachments/assets/74bd0d8e-2144-4f0a-a0b5-8b03724f08ff)

![image](https://github.com/user-attachments/assets/e1f83ff5-92e5-4a8e-925e-108c4a2b4ecf)

**Comment by Xebtria** [comment]
total elemental resistances is not the same as all elemental resistances.
you have 34 fire on that item so you have 34 total elemental resistances.

if you would have 34 fire and 20 cold you would have 54 total elemental resistances.
