### ISSUE TITLE
Background overlay (partial opacity) disable option

### ISSUE THREAD

**Issue by scottmudge** [SnosMe/awakened-poe-trade#147]
I commented about this issue before. It was marked as resolved, however it was **not** resolved.

The issue I am experiencing is that the white, partially-transparent whole-screen overlay (meant to isolate the item information window) is being activated when it should  be optional. This seems to have been added since version 2.0, and I do not need this whole-screen overlay at all. It is interfering with my game-play and is interfering with other plugins.

I would like to be able to disable this overlay.

Most of the times when this overlay is being activated is when the "Ctrl" key is held during game-play, and the "D" key is briefly tapped. The overlay is active for the entire duration of the Ctrl key being held, even when the "D" key is released. Because many items are being Ctrl-Clicked into the trade window when interacting with vendors, this becomes problematic. Please add an option to disable the overlay when the "D" key is released! And also to disable it entirely.

The screen flickering and interference with other plugins is highly annoying. Thank you.

Example with vendor trading: https://i.imgur.com/yXzUESL.mp4

**Comment by scottmudge** [comment]
I see that an option was added such that "Ctrl+Space" disables the overlay once it is active, but I would like to be able to disable it entirely.

**Comment by k4talin** [comment]
Same here. Please disable it... forever. who need that opacity in top of the game , like ever? Awful. I reverted back to 1.3 cause of that. Same problems w flickering as well and all previous mentioned. Thank you

**Comment by SnosMe** [comment]
Update with appropriate changes will be released in ~14h

**Comment by SnosMe** [comment]
Available in v2.2

**Comment by scottmudge** [comment]
Thanks! Works great now.
