### ISSUE TITLE
Onedrive - JavaScript Error

### ISSUE THREAD

**Issue by amunzac** [SnosMe/awakened-poe-trade#1470]
I deleted Onedrive out of frustration and have run into this issue since trying to start up awakened-poe-trade:
My appologies for not providing more information; uncharted realms for me, and im quite lost. 

![image](https://github.com/user-attachments/assets/006a54ed-9068-4377-870e-c1b1eb119aba)

**Comment by SnosMe** [comment]
Restart PC, check that you can open your Documents folder lol

**Comment by amunzac** [comment]
Ive rebooted a fiew times, still same error when loading from fresh reboot. 
I can do all things, except launch awakened-poe

**Comment by amunzac** [comment]
complete system restore ultimately worked, most certainly had something to do with my illiteracy and being foolish with my actions towards one drive. 

Thanks for the quick response :p

**Comment by amunzac** [comment]
Ty <3
