### ISSUE TITLE
Doesn't auto search

### ISSUE THREAD

**Issue by zefrogi** [SnosMe/awakened-poe-trade#1489]
I'm sure I'm missing something obvious, but I can't seem to see the trade results without clicking on search.

I've checked the auto-search settings, and they are clicked on. I tried to change keybinds and have done a complete re-install. Any ideas?

**Comment by zefrogi** [comment]
Hmm, that's fair. I just wondered if I had some setting active, as when I mouse over the search button from the top, it seems to search before I click. Thanks for letting me know.

Could there be scope for auto-searching items if certain things are met? A number of tier 1s, above 80% spell damage or something? It's probably more hassle than worth it, but I thought I'd ask.

**Comment by SnosMe** [comment]
Yep, triggering only from top is also coded with intention.
I don't want to add some threshold for mods, if you really want quick estimate enable price predictions.

**Comment by zefrogi** [comment]
No worries! Thanks for getting back to me so quickly and the addon in general. Cheers!
