### ISSUE TITLE
[Feature Request] Setting to control results quantity

### ISSUE THREAD

**Issue by home-alone-dev** [SnosMe/awakened-poe-trade#149]
With price fixers and frequent price deviations 20 results is too low.

P.S. Thank you for an awesome tool

**Comment by SnosMe** [comment]
Tool automatically handles price fixers, more results (even 100) will be requested if tool finds such cases. On the other hand forcing ALWAYS requests more then 20 results will lead you to be rate limited by ggg apis and as a result unusable tool at all.

**Comment by home-alone-dev** [comment]
Thank you!
