### ISSUE TITLE
Error parsing item

### ISSUE THREAD

**Issue by dgalimov-at** [SnosMe/awakened-poe-trade#1503]
Can't parse any item 
![Error parse](https://github.com/user-attachments/assets/c907f3f1-ee19-4ac6-9713-8f57529d506e)
Tried to restart the app and reinstall, but didn't help.

**Comment by SnosMe** [comment]
Change language in the app to English (or game to RU)

**Comment by dgalimov-at** [comment]
yeah, it hepled. thank you.
