### ISSUE TITLE
Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by dextep** [SnosMe/awakened-poe-trade#151]
Hi, i found out some bug, idk how to reproduce it but need to be handle for sure.
![image](https://user-images.githubusercontent.com/20928760/85953079-3c740900-b96e-11ea-86ce-75eb301143ad.png)

**Comment by kramarz89** [comment]
Can confirm, happened to me too, basically did nothing, just ctrl+alt + d on an equipped item with gems

![image](https://user-images.githubusercontent.com/6530012/85954110-78f73300-b975-11ea-8418-2fa72d1a78b2.png)

**Comment by nowx-gh** [comment]
same here.

**Comment by SnosMe** [comment]
Not really a bug, just a technical error msg, poeprices.info website  failed to respond to tool request. Just need to make this error a little bit friendly.

**Comment by eris667** [comment]
poeprices.info overloaded today? I am getting that same error in inventory, stash, equipped (rares)
if I price check a common unique it populates quickly with no error

**Comment by eris667** [comment]
![image](https://user-images.githubusercontent.com/66086539/85958364-ac789400-b95a-11ea-9594-17cc614d76a8.png)

**Comment by eris667** [comment]
If I manually click search I can see some prices - the the typical chaos equivalent price check (where the error is) is not working

**Comment by SnosMe** [comment]
> Will make this error a little bit friendly.

![image](https://user-images.githubusercontent.com/4292308/86094802-ad740780-bab9-11ea-8bda-bfc0906d79e4.png)
