### ISSUE TITLE
Program is requesting outgoing connections every minute.

### ISSUE THREAD

**Issue by HiPoEGH** [SnosMe/awakened-poe-trade#153]
The program is requesting outgoing requests to the PoE web servers (172.67.216.108 | 104.19.185.16 | ...) every minute.
**IMO this needs to stop**, even if it's "harmless", and should **only make requests when the player issues a request**. A toggle option under settings would help.
I don't think there is any reason to keep a connection live to their servers in this way, unless for the sake of argument of speed.

I don't know if this is related to checking for an update, as mine seems to fail, but I doubt it has anything to do with that.

**Comment by SnosMe** [comment]
Can you press Ctrl + Shift + I to get actual requests? 

![image](https://user-images.githubusercontent.com/4292308/86019632-81ac3f80-ba2f-11ea-9fe2-e6e04ea0e8be.png)

**Comment by HiPoEGH** [comment]
I don't understand if that's supposed to be a debug command (or the default keybinds), but nothing pops up when I do that.
Regular requests for price checks (Ctrl+P) work fine. (Alt+W) works fine.
I have my Log level set to debug. I can post it later if that helps.

**Comment by SnosMe** [comment]
Press Ctrl + Shift + I when APT window has focus (Ctrl+Alt+D, or Shift+Space), you may need to press it ~3 times due to some windows related bug.

**Comment by HiPoEGH** [comment]
Seems the requests are to PoENinja, found what you were looking for. Seems to get hung up on one request and the others fail.
It will go down the entire list, didn't bother to wait for them all.
Also, how do I close the inspector once it's open? Screen stays white unless I close/reopen program.
[https://i.imgur.com/Wlbyr7U.jpg](https://i.imgur.com/Wlbyr7U.jpg)

**Comment by SnosMe** [comment]
I have reviewed code and there is no bugs in it. All requests done sequentially. "hung up on one request and the others fail.
It will go down the entire list, didn't bother to wait for them all" sounds like a network error. Anyway, problem on your side.
