### ISSUE TITLE
map mods

### ISSUE THREAD

**Issue by AncientD** [SnosMe/awakened-poe-trade#157]
Please add "no regen" to danger mods

**Comment by SnosMe** [comment]
You can add it yourself

Here

![image](https://user-images.githubusercontent.com/4292308/86225318-be447c00-bb92-11ea-80d6-b1c16fa038bd.png)

or here, when you see this mod

![image](https://user-images.githubusercontent.com/4292308/86225661-3743d380-bb93-11ea-960d-eacee6e05211.png)
