### ISSUE TITLE
abyssal jewels weighing ilvl heavily

### ISSUE THREAD

**Issue by nandotech** [SnosMe/awakened-poe-trade#16]
Great work on the updates btw. Really enjoying this tool :)

I was starting to wonder why I had so many jewels worth 10-15c, I'm not sure if ilvl should be considered on these? Forgive me as this is my first season so some of this I'm not 100% sure on--but when I search poe trade I find many many better jewels with more/better affixes for cheaper. Seems to me it might be the ilvl.

See screens below:
Item:
```
Rarity: Rare
Ancient Sphere
Ghastly Eye Jewel
--------
Abyss
--------
Requirements:
Level: 49
--------
Item Level: 83
--------
Minions have +9% to all Elemental Resistances
Minions deal 4 to 8 additional Chaos Damage
Minions deal 11 to 14 additional Fire Damage
```

![image](https://user-images.githubusercontent.com/2347606/72270020-82bcf200-35f2-11ea-8bed-b271220746be.png)

However on PoE trade, searching just the modifiers: https://www.pathofexile.com/trade/search/Metamorph/RJnYkvWI7

Add ilvl: https://www.pathofexile.com/trade/search/Metamorph/02D6e6pIg

I don't know that ppl actually look for ilvl on jewels like that? (and if they do I'll just move right along)

Again great job with everything & thanks!

**Comment by nandotech** [comment]
also this is consistent for all abyssal jewels im finding. Sometimes it can be accurate-ish but i think the ilvl is throwing off. 

another: 
Item:
```
Rarity: Rare
Morbid Sight
Ghastly Eye Jewel
--------
Abyss
--------
Requirements:
Level: 32
--------
Item Level: 83
--------
+75 to Armour
8% chance to Avoid being Stunned
Minions have 4% chance to Taunt on Hit with Attacks
--------
```

![image](https://user-images.githubusercontent.com/2347606/72271123-530ee980-35f4-11ea-9788-efd3522a0633.png)

**Comment by SnosMe** [comment]
Please do not forget that the prediction functionality is served by other people to whom I have no relation.

But as a player, I can tell you that iLvl is not important for regular jewels

> Affixes for jewels follow some special rules:
> - No item level requirement
> - No tiered affixes
(https://pathofexile.gamepedia.com/Jewel)

However important for Abyss Jewels.

> Also, unlike regular jewels, Abyssal Jewel modifiers are item level dependent, so some modifiers and modifier tiers require a minimum item level to roll.
(https://pathofexile.gamepedia.com/Abyss_Jewel)
