### ISSUE TITLE
[Price Check] Is there a way to have "Item Level: " ALWAYS checked?

### ISSUE THREAD

**Issue by scottmudge** [SnosMe/awakened-poe-trade#161]
Is there a way to have the "Item Level:" field of the item price check feature always checked? It heavily influences the price of certain items/bases, and it is such a pain to have to manually check it every time.

Thanks!

**Comment by SnosMe** [comment]
![Item Base](https://user-images.githubusercontent.com/4292308/86490575-8abf4880-bd70-11ea-967d-3c3e54f9a5b2.gif)
