### ISSUE TITLE
v2 issues on KDE

### ISSUE THREAD

**Issue by FREEZEball** [SnosMe/awakened-poe-trade#162]
For Awakened PoE Trade to function properly on Linux (KDE Plasma with KWin on Arch with AMD GPU and mesa drivers, game is ran on amdgpu-vulkan) since patch v2.0 you need to turn on compositor. This is not a desirable option, because you have to turn it off every time I stop playing PoE; I need compositing off for other reasons.

2-nd issue with this is the game window constantly highlighting itself on taskbar:
![image](https://user-images.githubusercontent.com/11259935/86507627-6f8d2100-bde2-11ea-86c7-2792309f2c76.png)
Normal behavior in PoE is it highlighting when there are incoming whispers (indirect results of using Awakened PoE Trade) and the game is in background. Trading in Alt+Tab is hindered because of this. This might be Plasma/KWin issue, but it did not exist prior to 2.0 with compositing turned off.

3-rd issue is related to Alt+Tabbing (and you need to Alt+Tab a lot in this game). After you return your focus to the game via taskbar, the focus is "on overlay". No keyboard bindings (including Enter to chat) work, you need to click in game to move focus to it again. This is a minor annoyance and is probably Plasma/KWin issue, but still.

So please add an option to disable the permanent overlay.

**Comment by SnosMe** [comment]
1 .Compositor is required and the way how overlay works will not be changed.

2,3: it is indeed how your distro is tweaked from box, you need to undo this changes. Instruction what you need to do is posted by one of players somewhere in Discord #ask-intl cahnnel.

Keeping this issue open till I make a FAQ with clear instructions.

**Comment by Deckweiss** [comment]
When I have the compositor on, my game is lagging.
So I always play all games with the special window setting that blocks compositor while game is running. 

Awakened poe used to work fine before v2, I was able to use the permanent pricing pop up (while the overlay stuff was broken, which I didnt mind).

Now the overlay creates a black box over the poe client. 

Maybe you could add an advanced option that disables the overlay and still allows to price items like before v2 for people who want to block their compositor while playing poe.
