### ISSUE TITLE
Stat tags

### ISSUE THREAD

**Issue by atyrode** [SnosMe/awakened-poe-trade#163]
Hello,

When I started Harvest I felt yet again the same overwhelming feeling of loss as when I started Synthesis:

The game fails to provide us with enough data to be self-sufficient and I found myself yet again alt-tabbing every other minute. Not great for immersion, but also a wall for my newer friends who'd like a more casual approach to the game.

I started coding an addon in Python that'd aim at enhancing the Help panel of the game to add new buttons in the main screen of it ([here](https://i.imgur.com/XO1bOhj.jpg)); with the aim to eventually add buttons that open up "in-game windows" with the necessary and bare information to be able to successfully craft in Path of Exile without relying too hardly on third party.
(I was thinking, list of mods, list of item bases, list of gems, leagues spreadsheet, etc.)

I eventually gave up on it because I felt like this is something GGG should do, but then I stumbled upon [this](https://www.reddit.com/r/pathofexile/comments/hkv7z5/harvest_highlights_the_weakness_in_the_current/) today and the feeling of urge resurfaced.

I feel like this problem has to be tackled for we don't know if such issue will even be addressed before PoE 2.

I've dragged my point behind some backstory, so here's what I'm thinking:

I'm interested into your project and I'm all for open source community resources, could what I'm working on eventually become a feature you'd be interested into adding to Awakened Poe Trade and should I therefore start working in TypeScript to eventually make a pull request, or should that'd be an entire separate addon?

Thanks for reading and putting thoughts into it,
Alex

**Comment by SnosMe** [comment]
Thanks for sharing your thoughts.
All ideas you mentioned already planned. I accept PRs only for bugs.

**Comment by SnosMe** [comment]
https://twitter.com/bexchangewords/status/1279953188892708865?s=20
