### ISSUE TITLE
Search by item name

### ISSUE THREAD

**Issue by leet0rz** [SnosMe/awakened-poe-trade#164]
Would love to see a CTRL+i search like the regular trade macro has, lets say I would like to price an item I do not have, all I have to do with trade macro is CTRL+i and simply type "Goldrim" and then we'll get a list of goldrims, it looks like this:
https://i.imgur.com/FXgg5cK.png

This is what keeps me from switching, poe trade macro is so slow so I really want to switch, but I cant because I really use this feature all the time.

**Comment by leet0rz** [comment]
Any updates on this feature yet?

**Comment by leet0rz** [comment]
When are we getting this?

**Comment by SnosMe** [comment]
It has much much lower priority than what I'm working on, be patient.

**Comment by leet0rz** [comment]
> 
> 
> It has much much lower priority than what I'm working on, be patient.

Thanks

**Comment by SnosMe** [comment]
I don't like the idea of arbitrary search, you can use poe.ninja for this (and at the same time support it by watching ads).

However, in the next update you will be able to search for Gems in Heist.

![image](https://user-images.githubusercontent.com/4292308/164996563-c7d1a830-06b5-47ac-9d16-604e2e7ba1a4.png)

**Comment by leet0rz** [comment]
Its a start, appreciate it. I used to use the old one to just quickly look up basic uniques that I did not have yet in game so I didnt have to alt tab. Its nice at league starts when you are fully immersed. Would love to see this in your program and hope you eventually added it. Think it would be a great addition. Have a good day.
