### ISSUE TITLE
I cant tarde

### ISSUE THREAD

**Issue by zolw9** [SnosMe/awakened-poe-trade#166]
i casnt used macro to trade. dont work any hotkeys and i dont know maybe command is wrong i used /trade @last its good?

**Comment by NeroMorto** [comment]
@zolw9 Have you checked all requirements?
https://github.com/SnosMe/awakened-poe-trade/wiki/Download

**Comment by SnosMe** [comment]
If any hotkey doesn't work the restart with admin rights. Also your command joins the trade chat channel. The correct one can be found here https://pathofexile.gamepedia.com/Chat_console
