### ISSUE TITLE
Add auto-start capability

### ISSUE THREAD

**Issue by pfeigl** [SnosMe/awakened-poe-trade#168]
Hi, 

it should be fairly easy to add auto-start to the project. Either by using this https://www.npmjs.com/package/auto-launch or this https://www.electronjs.org/docs/api/app#appsetloginitemsettingssettings-macos-windows (which is meanwhile supported natively by electron).

This would be a great addition to the tool :-)

Thanks for your great work!
Philipp

**Comment by SnosMe** [comment]
- Windows
  Create shortcut in `%appdata%\Microsoft\Windows\Start Menu\Programs\Startup`
- Linux
  Create `awakened-poe-trade.desktop` file in `~/.config/autostart/`
