### ISSUE TITLE
Usage with GeForce Now

### ISSUE THREAD

**Issue by lars-berger** [SnosMe/awakened-poe-trade#170]
It seems like the clipboard of GeForce Now is completely isolated from the rest of the OS and there isn't an API available to access it.

One workaround mentioned for the same issue in [for POE-TradeMacro](https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/1140) is to:

1. Ctrl+c on an item (in the Geforce Now window)
2. Open the steam overlay and paste the contents in a steam chat message to yourself (in the Geforce Now window)
3. Ctrl+c the message and then the press a POE macro hotkey like ctrl+d (in steam chat outside of Geforce Now)

To get this working on `PoE-TradeMacro`, this requires a slight code change to remove the restriction of running the macro only while POE is running. However, I'm struggling to make a similar change to get Awakened PoE Trade working.

What I've tried is changing the window title that the overlay should bind to (`line 86 of ipc/types.ts`) to `'Path of Exile on GeForce NOW'`. This doesn't work unfortunately :( Also tried setting it to the window title of a notepad window for debugging purposes and that didn't seem to work either.

Any ideas on what else needs to be changed to get the overlay displayed on a different window than the normal POE window?

**Comment by SnosMe** [comment]
Settings>Debug>PoE window title. do not forget to expand steam chat window, better to maximize it

**Comment by lars-berger** [comment]
That's great to hear there's a setting to change the window title 👍👍

Unfortunately still can't get it working though. This is what I'm doing:

1. Set POE window title to `Untitled - Notepad` in settings and restart. 
2. Open notepad window.
3. Copy item info outside of Geforce window.
4. Focus on notepad window and then press a macro hotkey, eg. ctrl+d

The Geforce window seems to be fullscreen and not windowed fullscreen, so that's why I'm using notepad.

**Comment by SnosMe** [comment]
Do not forget to Ctrl+A the text you have in notepad

**Comment by lars-berger** [comment]
Aha that was it! Working fine now

**Comment by SnosMe** [comment]
Being similar to RDP, for some reason GFN doesn't forward clipboard. As soon as GFN devs implement clipboard forwarding, Awakened will work without any changes required.

**Comment by Kasvit** [comment]
Hi @SnosMe 
Any good news about GFN?)

**Comment by SnosMe** [comment]
> Hi @SnosMe Any good news about GFN?)

I think it works the other way, you tell me when GFN starts supporting clipboard forwarding.

**Comment by Kasvit** [comment]
@SnosMe is it possible to use the app directly with google chrome? GFN allow playing from the browser.

**Comment by SnosMe** [comment]
Unfortunately no because of https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
Standalone app allows me to disable these security restrictions.

**Comment by RAYSEN6661** [comment]
Any good news about Geforce Now?

**Comment by finchi** [comment]
Geforce Now just got copy & paste suppoer with the new update (2.0.41). Maybe this is possible now?

**Comment by SnosMe** [comment]
@finchi Have you checked if it is really bidirectional? From the docs it looks like you can only paste.

**Comment by RAYSEN6661** [comment]
This is the official message from their site:

"If you are running v2.0.41 app or later, you will have the ability to copy text from your local device and then paste it while in-stream on GeForce NOW, for example by pressing Ctrl+V or mouse right-click . Note: Mac users must use Ctrl+V (not the traditional ⌘ Cmd+V). This feature is available on PC, Mac, and Web Browsers.
 
When using this feature, GeForce NOW uses standard Windows clipboard functionality to allow you to only paste into the GeForce NOW stream.  GeForce NOW is not exposing the full clipboard functionality."

**Comment by SnosMe** [comment]
Yeah, I can't read, and some parts look not clear to me, that's why I am asking for an actual test, is it that hard for you guys?

**Comment by alaindwight** [comment]
@SnosMe I am able to ctrl-c text inside of GeForce Now and then ctrl-v that same text outside GeForce Now successfully. 

Not sure of the exact details, but the clipboard does seem to be bidirectional.

Currently trying a build with the modified window name in `ipc/types.ts` - will update with what I find.

I assume I make the modification then do `yarn install` and `yarn build` in the `renderer` directory.

**Comment by alaindwight** [comment]
@SnosMe thanks, now I'm able to open Awaken in GFN but after checking again it seems more like what you originally said: it allows you to paste, not copy.

Might have been that I had the wrong window open when trying to test it earlier.

**Comment by mihaigeorgech** [comment]
I created an AHK script that does the following:
ctrl+alt+click on target item, opens steam browser, goes to dontpad.com/whateryouwanthere and pastes the item data, then opens the dontpad url in chrome, where you can finally select the text and use the pricing macro.

The script is pretty sloppy, as I'm not experienced with AHK, the delays are a bit long, and sometimes it works like a charm, sometimes it skips a step.

Had to make the changes suggested in https://github.com/SnosMe/awakened-poe-trade/issues/170#issuecomment-946506421 
Renamed chrome window to always show "Google Chrome" instead the tab name, since I didn't want to have to copy the item data from chrome/steam chat to a notepad.

If anyone decides to use this script, you should replace the dontpad url to an unused one.

[https://pastebin.com/nnnf4vet](https://pastebin.com/nnnf4vet)

**Comment by Isoru123** [comment]
hi i have a problem evrything looks fine to the point when poe awakend is showing up bcs instead the item that i was pointing on i instead get grand spectrum

**Comment by KloppstockBw** [comment]
Hey, I wrote a script for price checking https://github.com/KloppstockBw/GFNPoEPriceCheck
