### ISSUE TITLE
constant high bandwidth usage

### ISSUE THREAD

**Issue by RinnzlerFRL** [SnosMe/awakened-poe-trade#171]
I installed the app about 5 days ago. It worked fine for 2 days and now every 20 minutes or so it starts using all of my bandwidth (i play using my cellphone connection) for around 10 seconds. I'm not really sure what could be the issue and maybe it could be something similar to issue #153.

**Comment by SnosMe** [comment]
You mentioned cellphone connection, most probably the auto-updater fails to download delta patch and does full exe redownload which is 50MB.

It is 100% not the #153, if failed requests retried every minute you will consume at max 60KB per hour.
There are no other sources in code that perform network requests without you triggering to do so.

**Comment by RinnzlerFRL** [comment]
is there a way to disable auto-updater?

**Comment by RinnzlerFRL** [comment]
> You mentioned cellphone connection, most probably the auto-updater fails to download delta patch and does full exe redownload which is 50MB.
> 
> It is 100% not the #153, if failed requests retried every minute you will consume at max 60KB per hour.
> There are no other sources in code that perform network requests without you triggering to do so.

is there a way to disable auto-updater?

**Comment by SnosMe** [comment]
Portable version checks for update but doesn't download it

**Comment by RinnzlerFRL** [comment]
still happens the same with portable version hmm
