### ISSUE TITLE
Auto-hide mode closes as soon as moving mouse by 1px: wrong cursor coords?

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [SnosMe/awakened-poe-trade#172]
Hello!

First of all, congratulations for creating this tool, it is amazingly fast and very well crafted.

When using this tool with the auto hide feature (ctrl+d), I don't know if it is a bug or if I moved my cursor by 1px, but there are times that the overlay automatically closes just after it was opened, even if I try to keep my cursor standing still. There are times that I do know that I moved the cursor a little bit (couple of pixels) and the overlay closes as expected. Because of this I have to reassure that the cursor is standing still to avoid the auto hide by mistake, which causes a unnecessary preoccupation when playing the game and using this tool.

I do want to use the auto hide feature, but would be possible to make the auto hide cursor threshold configurable? For default it would be 1px, but in my case I would try something like 5px. I play on 4k display, and 5px is really nothing, but would help those 1px mistakes.

**Comment by SnosMe** [comment]
Hi, the distance to hide is 40px, moreover this value is scaled depending on display DPI and app's font size setting. I'm sure that app should handle 4k display fine. Hint: outer circle, that you see around item in locked price check mode, is exactly same size where you can freely move mouse without auto-hide window being closed.

I'm not even sure where bug can be, so most probably I'll make a custom build with added logging for you to download.
What is your OS?

**Comment by rafaelrenanpacheco** [comment]
I'm using Windows 10.

> outer circle, that you see around item in locked price check mode, is exactly same size where you can freely move mouse without auto-hide window being closed.

I'm pretty sure I didn't move the cursor that much, because I always thought that I may have moved 1px or 2px.

**Comment by rafaelrenanpacheco** [comment]
Hello!

I'm not seeing this issue anymore, maybe the update to 2.3 fixed it.

Thanks.
