### ISSUE TITLE
Another tool to rule: POE-Trades-Companion

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [SnosMe/awakened-poe-trade#173]
Hello!

On the `One Tool To Rule Them All` section it is mentioned a tool called MercuryTrade, which is no longer maintained. I think the current alternative is [POE-Trades-Companion](https://github.com/lemasato/POE-Trades-Companion). Should this trade companion be listed as well in the "to rule" list? If awakened poe trade can handle trade request/receive as trades companion do, then there will be one less tool to start every time we are playing PoE. This would also help new players that are overwhelmed by the excessive tools needed to play PoE with efficiency.

**Comment by SnosMe** [comment]
MercuryTrade stands in list in meaning of "trade tool", than the specific tool to replace. This two tools in list is de facto standard for PoE community. So for example many people call Awakened PoE Trade the "macro", "awakened macro", however it's obviously not the AHK script like PoE-TradeMacro :slightly_smiling_face:
