### ISSUE TITLE
[question] about dump sorting feature?

### ISSUE THREAD

**Issue by Cipheriax** [SnosMe/awakened-poe-trade#175]
hey there, I love your tool! It's much faster than what I've been using so far (trademacro and mercurytrade later).
I've found this feature called "dump sorting", but I couldn't manage to make it work. All it does for me is highlighting items in my stash tab by automatically putting in "currency" in the search box for example. It doesn't put anything from my inventory to the stash, it just highlights.
I'm wondering if there's something I need to configure to make it work? And another question, would it be even allowed to use an auto dump feature like this?II ddon't want to see myself getting end up banned for something unintentionally. 

Thank you in advance! 
(also I would've used the question flair but couldn't figure out how to do that on mobile,sso I'm sorry)

**Comment by SnosMe** [comment]
> highlighting items in my stash tab by automatically putting in "currency" in the search box

Yep, it is how it works. Players usually have a bunch of quad tabs, zoom-zoom maps, and at the end of session sort this quad tabs.

> It doesn't put anything from my inventory to the stash. would it be even allowed to use an auto dump feature like this

Such tools exists, but this automation isn't allowed. Also recently GGG promised to add their own "tab affinity" ctrl+click sorting before, or when 3.12 is out.

(tags can be added only by repo owner)
