### ISSUE TITLE
Double Trade request on a price check. 

### ISSUE THREAD

**Issue by NyvenZA** [SnosMe/awakened-poe-trade#178]
I am using POE Trade Companion AHK and Awakened-PoE-Trade-2.2.0 portable. 

I have an issue that it looks like there are additional trade requests send out when i try and doe a price check. 

Steps to try and reproduce:
* Copy a Whisper from the PoE Trade site.
* Paste the trade request. 
* Open Inventory and hover over an item, Press Ctrl+D for a price check. 

I can see the same Whisper for the trade then pasted to the chat again.

**Comment by SnosMe** [comment]
Option 1
![image](https://user-images.githubusercontent.com/4292308/87235180-1759ae80-c3e2-11ea-95a2-a4fbf5d40be3.png)

Option 2

Since v2.3.0, "Restore clipboard: No"

![image](https://user-images.githubusercontent.com/4292308/87235217-a1097c00-c3e2-11ea-9d00-4be417fa9d56.png)
