### ISSUE TITLE
Add anoint price checking

### ISSUE THREAD

**Issue by trevorm4** [SnosMe/awakened-poe-trade#179]
Hi,
I'm not familiar with how the API that does the price checking works, but it would be really great if you could add a mod to search for that includes the annoint.

e.g. Allocates # {Passive_name}

**Comment by JusKillmeQik** [comment]
I don't think there is a tool that price checks anointments yet, but you could at least display what the anoint does and which oils it takes. If it takes Gold oils, we would know it is expensive.

**Comment by trevorm4** [comment]
I think for uniques it would be possible, but rares definitely harder
