### ISSUE TITLE
support for item base type when price checking influenced belts

### ISSUE THREAD

**Issue by rezk2ll** [SnosMe/awakened-poe-trade#180]
currently, price checking belts doesn't recognize the base type.

for example, price checking shaped leather belt ( 20 c ) is the same as any other belt.

![image](https://user-images.githubusercontent.com/6764881/87254213-c8128d00-c478-11ea-9b02-718e6fbe0eac.png)

**Comment by SnosMe** [comment]
![Item Base](https://user-images.githubusercontent.com/4292308/87254295-4fb4c780-c48a-11ea-9667-fc54ea3ddc33.gif)
