### ISSUE TITLE
Please document all hotkeys on the main github information page

### ISSUE THREAD

**Issue by sh00ter999** [SnosMe/awakened-poe-trade#181]
For the love of God, please do it. I know there are more hotkeys than there are listed. Is there no settings window that allows you to remap buttons? One shortcut I found by sheer trying is F9 to /exit. Or at least I believe it's from APT. Is it normal that right-clicking the Icon in the task bar does not open any context menu? No setting to exit or open settings? 

The most infuriating thing is that for some unknown reason some overlay opened in the top left of my screen with the options to add a countdown to the center of my screen. I brought it up by sheer mistake (just opening chat with Enter and started typing...) and now I don't know how to remove it because the underlying issue is: the full documentation of all shortcuts is missing. Please edit the information page, would be very helpful. 

PS: Great fan of your application. It makes price checking fast and much more fun than before. You've built a great program!

**Comment by RinnzlerFRL** [comment]
right clicking the icon in the task bar won't open any context menu if poe is in the background/screen. You need to alt+tab to another window like a folder or navigator and then you can right-click the icon.
