### ISSUE TITLE
[Suggestion] Option to change "shift-spacebar" hotkey for stash search

### ISSUE THREAD

**Issue by scottord** [SnosMe/awakened-poe-trade#182]
Love this application - fantastic work. I recommend it to everyone who asks, "price check" in guild chat!

I find that I sometimes open up the stash search (which I use, customize, and enjoy) by mistake when I'm typing - single capital letters followed by a spacebar press are the most common ("A question", for example).

Adding this to the current hotkey config would be a solid improvement. I think that feature could use a bit more instruction/documentation as well - it took me a little while to figure out what was going on.

Thanks!

**Comment by SnosMe** [comment]
This was released 19d ago

![image](https://user-images.githubusercontent.com/4292308/87447388-32573900-c603-11ea-9aeb-48a90ca5f2b9.png)

**Comment by scottord** [comment]
Just noticed the option in the latest release to change the overlay hotkey, fantastic - thanks!
