### ISSUE TITLE
[Suggestion] Allow the labels for the different stash search bars persist in the "anchor bar"

### ISSUE THREAD

**Issue by scottord** [SnosMe/awakened-poe-trade#188]
Enjoying this tool the more I use it, and the more I use it, the more time it saves me.

Presently, the "anchor bar" displays the names of any search bars that you've created, but they disappear from the horizontal list when they are maximized.

It is a little bit of a hassle to hover over the maximized search menu and mouse to the "Hide" menu item to actually hide it. Consider updating the anchor bar so that the titles of each search bar remained present while they are open/maximized - these can act as toggles to show/hide each bar.

I think the bonus here is that there's less UI elements moving around - just buttons highlighting ;)

Thanks for your work!

**Comment by SnosMe** [comment]
![image](https://user-images.githubusercontent.com/4292308/88462475-29dce900-ceb4-11ea-99d9-6ebb7349d67e.png)
