### ISSUE TITLE
Allow searches on unsealed Prophecies from the "Challenges > Prophecies" screen

### ISSUE THREAD

**Issue by scottord** [SnosMe/awakened-poe-trade#191]
Hello hello - I was turning in some Prophecies and noticed that the overlay will not activate on the unsealed Prophecies that you have in your "Prophecies" screen (Challenges menu).

It would be a nice time-saver (and currency saver!) to be able to price-check a Prophecy without sealing it - I suspect there might be a limitation due to it not being an actual item, but thought I would make the suggestion.

Thanks again for your work on this project!

**Comment by SnosMe** [comment]
> I suspect there might be a limitation due to it not being an actual item

You're right. Game doesn't copy the text of item when you press Ctrl+C in this tab, so no way.
