### ISSUE TITLE
Display price conversion in all fractions or all decimals

### ISSUE THREAD

**Issue by scottord** [SnosMe/awakened-poe-trade#194]
Hi there!

I spent longer than I'd like to admit trying to figure out why the price of Scours was ~4 times that of Chisels - finally noticed that the price conversion (e.g. 1 Scour > 1/2.1 Chaos) literally reads, "1 Scour will cost you '1 divided by 2.1' Chaos".
![chisel-price](https://user-images.githubusercontent.com/5332063/89055132-ea852100-d327-11ea-9656-c9e6403473a5.png)
![scour-price](https://user-images.githubusercontent.com/5332063/89055138-ed801180-d327-11ea-9b41-8bd4af50f85f.png)

I think it would be clearer to use decimals across the board (for this particular layout/display), e.g. 1 Scour > 0.5 Chaos.

That said, the price check functionality is outstanding, I tell anyone who asks for a price check to download Awakened PoE Trade while they're still shocked at how fast it allows you to search!

**Comment by SnosMe** [comment]
![image](https://user-images.githubusercontent.com/4292308/89188251-12ce8300-d5a7-11ea-9d85-e90e73aa4525.png)
![image](https://user-images.githubusercontent.com/4292308/89188346-32fe4200-d5a7-11ea-8850-f9e77e33ad74.png)

**Comment by SnosMe** [comment]
Trade site rounds price to 0.5 (and to 0.1 for exalts), so it's +1 to why to show price in bulk price format to set in Note.
