### ISSUE TITLE
Awakened PoE trade currently doesn't work with GeForce NOW

### ISSUE THREAD

**Issue by greatscottisay** [SnosMe/awakened-poe-trade#196]
Awakened PoE trade currently doesn't work with GeForce NOW cloud gaming system.

Using autohotkey window spy tool I checked the name of the game window when using GeForce NOW service, and I tried to change the window title in the config.json file from
`"windowTitle": "Path of Exile",`
to
`"windowTitle": "Path of Exile on GeForce NOW",`
Still, the awk poe trade doesn't seem to work.

**Comment by SnosMe** [comment]
This is clearly stated on Download page https://github.com/SnosMe/awakened-poe-trade/wiki/Download
