### ISSUE TITLE
Awakened-poe-trade Problem z instalacją 

### ISSUE THREAD

**Issue by adi14b** [SnosMe/awakened-poe-trade#197]
Instalacja zatrzymuje sie w połowie i mimo długiego oczekiwania nic więcej sie nie dzieje 
![Bez tytułu](https://user-images.githubusercontent.com/69306292/89613130-ca9eb180-d881-11ea-8590-1332a5dadefa.png)

**Comment by SnosMe** [comment]
![image](https://user-images.githubusercontent.com/4292308/89620939-232d7900-d899-11ea-9a4f-c71237643982.png)
