### ISSUE TITLE
Error: 200, poeprices.info is under load or down

### ISSUE THREAD

**Issue by borneleader** [SnosMe/awakened-poe-trade#198]
Hi!
I am having an issue with my desktop, an AMD 1600 radeon 5700. Whenever I use awakened poe trade to try to price something, it pops up "Error: 200, poeprices.info is under load or down" If it does get a read the price is wildly inaccurate. However, when I use my laptop intel 9970H? and gtx 1660ti , the awakened poe trade works and well. Any help would be great. I have reinstalled and installed it twice and redownloaded the file for a fresh install.

**Comment by SnosMe** [comment]
There is nothing that I can do it about it. All information is received from website [poeprices.info](//poeprices.info)
