### ISSUE TITLE
Clipboard may be posted instead of command

### ISSUE THREAD

**Issue by TheAssociated** [SnosMe/awakened-poe-trade#199]
The clipboard's content can be posted into chat, possibly due to a race condition or due to not checking if the clipboard has been successfully set (hard to reproduce).

Happened to me with my typical F3, F4 routine after a trade (ty, group leave).

This results in potentially bannable behavior, depending on what the content of the clipboard is.

Example ("Out of the Gate" is the clipboard's content)
![grafik](https://user-images.githubusercontent.com/29840239/89982825-b1797480-dc76-11ea-9935-b9bc3db9c05a.png)

**Comment by SnosMe** [comment]
Look at "option 2" here https://github.com/SnosMe/awakened-poe-trade/issues/178#issuecomment-657142841

Game has to process clipboard in 120ms, after that clipboard is restored.
