### ISSUE TITLE
If you Ctrl+C'opied item, a window for it will not open

### ISSUE THREAD

**Issue by SnosMe** [SnosMe/awakened-poe-trade#2]
https://github.com/SnosMe/awakened-poe-trade/blob/81c35c7d98a080ea5fb53f4a35d926c0199c3ee8/src/components/PollClipboard.ts#L11

If you are sure that you did not press Ctrl + C, perhaps another utility did it

**Temporary fix**: just copy another item to the clipboard or any text

**Comment by Jivonchi** [comment]
This issue is very prevalent for me as well, please fix asap!
