### ISSUE TITLE
[feature request] Ctrl+F to search the mouse over item

### ISSUE THREAD

**Issue by OlivierFerriot** [SnosMe/awakened-poe-trade#200]
Hi,

would it be possible to implement the Ctrl+F so that instead of simply opening the search field,
it also automatically types the Type / Name of the mouse over item ? 
So for exemple when I try to find all my Faster casting support gem, I simply Ctrl+F over it and it automatically type it in the search ?

My old PoE trade script does this but it has things that make me unable to use it :
https://github.com/PoE-TradeMacro/POE-TradeMacro

That would be SO good

Thanks

**Comment by SnosMe** [comment]
In Awakened it is solved using "Stash search" widget. You can edit existing and add new entries in overlay window (Shift+Space).

The problem with old Ctrl+F is it's ambiguity of what was your intention to search for. Maybe it's: faster casting gem, any gem with quality, any vaal gem, just a gem. Also for dump sorting it's important the order of search e.g. you should first take all maps via "map tier" and then all fragments via "map device", using ctrl+f you should remember this order.

**Comment by OlivierFerriot** [comment]
Could you please just help me, I cannot find the Stash search widget. Where is it ?

**Comment by SnosMe** [comment]
![image](https://user-images.githubusercontent.com/4292308/90178751-0ae7bd80-ddb5-11ea-84c6-349863075aa7.png)
