### ISSUE TITLE
Huge ping spikes in pt play

### ISSUE THREAD

**Issue by 151083** [SnosMe/awakened-poe-trade#202]
Whenever i got Poe Awakened macro active while in pt with 2-3 players and doing maps my ping spikes to 1k and everything freezes for couple of seconds.. ( my fps is constantly 144).

**Comment by SnosMe** [comment]
Tool cannot affect your ping.

Do you know how network stack works? You have to saturate bandwidth given by ISP to begin see ping spikes. 
And that can be easily spotted in Task Manager
![image](https://user-images.githubusercontent.com/4292308/90345756-0842cd80-e02c-11ea-93c8-0370902acfc2.png)

**Comment by 151083** [comment]
I do know how it works i am just stating that i tested the game in party play multiple times with and without the awakened macro and when it on the ping spikes are unbearable.

**Comment by SnosMe** [comment]
If you know how it works, then you can say what tool does to cause ping spikes...
