### ISSUE TITLE
Malware warning from latest update.

### ISSUE THREAD

**Issue by Fencat** [SnosMe/awakened-poe-trade#203]
Since installing last update I get a warning for Malware.Heuristic.106 from the file "Uninstall Awakened Poe Trade.exe" and a corresponding windows registry key.

Picture of reg key:
https://gyazo.com/f55dc04cb65e758e17988ea6a93f251e

Hopefully a false positive but thought I'd let you know.

**Comment by SnosMe** [comment]
Both Uninstall and Setup .exe look clean on VT.

https://www.virustotal.com/gui/file/356b889c71534fcae006f910419b7bbcc0fbe854c3b172cb6fc3403e9b9bce45/detection

![image](https://user-images.githubusercontent.com/4292308/90501416-04f73100-e155-11ea-85dc-d0044508f02d.png)

https://www.virustotal.com/gui/file/cde2786101ecc360d466b1906c5fbd07bc8e609eafeb194d2a85ceef2585973d/detection

![image](https://user-images.githubusercontent.com/4292308/90501480-1a6c5b00-e155-11ea-8e7c-ef8f54c11cba.png)

**Comment by Fencat** [comment]
Forgot to add it was from Malwarebytes. 

But yea thought I'd let you know anyway, ty for looking into it and keep up the great work.
