### ISSUE TITLE
Bitdefender false positive

### ISSUE THREAD

**Issue by EThaNol2005** [SnosMe/awakened-poe-trade#206]
Hi, since today i get a false positiv notification from my bitdefender, when i try to start the program.
I can't whitelist the file cause of random temporarily filename.
![seccenter_DbsFF0elMP](https://user-images.githubusercontent.com/6765072/91823438-82cd3900-ec39-11ea-9f3c-105cab16d95a.png)

**Comment by kirtmys** [comment]
Hi , since today i can't start it too , bitdefender is blocking it.
How i can fix this please ? i excluded the folder and it's still not working

**Comment by SnosMe** [comment]
Report false positive to AV vendor, disable AV till they fix this. You are the owner of PC, not an antivirus software. Would you go with drunk driver? - no, you'll call another taxi. So maybe it's time to switch to another antivirus product, if you don't trust yourself in what you do on your computer.

**Comment by EThaNol2005** [comment]
Yo, slow down. It's just one false positiv case. It's just a extra layer for safty. What can i do when a hobby programming geek like you patching a backdoor or other sneaky stuff? Right, a av at least. Should i check everytime a sourcecode? No reason for your senseless bitching of other ppl.

**Comment by SnosMe** [comment]
Can you quote the part of msg that was offensive to you? You have created the issue, so you want my response to it, and that's what my thoughts about it. If you use AV software then you are prepared to deal with false positives. Thank you for bringing this to the attention of the developer, just in case. But most often nothing can be done from my side, only the AV developer can fix...
Moreover, on Virustotal file is clean.

**Comment by EThaNol2005** [comment]
I am amazed at how quickly Bitdefender responded to the report. So it's done.
