### ISSUE TITLE
Appimage Core dump when run from Steam, since 2.4

### ISSUE THREAD

**Issue by Storm-Engineer** [SnosMe/awakened-poe-trade#209]
Hi!

I used to run 2.3 from the Steam launch options, like this:
`/path/to/Awakened-PoE-Trade-2.3.0.AppImage & %command%`

When the appimage updated to 2.4 I changed the version number in that command, but it won't work anymore. It works if I copy-paste that into terminal, but when launched from the Steam launch options, it doesn't.

I got this in console, and that's all I have:
`/bin/sh: line 1: 141212 Trace/breakpoint trap   (core dumped) /path/to/Awakened-PoE-Trade-2.4.0.AppImage`

Arch Linux, fully updated
Steam Native Runtime

**Comment by SnosMe** [comment]
I updated Electron in 2.4, so it may not like to be launched from "Steam launch options"

**Comment by Storm-Engineer** [comment]
So, is this something that can be fixed? It's not a big deal, but is still an inconvenience.

**Comment by SnosMe** [comment]
As being said it is Electron (Chromium). I'll upgrade it once again to v10, it might help you, can only hope
