### ISSUE TITLE
Installation aborted

### ISSUE THREAD

**Issue by dobrelaurentiu** [SnosMe/awakened-poe-trade#210]
Hi! 

I have an issue while trying to install the app. It just says that the "Setup was not completed successfully". Haven't had this issue before. Any ideas ? 
![image](https://user-images.githubusercontent.com/21999697/93002720-98980380-f541-11ea-9df1-e0deff75d8ec.png)

**Comment by SnosMe** [comment]
https://github.com/SnosMe/awakened-poe-trade/issues/205#issuecomment-680798126
