### ISSUE TITLE
Setup was not completed succesfully

### ISSUE THREAD

**Issue by joshuaboele** [SnosMe/awakened-poe-trade#211]
I've had awakened poe trade installed on my system, but wanted to install a new version.

It says there's already an instance on the PC (If I go to this Directory, there's nothing).

Trying to install to a different folder/disk etc doesn't work either, just permanently stuck on installing screen.

![afbeelding](https://user-images.githubusercontent.com/6242820/93756339-3ad07f00-fc05-11ea-9ebb-d5c488e6ed55.png)

![afbeelding](https://user-images.githubusercontent.com/6242820/93756320-3015ea00-fc05-11ea-9990-232149af5c78.png)

**Comment by SnosMe** [comment]
https://github.com/SnosMe/awakened-poe-trade/issues/205#issuecomment-680798126
