### ISSUE TITLE
Add support for Private Leagues

### ISSUE THREAD

**Issue by ribonuge** [SnosMe/awakened-poe-trade#212]
Wondering if this would be possible?

**Comment by Roondoggie** [comment]
Agreed. Private leagues support would be great!

**Comment by ksaldana1** [comment]
@SnosMe I took a look at what it would take to implement this functionality. At face value it didn't seem like it would be that hard to add, but the main issue is that private league APIs are scoped by the `POESESSID` cookie. You would need to have users add that value to the settings somewhere in the application. All requests for private league information would need to add this cookie to its headers (including the in-app browser). This isn't unprecedented, as many other community tools ask for this id (eg. ExilenceNext or anything that deals with stash APIs), but I'm not sure if you had a hardline stance on it. It's very convenient that you currently don't have to use a `POESESSID`—one less thing to explain to users and one less error case to have to work around on the UI. The APIs don't give descriptive error messages around this stuff (just returns `code 2: invalid query`), so it's pretty annoying to code around and have good UX. 

Another annoying thing is that a lot of functionality of the app is simply incompatible with private leagues (poe ninja pricing, poe price checker, etc). You could either drag in some flag in the global config such as `isPrivateLeague` and feature flag the stuff that makes sense, but that isn't particular elegant or future proof. You could also just show temp league information instead, but that could confuse users. Not the worst thing to deal with, just another UX concern / place that could confuse people.

If you do decide to implement this functionality, here were a few other things I looked into.

1) Populating the League menu
Currently the league submenu is populated by a generic call to https://api.pathofexile.com/leagues?type=main&realm=pc&compact=1. This works great for the normal public leagues, but sadly doesn't work for private leagues. The best alternative I landed on was having the user set their `POESESSID` and account name in APT settings, and making a call to https://www.pathofexile.com/character-window/get-characters?accountName=YOURACCOUNTNAME instead (using placeholder here make sure to change the URL). 

This returns back JSON that looks like:

```json
[
   {
      "name":"Swagauras",
      "league":"Standard",
      "classId":0,
      "ascendancyClass":1,
      "class":"Ascendant",
      "level":95,
      "experience":2949369944
   },
   {
      "name":"blahblahblahsssdsadas",
      "league":"ETHICAL LEAGUE (PL12057)",
      "classId":3,
      "ascendancyClass":0,
      "class":"Witch",
      "level":1,
      "experience":0,
      "lastActive":true
   },
   {
      "name":"Swagtoxic",
      "league":"Heist",
      "classId":6,
      "ascendancyClass":2,
      "class":"Trickster",
      "level":96,
      "experience":3198940876
   },
]
```

You could iterate through the characters to create your set of leagues to populate the dropdown. Doing it this way would have the downside of not including public leagues you don't have a character for, but I could possibly consider that a feature as well depending on how you look at it. Worst case you could make both calls and combine the lists to have a full list of private leagues and public leagues. 

2) Private League Trade URL
Private leagues use the full name of the league encoded in the URL (encodeURI) on trade site. So for example the private league above "ETHICAL LEAGUE (PL12057)" uses the trade URL of https://www.pathofexile.com/trade/search/ETHICAL%20LEAGUE%20(PL12057). Updating this should be pretty trivial, as this is consistent between private and public leagues. 

Nothing here is an enormous blocker, but there's some annoyances to these solutions. Forcing the `POESESSID` *only* for this functionality might seem a bit weird, but with good default fallbacks it might be okay. I will say that the PoE API doesn't do you any favors if that value is misconfigured, so it's hard to create UX around diagnosing that for users. 

Thanks for all the work you've put into APT, I really appreciate it! If you decide to go down this road I hope my exploration at least saves you a bit of time.

**Comment by SnosMe** [comment]
Waiting for deploy of OAuth by GGG, that will bring more apis

**Comment by SnosMe** [comment]
https://www.pathofexile.com/developer/docs/authorization

> We do not support the implicit grant or the PKCE (proof key for code exchange) extension. This means that any distributed application (one that runs on a user's machine) will need to be backed by a secure server in order to keep your application credentials secret.

Well, no support for private leagues then.
