### ISSUE TITLE
Certain rolls not showing up

### ISSUE THREAD

**Issue by leet0rz** [SnosMe/awakened-poe-trade#214]
https://i.imgur.com/sVIhwoK.png
As you can see here the armor es mode is not showing in the mods and when I select them to try to make it equal to 120% shaper's gloves it does not work. These are the basic es and armor mods that shows up when price checking, I did not tune them and when the gloves are perfectly rolled they do not work. 

Please have 120% es/armor instead of the flat values because you calculations are off.

Also add a custom search soon please, its been multiple months. I want to be able to price check a goldrim etc. in game without having the item in my inventory.

**Comment by gr-queiroz** [comment]
Hello @leet0rz. Its not a issue. The item that you are checking have 7 mods, and only 1 is a variable one, the other 6 are always the same for every Shaper's Glove item. Also, you're dragging the bar to a full max roll one, and you're getting replied that there's no Shaper's Gloves with these maxed rolls at the market yet.

**Comment by leet0rz** [comment]
> 
> 
> Hello @leet0rz. Its not a issue. The item that you are checking have 7 mods, and only 1 is a variable one, the other 6 are always the same for every Shaper's Glove item. Also, you're dragging the bar to a full max roll one, and you're getting replied that there's no Shaper's Gloves with these maxed rolls at the market yet.

Yes it is an issue because the calculations are off for the flat armor/es, I just checked the exact same item with poe.trade and it has multiple hits. The rolls should be 120% armor/es, not the local flat armor/es on the item itself because they show no results but other trade macros do show results due to picking 120% armor/es over the local flat values.

**Comment by SnosMe** [comment]
![image](https://user-images.githubusercontent.com/4292308/94603152-88e92080-029e-11eb-90e1-c85a24d116bf.png)

As you can see 20% quality with 120% incr roll  = 290 AR

**Comment by leet0rz** [comment]
You should have it search by 120% increased armour and energy shield, not its base values of armour/es on the item itself. The search fails a lot of the time when it tries to search by the items base values instead of the actual roles on the item, also add a damn custom search, we've been asking for it for months now.

**Comment by SnosMe** [comment]
custom search is poe.ninja

**Comment by leet0rz** [comment]
> 
> 
> custom search is poe.ninja

All the other trade macros have a custom search, yours dont - and for that reason I'll never use it.
