### ISSUE TITLE
Fractured mods not recognized

### ISSUE THREAD

**Issue by pozibrothers** [SnosMe/awakened-poe-trade#217]
I've had a few fractured items drop in Heist league and none of the fractured mods are recognised by the application. 

An example:
```
Rarity: Magic
Paua Ring of the Yeti
--------
Requirements:
Level: 30
--------
Item Level: 67
--------
+27 to maximum Mana (implicit)
--------
+26% to Cold Resistance (fractured)
--------
Fractured Item
```

When price-checking the item above, only the `Total maximum mana` is displayed in the search filters:
![Awakened_PoE_Trade_2020-09-24_21-19-52](https://user-images.githubusercontent.com/458909/94190086-e864bc00-feab-11ea-8e66-aabdc6cb6afa.png)

I'm using version 2.4.0.

**Comment by clopnaz** [comment]
Fractured mods also do not show up in pseudo calculations:
![image](https://user-images.githubusercontent.com/20732173/94192660-41692b80-fe7d-11ea-9644-cc016424e7b0.png)
![image](https://user-images.githubusercontent.com/20732173/94192698-4d54ed80-fe7d-11ea-977c-309957c4bdde.png)
I see pseudo 41 to intelligence when in fact it should be 82.
(in my example, the implicit and random affix add up to 41, which is only coincidentally equal to the value of the fractured mod)
