### ISSUE TITLE
Severe FPS issues in game while Awakened POE Trade is running

### ISSUE THREAD

**Issue by bwoods89** [SnosMe/awakened-poe-trade#218]
In POE, with Awakened Poe Trade running, any time I move the mouse, my FPS drops to the single digits. My FPS usually stays above 100 at all times.

The issue goes away when I exit Awakened Poe Trade

**Comment by SnosMe** [comment]
It cannot affect FPS

**Comment by bwoods89** [comment]
I know you say it can't, but my frame rate tanks when awakened Poe trade is running but is fine if it is not running.

**Comment by SnosMe** [comment]
Yes, it tracks mouse movement. I have PC from 2016, i5 + 1050Ti. Running Awakened doesn't affect my fps, and it uses 1% CPU of Explorer. Either you are playing on weak Laptop or some software interferes like Antivirus or Discord overlays etc

**Comment by bwoods89** [comment]
I'm playing on a very powerful PC with an RTX 2080, 32GB of ram, and an i7-9700k. I have the Discord overlay turned off, and no anti virus software besides Microsoft Defender. I'm running the standalone poe client, so I don't have the Steam overlay either. I've not had issues with awakened poe trade in previous leagues.

**Comment by SnosMe** [comment]
Such things cannot be logged. Can only recommend to test in clean environment: create new windows user profile.

**Comment by bwoods89** [comment]
So after a lot of fiddling, I decided to update my mouse software (iCUE from Corsair), and for some reason that resolved the problems I was having with framerate. Wanted to comment here in case anyone happens to come across this same problem.

The iCUE version I'm on that fixed it is 3.33.246
