### ISSUE TITLE
How to remove the stopwatch?

### ISSUE THREAD

**Issue by SnuK87** [SnosMe/awakened-poe-trade#219]
I added the stopwatch in my overlay and there is no way to delete or move it.

When I press move it just creates a copy and I end up with 2 stopwatches. At least I can delete the copied instance.

When I press the delete button until the bar fills up nothing happens.

**Comment by SnosMe** [comment]
![image](https://user-images.githubusercontent.com/4292308/94248023-94e38400-ff26-11ea-9e99-ac93fe1ff596.png)

Enter Overlay mode Shift+Space
Mouseover Delete button, press and hold.

Delete as many widgets as you've created, obviously more than one, they are stacked in same position.
