### ISSUE TITLE
Could You support for korean language?

### ISSUE THREAD

**Issue by MissaSolemnis** [SnosMe/awakened-poe-trade#220]
I recently came across this program and admire its amazing performance.
very fast and convenient.

But Awakended Poe does not support my language Korean unfortunately.
So I change Kakao POE client(POE korean version) language to English in order to use this awesome program.

Sidekick similar to this works for korean, so I think Awakended Poe trade can make it possible.
I am not a programmer, but I know it is not an easy task.
If you make it possible, It would be a great delight to many korean users loving POE.

**Comment by SnosMe** [comment]
I'm not comfortable supporting more languages.
This will be True at least for a while.
