### ISSUE TITLE
cant change "text": "/hideout", "hotkey":   to  "Ctrl + F"

### ISSUE THREAD

**Issue by LowrageTM** [SnosMe/awakened-poe-trade#223]
i cant change it in settings so i do that manual in the config file BUT every time i start the program its on default so i need to change it again.
Where is the problem?

**Comment by Storm-Engineer** [comment]
Ctrl+F is a global shortcut for searching. It puts your cursor in the search box that is eg. on the inventory panel or teh crafting bench panel, so of course you can't use that same shortcut.

**Comment by SnosMe** [comment]
![image](https://user-images.githubusercontent.com/4292308/94339746-ed894e80-0004-11eb-8326-e31c83416e7d.png)

**Comment by LowrageTM** [comment]
Ok thank you
