### ISSUE TITLE
Can't write capital G in chat if Awakened PoE Trade is running.

### ISSUE THREAD

**Issue by Storm-Engineer** [SnosMe/awakened-poe-trade#224]
As the title says, if APoET is running, I'm unable to write capital G (Shif+G) ingame.

I was thinking maybe there is a shortcut set for that combo by accident that is interfering with it, but I looked through the settings and didn't find such.

Arch Linux + KDE
Steam version of PoE

**Comment by SnosMe** [comment]
![image](https://user-images.githubusercontent.com/4292308/94550993-4e12c880-025d-11eb-9d18-72a880ca244b.png)

can you upload your config

**Comment by Storm-Engineer** [comment]
My apologies, I missed the reply notification.

Here is the config file. Had to ZIP it otherwise GitHub doesn1t allow uploading...
[config.zip](https://github.com/SnosMe/awakened-poe-trade/files/5386681/config.zip)

**Comment by SnosMe** [comment]
Nah, don't see anything interesting

**Comment by Storm-Engineer** [comment]
So then I wonder what may cause this weird phenomena?

**Comment by RodrigoHahn** [comment]
Just to contribute something, the same bug happens to me sometimes, but with the number 8.
