### ISSUE TITLE
Add option to lock overlay

### ISSUE THREAD

**Issue by Whytryzbs** [SnosMe/awakened-poe-trade#225]
When i click Ctrl+D, i need to hold Ctrl and move mouse to overlay and click on it and after i can unhold Ctrl button, But how i rememeber previously was I click  Ctrl+D and can do with mouse what i want and if i click outside overlay closing
May be already exist this option but i can't found?
Thanks a lot!

**Comment by SnosMe** [comment]
![image](https://user-images.githubusercontent.com/4292308/94339853-d6972c00-0005-11eb-9937-02253d684e2a.png)
