### ISSUE TITLE
Mac release

### ISSUE THREAD

**Issue by sergeysrabionyan** [SnosMe/awakened-poe-trade#227]
Hello, will there be a Mac release?

**Comment by SnosMe** [comment]
There is a chance, but it is so small that I'd not expect it earlier than December.

**Comment by james-prado** [comment]
@SnosMe  What are the limitations, and are you potentially looking for collaborators?

**Comment by SnosMe** [comment]
https://github.com/SnosMe/uiohook-napi
https://github.com/SnosMe/electron-overlay-window

**Comment by systray** [comment]
Hi, any progress?

**Comment by SnosMe** [comment]
Not even viewed at it, this is a very low priority.

**Comment by hsource** [comment]
If any of you are interested in trying a Mac version, take a look at #403 or my [thread with install instructions](https://www.pathofexile.com/forum/view-thread/3129523)
