### ISSUE TITLE
Delve grid not visible with Vulkan borderless when PoE is focused

### ISSUE THREAD

**Issue by LintharC** [SnosMe/awakened-poe-trade#229]
It's a tad bit weird one, but after pressing the keybind for toggling Delve grid, I don't see it if PoE is the focused app. I have to either click something on the 2nd monitor or press the windows key to be able to see the grid. I tried screenshotting it, but as it turns out, that screenshot did show the grid, despite not seeing it in-game. 
If it helps, overlay works as expected, price check without auto-hide also works, but price check with auto-hide does not.
Everything started working as usual when I switched back to DirectX. Running as admin didn't help.
I'm playing at FHD borderless with GTX 1060, Win10.

**Comment by SnosMe** [comment]
> Vulkan borderless
> price check with auto-hide does not

Update GPU drivers, that helped to everyone who wrote this in Discrod.
