### ISSUE TITLE
Captured beasts issue

### ISSUE THREAD

**Issue by LostPoE** [SnosMe/awakened-poe-trade#23]
When doing a price check on a captured beast I get the following: "ML Prediction error. Report to Poeprices forum thread. 

Thanks

**Comment by SnosMe** [comment]
Fixed by e34e11294d6d5ee9daf9a2996abe68c883614d35

Will be available in the next release.

![image](https://user-images.githubusercontent.com/4292308/72387080-5e186580-372b-11ea-920d-421396e35d43.png)
