### ISSUE TITLE
Auto-hide cannot be set to a hotkey without ctrl or alt

### ISSUE THREAD

**Issue by kevishi** [SnosMe/awakened-poe-trade#232]
As title says,

Deselecting either alt or ctrl results in the hotkey being unbound, but when rebinding the hotkey ctrl/alt are still selected resulting in the user being unable to bind any non ctrl/alt + hotkey to auto-hide

Initial State
![image](https://user-images.githubusercontent.com/9515715/94950718-10a67900-04b1-11eb-8373-9d9abd56ee6c.png)

Deselected
![image](https://user-images.githubusercontent.com/9515715/94950858-49465280-04b1-11eb-8460-6eac232f595c.png)

Attempted Binding (unbinded "Open Without Auto-Hide" beforehand)
![image](https://user-images.githubusercontent.com/9515715/94950906-5cf1b900-04b1-11eb-852b-0ff1e70f4f4a.png)

**Comment by kevishi** [comment]
To be fair, this looks like a design decision for a potential limitation based on Windows APIs, but opened in case its not

**Comment by SnosMe** [comment]
![image](https://user-images.githubusercontent.com/4292308/94951166-79f7ad80-04ec-11eb-8ece-d2ff30463df4.png)

Yep, by design it's a modifier button that you hold.
