### ISSUE TITLE
Give an option for less sensitive stash tab scrolling

### ISSUE THREAD

**Issue by LintharC** [SnosMe/awakened-poe-trade#233]
I love the ctrl+wheel functionality, but the wheel on my mouse is very sensitive, which often makes it change 2 or 3 tabs when I just tried to go the the next one. I'd love if there was a simple checkbox or sth next to that option to make the scrolling less sensitive to the wheel's input.

**Comment by SnosMe** [comment]
Each mouse has a physical scroll step.
Your mouse can be very old and it not working properly.

![image](https://user-images.githubusercontent.com/4292308/94961264-fe522c80-04fc-11eb-8e76-d3b19a901fa6.png)


Also, there are two things in game that has builtin scroll that make it looks like it double scrolls.
1) focused search box
or
2) when mouse is over tab list

![image](https://user-images.githubusercontent.com/4292308/94960620-e201c000-04fb-11eb-9cbc-f3a11fbc9e3f.png)

**Comment by LintharC** [comment]
It's a 1 year old gaming mouse, it works properly everywhere and it doesn't _always_ scroll through 2 or 3 tabs, it's just sensitive. I use it only to dump stuff from inventory to dump tabs, so it's nowhere near the stash window.

**Comment by SnosMe** [comment]
If you can't feel this physical step of wheel (see image), adding throttling will not improve anything.

**Comment by LintharC** [comment]
I _can_ feel the step and it works fine for less precision-demanding tasks such as scrolling a webpage or adjusting volume, but it feels incredibly clunky for high-precision jobs such as scrolling through _exactly_ 6 out of 28 tabs. I usually end up scrolling over by 1 or two and having to very slowly trace back. Many apps worldwide have an option for smooth vs step scrolling and it'd be lovely if this app did have something along those lines too.

**Comment by SnosMe** [comment]
Experience must match to game scroll behavior, and poe doesn't have this magic setting you want.
Poe's builtin tab scrolling, character zooming, stack splitting - all depended on mousewheel.

![image](https://user-images.githubusercontent.com/4292308/95172881-9cc1e480-07c0-11eb-82f7-7fa1dcba2f89.png)

---

Anyway, Portable version with custom setting
download https://we.tl/t-72yqn7rQsv

You must change default value 1 to what you want. (in config file)
![image](https://user-images.githubusercontent.com/4292308/95172525-1d341580-07c0-11eb-94ac-57eb360af377.png)

![image](https://user-images.githubusercontent.com/4292308/95172495-12798080-07c0-11eb-8815-709d23ab7f5b.png)
