### ISSUE TITLE
Focus when Vulkan renderer is active

### ISSUE THREAD

**Issue by kartelusm** [SnosMe/awakened-poe-trade#234]
This does not happen always, but happens often enough to be annoying. When I am using Vulkan as a renderer, which is mostly always, sometimes the game does not some into focus on ALT-TAB even when selected. I need to manually minimize all other windows and click on the game screen. When this happens, the only way to stop it is to restart this app.

One way to reliably reproduce it (at least for me) is to use the "open in external browser" functionality.

Thanks for all your hard work!

**Comment by SnosMe** [comment]
Linux/Win ?

**Comment by kartelusm** [comment]
I'm sorry, it is a Win 7.

**Comment by vekin** [comment]
I can reproduce this on Linux with Vulkan renderer with gloriouseggroll proton and awesome window manager.

The overlay steals all keyboard and mouse focus.  I used to be able to alt-tab to the game client and still trigger the overlay with the hotkey but now the overlay immediately steals all clicks/keyboard presses and doesn't allow them to pass through.
