### ISSUE TITLE
Emphasize High Value Items (Exalted Orbs)

### ISSUE THREAD

**Issue by scottmudge** [SnosMe/awakened-poe-trade#238]
At a quick glance, exalted orbs and chaos orbs look very similar. Both golden/yellow and round.

It's often not immediately evident that the estimated price of an item is set in Exalted Orbs rather than Chaos Orbs. If I have priced 30 jewels, and 1 has an exalted price while all others have low chaos prices, it would be easy to accidentally just throw it away thinking it, too, was a low chaos price.

Is there a way to either change the text color or add a border around the price when it is a high value, to emphasize that it is an exalted price, and not a chaos price?

Alternatively, would it be possible to add an option to price everything in Chaos only, and then add an estimated exalted price in parentheses, based on the current exalted price on poe.ninja?

**Comment by SnosMe** [comment]
![image](https://user-images.githubusercontent.com/4292308/95184952-bff49000-07d0-11eb-97d1-6486e7431060.png)

![image](https://user-images.githubusercontent.com/4292308/95185335-3e513200-07d1-11eb-96e5-93e7e319d604.png)
