### ISSUE TITLE
[Feature Request] Stash tab pricing with highlight

### ISSUE THREAD

**Issue by codeninja** [SnosMe/awakened-poe-trade#24]
As a zoom zoom maper: 
* I want to run maps and dump all my items in a stash tab for bulk price check.

Let me start a recording sequence which copies any item copied to the clipboard into a queue. When I execute the second command, the engine will price check all items in the list. I am then shown the results with the item and price range.

Stretch: If positioning within the screen or stash tab location can be somehow inferred or obtained, an overlay which denotes the area and relative price could be shown to highlight items within the stash tab visually in addition to the list.

**Comment by SnosMe** [comment]
Maybe I didn’t get your idea, but it seems to me that the "net worth" tools are more appropriate here.

- Currency Cop https://github.com/currency-cop/currency-cop
- Exilence https://github.com/viktorgullmark/exilence

**Comment by codeninja** [comment]
Not really, I was thinking more akin to https://www.poeprices.info/#priceallstashes but with the ability to copy a list of items to price check.

Imagine I have my pack full of items from a run and I go to zana, rather than cont+d on every item, I would cont+shift+d, then cont+c on every item to copy that item to the list. Then another press of cont+d would see that the list is populated, and price check each item. Perhaps for brevity all prices are shown in a range ( rather than a list row for each posted item).

If you would like me to explore the idea further I could mock something up

**Comment by SnosMe** [comment]
Here is an example of what I get after completing the map. 

![image](https://user-images.githubusercontent.com/4292308/72460466-88266200-37d5-11ea-97a8-389c76488da0.png)

Only highlighted items make sense to check. But since they are rare, you don’t really want to rely on ML predictions. You still have to identify all of rares/uniques. Other items go straight to their tabs. In the end, you could observe that most rare items are full of trash, then just hide them in the filter. Speaking of the filter, if something valuable drops, then this will happen with the sound and the item will be highlighted, I think you will definitely not forget about it at the end of the map)

**Comment by codeninja** [comment]
Ok, so I've never seen this functionality in the awakened poe trade tool.
How do I enable / recreate this?

Thanks,
Dallas
---------------------------------------
*Professional leader of highly performant engineering teams since 1997*
*512.923.4426 | Github  <https://github.com/codeninja>| Twitter
<https://twitter.com/dallaspool>| Linkedin
<https://linkedin.com/in/dallaspool>*

**Comment by SnosMe** [comment]
Paint :upside_down_face:

**Comment by codeninja** [comment]
Ah, yes, well you hit the nail on the head as far as what I was describing.
But I disagree with the ML reliance. If the engine would highlight anything
it predicts to be over a budget amount, IE: show me everything predicted or
listed above 10c, then that would be a good first pass over the items.



Thanks,
Dallas
---------------------------------------
*Professional leader of highly performant engineering teams since 1997*
*512.923.4426 | Github  <https://github.com/codeninja>| Twitter
<https://twitter.com/dallaspool>| Linkedin
<https://linkedin.com/in/dallaspool>*

**Comment by SnosMe** [comment]
From a technical point of view, I already know how to implement this. I advise you not to expect it before the next league.

**Comment by codeninja** [comment]
Awesome!

[Offtopic] is the ML code that your using for price prediction a public
thing? I'd love to take a look at it and try to up the accuracy. I have a
bit of experience in the field.

Thanks,
Dallas
---------------------------------------
*Professional leader of highly performant engineering teams since 1997*
*512.923.4426 | Github  <https://github.com/codeninja>| Twitter
<https://twitter.com/dallaspool>| Linkedin
<https://linkedin.com/in/dallaspool>*

**Comment by SnosMe** [comment]
> Not really, I was thinking more akin to https://www.poeprices.info/#priceallstashes but with the ability to copy a list of items to price check.

You just mentioned their site. Here is their forum thread http://www.pathofexile.com/forum/view-thread/1216141

Their code is closed, but they accept feedback for each prediction. Unfortunately, the tool already uses their APIs, but I have not added a form to provide feedback.

**Comment by codeninja** [comment]
I may give it a go then... we could use another tool.
