### ISSUE TITLE
Danger contracts modifiers

### ISSUE THREAD

**Issue by pwilkowski** [SnosMe/awakened-poe-trade#241]
Can we have this ability please? Well essentially it would be similar to checking map modifiers.

Example input of contract:

```
Rarity: Rare
Oblivion Oath
Contract: Smuggler's Den
--------
Client: Marcine Clavus
Heist Target: Enigmatic Assembly A4
Area Level: 81
Requires Trap Disarmament (Level 1)
Item Quantity: +65% (augmented)
Item Rarity: +39% (augmented)
Alert Level Reduction: +31% (augmented)
Time Before Lockdown: +21% (augmented)
Maximum Alive Reinforcements: +31% (augmented)
--------
Requirements:
Level: 62
--------
Item Level: 81
--------
Players are Cursed with Vulnerability, with 60% increased Effect
Guards deal 27% increased Damage
21% increased time before Lockdown
Lockdown occurs immediately when Alert Level is full
Reward Rooms have 15% increased Monsters
Players have 25% less Area of Effect
--------
"I currently possess four-hundred and forty-four pieces of this ancient
and puzzling device. A few seem to be missing. This part is crucial."
--------
Give this Contract to Adiyah in the Rogue Harbour to embark on the Heist.
```

**Comment by SnosMe** [comment]
Will be released soon c9a4ad670ee8fd68b50ec08192598d0f2b8987c6

**Comment by pwilkowski** [comment]
Any ETA on this?

**Comment by SnosMe** [comment]
Released 11 days ago. If you have any issues be more concrete.

![image](https://user-images.githubusercontent.com/4292308/96351029-93d6ea00-10c1-11eb-8c81-80f5158a2883.png)

**Comment by pwilkowski** [comment]
Oh wait, I think we misunderstood here. What i was talking is checking contracts like map modifiers:
![image](https://i.imgur.com/nIs95O9.png)

Essentially contracts are map, so I am preparing like 20-40 contracts and want to run them but I cant run reflect phys and don't really want to run reduced armor ones.

so alt + q would also work on contracts and notify me about bad modifiers. Now I have to check each time i run them manually.

**Comment by SnosMe** [comment]
@pwilkowski No ETA,  working now to fix a bit of missing Heist stats

**Comment by NeroMorto** [comment]
@pwilkowski Too late, but anyway) You can use a separate stash tab with this contracts and search dangerous mods by ingame search bar (bottom on tab)

**Comment by pwilkowski** [comment]
Thats not a solution. For maps this program has made my life much more easy but as for contracts - now part of the core, feature is still missing.

**Comment by SnosMe** [comment]
e765f4620870a25c1f6d6daabebb025b96c84a54 ready for next release
