### ISSUE TITLE
Pressing F2 (chat cmd /invite @last) in windows explorer with a file/folder selected tries to run and also deletes it

### ISSUE THREAD

**Issue by JasonCweb** [SnosMe/awakened-poe-trade#242]
It's easy to recreate this bug, just select any file in windows explorer and press F2 (which is currently bound to chat cmd /invite @last).

Earlier it seemed to Select All then delete, but luckily my folder was massive and it had to prepare to delete thousands of files before actually deleting them.

Might want to check the other hotkeys as well. Kind of afraid to try them out.

**Comment by SnosMe** [comment]
![image](https://user-images.githubusercontent.com/4292308/95106805-aa845500-0741-11eb-9fa1-58454c0d2155.png)

Tool activates by listening title of currently active window.
When in Explorer hierarchy you go through any folder named "Path of Exile", it will think it's a game and activates hotkeys.
There is no easy way to fix this, and too rare to mess with.
