### ISSUE TITLE
Highlight items & Force logout

### ISSUE THREAD

**Issue by Reewarp** [SnosMe/awakened-poe-trade#247]
Hello,
I'm trying to delete somes third-party programs from my daily usage while playing PoE.
Your tool is really great but only miss two essentials features for me : 

- "Highlight items and object" by pressing Ctrl + F.
- "Force logout" (not /exit command)

It's well know features that is present on a different program than yours.
It would be awesome to have thoses here.

**Comment by SnosMe** [comment]
1. https://github.com/SnosMe/awakened-poe-trade/issues/200#issuecomment-672838894
2. https://github.com/SnosMe/awakened-poe-trade/issues/127#issuecomment-647726122
