### ISSUE TITLE
awakened-poe-trade for standard?

### ISSUE THREAD

**Issue by aspalrobin** [SnosMe/awakened-poe-trade#25]
When I launch awakened-poe-trade, it checks the prices for metamorph league and I don't know how I change the league to standard softcore.

**Comment by SnosMe** [comment]
![image](https://user-images.githubusercontent.com/4292308/72665714-a5487400-3a13-11ea-828a-2812444cbace.png)

**Comment by aspalrobin** [comment]
Thanks. Does this project have any documentation?

**Comment by SnosMe** [comment]
What exactly are you interested in? When a project is under active development it’s difficult to keep track of all things, everything changes very quickly
