### ISSUE TITLE
After adding a new field to the Stash search widget it sometimes fails to input anything

### ISSUE THREAD

**Issue by JusKillmeQik** [SnosMe/awakened-poe-trade#250]
I added my own fields using the edit mode of the Stash search widget. I rearranged the order as well.

Now when I click on a field it will sometimes load properly into the search box and highlight the appropriate items. Sometimes nothing will happen. And sometimes it will open the chat menu (as if it only hit enter).

This is more noticeable if I click two things shortly after each other, for example if I have none of a certain item when the highlight comes up so I quickly move to the next field. I can click the field again multiple times, and eventually it populates. Sometimes it takes upwards of 10 tries to get it to work. I'm not sure if this is a bouncing issue or a wait issue, but the input is not making it into the search field.

**Comment by czer323** [comment]
I've never had the issue before, but tonight I installed Yolomouse and while it's running - I have the same symptoms.  Exiting the program resolves the behaviors.  I ended up using the Win 10 pointer size instead to increase the cursor size.

**Comment by SnosMe** [comment]
I have no issues with Yolomouse.

@JusKillmeQik What OS you have?

**Comment by JusKillmeQik** [comment]
I turned off YoloMouse and it started working again. On my other computer it works with YoloMouse on. I don't know why that breaks it on one of my computers. They are both Windows 10 systems.

I will say that it looks like it's just typing things too fast and not waiting long enough for PoE to have focus again. Perhaps adding a small sleep between clicking the widget, sending control f, and sending the text would help. I'm willing to download a different branch if you'd like me to test anything.

**Comment by SnosMe** [comment]
There is no need for additional sleep here.

You can try to disable restoring clipboard, but I don't think that will help, because it's kinda different issue you have.

![image](https://user-images.githubusercontent.com/4292308/95662943-734be480-0b43-11eb-9c6a-677895c82abf.png)

**Comment by JusKillmeQik** [comment]
I tried disabling the restore clipboard and it did not fix the problem. Please let me know if you can think of another reason it would open the chat menu like it was only getting the enter key. Or why sometimes it pastes the new text after the old text like it didn't send the control f first. It definitely feels like it's trying to send the keys too soon. But I'm willing to try anything you'd like, it sounds like I'm not the only one with this problem. I can disable YoloMouse for now, but I'd really like to have that back if possible.

**Comment by SnosMe** [comment]
I know how Windows message loop works inside, what's things synchronous and what asynchronous. Based on that there is no point in adding additional sleep. On the other hand we have 2 setups that have it working with Yolomouse, and 2 - not. Since my program doesn't work in isolated environment only you can figure out. As always my advice is to test in new Windows user profile. 🤷
