### ISSUE TITLE
goes into desktop

### ISSUE THREAD

**Issue by Symphhh** [SnosMe/awakened-poe-trade#251]
Hi,

I used poe awakening trade long time. Today, advanced price check doesn't work. Ctrl + D works ok, but ctrl + alt + D goes into desktop. I reinstalled, updated, didn't help.

**Comment by SnosMe** [comment]
![image](https://user-images.githubusercontent.com/4292308/95648620-64344a80-0ae1-11eb-894c-96ef9461063e.png)
