### ISSUE TITLE
When price checking it minimizes the game

### ISSUE THREAD

**Issue by Ryztard** [SnosMe/awakened-poe-trade#252]
A friend of mine is having a problem when he's trying to price check an item and while doing so, minimizes the game. We've tried changing the keybinds and we've redownloaded the app a couple of times but we're kind of at a loss of what to do. 

The app works perfectly for me, and my brother.. but for him its not working as intended. 

- Ryztard

**Comment by SnosMe** [comment]
![image](https://user-images.githubusercontent.com/4292308/95677878-65dd3b80-0bd1-11eb-98be-076c2c68d1d1.png)
