### ISSUE TITLE
Path of Exile window cannot be focused when clicked on the window from Win10 taskbar. Also it just uninstalled itself.

### ISSUE THREAD

**Issue by SyrupBuccaneer** [SnosMe/awakened-poe-trade#253]
I'll get back to you with further troubleshooting, debugs and specifics for the former, as I've just closed it after using it all day and

And it seems to have uninstalled itself. It was installed to Local Disk Program Files and now the folder is empty.

I just reinstalled it and it kept all my settings, and the taskbar bug seems to have been fixed.

Keeping this open until I understand what the hell just happened.

EDIT; Nah, the originating issue is back. It comes up front in Window's Windows Manager but is not in _focus_. 
Tell me what to send for debug.

**Comment by SnosMe** [comment]
1. #36
2. capture a video
