### ISSUE TITLE
One-key set price note

### ISSUE THREAD

**Issue by lxsli** [SnosMe/awakened-poe-trade#254]
I have an AutoHotkey macro set to `<HOME>~b/o <END> chaos`. This means I can open the note on an item, enter EG "30" and then tap a key to have the rest of the price added automatically. I find this considerably faster and more convenient than clicking through dropdowns. A bit less so now the default currency is chaos, but it's still annoying having to select price vs buyout.

Is this possible with Awakened please? Or is there an easier in-game way to do it? Or could it be added to Awakened please? A way to bind keys for other currencies could also be useful for some.

**Comment by Rottenbeer** [comment]
Isn't it against the "one click - one action" policy of GGG?

**Comment by lxsli** [comment]
That policy refers to one server action. While I'm no expert on GGG's server protocol, if I were implementing it, setting a note on an item would be a single action.

As an update, I've set up a second version to price by exalts. I use Insert for chaos and shift-Insert for exalted.

**Comment by SnosMe** [comment]
I think it's too individual and better to keep for AHK.
