### ISSUE TITLE
PoE native item rendering

### ISSUE THREAD

**Issue by ezloj** [SnosMe/awakened-poe-trade#255]
It would be great if items were rendered like this:
https://xteare.itch.io/path-of-exile-item-generator

Would take no effort to adjust and scan mods with your eyes as quickly as in-game. Also, more aesthetically pleasing.

**Comment by ezloj** [comment]
Why closed? Any explanation?

**Comment by SnosMe** [comment]
Game-like layout doesn't work good with all needed filters. Also window must be always full height, replicating item UI will look weird. If want so you can look at poe-overlay or it's community fork
