### ISSUE TITLE
Can't install after I deleted all files

### ISSUE THREAD

**Issue by Olsnn** [SnosMe/awakened-poe-trade#260]
Deleted awakened poe trade folder in AppData, tried to reinstall but it stops halfway saying the installation didn't finish properly.
are there more files I can delete somewhere to get a completely fresh install?

**Comment by SnosMe** [comment]
![image](https://user-images.githubusercontent.com/4292308/96159801-c0ea9780-0f1d-11eb-86a3-1d65954d00a7.png)
