### ISSUE TITLE
map checker misses curses mods

### ISSUE THREAD

**Issue by MarcinSosniak** [SnosMe/awakened-poe-trade#262]
map checker omits 'players are cursed with # with #% increased effect', they do not appear on the list (and therefore cannot be checked). tested on t16 and yellow maps for lower increased effect value. 

![image](https://user-images.githubusercontent.com/37940203/96365665-8c0b5a00-1142-11eb-8230-8f6fe6de3062.png)
![image](https://user-images.githubusercontent.com/37940203/96365688-b65d1780-1142-11eb-9633-2fb79dca9526.png)

**Comment by SnosMe** [comment]
Looks like you're not using the latest version (v2.6)

![image](https://user-images.githubusercontent.com/4292308/96368430-77d45680-115c-11eb-87b9-ccf2bb8fbad3.png)

![image](https://user-images.githubusercontent.com/4292308/96368455-8de21700-115c-11eb-8e19-ad7541a40d5e.png)
