### ISSUE TITLE
Dump sorting often takes multiple clicks to work properly.

### ISSUE THREAD

**Issue by gotex007** [SnosMe/awakened-poe-trade#263]
It's been a real frustration during the entirety of the feature's existence. It'll often times take multiple attempts to actually search because it'll manage to "ctrl-F" but not actually "paste" or it'll end up opening the chat window. Sometimes it's like it just fails outright, still closing the window but not actually searching anything. I really like the feature, I just wish it would work properly all of the time and not just half the time.

**Comment by SnosMe** [comment]
If you are on Linux it's a linux limitation.
Works smoothly on Windows. If you're experiencing this on Windows it's up to you to find problem.

**Comment by gotex007** [comment]
Excuse me? It's clearly _not_ working smoothly on windows. Isn't there something I can do to try to help figure out the problem instead of you shutting it down for no reason? It's been an issue since it was first implemented. I've just been expecting the issue to eventually get resolved without making a ticket and now that I finally do I just get shut down? Hello?

**Comment by SnosMe** [comment]
Duplicate of #250

Also 99% that it will correctly if you test in new clean Windows user

**Comment by gotex007** [comment]
Then say that instead of telling me to go fuck myself dude. Damn. At least I have something to look at now.

**Comment by gotex007** [comment]
I contacted the guy directly. The issue was never resolved. A different Windows user doesn't appear to have any impact. It's definitely related to YoloMouse as it works perfectly when YoloMouse is closed, which is ultimately what the guy decided he had to do in order to use the feature.

**Comment by gotex007** [comment]
I don't understand your refusal to acknowledge and your lack of caring towards fixing an actual dysfunctional aspect of your application. You have a really weird attitude like your ego is severely overinflated.

You "accept" that decimals exist and have chosen to "enhance" it despite it not being an actual issue at all and yet you disregard an actual issue because you personally apparently can't duplicate it or be bothered to help troubleshoot it to find the root cause and fix it.

This issue is not unique to me nor to JusKillmeQik which means that other people also have the problem or aren't using the feature. Why would you just not care and toss it aside? I even see he made suggestions (that he still believes is the answer, by the way) that you disregarded because you apparently know better. You also weirdly argue that since 2 machines have it work properly and 2 don't that it's not your problem. Pretty weird man. My machine makes it a 3rd. So as far as I know it's a problem on 60% of machines. I tried asking my friend if he has the issue but he has never used the feature so he doesn't know.

So if you _really_ know how Windows works, why is your application dysfunctional on 60% of tested machines that use YoloMouse?

**Comment by SnosMe** [comment]
But you missing point that I don't know how YoloMouse works. It can do crazy fkin things, YoloMouse is also was the case for bad performance.
So for example YoloMouse maybe has two multiple modes of work, so for some reason it picks what works on my PC and doesn't work on yours, and works on 2nd PC of JusKillmeQik.
