### ISSUE TITLE
Option to auto check all STATS when price checking?

### ISSUE THREAD

**Issue by ddoggo** [SnosMe/awakened-poe-trade#264]
Since the Roll on unique items can have a huge difference in price.  It would be nice to have a quick way to check instead of manually checking every stats every time. 

If it's always possible to do so, please let me know.  I wasn't able to see this option in setting. 
Thank you for the awesome tool.

**Comment by SnosMe** [comment]
Selecting all stats leads to unreasonable increase in price, if you want to sell item think like a buyer. You will buy an item with the most 2-3 important stats max rolled, but you don't care about another shit. Of course if you have item with all perfect rolls then it makes sense to tick all stats, but in PoE it's a very rare event.
