### ISSUE TITLE
Can't open settings when game is active.

### ISSUE THREAD

**Issue by Z0ld3n** [SnosMe/awakened-poe-trade#265]
Whenever game is active (windowed fullscreen) it is not possible to use Awakened PoE Trade tray icon, you can't go to settings/change league etc. I think that context menu of tray icon is being drawn below game window (or not shown at all). If it is hard to fix/reproduce maybe easy solution would be to add hotkey for settings window. I'm using WIN10 and this is happening both on DX11 and Vulkan renderers.

**Comment by SnosMe** [comment]
Open any window and then click icon (for example explorer Win+E, instead of just pressing Win).

This a bug of Electron, you can easily reproduce it with Discord tray menu too.

**Comment by oddehh** [comment]
Also, is the icon is in tray, when it is in the hidden part (you can open with the arrow icon) you'll be able to open settings.
