### ISSUE TITLE
Checking Map mods does not work with Zana

### ISSUE THREAD

**Issue by SiverDX** [SnosMe/awakened-poe-trade#268]
If you press the hotkey nothing happens (tried it with a simple one aswell, like just 'w')

I dont know if the original trade macro has this functionality, so i cant say if its even possible

Using version 2.6.0

**Comment by azra1l** [comment]
had the same issue with overwolf poe overlay.
i think the issue here is, that the map item stats ain't copied to clipboard, because the item doesn't belongs to you or something along these lines..

**Comment by SiverDX** [comment]
> had the same issue with overwolf poe overlay.
> i think the problem here is, that the map item stats ain't copied to clipboard, because the item doesn't belongs to you or something along these lines..

yeah, CTRL + C does not copy the mods of the map Zana is offering

**Comment by SnosMe** [comment]
> yeah, CTRL + C does not copy the mods of the map Zana is offering

That's correct

![image](https://user-images.githubusercontent.com/4292308/96758582-9f872100-13df-11eb-9f3f-d0d8352764ff.png)
