### ISSUE TITLE
Adds # passive skills on jewels is placed in the "Max" area instead of "Min"

### ISSUE THREAD

**Issue by djodars89** [SnosMe/awakened-poe-trade#270]
When price checking jewels, the number of passive skills is put in the maximum field instead of the minimum.
This significantly reduces the accuracy of the price.
(e.g.: a medium cluster jewel with Adds 6 passive skills is up to 3 times the price of a Adds 4 passive skills jewel).

**Comment by SnosMe** [comment]
Have a link for you https://pathofexile.gamepedia.com/Cluster_Jewel#Optimal_passive_skill_amounts

Also you can check poe.ninja builds to verify information in article. 😃
