### ISSUE TITLE
The exact rolls maths are off

### ISSUE THREAD

**Issue by leet0rz** [SnosMe/awakened-poe-trade#275]
The search has 239% armour and energy shield as is set to "exact roll", the search:
https://i.imgur.com/wLyDB4z.png

On the website:
https://i.imgur.com/Lbsv6h8.png

As you can see the search finds 238% armour and energy shield rolls too. Thoughts?

**Comment by SnosMe** [comment]
You didn't select to filter by this stat...

I you don't agree with me please attach item info(ctrl+c) and url on trade site (tick filters and click arrow button)

**Comment by leet0rz** [comment]
Select the filter by stats? It doesnt show the armour and energy shield
when I CTRL ALT D it. Here is the item copy:

Rarity: Unique
Incandescent Heart
Saintly Chainmail
--------
Armour: 1359 (augmented)
Energy Shield: 308 (augmented)
--------
Requirements:
Level: 70 (unmet)
Str: 99 (unmet)
Int: 115 (unmet)
--------
Sockets: B
--------
Item Level: 76
--------
239% increased Armour and Energy Shield
+90 to maximum Life
0.95% of Attack Damage Leeched as Life
Gain 20% of Elemental Damage as Extra Chaos Damage
25% of Elemental Damage from Hits taken as Chaos Damage
26% increased Light Radius
Light Radius is based on Energy Shield instead of Life
--------
Only light may banish the shadows from this land
And the black lies wrapped around your heart

As you can see it has " 239% increased Armour and Energy Shield", but 238%
also shows up when opening the trade as on the picture in trade.

https://www.pathofexile.com/trade/search/Heist/KezkO4LS5

**Comment by SnosMe** [comment]
You can find this stat under "hidden" switch. But you must search by an actual AR an ES. There are reasons behind this, like Atziri's Splendour that has variants, or corruptions that add incr pdps for unique weapons.

**Comment by leet0rz** [comment]
This is a problem with pretty much every item right now that we have to
take another step to open the search engine and go through the filter and
edit it ourselves. Having this work for thousands of items outweighs
Atziri's Splendours one special entry. You should change it to show the
item's % instead of their base flat values.

Also here is another search that is not working correctly (dying sun):
https://i.imgur.com/AmJOQnt.png

You have to move the -10 from minimum to maximum as it shows up on the left
side as default when it should be on the right side, now it shows all rolls
instead of 10 reduced charges used which is what everyone wants.
