### ISSUE TITLE
Shift + Space not very convenient shortcut, accidentally triggering while typing

### ISSUE THREAD

**Issue by Aemnesia** [SnosMe/awakened-poe-trade#276]
I couldn't figure out why the overlay was showing up randomly when typing to other players. As it turns out, when I ask a question and use a question mark (?) and press the space bar afterward, I am usually still with my finger on the shift key. This was falsely triggering this shortcut and I have since changed it to "Home." Now it only happens when I want it to- but I suggest shift + space be changed from the default because of frequent and accidental triggering.

**Comment by SnosMe** [comment]
This is described in https://snosme.github.io/awakened-poe-trade/quick-start
Nothing stops you from changing it

The default will not be changed, combination is easy to press for left hand, has no conflicts with apps like Steam, does not have meaning (you don't have uppercase space), moreover it's the only way that most people discover that overlay even exists.
