### ISSUE TITLE
add keybinding

### ISSUE THREAD

**Issue by primer97** [SnosMe/awakened-poe-trade#279]
- add a keybinding to search item
for example ctrl+F on an item would open the search with item name

- allow to scroll tab with right-click+Mouse-wheel

**Comment by SnosMe** [comment]
- https://github.com/SnosMe/awakened-poe-trade/issues/200#issuecomment-672838894
- mouse keys not easy to bind. 99% of time you hold Ctrl to transfer items, it's also consistent with built-in stash tab scroll that game has (do you know about that?, and you can't change it). If absolutely needed you can look at AHK scripts
