### ISSUE TITLE
Feature Request: Heist Cheat Sheet

### ISSUE THREAD

**Issue by Omegazed** [SnosMe/awakened-poe-trade#282]
A cheat sheet for heist, similar to the betrayal cheat sheet that shows reward by person and branch, a sheet for heist that shows what big chests certain jobs can have. (ex: observation may have div card big chests)

**Comment by joelmaust** [comment]
Go here and save image locally: https://i.redd.it/8r0n5apf5qo51.png

Shift+space in game, go to the cheat sheet, click edit, and you should be able to add the sheet manually. Thats what I did.

**Comment by MildPanda** [comment]
Interesting. DIdn't know certain jobs could only have certain chests. Thanks! I've been collecting a handful of cheat sheets; feel like you need them for this game as it's got so much going on.
Here is my google drive link for other cheat sheets in case we can have these added by default too. https://drive.google.com/drive/folders/1-kz1vy5bFmjM_8zyBEpANHo55c0kuYdw 
No idea how accurare any of these are still. Got everything except from essence cheat sheet here https://www.pathofexile.com/forum/view-thread/2451569 and I got essence cheat sheet here https://reddit.com/r/pathofexile/comments/52onwd/guide_a_quick_referencevisual_guide_image_for/

**Comment by SnosMe** [comment]
![image](https://user-images.githubusercontent.com/4292308/108563436-1db1f080-730a-11eb-90e1-e594d8154d1c.png)

I don't want to impose my opinion with what cheat sheets app should come, keep them updated... the widget was created to easily add images yourself.
