### ISSUE TITLE
Program attempts to uninstall itself when closed from the tray widget

### ISSUE THREAD

**Issue by Volatar** [SnosMe/awakened-poe-trade#283]
Whenever I close the program using the Quit button on the tray, it attempts to uninstall itself.

![image](https://user-images.githubusercontent.com/1719182/99294258-d2230e80-2811-11eb-8697-db0fce530291.png)

Luckily UAC kicks in and I can say no, but it is annoying to do every time and should not behave this way. I just want my processor cycles back, I don't want to be rid of the program entirely.

**Comment by SnosMe** [comment]
#36

**Comment by Volatar** [comment]
Ah ok, run as admin. Got it.
