### ISSUE TITLE
Potential autofill UI improvements

### ISSUE THREAD

**Issue by Mar-vo** [SnosMe/awakened-poe-trade#285]
If you're price checking lots of items, the following buttons would be useful:

1. Clear all automatically selected requirements
2. Fill exact values

short explanations:

1. Clear all automatically selected requirements
Often when i'm trying to pricecheck an item - for example an item base, i have to unselect default values. I often hit the request limit simply by removing the stats one by one. A little "X" to remove all stats next to the "y out of y stats" button would be nice QoL.
Edit: this could also just be a generic "clear all requirements" button.

2. Fill exact values
On some items, rolls really matter. And sometimes you find a perfect roll. Most of the time, they don't (so i  allow for a roll range), but it would be nice if there was a button to fill exact values into all fields for that moment when rolls matter. This could also be achieved by for example right clicking the little value drag bar or the "x out of y stats" button.

**Comment by SnosMe** [comment]
1. #377
2. No
