### ISSUE TITLE
Uncaught Exception After Updating

### ISSUE THREAD

**Issue by Gramatikal** [SnosMe/awakened-poe-trade#290]
Hello, I attempted to update today before playing the new league by opening, closing, then re-opening Awakened Trade after several minutes. I was met with this error message:
![image](https://user-images.githubusercontent.com/8893366/104784636-53cde480-574e-11eb-8484-ab453434b82c.png)

I've tried reinstalling and restarting but I get the same problem now every time I try to open it. Did I accidentally uninstall something the program is dependent on?

**Comment by SnosMe** [comment]
Hi, this was fixed in 2.8.1, download it manyally

**Comment by Gramatikal** [comment]
Awesome, thanks! We're up and running.
