### ISSUE TITLE
Problem with changing league in interface

### ISSUE THREAD

**Issue by ayylemao** [SnosMe/awakened-poe-trade#291]
When changing the League in the General Options tab from Standard to Ritual, the pricing interfaced accessable over default key bind ctrl+D still shows Standard at the top bar. Reinstalling didn't fix the issue and I can't price or search for items in Ritual league.

**Comment by SnosMe** [comment]
Hi, I was not able to reproduce this,
- try editing config by hand, or delete config
- restart app

![image](https://user-images.githubusercontent.com/4292308/104799161-7f47e200-57d5-11eb-9284-d10825a766e1.png)
