### ISSUE TITLE
Lookup leaves control key pressed

### ISSUE THREAD

**Issue by GIT-Cyclonus** [SnosMe/awakened-poe-trade#294]
Using Control for my mic transmit key.
When I do a lookup using this wonderful tool it keeps control in a "pressed down" state. 
The VOIP App I'm using is Mumble and I've configured awakened poe trade almost every different way ( including to not restore clipboard )

**Comment by SnosMe** [comment]
This is a bug in your VOIP App, that does not correctly listens for key states. If Ctrl was "pressed down" it would affect every app.

**Comment by GIT-Cyclonus** [comment]
I will log this with Mumble 👍 
Discovered with further testing that the issue goes away if I rebind the lookup to something that contains ```control``` in it. Binds that do not contain control in the modifiers will have this issue.

**Comment by GIT-Cyclonus** [comment]
@SnosMe is there a way to use Awakened POE Trade without using the control key at all while doing things with the app? Even the hideout hotkey is triggering control for some reason.
