### ISSUE TITLE
Awaken poe trade unistalls itself upon exit

### ISSUE THREAD

**Issue by meromex** [SnosMe/awakened-poe-trade#295]
every time i install the local installer and then close it it auto uninstalls itself so i have to install it again when i need to run it again, i dont think this is normal, i think its trying to run an update but fails to do so and stays uninstalled

there's a notice that old-unistaller is trying to run and if i accept it wipes it

Edit.
issue resolved after clearing temp files in %appdata% local, and files in roaming for awaken and re downloading newest version, was using an old version 2.6 and something went wonky, the update was inside awakened-poe-trade-updater but never ran.

closing ticket

**Comment by SnosMe** [comment]
Sorry for the inconvenience, I have no control over the updater, redownloading is the right choice.
