### ISSUE TITLE
Feature request: Close window when you mouse off it

### ISSUE THREAD

**Issue by sclient** [SnosMe/awakened-poe-trade#30]
the 0.30 version did this (yes I know another guy mentioned it on reddit, but Im also struggling with how much slower it is to click x, the speed of your tool is why I (was) mainly using it).

**Comment by SnosMe** [comment]
And it still does it.

You simply did not release Ctrl when you moved the mouse to the opposite side of the game window.

> Hold Ctrl if you do not want the window to close. As soon as the cursor is within the window, you can release Ctrl. Now, to close the window, press Esc or the cross icon in title bar.

Perhaps I will add auto-closing by condition: there was not a single click in the tool window on mouseout.

**Comment by sclient** [comment]
It stays open for me with no buttons held. Refuses to close without clicking the x button. Windows 10.

**Comment by SnosMe** [comment]
You can try the latest version. I am sure your issue has been addressed
