### ISSUE TITLE
Requests using undefined as the league name

### ISSUE THREAD

**Issue by Novynn** [SnosMe/awakened-poe-trade#300]
For both regular searches and exchange searches:

- /api/trade/search/undefined
- /api/trade/exchange/undefined

Appears to affect 2.8.1 and 2.6.0.

**Comment by SnosMe** [comment]
Cannot reproduce. 2.6.0 was very stable that lived through December events, and there were no problems with leagues. 
Undefined can be sent only before leagues are retrieved from API at app startup, and user performs price check very fast, which is  a very rare event. Also, every request can be only manually initiated, no auto-retries. Did you get a LOT of undefined's on backend ?

**Comment by Novynn** [comment]
Around 1% of requests have undefined as the league.
