### ISSUE TITLE
JavaScript Error

### ISSUE THREAD

**Issue by ApocalypseZenny** [SnosMe/awakened-poe-trade#301]
![image](https://user-images.githubusercontent.com/45135557/104861241-06dc4080-58fd-11eb-9b2d-e460089f9c31.png)

When I try to run the program, after uninstalling and reinstalling.  I'm sure it's something I'm screwing up, but just in case it's not.

**Comment by SnosMe** [comment]
Yes, it's something on your end.
Thanks
>  I'm sure it's something I'm screwing up, but just in case it's not.
