### ISSUE TITLE
Gfn

### ISSUE THREAD

**Issue by Newbrn** [SnosMe/awakened-poe-trade#303]
Any chance of being adapted to run on geforce now? :(

**Comment by SnosMe** [comment]
![image](https://user-images.githubusercontent.com/4292308/104950140-d06bf780-59c8-11eb-8796-3fa42b9c0cb5.png)

As soon as GFN starts to forward clipboard

**Comment by Newbrn** [comment]
already imagined :(
had any hope for a miraculous API. 

anyway, ty !
