### ISSUE TITLE
[Linux] awakened-poe-trade > 2.6 creates a black overlay on startup that covers the full PoE window 

### ISSUE THREAD

**Issue by eP-poe** [SnosMe/awakened-poe-trade#304]
I can not see the POE window anymore and "overlay" is black.

Streaming to discord results in "normal" view for participants.
I was able to navigate in POE (though without sight).
/hideout shortcut is working and i guess the rest too.

Anybody with similar observations?
I run manjaro.

**Comment by weidtn** [comment]
Same. I also use manjaro. And xmonad.  Disabling picom does not work. The game is running behind a solid black fullscreen overlay.

**Comment by SnosMe** [comment]
https://github.com/SnosMe/awakened-poe-trade/issues/185#issuecomment-723129140

**Comment by eP-poe** [comment]
I use gnome, and to my knowlegde I can not disable window composition -  enabled by default at all times.
This problem is not present in version 2.6.

-> meehhh **solution** -> start PoE + trade -> restart gnome (alt+F2) -> enter r for restart

This results in a normal PoE window. You can actually play (only a preliminary test).
Price check generates a full screen gray overlay for each check (so the overlays stack on each other...)
You can see it on the mouse cursor location and the old price check.

![Bildschirmfoto vom 2021-01-20 12-19-04](https://user-images.githubusercontent.com/77662965/105168495-7f6c1880-5b1a-11eb-867e-f78bbfd1e469.png)

**Comment by eP-poe** [comment]
I found a solution

-> disable "Hardware Acceleration" in awakened-poe-trade

**Comment by SnosMe** [comment]
sneaky, yet it's disabled by default
