### ISSUE TITLE
Handle Rogue Marker as Currency

### ISSUE THREAD

**Issue by AkumaNoTsubasa** [SnosMe/awakened-poe-trade#307]
Hello,
since currency is handled in a way it tells you how much your current stack is worth depending on the current market price, it would only make sense to add this feature to the rogue markers as well.
kind regards

**Comment by SnosMe** [comment]
Thank you for noticing. Unfortunately this block depends on data from https://poe.ninja/standard/currency
there is no price for Rogue Marker atm
