### ISSUE TITLE
Requests are never cached.

### ISSUE THREAD

**Issue by shadryck** [SnosMe/awakened-poe-trade#310]
As far as I can tell no lookups are ever cached at all. This means that if someone accidentally moves cursor he needs to do another lookup, resulting in another request unnecessarily eating away bandwidth. 

I believe it would be good for both the client and GGG's bandwidth that lookups done in quick succession should reuse a cached result. This result can even be tagged with a small label [Cached] to indicate that the result the user is looking at is indeed a cached result. One might argue that you always want the most fresh results and thus doing multiple lookups, but considering the heavy request limit that is already in place this is impossible anyway. This also has the advantage that when the request limit is reached, at least you will be able to see the last cached result instead of having to wait potentially 60 seconds to finally get the next requested lookup result.

**Comment by shadryck** [comment]
@SnosMe Why is this issue closed with no response whatsoever? The issue @J-Kat mentioned is completely unrelated.

**Comment by SnosMe** [comment]
https://github.com/SnosMe/awakened-poe-trade/releases/tag/v2.9.1
