### ISSUE TITLE
Feature Request: Add Poeapp or other source. 

### ISSUE THREAD

**Issue by Davst** [SnosMe/awakened-poe-trade#311]
Since the official trade site is almost useless at times, this affects the overlay. There are situations where the trade site just doesn't respond but searches can be made through poeapp. It'd be nice to be able to switch, like you can on poe.ninja.

**Comment by xenadmin** [comment]
Bold assumption, is Awakened PoE Trade (partly) the reason the official trade side is so slow at times?

**Comment by SnosMe** [comment]
poeapp is closing soon, also developer didn't give permission to use poeapp api (understandable)
