### ISSUE TITLE
Price estimation: Display values should be consistent for items worth less than 1c

### ISSUE THREAD

**Issue by Davst** [SnosMe/awakened-poe-trade#312]
The approximated value of an item is when looking up a yellow items are displayed as 0.x chaos, which is consistent with when items are worth more than 1 chaos. (eg. 2.4c)

However, when looking up items like fossils etc the value above 1c is listed in a consistent manner, but when worth less than 1c it is listed as a fraction, while 1/2c isn't that bad (still would be better as 0.5c) the more arbitrary fractions like 1/14c is generates a lot more cognitive load than 0.07c would.

Price estimations should use consistent decimal values in the UI at all times.

Bad example: https://i.imgur.com/MaDXu3J.png

Good example: https://i.imgur.com/7a7U16M.png

**Comment by SnosMe** [comment]
Disabled fraction format for non-stackable items, will be in next release
