### ISSUE TITLE
Error 1020 - Access denied - leagues loading

### ISSUE THREAD

**Issue by tonoslav** [SnosMe/awakened-poe-trade#313]
Somebody know how to skip this? 
![image](https://user-images.githubusercontent.com/3399021/105899386-e443d900-601a-11eb-9791-92dec1ba8b07.png)

When I open link in chrome to get leagues
For example: 
 - https://api.pathofexile.com/leagues?type=main&realm=pc
 - https://api.pathofexile.com/leagues?type=main&realm=pc&compact=1
Which are used by this plugin, I get normal responses

![image](https://user-images.githubusercontent.com/3399021/105899726-52889b80-601b-11eb-89b6-b86cad59351f.png)

**Comment by Packuh** [comment]
i have a similar problem

**Comment by Juts2** [comment]
GGG has blocked API access because of the huge load this tool put on the server. They need to disable the auto searching and put in a stronger rate limit,

**Comment by InTrustABC** [comment]
Ooh, damn. Do u have a source for that? Is all API acces denied or just for this tool?

**Comment by ThijsDesot** [comment]
Same problem here. Any solutions?

**Comment by ThijsDesot** [comment]
My friends are stille using it. Mine is not working.

**Comment by IdrisDose** [comment]
GGG has indeed blocked this tool temporarily until a patch comes out preventing it from spamming their API.
