### ISSUE TITLE
Error: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by Korach** [SnosMe/awakened-poe-trade#315]
I'm getting this error and I don't know what's causing the issue.
![unknown](https://user-images.githubusercontent.com/34204486/105909920-00c12080-5fdd-11eb-9d3b-d74f51355e81.png)
![unknown2](https://user-images.githubusercontent.com/34204486/105909930-03bc1100-5fdd-11eb-980e-38474cf7850f.png)

**Comment by J-Kat** [comment]
Could be that Awakened PoE Trade is the tool that was flooding the trade site and therefore disabled:
https://www.reddit.com/r/pathofexile/comments/l5ev9b/rip_trade_site/gkuveft/

Related issues: #273 #310 #314

**Comment by Korach** [comment]
Ah okay. Thanks.
