### ISSUE TITLE
Option for proxies

### ISSUE THREAD

**Issue by Sasstraliss** [SnosMe/awakened-poe-trade#317]
My wife and I commonly play together, and both use the extension. Thus, we get trade-banned for rate limit exceeding. This would be avoided if:

1. Awakened is aware there's another instance on the same IP and adjusts its internal rate limiting accordingly
2. Awakened allows use of proxies so I can avoid getting trade-banned

**Comment by SnosMe** [comment]
Add proxy flag to app shortcut  https://www.electronjs.org/docs/api/command-line-switches#--proxy-serveraddressport
