### ISSUE TITLE
Dumb sorting inconsistency problem

### ISSUE THREAD

**Issue by 8Times** [SnosMe/awakened-poe-trade#318]
Currently when I click on dumb sorting it sometimes works and sometimes it doesn't and instead opens the chat.

Here is a video showcase of the issue: https://youtu.be/G_Y6LOP6Btk

**Comment by SnosMe** [comment]
Hi, thank you for making video. It was reported before that some programs may cause this, e.g. YouloMouse. I don't see YoloMouse on video, but see some overlay in top left corner. When focus is brought back to poe, if that overlay is badly coded it can steal focus for a millisecond.

![image](https://user-images.githubusercontent.com/4292308/106241697-233a8000-620f-11eb-8be8-39a59d28ac95.png)

**Comment by 8Times** [comment]
Oh well, this is the recording software aka Nvidia's GeForce Experience.

I basically have it on 24/7 to record unexpected drops and other things.
