### ISSUE TITLE
Ilevel Missing

### ISSUE THREAD

**Issue by Millsy102** [SnosMe/awakened-poe-trade#319]
Hey there,

Please Develop a Box that you can put iLevel in and make it a tick box so you can include it in your search or not.
Ive been getting spammed due to it.....

**Comment by SnosMe** [comment]
Is it was Cluster Jewel ?

**Comment by Millsy102** [comment]
No. belt of the Deciever

**Comment by SnosMe** [comment]
Item level on unique items has no value. (well, on some popular unique items it can affect corrupted implicit. But Belt of the Deceiver isn't one of them)

**Comment by Millsy102** [comment]
Why am i getting Spammed then?

**Comment by Millsy102** [comment]
if it doesnt matter because clearly it does...or i wouldnt be getting spammed !

**Comment by SnosMe** [comment]
I'm repricing item after getting spammed, and if I spammed again I sell item and then ask what was valuable in it, get response every time.

**Comment by Millsy102** [comment]
The solution would be for the dev of the tool to develop a ilevel filter for those matters.....Im sure im not the only person being spammed due to this issue

**Comment by Millsy102** [comment]
Look ive found a problem with something that too you clearly a long time to develop. Im also the one coming to you to let you know. Now i see the dev looking for every reason not to do it.....Im going back to what i was using before.....
