### ISSUE TITLE
Request: Add empty prefix/suffix as a search parameter

### ISSUE THREAD

**Issue by rpm604** [SnosMe/awakened-poe-trade#320]
For many items having empty pref/suff can have a large effect on market value. Would love to be able to compare to items with similar life/resist AND empty slots.

**Comment by SnosMe** [comment]
This is a more complex problem than just adding empty --- modifiers filter. Found 64 items for this query.

![image](https://user-images.githubusercontent.com/4292308/108591378-25f14680-7371-11eb-88f6-455f03e0c2bf.png)

---

Adding only "Empty Suffix Modifiers" will yield only 29 results, which is not quite what I want.

![image](https://user-images.githubusercontent.com/4292308/108591522-d7907780-7371-11eb-81c0-9a50cc5e91df.png)

---

Yet another example of what you might want as a buyer, open suffix and filled 3 prefixes and none of them crafted. 11 Results.

![image](https://user-images.githubusercontent.com/4292308/108591620-5ab1cd80-7372-11eb-9164-b7d0419788d5.png)

Maybe some brilliant idea will come to my mind today.

**Comment by SnosMe** [comment]
I came to this solution (+optionally pref/suff)

![image](https://user-images.githubusercontent.com/4292308/108594283-bdf72c00-7381-11eb-8cc8-35e5ee9be063.png)

Will be in next release (shown under hidden toggle and only if item has 5+ stat lines)
