### ISSUE TITLE
Price Check Auto-Hide Mode: No Overlay after Win10 Upgrade

### ISSUE THREAD

**Issue by Lokkedian** [SnosMe/awakened-poe-trade#325]
Was on Win7. Ran MS's upgrade to Win10. As subject states. "Open Without Auto-Hide" does still work, as does Overlay and Open Item on Wiki.

**Comment by Lokkedian** [comment]
Update: All the overlays work when in Windowed Mode, but NOT in Fullscreen Windowed Mode (which they all did work in with Win7). I get this isn't a problem of this app, but any ideas what's going on in Win10?

**Comment by SnosMe** [comment]
> Open Without Auto-Hide" does still work

You probably didn't read https://snosme.github.io/awakened-poe-trade/issues
that says 
> Do you play with Vulkan renderer? Update your GPU drivers.

**Comment by Lokkedian** [comment]
I think that's it. After upgrading to Win10, and reading what you wrote, I checked my drivers and they are definitely not the newest ones, or even the same version I had before.
