### ISSUE TITLE
Cluster jewel pricing ignores notables

### ISSUE THREAD

**Issue by verydarkmagic** [SnosMe/awakened-poe-trade#326]
When I'm pricing a medium cluster jewel the search disregards notables

![image](https://user-images.githubusercontent.com/26402292/107264152-4f45d480-6a4b-11eb-89d1-a8dd27488296.png)

This is how correct search should look:
![image](https://user-images.githubusercontent.com/26402292/107264502-b6638900-6a4b-11eb-8a75-a6dbfb361cca.png)

This is the actual item
![image](https://user-images.githubusercontent.com/26402292/107264635-de52ec80-6a4b-11eb-9554-2e1b6de5c8d1.png)

**Comment by tamaroth** [comment]
What about cluster jewels that have 2 notables that are of interest and third is useless? Or just one is needed and the other can be anything? As it is now, you are still able to filter with the required notables, but you must chose to select yourself. Automatic selection of explicit modifiers is tricky as some modifiers are wanted and some are not, and these things vary from build to build, from league to league, and from type of the league to another (what is wanted in HC might not be as desireble in SC).

In my opinion, we should leave the search of cluster jewels as-is. Of course the decision lies in the hands of @SnosMe. But I just wanted to share my pov on the issue.

**Comment by verydarkmagic** [comment]
@tamaroth 
_2 notables that are of interest and third is useless_ - that is a **buyer specific** problem. Other builds might make use of the third notable. I hear what you are saying but I don't think this is relevant. Some jewels are more expensive than others because of different combination of passives. Those jewels will naturally be more expensive.

From a sellers perspective we don't really care about any of that. We care to get the market price - as fast and as accurate as possible.
Right now, the script will underprice any well-rolled cluster jewel **by default**.

**Comment by SnosMe** [comment]
> We care to get the market price - as fast

throw it in tab with fixed price, getting spammed? then manually reprice. Rotate tab prices at end of session

> and as accurate as possible

then do it by reviewing stats that synergizes and tick them.

Basically what you're doing rn is ticking stats in dumb way, sometimes overpricing item, sometimes never selling it, therefore wasted time on manually prechecking it in wrong way.
