### ISSUE TITLE
price check not working

### ISSUE THREAD

**Issue by Mackes-sys** [SnosMe/awakened-poe-trade#327]
Hello, 

i have the issue that the price check is not working. Other Hotkeys like the Overlay or Chat Makros are working fine. The Log file shows this warning:

{"source":"clipboard","timeout":500,"level":"warn","message":"No changes found"}

any idea?

Thanks and greetings

**Comment by SnosMe** [comment]
https://snosme.github.io/awakened-poe-trade/issues

Hope your client is in English and try restarting app with admin rights.
