### ISSUE TITLE
Does not work will with tiling window managers

### ISSUE THREAD

**Issue by Xandaros** [SnosMe/awakened-poe-trade#328]
If you are using a tiling Window manager, there are many issues:
- If the game is in full screen mode, all you get is a black screen
- If the game is in windowed mode and the WM considered it tiled (default), things get really weird. I get a mostly black screen, with a large white square in the top-left.
- If the game is in windowed mode and the WM considered it floating, the game is playable as normal and shortcuts like F5 do work. Ctrl-D does absolutely nothing visible. Ctrl-Alt-D does open up the price window, but it covers the entire screen and only parts of it belong to the actual window. ([Screenshot](http://tcp.st/e8ong.png))

Funnily enough, I can confirm that Ctrl-D does indeed work, by moving the trade window away from the game window and then pressing it. The window is hidden behind the game, but it does update ([Screenshot](http://tcp.st/z7pzy.png))

I don't know how the window handling is normally done here, but I can tell that the trade window updates its position and size to match that of poe. As mentioned previously, if the game is in full screen or tiling mode, the trade window seems to be in front of the actual game, making it unplayable.
What is actually meant to happen? Is it supposed to stay in the background and move itself to the front when needed? Is it meant to be in front, but transparent, passing input through to the game?

I can investigate some more once I know what it is actually meant to be doing.
For the time being, you are at least aware of the problem.

**Comment by SnosMe** [comment]
Hi, app window is supposed to be the same size as game and not clickable until overlay is active. App window has attribute of dialog window, it should always be on top of game window but not on top of all windows.
I never used tiling WM and don't know how it is compatible with regular.

More correct place for this issue is https://github.com/SnosMe/electron-overlay-window that app uses (library uses standard X11 events).

**Comment by Xandaros** [comment]
No, this is the correct place to report it.
I'm using your app and your app has a bug, so I'm reporting it here.

If the problem is actually upstream, you'll have to report it to them, since you are the one using their library. I'm not, I don't know anything about how it works and how it is used - I'd be the absolutely wrong person to report it.

That aside, many tiling window managers don't support dialogue windows - the active window is always on top, unless a window has always on top set. Maybe add a config option to force always on top?

Also, the majority of the window is probably meant to be transparent, but it is not. I saw [this ussue](https://github.com/SnosMe/electron-overlay-window/issues/9) on that linked library with the same problem, is hardware acceleration disabled for awakened poe trade, too?

**Comment by SnosMe** [comment]
Yes, it's off by default.

**Comment by weidtn** [comment]
What tiling manager do you use? The first problem with the black screen was reported multiple times but nobody in here seems to care. 
In Xmonad it works for me when game is set to "windowed" in the "Fullscreen" layout in Xmonad.

**Comment by Xandaros** [comment]
I use i3.
Like I mentioned, when I set the game to floating mode, it works fine, just not when it is set to tiling.

Well... except that the normal Ctrl-D overlay doesn't work at all. Ctrl-Shift-D does work... somewhat. It essentially goes full-screen, with the background being a mess. If I show a smaller window later, you can see the old window behind it. It can be a bit confusing, but it is usable.
