### ISSUE TITLE
Feature Request: Allow Maven's Invitations to be "Map-Checked"

### ISSUE THREAD

**Issue by freakpants** [SnosMe/awakened-poe-trade#330]
Maven's Invitations can be rolled like regular maps.
Replacing https://github.com/SnosMe/awakened-poe-trade/blob/2ba515974ca6387a7a985e14c8eb041521844aac/src/web/map-check/WidgetMapCheck.vue#L57 with  
```jsx 
if( true ) 
``` 
already results in this working:
![image](https://user-images.githubusercontent.com/12885929/108088761-1fb15080-7079-11eb-980f-23292061bf5e.png)

Obviously that's not a real implementation, as the parser needs to be expanded to detect those invitations and give them a basetype the widget can then check for as well as Map. I looked into creating the constants/basetypes, but I'm not quite sure which code is responsible for generating base_types.json (as RePoe has the files in slightly different format)

**Comment by SnosMe** [comment]
Completed as part of #241 
https://github.com/SnosMe/awakened-poe-trade/issues/241#issuecomment-782353073

---

I used RePoE before, but yeah it's automated via closed source scripts.
