### ISSUE TITLE
Readme should have basic 'how to use'. At least the default keybindings

### ISSUE THREAD

**Issue by Sweater-Baron** [SnosMe/awakened-poe-trade#331]
I installed this and ended up having to google how to use it.

It'd be nice if the readme at least had basic instructions like "here's how to open the settings page and view your keybindings"

**Comment by SnosMe** [comment]
I expect that downloads are made from website that has "Quick Start" in sidebar https://snosme.github.io/awakened-poe-trade/quick-start
