### ISSUE TITLE
Request: A toggle switch to always do a more detailed price check on unique items.

### ISSUE THREAD

**Issue by flapanther33781** [SnosMe/awakened-poe-trade#334]
First, let me say I really love this tool, it's DEFINITELY helped me this league!  Please keep supporting it!

That said, I do have one request: a toggle switch to always do a more detailed price check on **unique** items.

There are a few uniques that can have variable mods (like Watcher's Eye) - and I see the tool recognizes those - but for most unique items this is not the case.  I have my search set up to allow for 10% difference in values, but I still have to check the checkboxes for all unique items.  This is important because some unique items can be very valuable if it has one of the mods perfectly rolled, or almost perfectly rolled, so having the tool auto-check the checkboxes when searching would save me a lot of time.

I understand why you don't have the tool automatically check all the boxes for rare items.  (First, you don't know which ones the user will consider valuable, so if you check all of them the user will then have to uncheck some - there is no perfect solution there.  Second, since rare items can have any mix of mods a user may want to try more than one search to find good matches to compare their item with.)  But because this is not the case with the unique items it would be nice to have a little toggle switch that tells the tool to always do the more detailed search with all those boxes checked for unique items.

**Comment by SnosMe** [comment]
I'm enabling auto-selection on Uniques with < 4 stat filters. See also #727
