### ISSUE TITLE
Problem while I try price check and map info

### ISSUE THREAD

**Issue by danthespal** [SnosMe/awakened-poe-trade#339]
While I try to check a price for an item or map check, the app put the game in background mode and do nothing, until yerstarday it was working without any changes or update.

Now I compile 2.10.0 version, delete the old stuff from AppData\Roaming\awakened-poe-trade\, and same thing, still while I try to check a price it close the game to background mode and do nothing.

**Comment by SnosMe** [comment]
https://snosme.github.io/awakened-poe-trade/issues

![image](https://user-images.githubusercontent.com/4292308/111121115-ec2ced80-8574-11eb-967f-a67cc9997831.png)
