### ISSUE TITLE
No Portabl Version?

### ISSUE THREAD

**Issue by Nyab59** [SnosMe/awakened-poe-trade#34]
I'd like to try this. But there are many alternative tools.
I would appreciate if you could release with a portable zip file so that I can easily try this out.

**Comment by SnosMe** [comment]
Thank you for your interest. I also wanted this, so the portable version is available now.

**Comment by Nyab59** [comment]
Thank you very much for the quick response and implementation !
I'll try this now.
The goal of this tool is great.　I'm rooting for you.
