### ISSUE TITLE
Please add a way to disable the overlay.

### ISSUE THREAD

**Issue by jabberjabber** [SnosMe/awakened-poe-trade#340]
I never want to use the overlay and it is pretty annoying when it pops up. Every other option has a way to disable or "not set" a hotkey, please make it the same for the overlay.

https://i.imgur.com/amt9LY6.png

**Comment by SnosMe** [comment]
This is an important key, and it's easy to rebind to any unused key like Ctrl+9, like you did on screenshot. This key also sometimes  helps to fix visual bugs, so it's more than just overlay hotkey. You have 282+ available keyboard combinations and I don't see how consuming one of it can badly affect your experience.
