### ISSUE TITLE
JavaScript error: wmZorder is undefined

### ISSUE THREAD

**Issue by wisnia74** [SnosMe/awakened-poe-trade#341]
Hi man,

First of all, thanks for this tool - it's really awesome.

Today I cloned you repo, set up the project locally and was going through the code just out of curiosity. What I did was:

- `yarn install`
- `npm run serve` in one terminal
- `npm run electron:serve` in another terminal

Then I proceeded to just look at some of the requests made to poeprices.info - again, out of curiosity.

When I finished and closed both servers I wanted to run regular installation of APT I have installed and I got this error:
![Przechwytywanie](https://user-images.githubusercontent.com/41591175/111913283-bfde0900-8a6d-11eb-982b-f0fdab9d7efc.PNG)

I killed all APT processes I had in task manager, tried again - same result.
I uninstalled APT, restarted my PC, installed it again - same result.

Any idea what might be causing `wmZorder` to be `undefined` here?

**Comment by wisnia74** [comment]
Nevermind, I just now got to https://snosme.github.io/awakened-poe-trade/issues - deleting `%appdata%` stuff and reinstalling worked. I thought I might've messed something up with having:
- existing installation of APT on my PC
- cloning and building a project locally simultaneously

**Comment by SnosMe** [comment]
Yep, current code in repository modifies config that stored in %appdata%, therefore installed stable version can't run with newer config.
