### ISSUE TITLE
Feature request: Add option ot always open on browser on hotkey

### ISSUE THREAD

**Issue by binarydepth** [SnosMe/awakened-poe-trade#344]
There is concern about getting banned while using third-party tools with Path of Exile so I propose that we can configure to search by default of a browser window like Firefox or Chrome, also maybe allow custom commands in case there are incompatibilities with Linux and default settings on the Desktop Environments

**Comment by JajinderK** [comment]
+1. I'd rather see the "trade" button open the webpage.

**Comment by SnosMe** [comment]
duplicate of #116
