### ISSUE TITLE
CTRL+D (Pricecheck) not working?

### ISSUE THREAD

**Issue by Slayer418** [SnosMe/awakened-poe-trade#345]
Nothing happens when I try to use the pricecheck function now, no idea why. Up-to-date.

**Comment by ShanKanis** [comment]
Same issue, using latest version, worked fine few days ago iirc.

**Comment by markorm** [comment]
Can confirm. Must be related to the Ultimatum patch as PoE Overlay Community also doesn't work, that client returns the error "failed to parse item".

Win10 19043.928.

**Comment by shakesx** [comment]
Experiencing this as well since Ultimatum launch.

**Comment by scottmudge** [comment]
Confirming.

**Comment by Kritikally-Akklaimed** [comment]
Confirming as well

**Comment by apratimdas** [comment]
+1 Is this fixed yet for anyone else?

**Comment by jagotronic** [comment]
Same issue here. Have this message in the logs.
`{"source":"clipboard","timeout":500,"level":"warn","message":"No changes found"}`
Maybe poetrade external api not activated yet.

**Comment by theanonym** [comment]
ctrl+c output changed
https://www.pathofexile.com/forum/view-thread/3079973
> Copying an item's description with Ctrl + C now also copies the Item Class.

**Comment by LeonLiuY** [comment]
Looks like [this function](https://github.com/SnosMe/awakened-poe-trade/blob/master/src/parser/Parser.ts#L52) needs an update.

**Comment by SnosMe** [comment]
v2.10.0 was released
