### ISSUE TITLE
Not recognized modifier inside { brackets }

### ISSUE THREAD

**Issue by kabytos** [SnosMe/awakened-poe-trade#346]
How i can fix error with price check? All mods has error and says Not recognized modifier

**Comment by vladyslav-androshchuk** [comment]
Same here:
![image](https://user-images.githubusercontent.com/77970522/115113543-92647c80-9f93-11eb-9913-04414c4ec6d3.png)

**Comment by SnosMe** [comment]
As was written in app changelog change Alt in your hotkeys to Ctrl, to temporarily fix this issue. This is because poe now allows to copy advanced mod info text (more info in 3.14 patch notes on poe website), but app doesn't support it yet.

**Comment by Ketec** [comment]
Switched from ALT D to CRTL D and it made no difference.

**Comment by SnosMe** [comment]
Fixed in v2.10.1

`Alt` key is working again

**Comment by Yomamasz** [comment]
How do i fixed it really.... it doesnt work with your tips

**Comment by Yomamasz** [comment]
> Fixed in v2.10.1
> 
> `Alt` key is working again

HELP

**Comment by Yomamasz** [comment]
ver.2.10.5, please help

**Comment by SnosMe** [comment]
You should have `Alt` key here, it's the only requirement now. @Yomamasz 

![](https://media.discordapp.net/attachments/666709160380858381/833616368950706176/unknown.png)
