### ISSUE TITLE
Can't price check anything, ctrl + D not working  :(

### ISSUE THREAD

**Issue by Herrm2291** [SnosMe/awakened-poe-trade#347]
Can't price check anything, ctrl + D not working  :(

**Comment by Explaiz** [comment]
same

**Comment by Pascal-Kp** [comment]
Seems to be fixed in 2.10.0

**Comment by HiPoEGH** [comment]
Still have issues with 2.10, wasn't an issue before.
I think PoE is assigning the hotkey itself, which makes no sense, or I have another program taking it up.

**Comment by Herrm2291** [comment]
Working with the 2.10 patch, thank you @Pascal-Kp!
