### ISSUE TITLE
Error: Uncaught error

### ISSUE THREAD

**Issue by MorkaZ** [SnosMe/awakened-poe-trade#348]
![image](https://user-images.githubusercontent.com/4214815/115114507-161c6a00-9f90-11eb-925a-a21506601939.png)

**Comment by sopsop** [comment]
+1

**Comment by NitriusX** [comment]
Same problem here as well.

**Comment by SnosMe** [comment]
Report to poe prices forum thread http://www.pathofexile.com/forum/view-thread/1216141
