### ISSUE TITLE
2.10 Fail To Get Price Prediction?

### ISSUE THREAD

**Issue by potasium56** [SnosMe/awakened-poe-trade#349]
I just updated to the latest release and when i use ctrl + d on an item it days "Failed To Get Price Prediction?" tried multiple items worried this might be a bug or issue? just wanted to let the developer know of this.

**Comment by dillecd** [comment]
I am also experiencing this issue after upgrading to 2.10 earlier today.

**Comment by SnosMe** [comment]
Report to poeprices forum thread http://www.pathofexile.com/forum/view-thread/1216141
