### ISSUE TITLE
Warlord Item issue

### ISSUE THREAD

**Issue by NeroMorto** [SnosMe/awakened-poe-trade#35]
Hello!
I found an item that the macro does not work with (popup does not appear)

```
Rarity: Rare
Mind Clutches
Antique Gauntlets
--------
Quality: +15% (augmented)
Armour: 224 (augmented)
--------
Requirements:
Level: 59
Str: 58
--------
Sockets: R-R R R 
--------
Item Level: 86
--------
+44 to Dexterity
59% increased Armour
+12% to Lightning Resistance
30% increased Projectile Attack Damage
--------
Warlord Item
```

I can share it, if it is will be nessesary

**Comment by SnosMe** [comment]
Sorry, but I can't reproduce this. Make sure you are using the latest version and it is not related to #2 issue

**Comment by NeroMorto** [comment]
Now i can't reproduce it too. It was strange, when all items worked fine instead of this one. Ok, sorry for this)
