### ISSUE TITLE
Installer v2.10.1 does not open. No errors, no warnings

### ISSUE THREAD

**Issue by edufranzoni** [SnosMe/awakened-poe-trade#352]
I tried all the steps of the common problems.
uninstalled, removed the directory and nothing works.

I also disabled windows defender and avast antivirus and nothing.

OS: Windows 10

**Comment by SnosMe** [comment]
1. Installer hasn't changed from previous versions
2. Because installer is not developed by me try to google something like "NSIS installer not opening"
Maybe use portable version?
