### ISSUE TITLE
Hacvng issues, no stats, not recognized mod

### ISSUE THREAD

**Issue by Gazuntight** [SnosMe/awakened-poe-trade#353]
![No stats](https://user-images.githubusercontent.com/82783895/115163606-fceee880-a077-11eb-8f86-f35ad5823436.png)
![NOT rec](https://user-images.githubusercontent.com/82783895/115163608-fe201580-a077-11eb-9c88-009a497c47c7.png)

**Comment by superness** [comment]
Same no item stats are detected for the search

**Comment by SnosMe** [comment]
Duplicate of #351

This should be fixed if you update **PoE client** and app to v2.10.1

**Comment by Gazuntight** [comment]
Thanks for the reply, I am currently using updated versions of both, I have reinstalled both POE and trade macro, I am still having NOT RECOGNIZED MODS pop up. No idea why.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
