### ISSUE TITLE
Ignore base and tier on elder guardian maps

### ISSUE THREAD

**Issue by shk0307** [SnosMe/awakened-poe-trade#356]
When price checking for elder guardian maps, it fixes base map and its tier.

Most of the time the value of an elder map come comes form the fact that it's an elder guardian map, not because of it's tier and (especially) base type.

Currently, to price check elder maps, I have to manually go to the poe website and remove the base map.

**Comment by shk0307** [comment]
I just realized, but it would be nice if similar treatment was done to blighted maps; but unlike elder guardian, tier of the map needs to be taken into account for blighted maps.

**Comment by SnosMe** [comment]
Should be good now v2.10.2. Map tier is not toggleable yet though.
