### ISSUE TITLE
Shutdown with AMD Adrenalin 21.4.1

### ISSUE THREAD

**Issue by pzycho** [SnosMe/awakened-poe-trade#358]
System will Shutdown/Restart with the newest AMD Adrenalin software if using the Hotkey "ALT+D" ingame for Pricecheck. 
Disabled all Hotkeys in Adrena SW, and can reproduce this everytime. tested withoud AwaTrade, Game runs smooth for hours of Playing, started AwaTrade, restart of System after checking Items in Stash...

IDK why this happens, anything is killing the System with the overlay...

Hoping for a Fix, cause i Love AwaTrade...

**Comment by SnosMe** [comment]
Can't test and fix without buying AMD gpu I guess.
