### ISSUE TITLE
Вопрос совместимости

### ISSUE THREAD

**Issue by Steefff1** [SnosMe/awakened-poe-trade#359]
Могу ли я как то использовать данное приложение при игре в PoE через облачный сервис Geforce now?

**Comment by SnosMe** [comment]
Нельзя, на странице загрузки это написано как и причина почему нельзя

https://snosme.github.io/awakened-poe-trade/download

**Comment by Vorojbit** [comment]
https://github.com/SnosMe/awakened-poe-trade/issues/170#issue-653111484
https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/1140#issuecomment-622392182
