### ISSUE TITLE
Update is downloaded but not installed, if application was installed for all users (in Program Files) on Windows

### ISSUE THREAD

**Issue by SnosMe** [SnosMe/awakened-poe-trade#36]
**If the app was installed for all users (to C:/Program Files/...)** the UAC dialog launches, asking for permission (as expected), the app is uninstalled (as expected), but then it is not installed again (totally unexpected). No errors, no warning, no nothing.

**Comment by SnosMe** [comment]
Waiting for upstream fix https://github.com/electron-userland/electron-builder/issues/4474

**Comment by ShizuneHakamichi** [comment]
**Run as Admin.** IF you do not do this, updates will not apply, as they require elevated UAC (user account control.)

**Comment by kevindevm** [comment]
@SnosMe can you add a checkbox to not auto update?

**Comment by SnosMe** [comment]
#184

**Comment by rf232** [comment]
Upstream issue is closed due to staleness, perhaps they aren't interested in fixing it?

**Comment by pattonjh** [comment]
I am still having this issue. The relevant issue on Electron is marked as solved as of Dec 2021. See: https://github.com/electron-userland/electron-builder/pull/6450
