### ISSUE TITLE
Price checker bugged

### ISSUE THREAD

**Issue by spacedalien** [SnosMe/awakened-poe-trade#360]
it's reading thousands of exalts for every item

**Comment by Igneaalis** [comment]
![изображение](https://user-images.githubusercontent.com/7469854/115713919-99baca00-a387-11eb-9c91-8b4eca269eb5.png)
True

**Comment by BelovedTomboyishGirl** [comment]
![image](https://user-images.githubusercontent.com/43587824/115790294-ca6e2400-a3c6-11eb-96ab-2c4e352112fa.png)
Yes, i am so fucking rich !

**Comment by SnosMe** [comment]
This is because everything depends on chaos-exalted exchange https://poe.ninja/challenge/currency/exalted-orb
And there some "people" trying to fool it.
Developer of poe.ninja knows about this and will fix asap.
