### ISSUE TITLE
Awakened PoE unable to check item stats properly.

### ISSUE THREAD

**Issue by Thats-Karma** [SnosMe/awakened-poe-trade#361]
![Awakened Bug](https://user-images.githubusercontent.com/83015698/115715749-13c66100-a33e-11eb-8712-6664495bb54c.jpg)

Whenever I try to check item stats I get this type of error. A lot of times it doesn't show any info at all. I usually can't check box any mods except for a few on Weapons. All other items get the not recognized mod error.

I'm running APT v2.10.1 and the game is running in Windowed Fullscreen mode.

**Comment by SnosMe** [comment]
You need to change key as shown in https://github.com/SnosMe/awakened-poe-trade/issues/351#issuecomment-822038701

Duplicate of #351
