### ISSUE TITLE
Electron message when opening with command window

### ISSUE THREAD

**Issue by djodars89** [SnosMe/awakened-poe-trade#362]
Hi,

I've made a .bat to open all my addons and Path of Exile at the same time.

When opening Awakened PoE Trade with the command window, this message keeps the window opened (and if I manually close the window, it also closes Awakened PoE Trade):
(node:15852) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information

Thank you,

**Comment by SnosMe** [comment]
This message has nothing to do with keeping app in the background.

You need to pass flag.

```bat
start /B "" "Awakened PoE Trade.lnk"
```

```
B           Start application without creating a new window. The
                application has ^C handling ignored. Unless the application
                enables ^C processing, ^Break is the only way to interrupt
                the application.
```

**Comment by adamk33n3r** [comment]
This does not work. Something must have changed at some point. After running with the /B flag it still prints stuff to the console and if I close the prompt it closes the app.
