### ISSUE TITLE
Radeon video driver's crash 

### ISSUE THREAD

**Issue by Inquisitorr** [SnosMe/awakened-poe-trade#365]
Hello! I have a problem with new Radeon video draiver(21.4.1).
When I check price for items, driver is crashed.
API - Vulkan
[screenshot](https://cdn.discordapp.com/attachments/425395732497825803/835766511846293544/3aa28e6494b5fd42.png)

**Comment by UncleCerec** [comment]
I am having the exact same issue with 21.4.1 driver. Also using Vulkan

**Comment by SnosMe** [comment]
From Discord

![image](https://user-images.githubusercontent.com/4292308/115996318-768e5580-a5e7-11eb-9ba1-dd1b5f04f611.png)

So if I'm understanding it correctly it only happens on Vulkan in Windowed Fullscreen.
PoE previously had issues with this setup, so maybe code in game client depends on something that were changed with recent AMD driver update and PoE has to adopt to this changes or send bug report to AMD.

I can only advice to downgrade GPU driver, maybe find another way to crash PoE and then create bug report on PoE forum.

**Comment by hiveliberty** [comment]
Same issue for me on 21.4.1 AMD driver (not tested on previous version)
But, if i enable the hw acceleration in Awakened PoE Trade options, then the crashes stop
By default Awakened PoE Trade rendering GUI on CPU. I dont think that is GPU driver issue. But i submit crash report to AMD too.

**Comment by hiveliberty** [comment]
New details:
I tested previous driver version, 21.3.2, and issue is gone. Its driver related issue. Anyone who facing this issue should submit bug report to AMD through his form when the driver crashes.

**Comment by Wiktorl4z** [comment]
Same crash here :(
I will try your solution @hiveliberty.

**Comment by MarcelHofherr** [comment]
For me enabling Hardware Acceleration in Debug Settings fixed the issue with the Crashes:

System:
Ryzen 2700X 
16GB DDR4 3200C14
RX 6700XT Reference
Asus Strix X470-F Gaming

**Comment by dafillio** [comment]
> For me enabling Hardware Acceleration in Debug Settings fixed the issue with the Crashes:
> 
> System:
> Ryzen 2700X
> 16GB DDR4 3200C14
> RX 6700XT Reference
> Asus Strix X470-F Gaming
> Driver 21.4.1

Can confirm that enabling hardware acceleration fixed the issue for me, I was only getting a delay in the price checking window popup when on windowed fullscreen but now it doesn't seem to happen anymore. Was an issue for both vulkan and dx11.

**Comment by gimpfenlord** [comment]
can confirm. updated to latest driver yesterday and now it crashes when i try to pricecheck an item

**Comment by SnosMe** [comment]
AMD fixed it in 21.5.1

![image](https://user-images.githubusercontent.com/4292308/117535014-82711300-affc-11eb-9c47-a865d70da90a.png)

**Comment by noraj** [comment]
Radeon 21.5.1 + PoE Awakened v2.10.5 still crashing my drivers. I'll try enabling hardware acceleration as suggested in https://github.com/SnosMe/awakened-poe-trade/issues/384#issuecomment-835423707 but I have low hopes.

**Comment by SnosMe** [comment]
Current 3 workarounds: 
- enable hw acceleration

![image](https://user-images.githubusercontent.com/4292308/119261554-901fbe80-bbe0-11eb-96cf-6bdbeb747110.png)

- rollback AMD driver to 21.3.2

https://www.amd.com/en/support/kb/release-notes/rn-rad-win-21-3-2

- play in Windowed mode

**Comment by noraj** [comment]
HW acceleration seems to work work. I had no crash since I activated it.

**Comment by Andbax** [comment]
Keep crashing RX 570 driver 21.5.2 >> HW acc active >> Windowed mode

**Comment by hiveliberty** [comment]
Has anyone tested driver 21.6.1?

As far as I remember, I tested 21.5.* and sometimes crashes happens even with enabled HW acceleration.

**Comment by Inquisitorr** [comment]
> Has anyone tested driver 21.6.1?
> 
> As far as I remember, I tested 21.5.* and sometimes crashes happens even with enabled HW acceleration.

I tested driver 21.6.1. I cheked a lot of items with disabled HW and the issue didn't repeat.
awakened-poe-trade version  2.10.0

**Comment by hiveliberty** [comment]
> 
> 
> > Has anyone tested driver 21.6.1?
> > As far as I remember, I tested 21.5.* and sometimes crashes happens even with enabled HW acceleration.
> 
> I tested driver 21.6.1. I cheked a lot of items with disabled HW and the issue didn't repeat.
> awakened-poe-trade version 2.10.0

Yeah, I checked too
I can confirm that issue is gone with driver 21.6.1
