### ISSUE TITLE
Feature Request: Seperate +- sliders for items

### ISSUE THREAD

**Issue by sclient** [SnosMe/awakened-poe-trade#367]
I like to use tools like this at times to search for upgrades to my gear, and unfortunately if I increase the combined +- slider, it, of course, also shows me incrementally worse gear as well as better stuff. It would be really nice if this single slider was separated into a + and a - slider.

**Comment by SnosMe** [comment]
Not sure what you mean. Can you price check item and show one screenshot of how it does now and another how you want to min max value be.

**Comment by sclient** [comment]
This is the implementation in another tool.. Instead of the one +- slider, you have one for + and one for -..

![Item slider](https://user-images.githubusercontent.com/32541/116842526-aca47a00-ab91-11eb-838f-f925e1ab8174.jpg)

**Comment by SnosMe** [comment]
I don't see any benefit in this, stats are better only in one way, so you want another bound to be open, limiting another bound will only show less items with higher prices.

Also, min/max for some stats have inverted meaning.

**Comment by sclient** [comment]
This is how you can find upgrades to your gear, yes some stats have no or negative benefits, therefore you uncheck those when you do the search.

**Comment by SnosMe** [comment]
And still I don't get it, what is missing according to your screenshot?

![image](https://user-images.githubusercontent.com/4292308/117016511-7551dc80-acfb-11eb-854b-38974715e008.png)

**Comment by sclient** [comment]
Ok, I didnt understand that this would not set the max roll as well. Sorry for the misunderstanding!
