### ISSUE TITLE
Feature Request: Option to stop auto search when bulk price checking ?

### ISSUE THREAD

**Issue by Bass2Gamer** [SnosMe/awakened-poe-trade#369]
So I would really like an option to stop auto search when price checking scarabs, essences etc. so you can first set the bulk without spamming trade request to the server.

Because when you want to price check and set the bulk you already have 2 trade searches and with scarabs you have an extra trade search so after 3 or 4 full price checks you reach the "10 searches within 97s" and you cant continue price checking.

Solutions i could think of would be either a option to stop auto seraches completely or a shortcut for bulk price checking.

**Comment by Frunace** [comment]
Second this! Don't understand why it searches immediately, it just adds a lot of spam to the trade site that is entirely pointless. 
Would be much better to have to press the search button first, especially when keeping in mind that GGG WANT us to reduce spam.
Pricing a full essence tab takes literally hours using this tool, it's faster to search manually on the trade site which sort of defeats the entire purpose of using awakened poe trade in the first place.

Adding on the reduce spam part, maybe there could be an option to save recent searches locally for ~2 minutes. 
For example in case you check tier 1 essence, tier 2 essence, and go back to tier 1 essence.
There's a lot of that when comparing whether you should combine them or not. Could reduce the amount of load on the trade servers and make this tool run easily 2-3 times faster when doing a lot of checks like this.

**Comment by SnosMe** [comment]
@Frunace tool already saves results as you've described for 5 minutes.
