### ISSUE TITLE
Unintended interaction with LiveSplit

### ISSUE THREAD

**Issue by noxora** [SnosMe/awakened-poe-trade#370]
When using awakened poe trade, I set bound "/exit" to my backtick key, making a logout macro. With livesplit open and global hotkeys turned on, I logged out by pressing backtick and found that it stopped my timer. Pressing the button again restarted my timer. 

Steps to reproduce:
bind "/exit" to the back tick key
Start a livesplit timer with global hotkeys enabled
log in and then press the back tick key repeatedly

This doesn't happen when I use the Lutbot AHK script either in their logout macro section, or their text input section to send "/exit"

**Comment by SnosMe** [comment]
The actual sequence is

F9 - hotkey in settings

Enter - open chat
Ctrl + V - paste /exit
Enter - send command

Enter - open chat
ArrowUp - restore previous message
ArrowUp - restore previous message
Escape - close chat
---

So I think you are using ArrowUp key in LiveSplit and should rebind it

**Comment by noxora** [comment]
You're correct! Thank you
