### ISSUE TITLE
Uncaught Exception occured

### ISSUE THREAD

**Issue by FloxelGaming** [SnosMe/awakened-poe-trade#373]
PoE Trade crashed with this Message:
Uncaught Exception:
Error: net::ERR_HTTP2_PROTOCOL_ERROR
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6497)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)

Hopefully i did no typo in that :D.
Only happend once yet but i thought an uncaught Exception should be mentioned.

best regards Floxel

**Comment by SnosMe** [comment]
Why would retype it instead of taking screenshot? 😄 

As for error it's something on your end, maybe proxy with redirects?
