### ISSUE TITLE
Price check dont working.

### ISSUE THREAD

**Issue by RebKut** [SnosMe/awakened-poe-trade#375]
Price check dont working =(
Logs with debug, https://pastebin.com/Hkk2045m

**Comment by SnosMe** [comment]
`{"source":"clipboard","timeout":500,"level":"warn","message":"No changes found"}`

says can't find item, only 2 situations possible: client language is not english/russian, OR game running with admins rights but app not, restart app with admin rights too.

**Comment by RebKut** [comment]
The problem is not in the rights, the video showed the launch in both cases https://youtu.be/_M4dTtFvQAA. After your words, i try run client in English. It works, so now there is a problem with a Russian client = (

**Comment by SnosMe** [comment]
Glad you found it 

![image](https://user-images.githubusercontent.com/4292308/116819058-03508a80-ab77-11eb-91d9-c642c00e6a61.png)
