### ISSUE TITLE
Base item for every non-unique item?

### ISSUE THREAD

**Issue by carloverso** [SnosMe/awakened-poe-trade#377]
Currently, you can click base-item for influenced bases (but some-why not elder/shaper). But most of the rares/magics in the game are worthless. Would it be possible to make base-item button available for everything? Or perhaps make a default selection of item+iLvl+influence, instead of affixes.

Example of 99% of my usage: https://puu.sh/HDLyq/4999cc83e0.mp4

**Comment by SnosMe** [comment]
Next release will include "Base item" preset.
Let me know what you think about it after release.

![image](https://user-images.githubusercontent.com/4292308/155146251-88573a03-05f1-4b4d-b157-e2981ee7c491.png)

**Comment by carloverso** [comment]
@SnosMe It works great, I have noticed it after the update. Solved many problems. Thank you.
