### ISSUE TITLE
Autofill MAX value on Price check form

### ISSUE THREAD

**Issue by smismismismi** [SnosMe/awakened-poe-trade#379]
Would it be possible to add an option to auto fill MAX field on Price check form?

It does get filled if you click on it but it would save a lot of time if it was already prefilled.

**Comment by SnosMe** [comment]
So you will be ticking stats by clearing one of the min/max bounds?

**Comment by smismismismi** [comment]
Sorry, I wasn't aware that clicking on MAX field also ticks the stat checkbox. I was usually clicking on the checkbox itself or maybe name of the stat and only after that clicked on MAX field. 
Current behaviour is good enough for me although it will require a bit of training of my muscle memory (Which was influenced by TradeMacro as you've guessed).

From my perspective I don't see the point of the search without upper bound set and I would like it to be prefilled but current behaviour also works just fine. 

Thank you.
