### ISSUE TITLE
Program cant search unique synthesis items.

### ISSUE THREAD

**Issue by itsC0mrade** [SnosMe/awakened-poe-trade#38]
Item issue resolved with update 0.10
Is it possible to search in future for unique affixes without items base?
https://i.imgur.com/Y3L1v8a.png

**Comment by SnosMe** [comment]
You are right, Synthesized items are handled correctly, starting from v0.10.0

> search for unique affixes without items base

What is the point of searching for unique items not by name but by category (eg: any Unique Ring, according to your screenshot)?
Correct me if this is not what you mean.

**Comment by itsC0mrade** [comment]
There may be things like synthesis that cannot be found because of their base, but all affixes are already entered. On the other hand there is a built-in browser, but still.
Btw on the ring should not be "enchantment" with this affix(last in search), too, can not find a thing.

**Comment by SnosMe** [comment]
> Btw on the ring should not be "enchantment" with this affix

It seems you keep talking about the version before v0.10.0.

![image](https://user-images.githubusercontent.com/4292308/75781045-2a3de180-5d65-11ea-8202-d4aa502a5b9e.png)

**Comment by SnosMe** [comment]
> There may be things like synthesis that cannot be found because of their base

What do you mean. Item cannot be found only if you have selected all the specific "Syntesysis" mods that no one has listed on the trade site.

![image](https://user-images.githubusercontent.com/4292308/75784002-2bbdd880-5d6a-11ea-8ef3-42bc1963300d.png)

> Btw on the ring should not be "enchantment" with this affix(last in search), too, can not find a thing.

Verified, I will investigate.

**Comment by SnosMe** [comment]
v0.11.0
```
fix: If there is ambiguity between enchant and explicit stat, then the correct one is selected
```
