### ISSUE TITLE
On the function alt+d there is an issue

### ISSUE THREAD

**Issue by Reinicke** [SnosMe/awakened-poe-trade#380]
When im pricechecking items, the pricecheck shows price but under mods there is note that "Not recognized modifier" and i cant fully check it. Anyone knows how to fix it?

**Comment by foca1234** [comment]
as funções F5 ou shift+espaço funcionam mas para pesquisa de preços não esta funcionando

**Comment by SnosMe** [comment]
If you have one "Not recognized modifier" send Ctrl+C of this item here.

If you have a lot of "Not recognized modifier" then 
check that here's `Alt` and not `Control`.

![](https://media.discordapp.net/attachments/666709160380858381/833616368950706176/unknown.png)
If you want to keep using `Control` you can +1 bug report https://www.pathofexile.com/forum/view-thread/3085532

**Comment by Reinicke** [comment]
On all my items i have "Not recognized modifier", 
i have there alt and i have latest app version
whats next? :P

**Comment by SnosMe** [comment]
![image](https://user-images.githubusercontent.com/4292308/117297487-f4bbe900-ae7e-11eb-8fe7-123a42a05bef.png)

Send logs
