### ISSUE TITLE
Price checking with advanced mod descriptions

### ISSUE THREAD

**Issue by Gnomiro** [SnosMe/awakened-poe-trade#382]
I have an unusual keyboard setup where the advanced mod descriptions are shown when pressing control. Since this macro is reliant on the clipboard it in this scenario copies the advanced mod descriptions like this:

```
Item Class: Boots
Rarity: Rare
Honour Spur
Two-Toned Boots
--------
Quality: +20% (augmented)
Armour: 151 (augmented)
Evasion Rating: 151 (augmented)
--------
Requirements:
Level: 70
Str: 155
Dex: 123
--------
Sockets: R-R G-R 
--------
Item Level: 88
--------
{ Implicit Modifier — Elemental, Fire, Cold, Resistance }
+12(8-12)% to Fire and Cold Resistances (implicit)
--------
{ Prefix Modifier "Chosen" (Tier: 1) — Elemental, Cold, Speed, Ailment }
30(25-30)% increased Movement Speed
Cannot be Chilled
{ Prefix Modifier "Athlete's" (Tier: 1) — Life }
+88(80-89) to maximum Life
{ Master Crafted Prefix Modifier "Rin's" — Elemental, Cold, Ailment }
Cannot be Frozen (crafted)
{ Suffix Modifier "of Bameth" (Tier: 1) — Chaos, Resistance }
+35(31-35)% to Chaos Resistance
{ Suffix Modifier "of Tzteosh" (Tier: 1) — Elemental, Fire, Resistance }
+48(46-48)% to Fire Resistance
{ Suffix Modifier "of the Ice" (Tier: 2) — Elemental, Cold, Resistance }
+45(42-45)% to Cold Resistance
```

The advanced notes (all shown in {}-brackets) break the mod detection and everything which makes the makro usefull for fast pricing. As these mods are easily detectable by the brackets, would it be possible to make an update which just ignores everythin in {}-brackets?

EDIT: After checking the PoB github as well there is probably another issue. When the advanced mod descriptions are used (indicated by the {}-bracktes again) the mod value is followed by the value range in ()-brackets.

A workaround would probably to ignore values in ()-brackets if {}-brackest are within the current clipboard.

**Comment by jnordwick** [comment]
Is there any ETA on this? This has gone from my most useful POE software to mostly useless because of this issue. (Or just add a way for me to tell APT what button it should be pushing. (My kbd and mouse are heavily customized so it isn't really possible o change them).
