### ISSUE TITLE
js error

### ISSUE THREAD

**Issue by semagit** [SnosMe/awakened-poe-trade#383]
![BS6P8P1](https://user-images.githubusercontent.com/67645894/117520178-63ed2680-afc0-11eb-98b6-7d14965388c9.png)

**Comment by SnosMe** [comment]
you probably installed old awakened after using newer version, and config file got corrupted, delete it in appdata https://snosme.github.io/awakened-poe-trade/issues

**Comment by semagit** [comment]
thanks!

**Comment by SectsPanther** [comment]
I'm sorry, but this does not help. I do not know how to find or edit your code for your program. I have removed and re-downloaded this app a dozen times. After reinstalling the app, I cannot seem to find the src/main/config.ts file location anywhere. Wouldn't removing the program and reinstalling the program replace the "coinfig.ts" file with an updated one? Please help.

Thank you

**Comment by SnosMe** [comment]
> delete it in appdata

@SectsPanther What's not clear here?

After following link https://snosme.github.io/awakened-poe-trade/issues

you see 

![image](https://user-images.githubusercontent.com/4292308/118112719-0c9aec00-b3ee-11eb-95a1-7ca6e7a858af.png)
