### ISSUE TITLE
JavaScript Error: Cannot read property 'maps' of undefined

### ISSUE THREAD

**Issue by SectsPanther** [SnosMe/awakened-poe-trade#386]
Awakened Poe Trade has been working flawlessly for the the last year and now I cannot seem to load the program properly. Please help. 

Thank you
![Awakened Poe Error](https://user-images.githubusercontent.com/68574830/117904438-3933f400-b286-11eb-8f5b-6501e2e366a4.png)

**Comment by SnosMe** [comment]
Duplicate of #383
