### ISSUE TITLE
auto collapsing listings by account

### ISSUE THREAD

**Issue by PleaseFixThisItHurtssss** [SnosMe/awakened-poe-trade#388]
it auto collapsing listings by account, which hides all ur items in category beside 1. absolutely ruined my trading today. Can u please fix this? Have to manually go to trade each price check and untick that "collapse listings by account" , big waste of time

**Comment by SnosMe** [comment]
This helps to reduce load on GGG api, don't like this then create your API for me 😄

> hides all ur items in category beside 1

Not interested in providing support for people who price fix items either

**Comment by PleaseFixThisItHurtssss** [comment]
Reconsider. It was working perfectly fine. I haven't thought about price fixers, but this HURTS regular people more than fixers, u can just block them and never see scam prices.
What in  reality you did here - shot an arrow in the knee of CRAFTERS. I'm making multiple boots/chests/gloves of same type etc and i can't even price check them correctly now since my other items are simply not showing up. Like legit no point in using awak trade anymore by a portion of users who craft items.
