### ISSUE TITLE
Ctrl+D: window stays open (after having used ctrl+alt+d)

### ISSUE THREAD

**Issue by remcoros** [SnosMe/awakened-poe-trade#39]
When you have first used ctrl+alt+d to open a window (and keep it locked), the next time you use "ctrl+d" the window stays locked.

Probably because "isClickedAfterLock" is never reset to 'false' in: https://github.com/SnosMe/awakened-poe-trade/blob/master/src/main/positioning.ts

Maybe it has to be reset to false when ctrl+d is used.

**Comment by Tallion99** [comment]
Having the same issue too. just using ctl+d but then clicking the open larger search screen.

**Comment by remcoros** [comment]
@SnosMe I was trying from source (I see you just made a release), but for me, it completely broke  ctrl+d now. 

Holding ctrl, while moving to the trade window, hides the windows as soon as the mouse enters the window (still holding ctrl).

After the first try, ctrl+d stops working until completely restarted.

Using ctrl+alt+d now shows the Windows 10 taskbar for some reason (I tried setting altTabToPoe setting to true/false, but didnt have much effect)

I am reading and playing with the source to try and understand what is going on., but I cannot find it yet. (relatively new to electron, and the whole ipc/shortcuts/polling/isWindowLocked or not code is a bit hard to grasp at first sight)

Are you seeing the same? Or is this specific to my machine/setup?

**Comment by SnosMe** [comment]
> Are you seeing the same? 

Of course not, then I would not release. Every problem you stated works well.
Including `"altTabToGame": false` restores the previous taskbar behavior. Also can you clarify why it is not wanted change for you?

> Or is this specific to my machine/setup?

Even so, it would be great to know the reason, so if it happens again with others, the solution will already be known.
