### ISSUE TITLE
Long Cluster Passives are not recognized

### ISSUE THREAD

**Issue by TheReshi** [SnosMe/awakened-poe-trade#392]
If you try to search for Large Clusters with "10% Increased Attack Damage" or "10% Increased Spell Damage", it works fine.

But as for 
![image](https://user-images.githubusercontent.com/14064376/118312716-0c841480-b4f2-11eb-8344-929e68d3af3e.png)
or
![image](https://user-images.githubusercontent.com/14064376/118312667-faa27180-b4f1-11eb-94dd-fbbf9b6318d2.png)
it doesn't.

**Comment by SnosMe** [comment]
Thanks for report, ironically it was broken by introduction of this message about not recognized modifiers.
