### ISSUE TITLE
Add Reward and Input Ultimatums to Related Items

### ISSUE THREAD

**Issue by zocke1r** [SnosMe/awakened-poe-trade#393]
Currently the price check for ultimatums is rather useless as it simply searches for all inscribed ultimatum regardless of its reward or sacrifice.
As there is currently no way to properly filter for the number of item on the site, i think it would be a nice addition to the tool if it would tell you the prices of the reward as far as determinable as well as the required sacrifice

**Comment by SnosMe** [comment]
Agree this is the only reasonable way to price them.

![image](https://user-images.githubusercontent.com/4292308/118399021-cea6fd80-b663-11eb-823e-44f894e5a418.png)
