### ISSUE TITLE
How to remove the stopwatch?

### ISSUE THREAD

**Issue by soulesslight** [SnosMe/awakened-poe-trade#394]
Your answer does not help, already clicked 500 times to delete the center does not disappear ... very annoying
How can i return to the initial settings?

**Comment by SnosMe** [comment]
https://github.com/SnosMe/awakened-poe-trade/issues/219#issuecomment-698813737

or delete config file by clicking here and restart app

![image](https://user-images.githubusercontent.com/4292308/119096825-bd237400-ba1c-11eb-86b9-9d8b845e74d7.png)
