### ISSUE TITLE
Overlay oddities after patch

### ISSUE THREAD

**Issue by Davst** [SnosMe/awakened-poe-trade#396]
Since the patch, there have been some oddities with both keybindings and the buttons for the overlay.

**Some background info:** 
I have my alternate keybar bound to SHIFT-Buttons, the game still shows the alternate toolbar when i hold down CTRL though.

**Current bug 1:**
Using CTRL + Space as overlay keybind doesn't workfor some reason since the new patch.. I had to rebind this to Shift + Space

**Current bug 2:**
When using the overlay, some different things seem to happen when clicking a button that has a stash search. Sometimes nothing happens, sometimes you get the chat window opened, and in these cases you have to click in the search field for the stash before you open the overlay to get the search to pop up in the correct place.

**Comment by SnosMe** [comment]
Have no issues for 1

Using Shift and Ctrl+Space
![image](https://user-images.githubusercontent.com/4292308/119196839-7d49a480-ba8f-11eb-81a3-1c374c4ec8b0.png)

> game still shows the alternate toolbar when i hold down CTRL though

doesn't happen for me

----

Clicked a LOT in stash search widget, keeps working good.

So most likely some other software runs in parallel and causes conflicts for your.
