### ISSUE TITLE
Отсутствие окошка уверенности

### ISSUE THREAD

**Issue by Sheffield61415** [SnosMe/awakened-poe-trade#397]
Здравствуйте, не могли бы вы добавить в версии на русском языке окно с уверенностью в процентах (указано на картинке), которое есть в английской версии, но отсутствует в русской. Буду очень благодарен, так как начал играть недавно, и в английском языке пока не очень силен.
![Снимок экрана](https://user-images.githubusercontent.com/84594390/119188886-fe9b3a00-ba83-11eb-9f20-ab74839ee143.png)

**Comment by SnosMe** [comment]
Оно работает благодаря сайту https://poeprices.info/

так как он не поддерживает предметы на русском, то и в Авейкенеде оно не показывается

**Comment by Sheffield61415** [comment]
Понятно, спасибо за ответ
