### ISSUE TITLE
Open with bat

### ISSUE THREAD

**Issue by Xustis** [SnosMe/awakened-poe-trade#398]
Hi, i open all poe addons with a unique bat, but i have problems with this, I dont know why but when i execute the bat an error apear.

The command is start and the path of the .exe. 

I am not sure if it's some issue or i should do something special to open awakened poe, i can't understand why i can open the .exe with double click but not with this bat...

![imagen](https://user-images.githubusercontent.com/16080101/119240967-b4818980-bb53-11eb-8cc9-04b6334bf412.png)

**Comment by SnosMe** [comment]
This error isn't related to bat file.

It's actually this https://github.com/SnosMe/awakened-poe-trade/issues/383#issuecomment-835252234 , I think your shortcut and bat doesn't link to same exe.

**Comment by Xustis** [comment]
> 
> 
> This error isn't related to bat file.
> 
> It's actually this [#383 (comment)](https://github.com/SnosMe/awakened-poe-trade/issues/383#issuecomment-835252234) , I think your shortcut and bat doesn't link to same exe.

Thanks! i deleted app-data how the post say, and it resolve my problem
