### ISSUE TITLE
Crashes System - main monitor won't restore

### ISSUE THREAD

**Issue by runoran** [SnosMe/awakened-poe-trade#399]
When attempting to use the last two versions of Awakened Trade for POE, my game will crash (Windowed Fullscreen mode), all three of my curved monitors will go black, and only the outer two, will restore. The main monitor will not regain it's screen or accessibility. If I use the display settings within windows and change my left monitor as the main desktop, that screen goes black like the middle one does when it was the main screen. I can only regain usability of my main (middle) screen by rebooting my computer system. 

My System is a Ryzen 7 3900
16gb RAM
Sapphire Radeon RX 590 8GB GDDR
WD NvME 500GB SSD
GIGABYTE B550M AORUS PRO AM4 AMD B550

hope this info helps.

**Comment by SnosMe** [comment]
https://github.com/SnosMe/awakened-poe-trade/issues/365#issuecomment-846560382
