### ISSUE TITLE
Unidentified items

### ISSUE THREAD

**Issue by Ezo** [SnosMe/awakened-poe-trade#40]
My unid twilight temple is seen as a regular moon temple map.

**Comment by SnosMe** [comment]
I admit that something may not work with unidentified items. For this reason, I wanted to add a warning (WIP).

I just want to tell you that although you know what your unidentified **item is from its image**, this information is not available to me. I could guess the item by base. But, while some items have only one unique item per base type, others do not.

What then is the value in supporting unidentified unique items. For sale to those who wish to try their luck on rolls?

**Comment by Ezo** [comment]
Thanks for the detailed explanation. 
A warning seems like the most convenient fix.

I agree with unidentified items having a different (higher) value compared to the cheapest identified versions. Having watchers eye and high rolled uniques in mind. 
Perhaps worthwhile making a notice inside the warning of the opportunity value.

Is it truly impossible to gather screen information through JavaScript? I can understand its made impossible due to the user's privacy/security. Otherwise it might be a low priority feature to parse the image data as a fallback mechanism when tooltip data is unavailable.
To price items (like maps) where rolls are less relevant.

**Comment by SnosMe** [comment]
Done in v1.1.0
