### ISSUE TITLE
Request: Possibility to change api url

### ISSUE THREAD

**Issue by Shawak** [SnosMe/awakened-poe-trade#400]
I would like to request the possiblity to change the url returned by the function [getTradeEndpoint()](https://github.com/SnosMe/awakened-poe-trade/blob/f9b6c2521a76d2bf3c7f60499b7786394f0d4c0e/src/web/price-check/trade/common.ts#L59) so I can proxy my own api endpoint which uses my login credentials to increase the ACL on the app.

**Comment by SnosMe** [comment]
> uses my login credentials

Just login in builtin browser 
or https://github.com/SnosMe/awakened-poe-trade/issues/317#issuecomment-768843412
