### ISSUE TITLE
Unknown Modifiers Issue

### ISSUE THREAD

**Issue by Mauilow** [SnosMe/awakened-poe-trade#406]
Hi,
Since Ultimatum League I have the issue of unknown modifiers in brackets, like ppl had when using ctrl as a bind to price check.

I already tried reinstalling and changing my keybinds, but neither will work.

Any tip or fix would be appreciated, I rly love the tool :)

**Comment by SnosMe** [comment]
- check that you have latest app version
- check that here's `Alt` and not `Control`.

![](https://media.discordapp.net/attachments/666709160380858381/833616368950706176/unknown.png)
