### ISSUE TITLE
Kitava's Thirst - Modifier not recognized

### ISSUE THREAD

**Issue by SnailVendor** [SnosMe/awakened-poe-trade#407]
When price checking Kitava's Thirst two of the mods apparently aren't recognized. Since these mods don't change, it's not an issue, but thought you might want to know regardless.

![Kitava Thirst Bug](https://user-images.githubusercontent.com/79535142/120375309-f14f3c80-c31a-11eb-837e-b60032f32d0c.png)

**Comment by SnosMe** [comment]
Awakened doesn't support mods that grant more than one stat. On trade site, you can enter only one value, so you need to transform multiple stat values into one. How? Take an average of them. Yes, this will work for "Adds # to # Physical Damage" (and actually supported by Awakened). But stats such as on screenshot when averaged don't make any sense, so they are simply not supported and I clearly tell you about this as warning. Luckily rolls on this one is static.

> thought you might want to know regardless

Thanks, I always want to know about any oddities you find.
