### ISSUE TITLE
Fossils

### ISSUE THREAD

**Issue by Igneaalis** [SnosMe/awakened-poe-trade#414]
I think fossils should also show drops as splinters, catalysts etc.

**Comment by SnosMe** [comment]
This sidebar is shown to help you make a price decision: you can vendor items to get random catalyst, oil, etc. Fossils doesn't have such recipe.

And even if I decide to add them, they don't fit into one column. Place them in 2 columns? Well, I hope you noticed that 2 columns have special semantic meaning, it's not just to fit items, and... fossils doesn't have such meaning.
