### ISSUE TITLE
Not showing pdps or dps of multiple uniques

### ISSUE THREAD

**Issue by leet0rz** [SnosMe/awakened-poe-trade#417]
There is no overall pdps of "paradoxica" or total dps of "vaal of the rebuke" and other similar uniques

**Comment by SnosMe** [comment]
They are under "hidden" toggle
![image](https://user-images.githubusercontent.com/4292308/127204096-b6e14bc7-6da1-4d9f-816e-d63e08d78b40.png)

**Comment by leet0rz** [comment]
Checked this again for elemental damage for windripper and it does not show.
