### ISSUE TITLE
Can i use this with geforce now

### ISSUE THREAD

**Issue by PistoMisto567** [SnosMe/awakened-poe-trade#418]
I've been playing path of exile for some time now and i want to use a trade macro to make my life easier can someone help me  with this?

**Comment by SnosMe** [comment]
As soon as GeForceNow will support clipboard forwarding. 
![image](https://user-images.githubusercontent.com/4292308/124314016-6613d180-db7a-11eb-8131-8db44613eb1b.png)

Duplicate of #170
