### ISSUE TITLE
Dangerous map mods

### ISSUE THREAD

**Issue by RaphaelScho** [SnosMe/awakened-poe-trade#42]
Would be sweet to have a hotkey for item information like dangerous mods on selected map, effect of gem quality on selected gem, etc. (like poe trade macro)

**Comment by SnosMe** [comment]
> effect of **gem quality** on selected gem

There is a hotkey for opening an item on a wiki. I strongly believe that this information should be displayed by pressing Alt. Hope Reddit's angry threads lead to this someday.

> Would be sweet to have a hotkey for item information like **dangerous mods on selected map**

So do I. But it will be implemented in a different way, not what you see in some tools now.

**Comment by JusKillmeQik** [comment]
Hey, is this still something you think will be out with your next release? Will that be soon? With Harvest starting I'm sure you're busy but this is a must have feature for me and I'm hoping to use your tool!
