### ISSUE TITLE
Medium Cluster Jewel - Enchant "Not recognized modifier"

### ISSUE THREAD

**Issue by SnailVendor** [SnosMe/awakened-poe-trade#421]
Enchants on Medium Cluster Jewels seem to be bugged as of 3.15 release. Number of passives modifier works fine, but the modifier that defines what the passives grant is not recognized by the app. This is the only cluster jewel I have so far, so couldn't test whether this bug only happens for this specific enchant (i.e. "increased burning damage") or if it bugs out on all cluster jewels, regardless of the modifier. Here's a picture for reference:

![Medium Cluster Enchant Bug](https://user-images.githubusercontent.com/79535142/126873351-631420f3-80e8-4df9-ac52-2591ac21bc18.png)

**Comment by Xebtria** [comment]
happens to other jewels as well.
https://i.imgur.com/rH6OIUV.png

**Comment by SnosMe** [comment]
Fixed in v2.12

https://snosme.github.io/awakened-poe-trade/download
