### ISSUE TITLE
League choose

### ISSUE THREAD

**Issue by 18hannibal18** [SnosMe/awakened-poe-trade#422]
I i have problem about choose league in desktop when im going choose league in desktop with right botton up in setting theres nothing, another leagues was sucessfull and i hadnt problems but this league i cant choose league because i havent tab league up in settingss.thank you

**Comment by SnosMe** [comment]
You may need to complete captcha. Price check one item, then click "Browser" there, complete captcha, click "Retry", select league in tray.
