### ISSUE TITLE
Wayland + XWayland overlay support

### ISSUE THREAD

**Issue by NINNiT** [SnosMe/awakened-poe-trade#427]
Hi,

with the upcoming release of the Steam Deck and Wayland getting more and more mature, I was wondering if (X)Wayland support is planned and possible for APT?

I'm guessing it will have to be integrated upstream in `electron-overlay-window` which seems to only support X11 for now?

**Comment by SnosMe** [comment]
AFAIK Wayland focuses only on thing, rendering windows. I don't see any APIs to query currently active window name and it's size. If  you know how, link it
