### ISSUE TITLE
v2.12 Affixes Bug

### ISSUE THREAD

**Issue by ThorvaldtM** [SnosMe/awakened-poe-trade#430]
Affixes are no longer recognized in 2.12. It displays the item with only the base stats.

**Comment by SnosMe** [comment]
![image](https://user-images.githubusercontent.com/4292308/127226769-5d84b283-be91-4ac6-a234-d2affbca2cd0.png)

**Comment by faraddox** [comment]
Why? Any reason for that? I always use 2 buttons for this hotkey to prevent freezing and crashing in juiced maps or blights. It will be easier for me to use other price checkers than change this option for single button.

**Comment by ThorvaldtM** [comment]
Any reason for this change ? It was working fine before 3.12.
I use `Alt` for item pick up. Highlight is on `F` for me.

**Comment by SnosMe** [comment]
> Any reason for this change ?

App now requires advanced mod descriptions that game send when "Highlight items and object" key is pressed in addition to Ctrl+C. This can be improved to read key from game config file, but for now you need to set key as on screenshot.

**Comment by E2A4E789A3DCC7236FF998692ADE60E2** [comment]
I'm using different key for items highlight for years and this change completely breaks my gameplay flow.

**Comment by hhat42** [comment]
> I'm using different key for items highlight for years and this change completely breaks my gameplay flow.

I can only copy that. I am using Shift for advanced highlight for years. Please add an option to configure the key in the settings of the makro or to turn off the use of advanced highlight usage so it works as before.

**Comment by Blekota2k** [comment]
I dont know how to play the game now ... i have alt for pickup, ctrl for alt hotkeys ... how am i suppouse to use this now?

**Comment by msramachandran** [comment]
i do have `Alt` as the keybind for `Highlight items and objects` but the app is completely broken for me after the patch. I can't use it to read maps or look up trade prices. Can you please make this a settings option to use the feature ? or tell us if we have to update any other game configuration for this to work.
![image](https://user-images.githubusercontent.com/7046405/127422661-a5bb75e4-5cf3-4f17-9736-bec3634636e0.png)

P.S: I get the same result on any item for both `Ctrl + C` and `Ctrl + Alt + C` in my game client

**Comment by noraj** [comment]
I have always found <kdb>Alt</kdb> not very convenient I have used this for years instead.

![image](https://user-images.githubusercontent.com/16578570/127535083-dcd648fb-ed74-450f-90ef-9e91ff82f174.png)

**Comment by dntu622** [comment]
> Any reason for this change ? It was working fine before 2.12.
> I use `Alt` for item pick up. Highlight is on `F` for me.

Same as mine. I changed like this since the first day I know about lootfilter in PoE. XD

**Comment by thisVioletHydra** [comment]
![image](https://user-images.githubusercontent.com/11839238/127684007-ede20513-a625-40f9-9b16-fee89812dc30.png)
😢

**Comment by cyberbird88** [comment]
Using another hotkey too, please make it work somehow =)

**Comment by thisVioletHydra** [comment]
if i hold my highlighting button and press ctrl+D, it's steal work ;c

**Comment by noraj** [comment]
> 
> 
> if i hold my highlighting button and press ctrl+D, it's still work ;c

Yes it's just super annoying to have  to press 4 keys (2 hands), eg. CTRL+ALT+D+Highlight item key

**Comment by tjorb** [comment]
This change is Awful. It bugs out when I put the highlight keybind on Ctrl and starts flickering. Alt is my push to talk key and C is my open inventory.

**Comment by SnosMe** [comment]
Added support in 2.12.1
