### ISSUE TITLE
Endlessly opening Chrome tabs after 2.12.0

### ISSUE THREAD

**Issue by DisguntinJusin** [SnosMe/awakened-poe-trade#432]
Hey guys
Has anyone had the following issue?

I just updated from 2.11 to 2.12. Now whenever i try to price check with CTRL+ALT+D it opens an infinte amount of Chrome tabs. With every tab opening it also brings chrome to the front(the active window) so trying to use task manager to close poe-trade is impossible. Switching back to 2.11 sadly "fixes" the problem.

I've tried running the game and poe-trade as both admin and non-admin.
Scanned pc for everything, although v2.12 is the only thing i've DL'ed and run.
I thought that maybe RivaTunerStatistics was causing a problem, but it still persist withhout Riva.
Has anyone else run into thhis frustrating problem?

Cheers

**Comment by MatthewClair** [comment]
I can confirm that I am also having this issue since updating to 2.12.0

**Comment by noraj** [comment]
I can confirms that the bug **doesn't** appear on Firefox.

**Comment by SnosMe** [comment]
![image](https://user-images.githubusercontent.com/4292308/127544797-5f7de835-9643-4df6-a5ff-353008af6732.png)
