### ISSUE TITLE
Using the Macro (Ctrl+d) while chat is open causes special letters to appear in chat.

### ISSUE THREAD

**Issue by ShanKanis** [SnosMe/awakened-poe-trade#434]
As in title, if macro is used while chat is open (common), the letter ć  (normally input with alt+c) will appear in the chat. This will only happen on non-native English keyboard input layouts, normally there is nothing under alt+c combo.

This is likely because of "Now uses advanced item description (Ctrl+Alt+C) " from last update. This didn't happen before it, and using previous version confirms it.

**Comment by SnosMe** [comment]
AltGr is part of Keyboard Layout built in Windows. You're right that price checking while *some* non-English kb layout is active you can see this. There is nothing can be done from my side.

**Comment by ShanKanis** [comment]
Thanks for response. Shame it's not possible to fix that from Awakened Trade side. Anyway, I've managed to fix it on my side by creating new custom layout for the keyboard using Keyboard Layout Creator (native windows tool). Simply moved ć to other key. I rarely use it anyway. Hope this helps for anyone having same issue.

**Comment by SnosMe** [comment]
Created bug report https://www.pathofexile.com/forum/view-thread/3156450
