### ISSUE TITLE
Last message sent

### ISSUE THREAD

**Issue by noraj** [SnosMe/awakened-poe-trade#436]
I have a question, does someone know why sometimes when I press CTRL + D to price check it sends again the last private message I sent? I don't even see this kind of shortcut in PoE.

**Comment by SnosMe** [comment]
@noraj check if changing to "No" helps you

![image](https://user-images.githubusercontent.com/4292308/127837414-993d6092-a823-479d-ab45-7e33906d525a.png)

**Comment by noraj** [comment]
I changed to no but it still happening.

**Comment by SnosMe** [comment]
Check this https://github.com/SnosMe/awakened-poe-trade/issues/178

**Comment by noraj** [comment]
As option 2 didn't work I'll rather try option 1, yes i'm using poe trade companion too.
