### ISSUE TITLE
HOW? support for custom "Highlight items and objects" key

### ISSUE THREAD

**Issue by thisVioletHydra** [SnosMe/awakened-poe-trade#438]
![image](https://user-images.githubusercontent.com/11839238/127916689-188a7b80-8428-4781-befa-68c54f213437.png)
how to change this field ? ? 
😢

**Comment by SnosMe** [comment]
This key auto-detected from reading config file here

![image](https://user-images.githubusercontent.com/4292308/127926876-9c81db8c-c312-4bb4-b1f3-cdc45e37092b.png)

**Comment by SnosMe** [comment]
Mouse keys are not supported
