### ISSUE TITLE
No Keyboard on Linux

### ISSUE THREAD

**Issue by Dukadyr** [SnosMe/awakened-poe-trade#439]
Hey Guys,

If im running APT and PoE, the Keyboard will only react to APT Commands.
So I am not able to press any keys in the Game, like Flask, Inventory etc.
I think there should be a simple solution, but i don't get it right now...

im running gnome on ubuntu 21.04 (on kde apt isnt working at all).

greetings, dukadyr

**Comment by SnosMe** [comment]
Try hitting Shift+Space two times
