### ISSUE TITLE
App doesn't recognize incoming whispers from people with Asian (Korean?) characters in their names.

### ISSUE THREAD

**Issue by flapanther33781** [SnosMe/awakened-poe-trade#442]
Hey!  TY so much for everything you've done with this app.  I just wanted to let you know that something seems to have changed and now the app doesn't recognize incoming whispers from people with Asian (Korean?) characters in their names.  I didn't play last league but I was trading in Standard, and I'm pretty sure it was working then.  I think it was the patch to Expedition where it stopped working.  It's taken me a while to realize the common denominator for the failures was the Asian characters in the usernames, but I'm fairly certain that's what the problem is.  I didn't see this in your list of open items so I thought I would mention it.

**Comment by SnosMe** [comment]
Hi, Awakened doesn't have such functionality, you mixed up with another app. But on behalf of another app I can say that whispers from korean players are not logged since Legion league. This is because of legal stuff.

**Comment by flapanther33781** [comment]
Whoops! Sorry for that!
