### ISSUE TITLE
Seething flaks not found

### ISSUE THREAD

**Issue by Feuerhai** [SnosMe/awakened-poe-trade#443]
If you're searching for the price of a seething flask, it searches for "instant recovery" of at least 90, but the modifier itself doesn't have a value and doesn't find anything if it's higher than 1. That causes it to not find any result when quick searching them.

**Comment by SnosMe** [comment]
yep, this one doesn't follow logical rules. The flask system is old and ggg just have mod with this stat that have roll 1 😦
