### ISSUE TITLE
latest update, price check, map mods not working

### ISSUE THREAD

**Issue by SoM6666** [SnosMe/awakened-poe-trade#445]
just got the latest update, price checking not working, nothing pops up, map mods dont show up..

**Comment by SnosMe** [comment]
1. Make sure Ctrl+Alt+C is not used by another application. You must be able to copy item text to clipboard from game using it.
2. Make screenshot of hotkeys setting in awakened poe
3. send logs

![image](https://user-images.githubusercontent.com/4292308/128624141-98cffa40-d97b-420c-bf9c-efd4cf4255f9.png)

This is a local issue for you and better to be asked in Discord. 😉
