### ISSUE TITLE
Report if you see this text

### ISSUE THREAD

**Issue by kuasimikua** [SnosMe/awakened-poe-trade#449]
![image](https://user-images.githubusercontent.com/10751277/129657591-ef6a49d2-b92c-4d7b-952e-61df6431d587.png)
![image](https://user-images.githubusercontent.com/10751277/129657630-1811a7f6-4389-481c-a0c5-2c58f5f7344b.png)

**Comment by SnosMe** [comment]
You're using an old version of the app.
