### ISSUE TITLE
/tradewith @last and similar macros not working

### ISSUE THREAD

**Issue by elmo667** [SnosMe/awakened-poe-trade#450]
Hi,

macros like /tradewith/hideout/invite @last arent working, @last <whispertext> is working.

Maybe this is a timing issue? Because when I remove the "press enter" toggle, the correct command is put into chat and pressing enter manually makes it work as expected. If "press enter" is selected, hitting the macrokey only writes the target character name to local chat.

Using Linux and running POE via steams Proton (mentioning because it might be relevant to timing). 

Would it be possible to maybe add a 1-5 ms sleep before pressing enter after pasting the command into chat if "press enter" is checked?

**Comment by SnosMe** [comment]
> Would it be possible to maybe add a 1-5 ms sleep

This is a bad idea, because timings depend on how performant your PC is.

**Comment by elmo667** [comment]
Hi @SnosMe 1.14 made this problem significantly worse. Now if you press F5 its about 50:50 whether it will paste /hideout into the chat OR your current clipboard content. This happens with ALL of the macro functions.    
    
A (very annoying) workaround seems to be to hold down the macro key (F5 in this demo case) for longer than normal. Holding the button down until the macro command is fully pasted to the game seems to help. But I can see it inputting the characters of the macro command character by character, so it was slowed down significantly by some change in 1.14.0 (1.13.1 worked fine!)

**Comment by SnosMe** [comment]
It's a C https://github.com/octalmage/robotjs

**Comment by elmo667** [comment]
interesting, was not aware you using external libraries. We may be talking about https://github.com/octalmage/robotjs/issues/530 then. That issue is a bit of a mess but it sounds like the version/s available via npm may not have the required fix in it

**Comment by SnosMe** [comment]
@elmo667 awakened includes patch to remove all delays https://github.com/SnosMe/awakened-poe-trade/blob/master/patches/robotjs%2B0.6.0.patch

**Comment by elmo667** [comment]
Randomly stumbled upon the settings option Debug --> Restore Clipboard. If you set that to no, it removes the problem entirely. Id much rather "lose" my previous clipboard content than spam random people or towns local chat with garbage :)
