### ISSUE TITLE
Price checking overlay won't open

### ISSUE THREAD

**Issue by Jrribas** [SnosMe/awakened-poe-trade#451]
Hello, 
when I click CTR-D the price checking won't open in the latest update.
If I try to open overlay it works SHIFT+SPACE it works.

EDIT:
Note: I was using 2.10.3 before updating to new version. 

I just found "the issue". I am using Keepass. And before both worked fine at the same time, but with your new update whenever I click CTRL-D it opens New entry window on keepass. If I change the keybinding for ALT-D the same happens. Athough in keepass the keybing assigned to new entry is CTRL-I....

If I turn off keepass it works fine.

As I didn't update keepass my hipothesys is that something was changed in the code of awakened poe trade.

Best regards

**Comment by stvndall** [comment]
I get the same, for some reason when I press Ctrl+D it now opens my character sheet. And Ctrl+Alt+D going into some odd loop that seems to have my ctrl key press inverted. I thought it was just me when I updated last night

**Comment by stvndall** [comment]
Rolled back to 2.11.0 and everything is good again.

**Comment by stvndall** [comment]
2.12.1 has this problem with the input as well.

**Comment by SnosMe** [comment]
@Jrribas check that hotkey to copy item from game is not used by any app

![image](https://user-images.githubusercontent.com/4292308/130137321-a7464b5d-d454-4d1a-99a4-addc64f3818d.png)

**Comment by SnosMe** [comment]
>  And Ctrl+Alt+D going into some odd loop

@stvndall check that Ctrl+Alt+C is not used in any other hotkeys in Awakened.

**Comment by Jrribas** [comment]
@SnosMe I understand that is the problem, with me using keepass and webautotype which as the same hotkey. But This didn't happen before. Is there a way for me fiz this without changing the hotkey in the keepass?

**Comment by SnosMe** [comment]
> This didn't happen before

Because app previously was more simple and didn't understand advanced mod descriptions. It's using them now exclusively, so this hotkey is required. Either you change key in keepass or change "Highlight items and objects" key in PoE settings

**Comment by stvndall** [comment]
@SnosMe I don't appear to have anything trapping that particular key combination. I might be wrong, but it doesn't seem to be picked up by anything else. Any ideas to pick up what might be reading from the global keystrokes?
