### ISSUE TITLE
Linux: XRecord is not available

### ISSUE THREAD

**Issue by Fratze1995** [SnosMe/awakened-poe-trade#452]
So i am currently on a pop-os 21.04 64bit and if i try to launch the appimage it show for one second and then disappears.
If i try to launch it from my terminal it show me this message before it disappears:
```
hook_thread_proc [101]: Could not set thread priority 49 for thread 0x7FF5CEE31640!
xrecord_query [947]: XRecord is not currently available!
```

And when i launch it as root the XRecord error still pops up.

**Comment by SnosMe** [comment]
XRecord is required extension for X11 for app to function. Install/enable it in config.
