### ISSUE TITLE
Request: A way to scroll through stash tabs with just scroll wheel.

### ISSUE THREAD

**Issue by Allano666** [SnosMe/awakened-poe-trade#456]
I am still using old trade macro with all functions disabled just to scroll through my tabs without holding CTRL, please add option to   switch between  CTRL + scroll and just scroll so i can finally unistal it into oblivion.  Especially since GGG added option to disable mousewheel zoom so it shouldn't interfere.

**Comment by SnosMe** [comment]
No. https://github.com/SnosMe/awakened-poe-trade/issues/335#issuecomment-892013264

**Comment by Allano666** [comment]
That's sad. Trade macro somehow allows to do so and scrolling through stack size still works.
