### ISSUE TITLE
[Suggestion] Ingame Menu Navigation

### ISSUE THREAD

**Issue by M0RDREAD** [SnosMe/awakened-poe-trade#457]
Would it be possible to navigate the ingame menu?
For example: 
If you look up an oil or catalyst ingame you see a full list of all oils/catalysts on the right side.
It would be very helpful, if you could navigate through that menu to switch to another oil/catalyst and then would see the available offers. 

Thank you very much for your awesome work!

![image](https://user-images.githubusercontent.com/89800159/131498933-c964c323-0249-49d8-a580-ff11a193bb75.png)

**Comment by SnosMe** [comment]
![image](https://user-images.githubusercontent.com/4292308/134824282-83b40f30-10fc-4e74-8675-23f07c797be2.png)

There can be different types of items, they are represented by simple pair of name-basetype and this is not enough to perform a search. Such additional info comes from item text itself when you price check. I'd say the tool isn't ready to perform an arbitrary search by name-basetype yet. 

cc #164
