### ISSUE TITLE
Ctrl and Alt Hotkey hooking conflicts with Radeon Software hotkey hooking

### ISSUE THREAD

**Issue by Floirt** [SnosMe/awakened-poe-trade#459]
Ctrl and Alt shortcuts do not work at all if you use Radeon Software (the AMD graphics card software) and hotkeys are enabled in there. Shift-Space for the overlay and chat commands still do.

![cnUqVm7hF8](https://user-images.githubusercontent.com/6320256/132080337-88b5193b-2c94-452c-bba7-1609ebb9706e.png)

It took me a while to figure out it was that setting messing with the Ctrl-D price check.
While I simply can just disable hotkeys while I play with the macro on, this means I can't hit my shadowplay hotkey to record anything, so it's particularly aggravating. 

Edit: I saw in #451 that the same problem happens with keepass and the origin of that is Ctrl-Alt-C keybinds, maybe a warning should be added somewhere about needed free hotkeys?

**Comment by SnosMe** [comment]
Failed shortcut registration will be added to the log file.
