### ISSUE TITLE
ctrl + d doesnt work

### ISSUE THREAD

**Issue by kekikcilerakin** [SnosMe/awakened-poe-trade#46]
But ctrl + alt + d works, any idea why?

**Comment by SnosMe** [comment]
Have you launched any other trading- tools at the same time? They may conflict. Close every possible application that works in your tray.

**Comment by kekikcilerakin** [comment]
No this the only one I'm using.

**Comment by SnosMe** [comment]
It will seem to you that this is a long process, but it will greatly help narrow down search for a problem.  You need to create a new Windows user and check if the tool works as expected in it. Since this has not happened to me or anyone else, I don’t know what else to advise

**Comment by whycantiquit** [comment]
I can verify ctrl +D does not work. Ctrl+alt+d will work most the time. The application is also random closing it’s self out and have to restart. I’ve attempted to change the keys to get the ctrl+D to work but it has no affect.

**Comment by tfp** [comment]
Same problem. ctrl+D (or in my case ctrl+4) does work for a few minutes. Then after a while ctrl+d stops working and only ctrl+alt+d does work, until I restart the app.

**Comment by whycantiquit** [comment]
After reinstall ctrl+d now works how ever now with ctrl alt D I can not click on any of the boxes the app goes into the background. I’ve tried all window and full screen options.

**Comment by SnosMe** [comment]
Fix has been added. You must check it after release (~6h).

**Comment by kekikcilerakin** [comment]
> 
> 
> Fix has been added. You must check it after release (~6h).

When?

**Comment by SnosMe** [comment]
Now 😉

**Comment by TheBootyMessiah** [comment]
Its still now working properly even after the update. I run as admin every time.

**Comment by tfp** [comment]
Fix worked for me so far. Thank you! It's really one of the best price checking apps out there!

**Comment by SnosMe** [comment]
Another attempt to fix this comes with v0.14

> Hardware acceleration is now disabled by default (Solves Windows 7 issue, and any other compatibility bugs between GPU and Chromium)
