### ISSUE TITLE
Humble question: is not this claw over-estimated?

### ISSUE THREAD

**Issue by Eqatrpfvvzzih** [SnosMe/awakened-poe-trade#463]
Hi, I am trying to start using this tool.
Here is a claw:
https://i.postimg.cc/kGys9NwJ/pricecheck111.png
Here is the estimated price: (51-76 chaos)
https://i.postimg.cc/d3JRWkFz/pricecheck112.png

So, I will be able to (quickly) sell this item for 51 or even 61 chaos? Or what? It seems (for me) it is rather weak: itemlevel 46, reqlevel 21, with neither flat nor increased physical damage, no attack speed. Has tier12 and tier9 mods.

What is some real price of this item? Can this tool tell me that? If so, exactly how to extract the real price value from this tool (tool's showings)?

**Comment by SnosMe** [comment]
Well, I hope noticed that line. Price prediction does 3rd-party site https://poeprices.info/
Why it's saying so high confidence, that is the question to developer of it.
![image](https://user-images.githubusercontent.com/4292308/133940522-3155420b-e531-4390-bd63-2915a5b19433.png)

> What is some real price of this item? Can this tool tell me that?

You tick checkboxes and tool shows results from https://pathofexile.com/trade/search
How to know which ones to tick? The more time you've spent in the game, the more builds you've played, the better you understand pricing.
