### ISSUE TITLE
Always on top prevents PoE-Window-Active recognition

### ISSUE THREAD

**Issue by 1stkeks** [SnosMe/awakened-poe-trade#477]
Since updating to the most recent version with the "Always on top - Feature" my Corsair software can't recognize PoE being the currently active window to change profiles accordingly.

**Comment by Schwanhelt** [comment]
> Duplicate of #105
> 
> I'm sorry, but their software is bugged.
> 
> Awakened doesn't steal focus/makes window foreground. It just makes it visible.
> 
> ![image](https://user-images.githubusercontent.com/4292308/138677773-2a174de5-63c4-45c3-821c-8f6f4ac3d238.png)

This is not an Icue software issue as the last version 3.38.61 was put out on 03/15/2021 and this issue only started happening with awakened poe trade with its last update.

Just to be sure, I went back and downgraded to iCUE 3.33.246 and had the same issue, then updated to iCUE 4.16.194. Same issue.

Reverting to the 2.13.1 version of awakened poe trade fixes this issue completely. 

Please just give us the option to turn the always on top mode off.

**Comment by str0yd** [comment]
Looks like you tested it wrong.
On my side the problem only appears if POE is in windowed fullscreen mode.
I figured that the problem won't arise if the game is in windowed mode so I tried to fix it by leaving the game in windowed mode and handle the fullscreen window mode by Borderless Gaming. But with the fullscreen mode from Borderless Gaming I get the same wrong behavior as like with the windowed fullscreen mode from POE.

**Comment by str0yd** [comment]
Ok tested it myself.
![image](https://user-images.githubusercontent.com/29361982/143763409-4aac5d92-de58-494d-b186-cf7b975dc8ce.png)
The first event is the event entering POE after enabling the debug.
At this point POE was set to windowed mode.
Then I opened APT, closed it and checked that ICUE still working. In this state ICUE correctly sets the desired profiles (POE profile while in POE and Default profile while in APT or any other window).
Then I switched POE to windowed fullscreen and tested it again.
As long as I do not open APT everything works still fine. ICUE switches the profiles as intended.
But the first opening of APT brakes the ICUE software (but only in windowed fullscreen mode).
ICUE then switches to the Default profile again but won't switch back to POE after closing APT. Also tabbing out to any other window and back to POE won't switch back to the POE profile set up in ICUE.

**Comment by SnosMe** [comment]
Just in case, I tested Windowed Fullscreen with Vulkan and DirectX, got same results, working correctly.

You have recorded wrong event types, instruction here https://github.com/SnosMe/awakened-poe-trade/issues/497#issuecomment-964634527

Also do a screen recording, it's quick and makes order of events much clearer.
