### ISSUE TITLE
Not showing elemental dps (total edps) or total dps of multiple uniques

### ISSUE THREAD

**Issue by leet0rz** [SnosMe/awakened-poe-trade#488]
Missing edps for windripper, total dps for vaal of the rebuke and many other uniques that either have a lot of mixed elemental dps or mixed total dps.

**Comment by mataski** [comment]
Can confirm, old poe-trademacro used to calculate total pdps for white/magic/rare and unique weapons on ctrl+c (map check command I think)

I think right now awakened poe trade calculates e.g. 2h magic axe shows total pdps with 20% quality, but does not show total pdps for e.g. unique Lakishu's Blade.

**Comment by SnosMe** [comment]
Some changes will be included in v2.15, other than this it's a duplicate of #118
