### ISSUE TITLE
Tool does not open on linux.

### ISSUE THREAD

**Issue by nilzeronull** [SnosMe/awakened-poe-trade#49]
Downloading version 0.11 at least shows a window, 0.12 exits with:

```./Awakened-PoE-Trade-0.12.0.AppImage
Checking for update
(node:154798) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:154798) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
Update for version 0.12.0 is not available (latest version: 0.12.0, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null
```

**Comment by SnosMe** [comment]
0.12 no longer show initial load window. As for this log, this is a 3rd party auto-updater, no interesting stuff here.

So you don’t even see the tray icon, right?

**Comment by nilzeronull** [comment]
Correct, no tray icon.

**Comment by SnosMe** [comment]
I'm testing the Linux version on Ubuntu 19.04.

**Comment by SnosMe** [comment]
✔️ Tool
> checking prices now works

✖️ WM
> The tray icon stays gone
> black bars around the pop-up

I am closing this, because the tool works as expected, and all other problems are related to your WM.
