### ISSUE TITLE
Can't search for stats on items.

### ISSUE THREAD

**Issue by therock182** [SnosMe/awakened-poe-trade#493]
i want to price check a rare item, but it shows only 1 stat or no stat which i can search for.
the predicted price  shows all stats from the item.
![1](https://user-images.githubusercontent.com/12401617/140582886-c1a50a2e-57e7-4ea4-97f4-f61d9eba6abf.jpg)

**Comment by SnosMe** [comment]
Check what's in the logs, most likely says

`error [game-config]: Failed to read key. {"key":"5"}`

If so, change `Highlight items` key in PoE from mouse to keyboard key and restart Awakened.

**Comment by nmarkey10** [comment]
@SnosMe , sorry, just saw the reply.  It worked after changing it from Alt, to `,` but I cannot get it to work with Alt bound as Highlighting items and objects.  Which is weird, because it has always been Alt.  Still seems like there might be a bug to me.
