### ISSUE TITLE
Cluster jewels pricing totally bugged

### ISSUE THREAD

**Issue by Fnts7** [SnosMe/awakened-poe-trade#495]
Cluster jewel pricing is totally wrong as it selects "adds # passive skills" as minium, not maximum". And also doesn by default take ilvl into account properly. This way I almost mispriced 1.2ex jewel for 1c jewel. I wonder how long is it and how much I lost last league because of it.

So seems you probably dont handle well any mods in which the lower is better. This is also e.g. case of flasks were you have negative increased charges used. The lower negative number the better.

**Comment by SnosMe** [comment]
> it selects "adds # passive skills" as minium, not maximum"

This filter doesn't autofill max value which is a bug tracked in #484 
![image](https://user-images.githubusercontent.com/4292308/140643599-852d8a02-4122-44f3-b602-103f88040bac.png)

> And also doesn by default take ilvl into account properly

This is intended same as for craftable items, if you want to sell jewel as crafting base you need to activate Item Level filter.

> how much I lost last league

 "adds # passive skills" bug appeared only in the latest release and wasn't affecting previous league

---

> So seems you probably dont handle well any mods in which the lower is better

This is very well handled long ago, but there are some exceptions to this, there is no magic way to get list of them, so you can report them here #465 

> This is also e.g. case of flasks were you have negative increased charges used

I'll check why this one is no longer recognized.
![image](https://user-images.githubusercontent.com/4292308/140644159-3d4a6e39-40c6-4ba2-ab4f-a615fbf45f79.png)
