### ISSUE TITLE
Add Wiget Greyed out

### ISSUE THREAD

**Issue by ajs1351** [SnosMe/awakened-poe-trade#498]
when I try to add a widget, it is greyed out.  is there something im doing wrong or was it disable?

**Comment by SnosMe** [comment]
Screenshot?

**Comment by ajs1351** [comment]
![widget](https://user-images.githubusercontent.com/94127190/141501458-773a923a-7a01-4ca6-81ea-dcb7994977a7.jpg)

**Comment by SnosMe** [comment]
It's description, probably to be more correct it should have ellipsis "Add widget...", so you actually picking the type of new widget at the bottom.
