### ISSUE TITLE
Bring back filtering by resistance !!

### ISSUE THREAD

**Issue by hejz0r** [SnosMe/awakened-poe-trade#500]
Can you please bring us back possibility to filter item strictly by its resistance?

Before, last league, under "hidden" we could search for item cold/light/res resistance ... now it seems bugged :

Item has 3 diff resistances, and under "hidden" there is only one to choose

Filtering by total resistance makes item much underpriced!

**Comment by SnosMe** [comment]
No, you can join the discussion in #483 and give a take about how hard for avg player to get Harvest change res crafting.
