### ISSUE TITLE
Pricing Items with Same Name is not handled well

### ISSUE THREAD

**Issue by angelic-knight** [SnosMe/awakened-poe-trade#501]
I tried to do a price check on The Twins (the prophecy) but the search hotkey looked up The Twins (divination card) instead.
There are only a few other items in the game which have duplicate names.
This is probably only going to be significant in scourge league where using The Twins to duplicate rare monsters is valuable for scourged maps.

**Comment by SnosMe** [comment]
Same for "The Scout".
