### ISSUE TITLE
Make price check currency configurable

### ISSUE THREAD

**Issue by elmo667** [SnosMe/awakened-poe-trade#503]
Hi,

due to abuse of incorrect chaos<->ex rate displays in the trade API, awakened-poe-trade will currently show 0.4ex prices above 50c prices (even though 0.4ex currently converts to 58c). This is being abused heavily and makes the price checker essentially useless for items in the 0.1-5ex price range.    
    
I would recommend making the currency configurable so that theres either a global config switch or a little switch in the Ctrl Alt D menu that shows prices strictly in chaos only.

**Comment by SnosMe** [comment]
I hope that you understand that if first 20 listings are 0.4exalts, and later ones are in chaos, normalizing first 20exa to chaos will do literally nothing because app doesn't know about next listings after first 20, therefore can't sort them

**Comment by elmo667** [comment]
Hi, I dont know how the queries you send to the APIs work, but on the trade site itself, you can tell it to ONLY show you offers that were posted in chaos and flat out ignore prices in (fractions of) exalteds. Is that possible to set as a query paremeter?

**Comment by SnosMe** [comment]
Imagine this
20 x Listings in Exalted,
03 x In Chaos,
20 x In Ex,
10 x In Chaos

![image](https://user-images.githubusercontent.com/4292308/142595582-fb827f5c-0e90-4949-9f33-f08d9a38f842.png)

If you choose to show only results in Chaos you will see first 3 listings and think they're pricefixed and skip them, then you will see next 10xlistings but they're actually more expensive than previous that you filtered out, now you're overpriced the item.

I really want this to be solved on GGG's end so not only macro users benefit but anyone visiting the site as well.
