### ISSUE TITLE
Stash search fails with a specific Gwennen string

### ISSUE THREAD

**Issue by enki1337** [SnosMe/awakened-poe-trade#505]
The following search string does not appear in the stash search box when clicked:

> "(fien|hecy|gem|sie|bony|hon|occ|sadi|leat|stud|turq)"

Simply removing the brackets and quotation marks seems to fix the issue.

> fien|hecy|gem|sie|bony|hon|occ|sadi|leat|stud|turq

This one works fine for me.

**Comment by SnosMe** [comment]
You can't type more than 50 characters in the search field, therefore Ctrl+V with text in clipboard that has more than that length will not paste anything at all.

**Comment by enki1337** [comment]
Ahh, that makes sense! Maybe it would make help to limit the entry field length or provide some sort of indication (!) it if the input is too long, so it's obvious why it's not working.

**Comment by SnosMe** [comment]
![image](https://user-images.githubusercontent.com/4292308/147384753-42c06228-12b5-48b9-a91b-ebdad1fd66a7.png)
