### ISSUE TITLE
Linux version opens on wrong screen

### ISSUE THREAD

**Issue by royalmustard** [SnosMe/awakened-poe-trade#507]
This is most likely an issue with xorg, where the 0,0 coordinates are not on the same physical screen as the game.

**Comment by SnosMe** [comment]
https://github.com/SnosMe/electron-overlay-window/issues/16

> Different managers send X11 events in different order, why?

This will be fixed by itself as soon as there will be some consistency in linux Desktop world.
I've tested it in Ubuntu 20.04, where it works.
