### ISSUE TITLE
Cannot remove logout macro

### ISSUE THREAD

**Issue by Bromkar** [SnosMe/awakened-poe-trade#508]
previously there was setting for binding logout, now i cant find it to change/remove but it still works, checked evrywhere in hotkeys and chat macro list, re installing dosent help

**Comment by SnosMe** [comment]
Tool can't log you out other than typing this chat command.

![image](https://user-images.githubusercontent.com/4292308/145103443-d888f9e4-294c-46f2-9a5f-4ad00d600862.png)
