### ISSUE TITLE
On linux, hideout key pastes clipboard

### ISSUE THREAD

**Issue by 99TonyStark99** [SnosMe/awakened-poe-trade#509]
if you whisper someone from the trade site, after completing the trade, press F5

expected behaviour:
goes to hideout.  

actual behaviour:
pastes the contents of the clipboard into chat window (which typically just sends the trade whisper again)

**Comment by LillieSatou** [comment]
This can be reproduced on Windows 10/11 as well! Doing too many actions too quick (> 1 action PER second) can also have you paste whatever the contents of your clipboard to whichever chat's selected (Global, Guild, Party, LastWhisperedPlayerName, or Normal/General/Local.)
