### ISSUE TITLE
Default "online" instead of "online in league" for permanent leagues

### ISSUE THREAD

**Issue by ferrosa** [SnosMe/awakened-poe-trade#510]
Currently, price checking from Standard by default shows only people logged into Standard. But most people are willing to switch leagues for trading unless it's for scraps (a few chaos). The majority will switch for a 20c+ trade, and virtually everyone will switch for a 10ex+ trade. The current setting is making these people and thus the majority of pricings invisible, giving wrong guidance when price checking.

I'm resorting to opening the browser link and changing the setting to "online" for maybe three quarters of my last 1000 or so price checks, and it's getting tedious... but not doing so produces garbage pricing.

The obvious "proper" solution is to implement an option picker for this selection, but until then I would like to suggest changing the setting back to just "online".

**Comment by LillieSatou** [comment]
I'm against this, as this would make you be shown **in ALL leagues**, not just the one you're shown in.

**Comment by ferrosa** [comment]
This is not an opinion poll, so let's stick with reporting observations: I've had multiple trades between 10 and 500 ex from sellers from other leagues, and nobody so far gave the slightest hint that they wouldn't want to be disturbed or disliked switching.
But that only works if you search for "online" instead of "online in league". Note that this is the (reasonable) default setting for pathofexile.com/trade, so changing it should be well-reasoned as well.

**Comment by SnosMe** [comment]
Will be able to select in v3.15, the default is still "online in league".

![image](https://user-images.githubusercontent.com/4292308/151236515-60ea2f8c-4453-47a0-88e7-5296229865b2.png)
