### ISSUE TITLE
Checkbox to select all modifiers

### ISSUE THREAD

**Issue by hexadezi** [SnosMe/awakened-poe-trade#511]
Can you add a checkbox to select all modifiers at once?

Like this:

![image](https://user-images.githubusercontent.com/11984646/147007853-a42b468d-b5fc-4d68-8e9d-b2ce1bb9f683.png)

**Comment by SnosMe** [comment]
No, this is not the intended way.  #264

**Comment by hexadezi** [comment]
Okay, I understand that. What about unique items?
