### ISSUE TITLE
Return 'Settings' to taskbar

### ISSUE THREAD

**Issue by dovry** [SnosMe/awakened-poe-trade#516]
It's the default for every single program in my taskbar, except yours. Please revert it back

**Comment by SnosMe** [comment]
No, I'm not interested in maintaining synchronization between it and overlay window.
Bug in Electron/Chromium also was annoying for everyone #265.

**Comment by dovry** [comment]
I have literally never had that issue. Thanks for the program but I'm moving on. It seems to get more clunky with every update.
