### ISSUE TITLE
dont work. Pricelist blanked if russian lang on

### ISSUE THREAD

**Issue by Heretik22** [SnosMe/awakened-poe-trade#520]
Everything in title.
ctrl+D open blanked list.
In Eng language work well

**Comment by ifilthi** [comment]
Yes, the price tab is displayed empty on the ru client. Also, the check of cards does not work, the settings menu just appears.

**Comment by SnosMe** [comment]
From GGG patchnotes 3.17:
> The Advanced Mod Descriptions of an item will now display the English name of base item types and Unique items when playing Path of Exile in languages other than English.

So I was expecting it to break and fix will be with the next update.

**Comment by SnosMe** [comment]
Fixed in v2.15.1

**Comment by Heretik22** [comment]
ty
