### ISSUE TITLE
Affixes on item search no longer showing

### ISSUE THREAD

**Issue by gazornuh** [SnosMe/awakened-poe-trade#521]
Hello,
Find a problem today, that I can no longer search by affixes, same problem as in old threads, but none of the solutions helped.
tried change Highlight items key in PoE from mouse to keyboard key and restart Awakened, and then I highlight item it's shows only half of affixes, logs says literally nothing
no other AHR are running, so there is nothing to conflict with the trade8
![image](https://user-images.githubusercontent.com/99076191/152640115-c8c8c680-b276-49a8-95a1-42149b3b50d1.png)

**Comment by SnosMe** [comment]
So uhm, from screenshot it works as expected, what the stats you're missing here?

**Comment by gazornuh** [comment]
I messed up, because of the new design (or something like that), because now elemental resistance not shown individually, but as a total. And in the screenshot for some reason the numbers of lightning damage are different. But the main issue of the thread is solved.
