### ISSUE TITLE
Essence Upgrade Price Checking

### ISSUE THREAD

**Issue by livejamie** [SnosMe/awakened-poe-trade#523]
Now with Essences being more involved in the economy, it would be nice if APT considered the upgraded essences when price checking.

Similar to how upgrade paths are shown for Breach Blessings.

For example, a Shriekling Essence of Greed is currently 2c
![image](https://user-images.githubusercontent.com/49513/152709875-65908b79-617c-4724-9067-6b1007d7a2c8.png)

You can upgrade them 3:1 to Deafening Essence of Greed which are going for 4c

![image](https://user-images.githubusercontent.com/49513/152710155-7b4d4274-10f4-4918-8b28-2d2f19f8a3d3.png)

So in this example, it's not worth spending 6c to make 4c but I'm sure there are Essences where you'd want to upgrade them.

Thanks!

**Comment by SnosMe** [comment]
Will land in next release.

![image](https://user-images.githubusercontent.com/4292308/153500050-0564c2bd-ecff-46cc-ac6f-deb214cdf0a1.png)

![image](https://user-images.githubusercontent.com/4292308/153500092-dddbaa52-e8aa-4ccd-b322-64d9d9ccddfe.png)
