### ISSUE TITLE
[2.15.1] Search window empty for Archnemesis items

### ISSUE THREAD

**Issue by SealviewTW** [SnosMe/awakened-poe-trade#524]
Hello,

I can't seem to get the app to work for new Archnemesis items. The trade window is empty

https://i.ibb.co/FK5tgfx/empty.png

I know that for other ppl it is working.

I have tried uninstall, delete appdata folder, restart pc, nothing works.

Is this a 'me' issue or maybe a known issue?

**Comment by Boberg89** [comment]
Same issue here, a friend has it aswell. Seems to only be in v 2.15.1

**Comment by SnosMe** [comment]
New items and mods are not supported, be patient.

**Comment by Coilbone** [comment]
My friend have 2.14.1 version of the APT and have no issues with new items.

**Comment by SealviewTW** [comment]
> New items and mods are not supported, be patient.

Did you look at the photo I linked?

Its not the same as not supported, I know how that looks every league when NEW mods are introduced.

This is different. The whole screen is blank and if I pricecheck an old item, lets say Tabula, next time I pricecheck a ArchNem item it shows results for tabula.

And also, all my friends can price check new currency items, I can't as I have this exact problem.

**Comment by SnosMe** [comment]
> This is different. The whole screen is blank and if I pricecheck an old item, lets say Tabula, next time I pricecheck a ArchNem item it shows results for tabula.

Yes, this is exactly how what I expected.

**Comment by SnosMe** [comment]
fixed in [3.17.10003](https://github.com/SnosMe/awakened-poe-trade/releases/tag/v3.17.10003)

**Comment by Boberg89** [comment]
> fixed in [3.17.10003](https://github.com/SnosMe/awakened-poe-trade/releases/tag/v3.17.10003)

Amazing! Thank you <3
