### ISSUE TITLE
Electron error

### ISSUE THREAD

**Issue by Netoen** [SnosMe/awakened-poe-trade#525]
I wrote a small *.bat file to start all of my tools and PoE - together with the AwPoET. Initially was working just fine.
Haven't touched it in like a month - since the start of this league started to get error:
`(node:10912) electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.
(Use `Awakened PoE Trade --trace-warnings ...` to show where the warning was created)
[16608:0207/192540.816:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is disabled`
If I press any key everything except AwPoET starts fine.
AwPoET still starts normally if launched directly.
AwPoET v2.15.1
As far as I can tell --trace-warnings does nothing - even logs aren't being populated.

**Comment by SnosMe** [comment]
It's a deprecation warning, not an error. It doesn't affect awakened. For bat file see https://github.com/SnosMe/awakened-poe-trade/issues/114#issuecomment-657186351

**Comment by Netoen** [comment]
I already was starting it like that, the
`start "" "Awakened PoE Trade.exe"` doesn't solve it for me.
Any chance for any other ideas ?

**Comment by SnosMe** [comment]
I know that people somehow break their Windows/Explorer and it stops working as expected.
Here is a solution found in Discord:
> Hey so I wanted to share how I fixed it =)
Running it with bat ALONE would work flawlessly, but when other programs were added, it would produce that problem CMD window
So what I did was, I created a whole new bat file with just APoET inside, and in the original bat, I edited the line to run that new bat
Everything now works as I intended. Sloppy but effective solution

**Comment by Netoen** [comment]
Tried that, sadly, still no luck, neither "start" the new bat nor "call" it.
Is there a possibility maybe some positional argument like "--quiet" for the electron to supress its messages/warnings ?

**Comment by ne0ark** [comment]
Hello, I am running into the same issue. Did anyone find a solution?

**Comment by SnosMe** [comment]
I found another thing that can help you https://www.electronjs.org/docs/latest/api/environment-variables#electron_no_attach_console-windows

**Comment by ne0ark** [comment]
> I found another thing that can help you https://www.electronjs.org/docs/latest/api/environment-variables#electron_no_attach_console-windows

This worked I added the following to the batch script:

```
@echo on
set ELECTRON_NO_ATTACH_CONSOLE=true
```
