### ISSUE TITLE
Archnemesis cheatsheet

### ISSUE THREAD

**Issue by coani** [SnosMe/awakened-poe-trade#526]
Unless GGG listens to the complaints & adds some kind of UI recipes list in the game, it would be really handy to have a recipes cheat list in APT (though i guess it would be a bit more complex than the syndicate cheatsheet :|

**Comment by SnosMe** [comment]
There are a lot of cheatsheets on reddit already. You can edit widget to add image yourself. You can also use Stash Search widget to search in archnem window.
