### ISSUE TITLE
ItemLvL Range wit Cluster Jewels

### ISSUE THREAD

**Issue by RandomHero13** [SnosMe/awakened-poe-trade#527]
Hi,

as cluster jewels have some break points where new notables/tiers become avaible, it would be nice to be able limit searches to those certain itemlvl ranges (1-50, 50-67, 68-74, 75-83, and 84+) and not just "itemlvl of the item or higher".

also sth completely different: 2 checkboxes for empty pre/suffix on all itemtypes would also be great.

thanks

**Comment by SnosMe** [comment]
> also sth completely different: 2 checkboxes for empty pre/suffix on all itemtypes would also be great

It's available under "hidden" toggle. It's there because most of the time, checking it will require you to log in into website due to search complexity.

**Comment by SnosMe** [comment]
Can you link build guides, youtube videos, etc  with recommendation about jewel item level.

**Comment by RandomHero13** [comment]
new notables become avaible on cluster jewels with itemlvl 50, 68, 75 and the small passive breakpoints are 68 and 84.
for example on the minion cluster jewel (it is the same for all clusterjewels) [www.craftofexile.com](https://www.craftofexile.com/?b=177&ob=both&v=d&a=e&l=a&lg=9&bp=y&as=1&req={%22195%22:{%22l%22:68,%22g%22:9},%22215%22:{%22l%22:84,%22g%22:10},%22278%22:{%22l%22:1,%22g%22:5},%22337%22:{%22l%22:1,%22g%22:6},%22415%22:{%22l%22:68,%22g%22:4},%22431%22:{%22l%22:68,%22g%22:1},%22435%22:{%22l%22:50,%22g%22:7},%22441%22:{%22l%22:50,%22g%22:8},%22458%22:{%22l%22:68,%22g%22:2},%22501%22:{%22l%22:75,%22g%22:3}}&bld={}&im={}&ggt=|&ccp={}).
if the itemlevel of the jewel is 64 and i click on the itemlevel in the search it searches for jewels 64 and higher, but in this case it doesnt matter if the jewel is 50 or 67, between those itemlevel nothing changes. so i would recommend (if possible) to have 2 itemlvl selectors for jewels. one for the minimum itemlvl (50 if <= 67, 68 if <= 74, 75 if <= 83 and 84 for 84+) and a maximum itemlevel (49 if < 50, 67 if < 68, 74 if < 75) this will help to search for jewels wich exlode certain possible roles cause of their itemlvl and are therefore more/less expensive.
