### ISSUE TITLE
Disabling the map screenshots

### ISSUE THREAD

**Issue by dodgemeat** [SnosMe/awakened-poe-trade#529]
I may be wrong but i was able to disable the map pictures when the settings were in taskbar but can't find it on overlay settings now.

**Comment by SnosMe** [comment]
This options never existed.
But what is the reason behind this feature request?

**Comment by dodgemeat** [comment]
Sorry my mistake i don't play that much maybe because not all maps have a picture before i thought i disabled them.
Honestly i find it very distracting for me staring the picture over map mods but i think i can get used to it later. 
Sorry to bother with a issue like this.
_(P.S: Decreasing the font size in general also makes the picture smaller which helped me a lot if anyone has the same situation.)_
