### ISSUE TITLE
Show accountName of seller in search results

### ISSUE THREAD

**Issue by thisisakash92** [SnosMe/awakened-poe-trade#53]
Showing the account names of sellers in the search results would help to find price fixing. This is prevalent for bulk listings as well to undercut bots while listing currencies and such.

 Please (╯°□°)╯︵ [accountName: result.listing.account.name](https://github.com/SnosMe/awakened-poe-trade/blob/cc22961ae73d436add904304b1ab2b9f0eb3b32d/src/components/trade/pathofexile-trade.ts#L378) into search results please.

**Comment by SnosMe** [comment]
v0.14
> You can enable the column "Seller" in the settings
