### ISSUE TITLE
Feature Request: Grouping of widgets so they all open with 1 click

### ISSUE THREAD

**Issue by Hillgrove** [SnosMe/awakened-poe-trade#531]
With the new league comes the new ArchEnemies crafting, that some crafty people on Reddit has made a lot of tiered regex widgets for.

Issue is that to present it properly, it's been made with 5 search-widgets and 1 image-widget. All has to be opened or closed individually.

It would be a great QoL if it was possible to group all these 6 widgets into one widget, that would enable/disable them all at once with one click.

https://imgur.com/a/Cw1LxXt

**Comment by SnosMe** [comment]
Related to #413 "Subfolders / Collapsable menu"
