### ISSUE TITLE
Auto set minimum amount on exchange searches

### ISSUE THREAD

**Issue by Sykh** [SnosMe/awakened-poe-trade#532]
Like when i pricecheck my essences and i got more than 10 then search the exchange with minimum 10 so i get the bulk price and not the (bad) single price - that would be awesome!

**Comment by LillieSatou** [comment]
Minimum amount for exchanges is 0.5c - this is controlled by poeninja.

**Comment by SnosMe** [comment]
Is something wrong with this setting? 
![image](https://user-images.githubusercontent.com/4292308/153261688-39a20554-f3b1-4a89-99e5-a38e2c247204.png)
