### ISSUE TITLE
Parsing of expedition logbook faction types (and possibly logbook zones)

### ISSUE THREAD

**Issue by dafillio** [SnosMe/awakened-poe-trade#533]
Hey there,

Currently price checking doesn't seem to support choosing expedition faction types which is the primary method of pricing logbooks. The trade site has pseudo mods available for filtering for these faction types as shown in here:
![image](https://user-images.githubusercontent.com/30607419/153282128-0c2ad7c1-7b2e-4037-a0d0-693b7d271369.png)

The copied data from logbooks contains enough information to match up the factions with the pseudo trade modifier so it would be great to see this implemented in the future. Logbook zones are also given information that matches up with some pseudo modifiers on trade that might be relevant to consider.

Thanks.

**Comment by SnosMe** [comment]
Will be available in the next release.

![image](https://user-images.githubusercontent.com/4292308/155145675-960527fa-29aa-4897-b7ca-4fb72a078827.png)
