### ISSUE TITLE
Legacy modifier value recognition

### ISSUE THREAD

**Issue by patrycos** [SnosMe/awakened-poe-trade#534]
Hi there,

One of the 3.17 updates seems to have introduced an issue with recognizing modifier values outside of the current range as you can see on the screenshots below. I have been pricechecking these very items in late 3.16 and it's been working perfectly fine. Interestingly the issue only seems to occur with unexpected modifier values, and legacy modifiers that don't even exist on non-legacy items anymore (1.99% crit on Bottled Faith) are being recognized just fine.

![pc](https://user-images.githubusercontent.com/51199756/153307241-aabcd9ee-c424-4b5d-b01f-db534680b8a5.png)
![pc5](https://user-images.githubusercontent.com/51199756/153307857-c5fd16c2-4a29-4e6f-a264-bd9347b503ee.png)

**Comment by Mar-vo** [comment]
I have this same problem and it's very annoying

**Comment by patrycos** [comment]
Thanks dude
