### ISSUE TITLE
Can't access settings, key does not exist

### ISSUE THREAD

**Issue by Storm-Engineer** [SnosMe/awakened-poe-trade#536]
I came back to Poe after a break and downloaded the latest version of APT. When trying to access settings I get a popup telling me to press "Shift + BracketRight".

Non-English keyboard layouts do NOT have dedicated bracket keys. On mine (Hungarian) the right bracket is AltGr+G, and Shift+AltGr+G does not work.

Please do not use keys that only exist on English keyboards. :(

Is there at least a way for me to change it to a key that exists?

**Comment by SnosMe** [comment]
The default is and always was Shift+Space, you've changed it. Anyway, you can revert it in folder with logs

![image](https://user-images.githubusercontent.com/4292308/153369658-590e3d47-a5a5-4ee5-a09e-10a7a80482ca.png)

**Comment by Storm-Engineer** [comment]
How could I have changed it to a key that physically doesn't exist? And why on Earth would I have done such a thing?

I had no issue accessing settings in teh last version I've used back in Heist and I have just downloaded this one fresh.

Where is "folder with logs"? I'm using the appimage version on Linux.
