### ISSUE TITLE
Show all attributes, not only the one/two highest ones

### ISSUE THREAD

**Issue by crash0verwr1te** [SnosMe/awakened-poe-trade#537]
Example Strength and Dex are gone.

https://i.imgur.com/YLPcbMy.png

**Comment by patrycos** [comment]
This is also true for some legacy modifiers, for example instant leech on legacy Atziri's Acuity

**Comment by Ricael** [comment]
Same problem here, tried reinstalling. The only thing I notice is this error in logs:

`error [game-config]: Failed to read key. {"key":"5"}`

**Comment by SnosMe** [comment]
@Ricael https://github.com/SnosMe/awakened-poe-trade/issues/493#issuecomment-962249979

**Comment by german3993** [comment]
Another example of the program ignoring stats
[](https://prnt.sc/1JKGBybaynhs)
It's completely ignoring the implicit attributes

**Comment by cronburg** [comment]
Same problem, not picking up dexterity and intelligence in an implicit modifier: https://imgur.com/a/u6k7udB

**Comment by SnosMe** [comment]
https://www.pathofexile.com/forum/view-thread/3247643
