### ISSUE TITLE
[Feature] Cache poe.ninja at start and every X hours

### ISSUE THREAD

**Issue by Pegoth** [SnosMe/awakened-poe-trade#538]
I'm using price check on uniques a lot to check if they are worth bothering with, at first I always check the price range with poe.ninja, and only search for actual price it is worth more than a couple of chaos (to filter out crap).

The ninja price is fairly slow. I think it would be nice to have an option to "download" all poe.ninja prices at start and cache it for use for a few hours at least, that way showing prices on items (with ninja) would be instant.

**Comment by SnosMe** [comment]
Everything is cached already. This delay is artificial and is designed to smooth out the waiting time for the trade request rate limiting.

**Comment by SnosMe** [comment]
If waiting 0.8s is too annoying for you, you'd be better to make item filter more strict.
