### ISSUE TITLE
Can't price check yellow items.

### ISSUE THREAD

**Issue by PluttenHFH** [SnosMe/awakened-poe-trade#540]
Price check only works for uniques and currency items.

**Comment by SnosMe** [comment]
Screenshot/video?

**Comment by old4ever** [comment]
Same issue for me. Seems like the app doesn't capture mods (that can roll?). Same with map mods check, they're simply missing.
My guess that it has something to do with key bindings, although I'm not sure.

Video to demonstrate: https://streamable.com/v3n3h4

**Comment by c3lest1al** [comment]
almost the same problem, its only show unique, so when i press ctr+d next i need to press search or its not showing the price predict, and i dont know its only for me or some one else have this but few price have quastion marks ... i dont see this before.

**Comment by SnosMe** [comment]
@PluttenHFH @c3lest1al I think you guys're talking about rare items price predictions, you can enable them again as explained here https://github.com/SnosMe/awakened-poe-trade/releases/tag/v2.15.0
@c3lest1al What question mark means also explained there.

**Comment by PluttenHFH** [comment]
@SnosMe Sorry I was traveling for work almost immediately after posting this. Thank you for the assist.
