### ISSUE TITLE
A javascript errror in the main process

### ISSUE THREAD

**Issue by Traktirshchik** [SnosMe/awakened-poe-trade#545]
Hi, when trying to start APT have this problem, maybe u now what the reason ? 

![изображение](https://user-images.githubusercontent.com/95852496/154353476-d47cd701-b480-4a66-b81f-2c398af72063.png)

Reinstalling is not helping? yesterday APt was working normally

**Comment by SnosMe** [comment]
You'll need to delete config in the folder with log file. https://snosme.github.io/awakened-poe-trade/faq
