### ISSUE TITLE
Error: net::ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by therealgoodstuff** [SnosMe/awakened-poe-trade#554]
price check with ctrl-D not giving prices
it gives prices for uniques though.
I tried to check the setting but program tells me to open the setting ingame by pressing bracket right, wich doesn´t work.
Several versions before I had no issues at all.
I checked the log.txt : 

error [etc]: Error: Error: net::ERR_NAME_NOT_RESOLVED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:7068)
    at SimpleURLLoaderWrapper.emit (events.js:376:20) {}

in the .js file the correct league is set : 
leagueId | "Archnemesis"

What is the issue ?

**Comment by SnosMe** [comment]
> price check with ctrl-D not giving prices

Screenshot + click "Browser" button there

**Comment by therealgoodstuff** [comment]
screenshot of what excactly ? and where do I find that button pls ?

**Comment by SnosMe** [comment]
Screenshot of where you expect to see prices but doesn't

**Comment by therealgoodstuff** [comment]
it only gives me this in reply : 
Failed to load leaguesRetryBrowser
Verify that the realm is not under maintenance and pathofexile.com is loading.

**Comment by SnosMe** [comment]
so now you know where the "Browser" button is, click it, waht's showing there

**Comment by therealgoodstuff** [comment]
[{"id":"Standard","realm":"pc","url":"https://www.pathofexile.com/ladders/league/Standard","startAt":"2013-01-23T21:00:00Z","endAt":null},{"id":"Hardcore","realm":"pc","url":"https://www.pathofexile.com/ladders/league/Hardcore","startAt":"2013-01-23T21:00:00Z","endAt":null},{"id":"SSF Standard","realm":"pc","url":"https://www.pathofexile.com/ladders/league/SSF+Standard","startAt":"2013-01-23T21:00:00Z","endAt":null},{"id":"SSF Hardcore","realm":"pc","url":"https://www.pathofexile.com/ladders/league/SSF+Hardcore","startAt":"2013-01-23T21:00:00Z","endAt":null},{"id":"Archnemesis","realm":"pc","url":"https://www.pathofexile.com/ladders/league/Archnemesis","startAt":"2022-02-04T19:00:00Z","endAt":"2025-02-04T22:00:00Z"},{"id":"Hardcore Archnemesis","realm":"pc","url":"https://www.pathofexile.com/ladders/league/Hardcore+Archnemesis","startAt":"2022-02-04T19:00:00Z","endAt":"2025-02-04T22:00:00Z"},{"id":"SSF Archnemesis","realm":"pc","url":"https://www.pathofexile.com/ladders/league/SSF+Archnemesis","startAt":"2022-02-04T19:00:00Z","endAt":"2025-02-04T22:00:00Z"},{"id":"SSF Archnemesis HC","realm":"pc","url":"https://www.pathofexile.com/ladders/league/SSF+Archnemesis+HC","startAt":"2022-02-04T19:00:00Z","endAt":"2025-02-04T22:00:00Z"}]

**Comment by SnosMe** [comment]
You can click "Retry" and it should work.
Probably you used VPN or something was wrong with network.

**Comment by therealgoodstuff** [comment]
yes using VPN. "retry" not working for me

**Comment by therealgoodstuff** [comment]
how do I leave a screener here ?

**Comment by therealgoodstuff** [comment]
![awakened](https://user-images.githubusercontent.com/54578544/154864147-cf189d84-2b73-496d-b84b-f1ab7327e978.jpg)

**Comment by therealgoodstuff** [comment]
its not resolved but you closed it.
sure :-/

**Comment by SnosMe** [comment]
> its not resolved but you closed it. sure :-/

I'm not dealing with network directly, electron (chromium) does it.

The only thing actionable within the app is clicking Browser, Retry if you have got captcha from Cloudflare.
