### ISSUE TITLE
Price Check showing only in full screen mode

### ISSUE THREAD

**Issue by xKTPOE** [SnosMe/awakened-poe-trade#555]
Few days ago it was working all fine but now price check doesnt show up in windowed/windowed fullscreen, Overlay is working fine just the price checker is there any way to fix this ?

**Comment by SnosMe** [comment]
Most likely non-English game language, if I'm wrong, attach the log file here.

**Comment by xKTPOE** [comment]
[logs.txt](https://github.com/SnosMe/awakened-poe-trade/files/8110180/logs.txt)

**Comment by SnosMe** [comment]
https://snosme.github.io/awakened-poe-trade/nothing-happens

**Comment by xKTPOE** [comment]
Fixed. Problem was with Radeon Software where the camera shortcut for recording is Ctrl+Alt+C, I changed the camera shortcut and now it is working fine thanks
