### ISSUE TITLE
Possible was banned because of 3.17.10003?

### ISSUE THREAD

**Issue by devnbp** [SnosMe/awakened-poe-trade#557]
Hello, I was banned almost 2 weeks ago (Feb 9, 2022) after updating to 3.17.10003 version, the reason is "Third Party Software", this is the only software I was used. Appeal is still at the "Pending Review" stage. GGG support cant give any information or help. I was created thread on reddit and found at least 4 players with exactly same situation.

I was playing the game, then when I noticed new version with new items support I updated awakened-poe-trade to 3.17.10003 version, then I played for 30min and went afk while the game and awakened-poe-trade was launched, after 1-2 hours I came back and found that my account was banned.

Here is link to the reddit thread https://www.reddit.com/r/pathofexile/comments/son60o/reason_third_party_software/

So, I want to ask the developers if you could investigate your code changes that could lead to this situation for the players?

**Comment by SnosMe** [comment]
I'll quote `@zao`'s response

> APT is about as friendly as you can get for a third party tool. Doesn't hook the game to render (instead showing a window above), the only interaction it does is sending input to make an item copy when you check an item and read the clipboard contents back.
> Don't trust everything others say either, there's quite a bit of people who cheat and try to cover it up.
If you're innocent, it may be unfortunate timing around ban waves, or something sketchy about the rest of your machine or IP.
> It's by design hard to find out the reasons for a ban too, as obscurity is part of the countermeasures to keep the game healthy.

I understand that it's frustrating to sit being banned without getting a response from GGG. All I can say is to be patient.

If something wrong with how app interacts with game client, GGG can ban it from making requests to the website altogether.

> after updating to 3.17.10003 version

Most likely a coincidence. All the changes made are about fine-tuning the search filters, nothing related to interaction with the game.
