### ISSUE TITLE
Item level checking range was changed in .10004 ?

### ISSUE THREAD

**Issue by erocheleau** [SnosMe/awakened-poe-trade#558]
![image](https://user-images.githubusercontent.com/2488155/155623726-16da58dd-2117-4aaf-a965-1c44ec2f934b.png)

I am looking at a cluster jewel ilevel 83, why is it defaulting to ilevel 75-100? I tried to find a setting to check to default on the proper ilvl. Even selected the option to check for exact values of attributes with no luck, it seems to always pick 75-100 as ilevel range?

Am I doing something wrong?

**Comment by SnosMe** [comment]
See #527 and mos iLvl requirements. I might actually add ilvl 78 for small passives, but next breakpoint is 84, not the 83

**Comment by erocheleau** [comment]
Wow I was late to update 😂
Thanks a lot for the quick reply too! I actually thought there were breakpoints at 81 for cluster jewels. 

Does that mean the breakpoints depend on the type of item? Because for some other types of items, the ilevel breakpoints are different than for the cluster jewels: See example of Armor, Tier 2 life roll starts at 81 for example:

![image](https://user-images.githubusercontent.com/2488155/155627125-a0a5f366-5356-439c-8d96-8f270873af3f.png)

**Comment by SnosMe** [comment]
They do, but different mods are more unformally distributed across ilvl 82-86 and players drop a lot of items as well, so it's not critical.

**Comment by erocheleau** [comment]
Alright thanks!
