### ISSUE TITLE
Searching for "Bleeding cannot be inflicted on you" does not work

### ISSUE THREAD

**Issue by sagg** [SnosMe/awakened-poe-trade#561]
Hi there,

this item has the stat `Bleeding cannot be inflicted on you (implicit)`:  
```
Item Class: Rings
Rarity: Unique
Le Heup of All
Iron Ring
--------
Requirements:
Level: 48
--------
Item Level: 80
--------
Bleeding cannot be inflicted on you (implicit)
--------
+26 to all Attributes
24% increased Damage
23% increased Rarity of Items found
+24% to all Elemental Resistances
--------
Existence is infinite
A weave of the living and dead
Beyond the understanding
Of the many mortal threads
--------
Corrupted
```

When trying to run a price check including this stat the following filters are generated:  
<img width="557" alt="Unbenannt" src="https://user-images.githubusercontent.com/2134194/155875802-67b99128-9e8f-403a-8b73-0578ccb03ff4.PNG">

From Awakened PoE-Trade generated Link:  
https://www.pathofexile.com/trade/search/Archnemesis/YoV963kSY

The last filter `Bleeding cannot be inflicted on you` should get passed without the minimal value `100`, currently there are never results cause of that. 

Thanks a lot! :)

**Comment by LillieSatou** [comment]
The filter "Bleeding cannot be inflicted on you" needs to be set to 1, as that uses a boolean value.
0: FALSE (MAX Only, NOT Stat Group only
1: TRUE (MIN Only)
