### ISSUE TITLE
Ctrl + Mousewheel stop working after a few minutes, only reinstall fixes it and only for couple minutes.

### ISSUE THREAD

**Issue by bgsouto** [SnosMe/awakened-poe-trade#564]
I already tried everything. What is wokring right now is to uninstall and reinstall and it works for period of time and then it suddenly stops.

When it stops, also the debug log stops and starts with a weird behavior:

```
debug [shortcuts]: Keydown {"keys":"Ctrl"}
debug [shortcuts]: Keydown {"keys":"Ctrl"}
debug [shortcuts]: Keydown {"keys":"Ctrl"}
debug [shortcuts]: Keydown {"keys":"Ctrl + ArrowLeft"}
debug [shortcuts]: Keyup {"key":"ArrowLeft"}
debug [shortcuts]: Keydown {"keys":"Ctrl"}
verbose [poe-window]: Not focused {}
verbose [shortcuts]: Unregistered Global {}
verbose [poe-window]: Is active {}
verbose [shortcuts]: Registered Global {"total":8}
verbose [poe-window]: Not focused {}
verbose [shortcuts]: Unregistered Global {}
```

The verbose part is when it suddenly stops working. After it stops working, nothing brings back the Ctrl+Mousewheel scrolling back. I tried restarting the pc, turning it off and on. Etc. This behavior started this week, and I didn't installed anything new on my windows 10 gaming pc.

The only way to bring back ctrl+mousewheel tab scrolling is to reinstall Awakened Poe Trade. And even like this, it only works for a brief period of a couple minutes.

Only the scroll stops working (the in game scroll continues fine, when you put the mouse over the stash window). All functions like ctrl+d, and other shortcuts like map check, ctrl+d etc works fines.

**Comment by SnosMe** [comment]
Check that you don't have any `Ctrl + ArrowLeft`, `Ctrl + ArrowRight` hotkey conflicts.

Maybe something to do with running applications on your PC.
