### ISSUE TITLE
Portable app autoupdates to latest version and installs itself

### ISSUE THREAD

**Issue by rwrwrwrwrw** [SnosMe/awakened-poe-trade#57]
(Windows) The portable app on v0.13.0 autodownloaded the latest update and then installed itself. Update checking in portable app mode should probably just notify that an update is available and have a link to the github releases page or something

**Comment by RUSshy** [comment]
same, this needs to be fixed asap..

**Comment by SnosMe** [comment]
v0.15.0
> Revisited updater

Now updater works as intended

**Comment by RUSshy** [comment]
thanks!
