### ISSUE TITLE
Improved defaults while price checking charged compasses

### ISSUE THREAD

**Issue by dafillio** [SnosMe/awakened-poe-trade#573]
Currently price checking a charged compass sets the minimum uses remaining as 1 even if it's higher than that and it sets the item level as 60 which bricks the search entirely until unselected.

Suggested:
1.  Remove selecting ilvl for charged compasses
2. Set "# uses remaining" minimum and maximum to the exact roll on the item itself.

**Comment by SnosMe** [comment]
Duplicate of #560
