### ISSUE TITLE
reduced/increased mana reservation efficiency of skills

### ISSUE THREAD

**Issue by notoaksoy** [SnosMe/awakened-poe-trade#575]
Search parameter for helmet delve mod "reduced mana reservation efficiency of skills" needs to be a **negative number** if possible so that it can show correct search results. 
This causes many items with the delve mod not show in search results where essence and redeemer mods show up.

![reservation1](https://user-images.githubusercontent.com/101754583/158697981-f6510c0b-e95a-4135-b3de-868f1b6c199f.jpg)

![reservation2](https://user-images.githubusercontent.com/101754583/158698009-642da577-50da-4542-ab93-c3683918029a.jpg)

**Comment by SnosMe** [comment]
Guess I need more granularity for "inverted" here

https://github.com/SnosMe/awakened-poe-trade/blob/d020ab8e52c4df55d076bb1dc222e9f283a08265/src/assets/data/interfaces.ts#L23-L28
