### ISSUE TITLE
Error: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by Acsido** [SnosMe/awakened-poe-trade#582]
Hi!
I currently cannot search any items as I get this error every time. Error: Unexpected token < in JSON at position 0. Any solutions?

**Comment by SnosMe** [comment]
![image](https://user-images.githubusercontent.com/4292308/160199077-8443c37d-1516-441d-9c0d-114b5dbacbba.png)

**Comment by Acsido** [comment]
That will do it. Duh. Thanks!
