### ISSUE TITLE
"Load_input_helper [1797]: XkbGetKeyboard failed to locate a valid keyboard!"

### ISSUE THREAD

**Issue by budalmeida** [SnosMe/awakened-poe-trade#584]
Hello
So I'm currently using a Chromebook to play POE. Tries to use the linux already installed on the chrome to run AWK, but couldn't make it.
Running on termirnal,

load_input_helper [1797]: XkbGetKeyboard failed to locate a valid keyboard!

I appreciate any help.

**Comment by SnosMe** [comment]
Are you using Wayland? Only X11 is supported, and even it has bugs.
I don't use linux myself and can't tell what you need to check in your X11 installation.

**Comment by budalmeida** [comment]
Well, im pretty an ignorant about TI stuffs, but manage to find the info using, xdpyinfo, it says I'm using the X.Org version 1.20.8, and version number 11.0
Should I att manually this?

**Comment by najamelan** [comment]
> Are you using Wayland? Only X11 is supported

Is this still the case? Can't get it working and getting this keyboard error.
