### ISSUE TITLE
Can not click on boxes for price check

### ISSUE THREAD

**Issue by whycantiquit** [SnosMe/awakened-poe-trade#59]
I’m unable to modify any of the price check options as I click any where on or off the pop up window it goes into the back ground. Yes this is using ctrl alt D .

**Comment by SnosMe** [comment]
Have you scaled your display?

![image](https://user-images.githubusercontent.com/4292308/77230541-9b6ef880-6b9d-11ea-8f94-db84b3c357b7.png)

**Comment by whycantiquit** [comment]
Looks like that did it. Thanks case closed!
Best price check ever!

**Comment by SnosMe** [comment]
I'll fix scaling in the next release

**Comment by SnosMe** [comment]
v0.15.0
> fixed bugs when display scaling is not 100%
