### ISSUE TITLE
Request: Shortcut to open item on poe.ninja

### ISSUE THREAD

**Issue by Xebtria** [SnosMe/awakened-poe-trade#592]
Title. would be nice to have that if I want to see the latest price development of an item

obviously, not applicable for rares and such, but for uniques, currency etc this would be a nice2have.

**Comment by SnosMe** [comment]
![image](https://user-images.githubusercontent.com/4292308/172954195-9e7b2939-d35c-400e-90a2-aef03940e697.png)

You'll be able to do it by clicking on graph
