### ISSUE TITLE
Stuttering

### ISSUE THREAD

**Issue by tonpix** [SnosMe/awakened-poe-trade#595]
Game gets micro stuttering when I'm playing and tool is working in background. Closing it makes micro stuttering fully gone.

Not sure what I could do to alleviate it, nor what info you would need to troubleshoot.

**Comment by tonpix** [comment]
Actually, I've opened performance graphs ingame and found interesting difference, there are regular gpu spikes with tool in background.

With tool working in background:
![image](https://user-images.githubusercontent.com/13473971/168188824-b2cb8541-9f99-4e91-966d-c2dd6e79db39.png)

Without:
![image](https://user-images.githubusercontent.com/13473971/168188987-8eaa23a7-b88b-419c-a2f3-c93a8d68cb2a.png)

**Comment by SnosMe** [comment]
Mine is ok
![image](https://user-images.githubusercontent.com/4292308/168267140-455110bd-bd0d-4bfd-9822-82ecf9b1415e.png)

Other than https://github.com/SnosMe/awakened-poe-trade/issues/415#issuecomment-864084650 I have no suggestions for you.
