### ISSUE TITLE
Error: ENOENT

### ISSUE THREAD

**Issue by Boladoguda** [SnosMe/awakened-poe-trade#596]
![image](https://user-images.githubusercontent.com/105543750/168421784-06ff4e09-d1a9-4425-b23d-f41f4d512fac.png)

after installing the poe trade it shows this message and i can't open it
how do i fix it?

**Comment by SnosMe** [comment]
I tested installation in a clean environment (Windows Sandbox) with no errors.
I have no suggestions other than to reinstall and disable the antivirus.

**Comment by Krytyk88** [comment]
have same issiue, nothing helps...
