### ISSUE TITLE
elemental damage modifiers not working

### ISSUE THREAD

**Issue by sisco1986** [SnosMe/awakened-poe-trade#598]
anything related to EDPS is not showing on the item when you price check

**Comment by SnosMe** [comment]
Please paste item text here. Have you clicked the "hidden" switch?

**Comment by sisco1986** [comment]
Item Class: Thrusting One Hand Swords
Rarity: Rare
Golem Razor
Dragonbone Rapier
--------
One Handed Sword
Physical Damage: 38-117 (augmented)
Elemental Damage: 66-118 (augmented), 6-131 (augmented)
Critical Strike Chance: 6.38% (augmented)
Attacks per Second: 1.67 (augmented)
Weapon Range: 14
--------
Requirements:
Level: 58
Dex: 185
--------
Sockets: G 
--------
Item Level: 77
--------
+25% to Global Critical Strike Multiplier (implicit)
--------
Adds 19 to 42 Physical Damage
Adds 66 to 118 Cold Damage
Adds 6 to 131 Lightning Damage
11% increased Attack Speed
16% increased Critical Strike Chance
Attacks have 30% chance to cause Bleeding
46% increased Damage with Bleeding
--------

looks like this https://imgur.com/a/QYeIbB9

the mods are not even showing on the item search if i press the trade button https://imgur.com/a/F17PF5h

**Comment by SnosMe** [comment]
As I said, it's under "hidden" toggle. 

You don't even have to price check it, bleed+ele dmg don't complement each other.

![image](https://user-images.githubusercontent.com/4292308/168498636-b606954d-fd0f-4fad-a608-a9999c601c98.png)

I will gladly tweak the logic if you show me a real Item on which the current logic doesn't work the best.
