### ISSUE TITLE
Stash Tab Scrolling

### ISSUE THREAD

**Issue by SahalMD** [SnosMe/awakened-poe-trade#60]
Scrolling though stash tabs always skips a tab unless I mouse over my stash when I scroll and I can't seem to disable it. EG. instead of going tab 1 > 2 > 3, it goes tab 1 > 3 > 5 etc.

**Comment by SnosMe** [comment]
v0.15.0

> fixed bugs when display scaling is not 100%

**Comment by SnosMe** [comment]
If you still have issues with v0.15.0, make sure that you do not run PoE-TradeMacro at the same time.
