### ISSUE TITLE
Failed to load league

### ISSUE THREAD

**Issue by Alderionn** [SnosMe/awakened-poe-trade#601]
it worked on first day of the league and now only get this error, if i click to open browser he get and error
![bugawa](https://user-images.githubusercontent.com/92063574/168477812-ecaa1876-e966-4de9-b96a-7692b072a2d3.jpg)

**Comment by SnosMe** [comment]
Just click "Retry"

**Comment by Alderionn** [comment]
yes, i´ve done 999 times

**Comment by imbotnoob** [comment]
{
    "id": "Standard",
    "realm": "pc",
    "url": "https://www.pathofexile.com/ladders/league/Standard",
    "startAt": "2013-01-23T21:00:00Z",
    "endAt": null
  },
  {
    "id": "Hardcore",
    "realm": "pc",
    "url": "https://www.pathofexile.com/ladders/league/Hardcore",
    "startAt": "2013-01-23T21:00:00Z",
    "endAt": null
  },
  {
    "id": "Solo Self-Found",
    "realm": "pc",
    "url": "https://www.pathofexile.com/ladders/league/Solo+Self-Found",
    "startAt": "2013-01-23T21:00:00Z",
    "endAt": null
  },
  {
    "id": "Hardcore SSF",
    "realm": "pc",
    "url": "https://www.pathofexile.com/ladders/league/Hardcore+SSF",
    "startAt": "2013-01-23T21:00:00Z",
    "endAt": null
  },
  {
    "id": "Ruthless",
    "realm": "pc",
    "url": "https://www.pathofexile.com/ladders/league/Ruthless",
    "startAt": null,
    "endAt": null
  },
  {
    "id": "Hardcore Ruthless",
    "realm": "pc",
    "url": "https://www.pathofexile.com/ladders/league/Hardcore+Ruthless",
    "startAt": null,
    "endAt": null
  },
  {
    "id": "SSF Ruthless",
    "realm": "pc",
    "url": "https://www.pathofexile.com/ladders/league/SSF+Ruthless",
    "startAt": null,
    "endAt": null
  },
  {
    "id": "Hardcore SSF Ruthless",
    "realm": "pc",
    "url": "https://www.pathofexile.com/ladders/league/Hardcore+SSF+Ruthless",
    "startAt": null,
    "endAt": null
  },
  {
    "id": "Settlers",
    "realm": "pc",
    "url": "https://www.pathofexile.com/ladders/league/Settlers",
    "startAt": "2024-07-26T20:00:00Z",
    "endAt": null
  },
  {
    "id": "Hardcore Settlers",
    "realm": "pc",
    "url": "https://www.pathofexile.com/ladders/league/Hardcore+Settlers",
    "startAt": "2024-07-26T20:00:00Z",
    "endAt": null
  },
  {
    "id": "SSF Settlers",
    "realm": "pc",
    "url": "https://www.pathofexile.com/ladders/league/SSF+Settlers",
    "startAt": "2024-07-26T20:00:00Z",
    "endAt": null
  },
  {
    "id": "HC SSF Settlers",
    "realm": "pc",
    "url": "https://www.pathofexile.com/ladders/league/HC+SSF+Settlers",
    "startAt": "2024-07-26T20:00:00Z",
    "endAt": null
  },
  {
    "id": "Ruthless Settlers",
    "realm": "pc",
    "url": "https://www.pathofexile.com/ladders/league/Ruthless+Settlers",
    "startAt": "2024-07-26T20:00:00Z",
    "endAt": null
  },
  {
    "id": "HC Ruthless Settlers",
    "realm": "pc",
    "url": "https://www.pathofexile.com/ladders/league/HC+Ruthless+Settlers",
    "startAt": "2024-07-26T20:00:00Z",
    "endAt": null
  },
  {
    "id": "SSF R Settlers",
    "realm": "pc",
    "url": "https://www.pathofexile.com/ladders/league/SSF+R+Settlers",
    "startAt": "2024-07-26T20:00:00Z",
    "endAt": null
  },
  {
    "id": "HC SSF R Settlers",
    "realm": "pc",
    "url": "https://www.pathofexile.com/ladders/league/HC+SSF+R+Settlers",
    "startAt": "2024-07-26T20:00:00Z",
    "endAt": null
  }
] 


this is what i get and same problem here
