### ISSUE TITLE
Replica search button is not toggleble

### ISSUE THREAD

**Issue by carloverso** [SnosMe/awakened-poe-trade#606]
Is it possible to use it or its under development?
I understand what WIP means, but perhaps it could be greyed out or not there at all for now.

https://i.imgur.com/SK9neeW.png

I'm happy to test it for you.

**Comment by SnosMe** [comment]
Yeah, it's not available even for preview 😄

**Comment by SnosMe** [comment]
Yes, I'd like to see

**Comment by SnosMe** [comment]
You can use it now https://github.com/SnosMe/awakened-poe-trade/releases/tag/v3.18.10004

still waiting for a 

> couple suggestions

😄
