### ISSUE TITLE
Currency price check error

### ISSUE THREAD

**Issue by zmerdev** [SnosMe/awakened-poe-trade#607]
bulk exchange items are throwing an error on price check. 

Temporarily unavailable, please use the new exchange engine.

![image](https://user-images.githubusercontent.com/89794264/168630404-5647b33b-c71f-42f2-8286-0ac27e2abd87.png)

**Comment by Xpatro** [comment]
I just recived the update, Cannot find this "New Exchange" to make the ADDON work anymore... completely broke for me, Panic!

**Comment by KonstantinMochalov** [comment]
![image](https://user-images.githubusercontent.com/22779801/168666098-0bd81e5f-abb9-47d4-b86f-2cc109d8f09a.png)
Legacy version doesn't work on site either.

**Comment by netoprax** [comment]
I am receiving the same error. Is there a solution for this?
