### ISSUE TITLE
New Exchange Engine

### ISSUE THREAD

**Issue by guivc** [SnosMe/awakened-poe-trade#609]
![image](https://user-images.githubusercontent.com/25881395/168697805-262ffea4-7340-4105-9df8-b65342815b20.png)
```
Trade site request failed
Error: Temporarily Unavailable; Please use the New Exchange Engine
```

Still not supported or I did something wrong here. How should I proceed?

**Comment by BunFrith** [comment]
same issue

**Comment by SnosMe** [comment]
#607
