### ISSUE TITLE
Error: Temporarily unavailable; Please use the new exchange engine

### ISSUE THREAD

**Issue by leet0rz** [SnosMe/awakened-poe-trade#611]
Is there a fix for this?
![JhqBRQZ 1](https://user-images.githubusercontent.com/29175192/168706384-531f6a6e-94f0-4fac-b202-4a6505becfbc.png)

**Comment by dimon222** [comment]
#607

**Comment by leet0rz** [comment]
> #607

![s5ByK6Y 1](https://user-images.githubusercontent.com/29175192/168731066-32f06bf2-af09-4d4b-9e34-9740debc7ea2.png)
Same as in that thread

**Comment by thisVioletHydra** [comment]
![image](https://user-images.githubusercontent.com/11839238/168739119-8a374b0c-9fff-4557-adda-baec5f4eda51.png)

**Comment by Discipol** [comment]
This is happening for me nonstop

**Comment by githubhao0705** [comment]
same error😂

**Comment by paszu** [comment]
![image](https://user-images.githubusercontent.com/21226488/168791820-6e8a2d17-547b-415e-a031-f5427c5a65ac.png)

Sadly the same

**Comment by nanitll** [comment]
The same :C

**Comment by jakichanka** [comment]
![image](https://user-images.githubusercontent.com/43546272/168837494-7f7b243d-21e4-4d25-8ba0-833d4d381313.png)

**Comment by Pantera3370** [comment]
> Is there a fix for this? ![JhqBRQZ 1](https://user-images.githubusercontent.com/29175192/168706384-531f6a6e-94f0-4fac-b202-4a6505becfbc.png)

same problem

**Comment by LMOspaceace** [comment]
same issue here. thought it was something i changed but seeing this lets me know it's not lol

**Comment by Yamzball** [comment]
same here :(

**Comment by msoturn** [comment]
This appears to affect any items that can be bought in bulk (currency, fragments, maps, etc) and not other items.

**Comment by helpppp** [comment]
{"query":{"status":{"option":"online"},"have":["chaos"],"want":["chrome"],"minimum":1222,"fulfillable":null,"collapse":true,"account":"oh"},"sort":{"have":"asc"},"engine":"new"}


Add query  -> "engine":"new" 

new json query  modify 
put this in and it will work
from Korea  ^^

**Comment by msoturn** [comment]
> {"query":{"status":{"option":"online"},"have":["chaos"],"want":["chrome"],"minimum":1222,"fulfillable":null,"collapse":true,"account":"oh"},"sort":{"have":"asc"},"engine":"new"}
> 
> Add query -> "engine":"new"
> 
> new json query modify put this in and it will work

If you check for update on your taskbar, the issue seems to be fixed in an update.

**Comment by Nickakanickiam** [comment]
Not for me.

**Comment by SnosMe** [comment]
This has been fixed.

**Comment by nebucadneza** [comment]
had same issue when i updated.
uninstalled and reinstalled fresh and now the issue is gone
