### ISSUE TITLE
Add button "Quit/Exit"

### ISSUE THREAD

**Issue by Divertisment** [SnosMe/awakened-poe-trade#617]
![image](https://user-images.githubusercontent.com/5182065/169161132-62070a55-34d1-407e-965b-b1f5b2d525b3.png)
how to get out (quit/exit) of your wonderful program.
For example, in order to get an update.
The only option that I know of is to kill the process through the task manager. but in this case, the update will not download, since the program will not know that it has been released.
![image](https://user-images.githubusercontent.com/5182065/169162333-303bad79-c4c7-46d7-b686-c5461a31216a.png)

**Comment by wlastas** [comment]
> you could right click on the icon is the systray (if you use windows)
yes i am using windows but this popup menu is never called. It just doesn't pop up and I don't see it at all.
Look - the mouse is over the icon of your application, I'm in the game at this time
![image](https://user-images.githubusercontent.com/5182065/169188632-5ebc9995-f19c-4e3e-b3c6-cf79eaccd532.png)

**Comment by SnosMe** [comment]
Not specific to Awakaned #265, but a reasonable suggestion.

**Comment by wlastas** [comment]
> Not specific to Awakaned #265, but a reasonable suggestion.

O, bogi spustilis' s Olimpa! Privet YA izuchil prededushchiye predlozheniya k kotorym ty priatachil moye. Teper' ya prosto predlagayu sdublirovat' vse optsii, sgurippirovane v menyu, dostupnom po pravomu kliku po ikonke v sistemnom treye(kartinka vyshe), v soderzhimoye otdel'noy dopolnitel'noy tab na vniutriigrovoy setting paneli. Tak my poluchim dostup ko vsem im, a ne tol'ko k tak neobkhodimoy "Vykhod"
Show more
388 / 5,000
Translation results
Oh, the gods have descended from Olympus! Hey
I studied the previous sentences to which you attached mine.
Now I just suggest to duplicate all the options grouped in the menu available by right clicking on the system tray icon (picture above),
into the contents of a separate additional tab on the in-game setting panel.
This will give us access to all of them, not just the much-needed "Exit/Quit"

**Comment by kevindevm** [comment]
@wlastas in windows you can use win+d to minimize all apps, the downside if u use multi monitor then all other apps will be minimized

**Comment by wlastas** [comment]
> @wlastas in windows you can use win+d to minimize all apps, the downside if u use multi monitor then all other apps will be minimized

 I tested  win+d  - it works great - I will definitely use it in the future - thanks
