### ISSUE TITLE
Can not Price check, shoots on screen confetti

### ISSUE THREAD

**Issue by sadPandaIsSad** [SnosMe/awakened-poe-trade#620]
Hi, so I am able to access all other functionalities of Awakened PoE Trade(APT), but whenever I attempt to price check an item, my screen just shoots on screen confetti from the bottom two corners. I believe I followed the proper process to record the logs of the interaction, so attached is said file. Any help with this issue would be greatly appreciated
[logs.txt](https://github.com/SnosMe/awakened-poe-trade/files/8735138/logs.txt)

![image](https://user-images.githubusercontent.com/4292308/169514320-a9669162-7e84-485b-82ad-ce9eb5a372cb.png)

**Comment by SnosMe** [comment]
You need to close Loom, or change/unbind Ctrl+Alt+C in it.

The reason why APT uses this hotkey too is described here  https://snosme.github.io/awakened-poe-trade/nothing-happens

**Comment by sadPandaIsSad** [comment]
Thanks so much!
