### ISSUE TITLE
Price Check dont work

### ISSUE THREAD

**Issue by Br00Kz** [SnosMe/awakened-poe-trade#622]
Hey I cant use the Price check. If I press F5 for example that works or Shift+Space for settings. Im on Borderless Window mode.

**Comment by SnosMe** [comment]
Can't help without you being more specific https://snosme.github.io/awakened-poe-trade/issues

**Comment by SnosMe** [comment]
> I checked the Logs and it says : warn [clipboard]: No item text found. {"text":"Failed to register a shortcut. It is alr"}

Well, now you know that you need to change that hotkey in Awakened Trade or close another application that uses it.
