### ISSUE TITLE
Flickering in Shadowplay Recordings

### ISSUE THREAD

**Issue by Gikona** [SnosMe/awakened-poe-trade#628]
Seems like the overlay, or how it's rendered is causing Shadowplay to bug out and flicker rapidly in any recordings.

The only ways I found to fix it is to completely quit Awakened Trade OR turn off desktop recording in shadowplay, and I very much prefer not to do either as sometimes shadowplay doesn't capture everything I want it to in "game-only" mode.

I've tried both Hardware Acceleration enabled and disabled with no use. No idea about any other debugging steps I could take.

How it looks: https://www.youtube.com/watch?v=euuNyEAKS5g

**Comment by SnosMe** [comment]
Seems to be local to your PC.

DX12
https://user-images.githubusercontent.com/4292308/169886160-10e346ae-e24e-49f2-85fd-a57f49738d56.mp4

Vulkan
https://user-images.githubusercontent.com/4292308/169886199-c2f99fc0-a2f3-461a-958a-be0fa30cfa17.mp4
