### ISSUE TITLE
Pricecheck does not offer me to check modifiers

### ISSUE THREAD

**Issue by BadZooka** [SnosMe/awakened-poe-trade#632]
Hey, sorry if this is out of the blue or not where such things belong to.

I cannot choose modifiers on any items when price checking. I didn't play for about a year, but last time I was active I had no issues whatsoever. Any idea how to fix this?

![POE Trade modifiers missing](https://user-images.githubusercontent.com/106256915/170283881-0f15f7e4-9b41-4960-87e7-06437f5480ea.png)

**Comment by SnosMe** [comment]
https://github.com/SnosMe/awakened-poe-trade/issues/493#issuecomment-962249979
