### ISSUE TITLE
Overlay not opening on Card tab (BUG)

### ISSUE THREAD

**Issue by Tricky-Ricky** [SnosMe/awakened-poe-trade#636]
Overlay works on the tabs I have currently, except will not open on the card tab.

To price check a card, I have to drag it to my Inventory, then use the hotkey to open the overlay.

I would expect it to work directly from the card tab

**Comment by SnosMe** [comment]
https://snosme.github.io/awakened-poe-trade/faq

> I can’t price check items in Divination Card stash tab.
> I can’t price check rewards in Curio Display room (Heist Blueprints).
> I can’t check modifiers of the maps proposed by Kirac.
> 
> Yes, you can’t. The game doesn’t copy anything to clipboard when pressing Ctrl + C in these places. And as mentioned in the [Quick Start](https://snosme.github.io/awakened-poe-trade/quick-start), the whole thing how app works based on text of item in clipboard.
> 
> Regarding Divination Card stash tab, you can use another 3rd-party apps that price check your stash tabs (e.g. [Exilence Next](https://github.com/viktorgullmark/exilence-next/#readme))
