### ISSUE TITLE
Flickering when overlay is open

### ISSUE THREAD

**Issue by S-Duchev** [SnosMe/awakened-poe-trade#637]
Since the start of the league I've been having this issue where the screen flicker every time the overlay is open. You can see it here in this [recording](https://youtu.be/Ul_MifYsAEg). This only happens with Awakened and it seems to only happen when using DX11 or Vulkan renderers. It doesn't happen on DX12, however I get better performance on Vulkan so I'd like to continue using that if possible.

My GPU is 5600 XT using the latest drivers.

**Comment by SnosMe** [comment]
It has something to do with transparent window composition by Windows, I would assume, 
but I don't have any knobs for that.

Try disabling/enabling HW acceleration, but I doubt it will do anything.
![image](https://user-images.githubusercontent.com/4292308/170666883-9c3183a5-dd57-4e59-ab91-e9f0c6aa0cb1.png)

**Comment by S-Duchev** [comment]
Huh. Enabling that setting actually reduced the flickering a decent amount. It still happens but it's not nearly as bad as in the video. Thanks.

**Comment by TesterNA** [comment]
@SnosMe no more this feature? cause i also got this issue for dx11 renderer

**Comment by SnosMe** [comment]
No, it's force disabled
