### ISSUE TITLE
Do custom commands have /sleep?

### ISSUE THREAD

**Issue by Bannedmyself** [SnosMe/awakened-poe-trade#64]
Seems like i can't spam for example, ctrl + 3 for /oos, maybe it works 1 out of 4-5 presses, pretty annoying as ive died to this issue, i don't know why it happens

I've tried putting /oos into another hotkey and the problem is still there.

**Comment by SnosMe** [comment]
There is no sleep, but you need to press all buttons again (Ctrl + 3), not just holding Ctrl and then 3, 3, 3, 3...
