### ISSUE TITLE
Helm lookup uses wrong "Your Cold Damage Can Ignite"

### ISSUE THREAD

**Issue by xanthics** [SnosMe/awakened-poe-trade#640]
Using this helm it generates [this search](https://www.pathofexile.com/trade/search/Sentinel/EberKpBf5) which will return no results unless you change `Your Cold Damage Can Ignite` to the [second entry](https://www.pathofexile.com/trade/search/Sentinel/Ody3ygaCE)

![image](https://user-images.githubusercontent.com/3137623/170837706-5a7ebd76-cd68-4bc0-b73e-e14539a2a30d.png)

```
Item Class: Helmets
Rarity: Rare
Horror Crest
Ursine Pelt
--------
Quality: +5% (augmented)
Evasion Rating: 501 (augmented)
--------
Requirements:
Level: 65
Dex: 114
--------
Sockets: G-G R-G 
--------
Item Level: 81
--------
Arc Chains an additional time (enchant)
--------
+1 to Level of Socketed Minion Gems
+34 to Dexterity
+174 to Evasion Rating
+90 to maximum Life
+33% to Fire Resistance
Your Cold Damage can Ignite
```

**Comment by SnosMe** [comment]
This Sentinel specific Mod was not in trade at the time data that comes with the app was generated. Fixed in 3.18.10003
