### ISSUE TITLE
Veiled Persons arent selectable anymore

### ISSUE THREAD

**Issue by Sykh** [SnosMe/awakened-poe-trade#643]
I am pretty sure you had a dropdown on veiled items where you could select "veiled by xxx" because you couldn't read it from the item itself which was super helpfull...but its not there anymore.

**Comment by SnosMe** [comment]
You just don't have to do it manually anymore.

Example ring
![image](https://user-images.githubusercontent.com/4292308/170956279-0d6f2b67-8e97-4ceb-aabe-d533aa69b4cc.png)

Correctly selects stat on trade site
![image](https://user-images.githubusercontent.com/4292308/170956447-cff70264-22a2-4c3c-abf7-044dd4e833bb.png)

**Comment by Sykh** [comment]
Ah my bad, could you state somewhere in the search that its looking for that exact mod? I thought it just got lost - thanks!
