### ISSUE TITLE
Windows Defender - Threat Blocked

### ISSUE THREAD

**Issue by anileger** [SnosMe/awakened-poe-trade#65]
Today Windows Defender starts to remove .exe file because of:

Thread Detected : Trojan:Win32/Fuery.C!cl
Date : 31/03/2020 13:22
Category : Trojan
Details: This program is dangerous and executes commands from an attacker.

**Comment by xAaeEx** [comment]
I got the same issue when trying to execute the installer.

**Comment by SnosMe** [comment]
Guys, when there is a bug in tool you create issue here.
When there is a bug in AV you go to the vendor and report it to him.

What you are expecting me to do? All in your hands, report that threat is false positive, whitelist file, and that's all.

**Comment by xAaeEx** [comment]
Don't need to be so sensitive, as a programmer it's the job of the programmer to hear about bugs. 
And this is a bug, because your setup signature is being treated as a Malware.

**Comment by anileger** [comment]
> Guys, when there is a bug in tool you create issue here.
> When there is a bug in AV you go to the vendor and report it to him.
> 
> What you are expecting me to do? All in your hands, report that threat is false positive, whitelist file, and that's all.

I do not blame you dude. It Just happened and I shared this experience with others.

**Comment by SnosMe** [comment]
Fixed in v0.17 thanks to @morguldir
