### ISSUE TITLE
3.18.10003 broke flask enchantment search

### ISSUE THREAD

**Issue by erocheleau** [SnosMe/awakened-poe-trade#650]
I can no longer search for the Enkindling Orb modifiers 
![image](https://user-images.githubusercontent.com/2488155/171081087-95b8c368-0503-464a-8b14-ee08beef364b.png)

**Comment by SnosMe** [comment]
I'll put enchant for flasks in hidden rather than removing completely

**Comment by erocheleau** [comment]
Thanks a lot! Just FYI, this flask, there's only one diamond flask with both a duration roll and a duration enkindling mod right now and it's set to 100c, even just the enkindling Diamond flask is worth quite a bit because of the weighting from enkindling orb. I think it's because a lot of people are playing Flicker with soulthirst to boss rush and need flasks that last as long as possible.
It's about 15% to roll increased duration, and Enkindling orbs are worth ~1c:
![image](https://user-images.githubusercontent.com/2488155/171176649-0fa41e87-1ee0-441f-9ece-0de969e893e5.png)


Putting them in hidden is perfect!

**Comment by E2A4E789A3DCC7236FF998692ADE60E2** [comment]
The latest change also removed all the crafted flask mods from available mods list. 
This tool supposed to be used for price check but it feels like the changes going is some wrong direction.

**Comment by SnosMe** [comment]
@E2A4E789A3DCC7236FF998692ADE60E2 can you paste Ctrl+Alt+C of that flask here

**Comment by E2A4E789A3DCC7236FF998692ADE60E2** [comment]
```
Item Class: Mana Flasks
Rarity: Magic
Enduring Eternal Mana Flask of the Order
--------
Quality: +20% (augmented)
Recovers 734 (augmented) Mana over 7 Seconds
Consumes 8 of 42 Charges on use
Currently has 0 Charges
--------
Requirements:
Level: 65 (unmet)
--------
Item Level: 84
--------
{ Prefix Modifier "Enduring" (Tier: 1) — Mana }
66% reduced Amount Recovered
Flask effect is not removed when Unreserved Mana is Filled
Flask effect does not Queue
(The duration of this flask's effect will still expire while other flask effects are active, even if they are from the same flask)
{ Master Crafted Suffix Modifier "of the Order" — Mana }
25(25-20)% reduced Mana Cost of Skills during Flask Effect (crafted)
--------
Right click to drink. Can only hold charges while in belt. Refills as you kill monsters.
--------
Note: ~price 72 chaos

```

**Comment by SnosMe** [comment]
Will be in next release

![image](https://user-images.githubusercontent.com/4292308/171425429-5f30456e-7f2d-4681-af22-db9359167d87.png)

![image](https://user-images.githubusercontent.com/4292308/171424315-4d79863d-c35f-4311-abd5-cb85d9cd690a.png)

![image](https://user-images.githubusercontent.com/4292308/171424633-09dc529a-fd38-4ad8-b5dc-958f5c2a354f.png)
