### ISSUE TITLE
chat commands not working properly

### ISSUE THREAD

**Issue by oyasumidoge** [SnosMe/awakened-poe-trade#653]
my chat commands (kick, tradewith, invite etc) do not work. only /whisper @last works
i cleared my clipboard history and reinstalled the awakened poe but still the same issue.

**Comment by SnosMe** [comment]
Commands screenshot?

**Comment by oyasumidoge** [comment]
![image](https://user-images.githubusercontent.com/106823052/171876491-62892c80-59e0-4354-8207-e9351cfb5937.png)
when i try to use other commands, it prompts the chat with /kick for example but without any nickname

**Comment by oyasumidoge** [comment]
Home and Del keys are working properly, and it gets the command from
clipboard alright but does not get @last. ***@***.*** only works in /whisper and
not other commands)
