### ISSUE TITLE
Ctrl-D / Ctrl-Alt-D / Alt-W are not working because of hotkey on Windows desktop

### ISSUE THREAD

**Issue by samot1** [SnosMe/awakened-poe-trade#654]
I just installed awakened-poe-trade, but Ctrl-D was not working although all the requirements (English, Windowed Fullscreen) etc. were met.

After about an hour testing (different hotkeys, closing most of my apps ...) I found the problem:
I have (since decades) set Ctrl-Alt-C as hotkey for the Total Commander icon on my desktop (open the properties of the desktop icon and set a hotkey, I guess any other lnk-file on the desktop would work too). 

I have absolut no idea why, but it seems to interact somehow with PoE trade. After removing the hotkey Ctrl-D is working now...

PS: I found the solution, because sometimes Total Commander started when I pressed Ctrl-Alt-D (althogh the hotkey for Total Commander was set to Ctrl-Alt-C)

**Comment by SnosMe** [comment]
> I have absolut no idea why, but it seems to interact somehow with PoE trade.

It does https://snosme.github.io/awakened-poe-trade/nothing-happens
