### ISSUE TITLE
Can't search shield crush in gem search

### ISSUE THREAD

**Issue by jwoo2023** [SnosMe/awakened-poe-trade#656]
![image](https://user-images.githubusercontent.com/79891380/171995900-07bbe1bb-239c-4ca7-9a1a-bc7fa0c738e3.png)
![image](https://user-images.githubusercontent.com/79891380/171995913-001b85a6-d709-41bd-ba9c-49f9e3c37d46.png)

**Comment by SnosMe** [comment]
#625
