### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by Applefaerie** [SnosMe/awakened-poe-trade#659]
"Trade site request failed. Error: Internal error"

I have deleted app data + reinstlaled, uninstalled/deleted app data + restarted comp + reinstalled. Opening it before and after running the game. 

I can use it to price check currency/bulk items, as well as specific items (unique). The trade site is working in my browser. Using the in-app trade page also returns the same error. So it appears that regular drops cannot be searched.

It worked fine yesterday. I searched reddit but was unable to locate anyone else posting this.

I am running DX11, windowed full screen. Windows 10. Running as admin in both game and APT. Standard league. 

The log file is as follows, after relaunch and search of a single item for clarity.
[logs.txt](https://github.com/SnosMe/awakened-poe-trade/files/8846779/logs.txt)

**Comment by SnosMe** [comment]
https://github.com/SnosMe/awakened-poe-trade/issues/658#issuecomment-1147753921
