### ISSUE TITLE
Search error Trade Site Request Failed Error: Internal Error

### ISSUE THREAD

**Issue by Sgar465** [SnosMe/awakened-poe-trade#660]
This did work fine a few days ago but now there are issues. If I search for bulk Items it seems to work and resolves to a list or whatever currency is chosen. If I do a search for a any hardware the list of attributes comes up fine but when the search button is selected it immediately puts the error up no matter what is selected. If I follow the browser button the search still fails.  If while in the integrated browser I delete all the attributes and the count just leaving the item type and general attributes the browser will then provide a list of items with no error. I have uninstalled and reinstalled twice removing all files and downloading the installation, ran as administrator.

any help would be appreciated
thanks

![first](https://user-images.githubusercontent.com/107004589/172255300-d7da786c-3910-4e79-b2e2-67f412a1d3e5.GIF)
![second](https://user-images.githubusercontent.com/107004589/172255302-3a5008b0-d21b-492e-a137-17ffe2770ecc.GIF)
![third](https://user-images.githubusercontent.com/107004589/172255304-3961b654-a2b0-4f7c-a7ec-a42fda4079ee.GIF)

**Comment by SnosMe** [comment]
#658
