### ISSUE TITLE
+# to all Attributes misses rest pseudo attributes

### ISSUE THREAD

**Issue by message** [SnosMe/awakened-poe-trade#669]
`+# to all Attributes` is mashed with single pseudo `+# to Intelligence` ignoring `+# to Dexterity` and `+# to Strength`.

![image](https://user-images.githubusercontent.com/492026/174504198-d397c684-19aa-4523-969f-446590ea00fe.png)

Missing `+33 to Dexterity` and `+33 to Strength` here:

![image](https://user-images.githubusercontent.com/492026/174504270-ed59755d-eb9b-412b-b32d-e3b34885bb88.png)

```
Item Class: Amulets
Rarity: Rare
Oblivion Rosary
Lapis Amulet
--------
Requirements:
Level: 68
--------
Item Level: 85
--------
{ Implicit Modifier — Attribute }
+28(20-30) to Intelligence (implicit)
--------
{ Prefix Modifier "Gentian" (Tier: 6) — Mana }
+50(50-54) to maximum Mana
{ Prefix Modifier "Rotund" (Tier: 3) — Life }
+69(60-69) to maximum Life
{ Suffix Modifier "of the Multiverse" (Tier: 1) — Attribute }
+33(33-35) to all Attributes
(Attributes are Strength, Dexterity, and Intelligence)
{ Suffix Modifier "of Plunder" (Tier: 4) }
7(6-10)% increased Rarity of Items found
```

**Comment by SnosMe** [comment]
They should be under "hidden" toggle
