### ISSUE TITLE
Items like Ventor's gamble are not filtered correctly by default on price checks

### ISSUE THREAD

**Issue by ReiMasa** [SnosMe/awakened-poe-trade#672]
I've noticed when doing certain items the stats that are in the right side of the panel are completely wrong by default and I have to set the stats to my item specifically.

![mVQbtSD](https://user-images.githubusercontent.com/13143101/175778436-cfa1927f-da54-4646-ab82-c3fb4e040f22.png)

If I click the checkmark to filter each stat, it will filter it based on those completely incorrect stats on the right instead of the actual stats of my item on the left. This causes insanely wrong price checks in some cases. It is not clear what determines these completely incorrect stats on the right.

**Comment by SnosMe** [comment]
You can change it in settings 

![image](https://user-images.githubusercontent.com/4292308/175778628-325836c7-e7f9-4b89-a94a-c8d6e2313c66.png)
