### ISSUE TITLE
Heist Contracts aren't working anymore

### ISSUE THREAD

**Issue by Sykh** [SnosMe/awakened-poe-trade#673]
I am pretty sure they did work...right?

```
Item Class: Contracts
Rarity: Normal
Contract: Prohibited Library
--------
Client: Kondor Larcius
Heist Target: The Goddess of Water (High Value)
Area Level: 83
Requires Deception (Level 5)
--------
Item Level: 84
--------
"The relief depicts some sort of forgotten Maraketh goddess. I have no idea what
the context is. The important thing is that you steal it before Bazira does."
--------
Give this Contract to Adiyah in the Rogue Harbour to
```

**Comment by SnosMe** [comment]
Yes, not Unique Contracts are intentionally disabled. 

It's a consumable item that doesn't have special mods (like enchants on Maps).
Since it's not available on Bulk exchange it was disabled, use TFT to get **correct (higher) bulk price**.

![image](https://user-images.githubusercontent.com/4292308/175789732-e56b34f2-9168-4dfb-8d25-25b37ab8c91c.png)

**Comment by eduardolbueno** [comment]
Could this be reviewed perhaps?
It doesn't make sense to me that I can't check prices of contracts because they were disabled for some reason.

**Comment by SnosMe** [comment]
There is only one type of Contract that worth u TP out of map, Deception currently costs 5c and 10c in bulk on TFT.
I'm happy to add support once contracts are added to Bulk Exchange on Trade website (you can help with this by asking on PoE forum).

![image](https://user-images.githubusercontent.com/4292308/187530644-a52a36f8-da2d-42ae-897a-bd3e91a2b7a8.png)

**Comment by eduardolbueno** [comment]
No, cmon. If they're worth it or not, depends on the player.

Is there a technical limitation that prevents you from doing so?

Players use Awakened for, among other things, check prices for sales. If for some arbitrary reason it doesn't support one item or another, they will move to another tool.

**Comment by SnosMe** [comment]
Ask GGG to add contracts into bulk exchange by Heist Job type.
