### ISSUE TITLE
Unable to include fractured mod in item search with other mods

### ISSUE THREAD

**Issue by emailsbecker** [SnosMe/awakened-poe-trade#675]
I'd noticed this before, but this is the first time I seem to have a fractured mod that might be adding enough value to an item to make it worth opening an issue.  I have this item:

![image](https://user-images.githubusercontent.com/63986025/176436577-a994fc0f-8103-4b0e-a5ce-5046ed1134c3.png)

If I search for that fractured mod, which is only available on the Base Item tab, it looks to be decently valuable:

![image](https://user-images.githubusercontent.com/63986025/176436844-716a3f16-a1d3-4049-b4cd-4feae0f4707c.png)

Two of the other mods on it probably don't add much, but I was curious if adding the increased projectile speed would narrow down the results, however I can't find any way to get the app to let me select both that and the fractured mod at the same time.  I can either search for the fractured mod and nothing else, or the other mods but ignore that one of them is fractured.

I can't see why this should be the intended use for a case like this, so opening an issue.

**Comment by SnosMe** [comment]
Fractured mods exist in Pseudo tab under "hidden" toggle. (make sure you have latest version of app)
It doesn't happen that often that you have good 3 suffixes and good 1 fractured prefix, but you don't want to finish the item and decide to sell it.

**Comment by emailsbecker** [comment]
Confirmed.  I had v3.18.10003, upgraded to 10004 and the Hidden selector is now available.  Thanks.
