### ISSUE TITLE
Nothing happen when i tried to open the installer?

### ISSUE THREAD

**Issue by p3t3p3t3** [SnosMe/awakened-poe-trade#676]
I already installed it last month and last week i unstall it for some reason... now i cant install it again nothing happen when i click the installer i even downloaded a new one...

**Comment by SnosMe** [comment]
Windows is notorious for stuck installers.
The installer itself is called NSIS, maybe googling will help. 
I can't give more advice because it's a blackbox for me as well as for you, I just give it the files to install, and it creates the package.
