### ISSUE TITLE
Mouse / Cursor position moved to center of screen

### ISSUE THREAD

**Issue by PayamTavakoli1** [SnosMe/awakened-poe-trade#678]
When map checking the cursor gets set to middle of the screen, and lately I've experienced that it does it whenever I'm not map checking (like in the middle of maps etc it just puts the cursor in the middle of the screen which is very annoying and has killed me a couple times)

**Comment by SnosMe** [comment]
There is not a single line of code in source code to reposition the mouse cursor. 
Unfortunately, your guess is wrong and you need to find another app that does this on your PC.

**Comment by PayamTavakoli1** [comment]
It's strange how it ends when I turn off APT, guess it's some cross interactions then.
Thanks for the answer
