### ISSUE TITLE
Crafted Chaos Resist

### ISSUE THREAD

**Issue by tehgather3r** [SnosMe/awakened-poe-trade#68]
Items with crafted chaos resistance do not have the chaos resistance appear when pricing an item. The chaos resist doesn't appear in the hidden section either.

These are the Fire and Chaos, Lightning and Chaos, and Cold and Chaos Resistances crafts.

**Comment by SnosMe** [comment]
Fixed in v0.17

Now it will be shown in hidden section with appropriate reason.

![image](https://user-images.githubusercontent.com/4292308/78579937-59e77a00-783a-11ea-876e-77170eba6d95.png)
