### ISSUE TITLE
Latest patch bricked app from reading mods on items.

### ISSUE THREAD

**Issue by CycMarques** [SnosMe/awakened-poe-trade#680]
Been using Awakened for multiple leagues now and haven't had a single issue with it. Unfortunately the latest patch (v3.18.10004) completely bricked the app and it cannot read any mods on the items. I tried to roll back on last working app (10002) but installer automatically gives me the latest patch (10004). 

Tested on few items and app cannot read any of them, sometimes getting a message: "No relevant stats were found" on a perfectly normal accessory (a two-stoned ring in this case).

**Comment by SnosMe** [comment]
It's just a coincidence and not related to the latest update.
For solutions, seek #504

**Comment by CycMarques** [comment]
> So you didn't have a mouse button there, then it's likely AHK script or some program interfering with key presses. (not a bug)

Never had highlight on mouse, app is not creating any log to check the issue and it's still persisting.

**Comment by SnosMe** [comment]
Nope, still handles custom Highlight key without any issues.

**Comment by gotex007** [comment]
I just had to troubleshoot this issue. For some reason it can't find the mods and says "No relevant stats were found" if Show Advanced Item Descriptions is bound to anything other than Alt.
