### ISSUE TITLE
the problem with the Awakened pole trade

### ISSUE THREAD

**Issue by xDotTx** [SnosMe/awakened-poe-trade#681]
hello everyone. I ask for help in solving the problem with the program. Everything works on the English version of the client and the program. In the Russian version, he writes on each subject: "unknown object. If it's a new item in this league, most likely it will be added in the next update." ApT reinstalled. It didn't work on the previous three versions. (I didn't try it even later). Windows 11.  in the log file at startup apt writes: error [game-config]: The key could not be read. {"key":"6"}

**Comment by xDotTx** [comment]
> > In the Russian version, he writes on each subject
> 
> You need to change language in app settings and restart it https://snosme.github.io/awakened-poe-trade/faq
> 
> > in the log file at startup apt writes: error [game-config]: The key could not be read. {"key":"6"}
> 
> Regarding this one change key in PoE, see #493

![изображение_2022-07-05_221740306](https://user-images.githubusercontent.com/108754894/177390660-21b0acaf-eb17-420d-8edb-20e4405bd570.png)

**Comment by xDotTx** [comment]
> > In the Russian version, he writes on each subject
> 
> You need to change language in app settings and restart it https://snosme.github.io/awakened-poe-trade/faq
> 
> > in the log file at startup apt writes: error [game-config]: The key could not be read. {"key":"6"}
> 
> Regarding this one change key in PoE, see #493

![изображение_2022-07-05_221826210](https://user-images.githubusercontent.com/108754894/177390763-24889427-d41b-4935-b8e9-cfec8a563c2b.png)

**Comment by SnosMe** [comment]
This screenshot does not add any valuable information, you have already described it. 

> he writes on each subject: "unknown object. If it's a new item in this league, most likely it will be added in the next update."

**Comment by xDotTx** [comment]
> This screenshot does not add any valuable information, you have already described it.
> 
> > he writes on each subject: "unknown object. If it's a new item in this league, most likely it will be added in the next update."

Thank you very much, you are a great person! Changing the purpose of the key to display objects helped
