### ISSUE TITLE
Handling of the mod rolls slider got worse

### ISSUE THREAD

**Issue by TomSoflow321** [SnosMe/awakened-poe-trade#684]
I've just updated from 3.18.10001 to 3.18.10004 and noticed that the handling of the slider under mods with variable ranges got worse than before.
Before the update I could select values for min and max moving the slider from either side to narrow the search. Now one side is fixed and I can only move the slider for either min or max depending on which site is fixed no matter where I click on the slider. This forces me to manually write the desired number in the box for the other/fixed site to get range I want to search for.

If there it is still possible to move the slider for both values, then I haven't found out how. There is no hotkey to "switch" the fixed side, clicking on the farthest left or right side on the slider to select min or max doesn't work and when I click on the numberfield to "switch" which value I want to change with the slider doesn't work either, because that locks the slider for both values.

I couldn't find any issue post here which asks for that change or any entry in the changelog between both versions which mentions that change, so I wonder if this is a bug or made unintuitive on purpose. If it is the latter, please either revert that change, provide better explanation on how this is supposed to work or add an option to switch back to the old slider style.

**Comment by SnosMe** [comment]
What is a use-case to fill both min and max values?

**Comment by TomSoflow321** [comment]
For example to look for items similar to mine. Simple example: Abyssus. When I found one with 43%, when I look what 42% - 44% costs like. Having an open ended 42% would include all the cheaper 50% items I don't look for and an open ended 44% includes price-fixed 40% versions I don't look for either.
