### ISSUE TITLE
Tauri as a replacement for Electron

### ISSUE THREAD

**Issue by SnosMe** [SnosMe/awakened-poe-trade#688]
https://tauri.app/

| Electron / npm | Tauri / crate |
|---|---|
| electron-overlay-window | ? |
| uiohook-napi | ? |
| Self Updater | ✅ |
| Clipboard | ✅ |
| Tray menu | ✅ |
| `<webview>` tag | 🚫 |
| Font size | ? |
| Implicitly pass POESESSID cookie | ? |
| `screen.dipToScreenPoint` | ? |
| global shortcuts | ✅ |
| Transparent window | ✅ |
| `window.showInactive` | ? |

**Comment by Samusia** [comment]
Will Tauri remove MacOS support that was added in https://github.com/SnosMe/awakened-poe-trade/pull/403?
