### ISSUE TITLE
Awakened PoE Trade spams errors when launched through Launch of Exile

### ISSUE THREAD

**Issue by JaniHugsPlease** [SnosMe/awakened-poe-trade#690]
When I try to launched Awakened PoE Trade via Launch of Exile I get spammed with errors. This does not happen if I launch it separately.  Both Launch of Exile and Awakened PoE Trade are up to date. I have also set to run as admin but it hasn't made a difference. I have also tried reinstalling.

I have reached out to the LoE dev and they said it was an issue for you to fix not him so, here I am.

The error:

![Capture](https://user-images.githubusercontent.com/110821295/183395825-18f5b572-d491-44dc-bf20-26a2b83cc0bf.PNG)

**Comment by SnosMe** [comment]
> they said it was an issue for you to fix not him

Well, idk where I need to fix this.
But it seems to me that LoE dev should spawn process with correctly setup IO handles.

**Comment by CptBlacksheep** [comment]
LoE dev here, this can be closed. You were right (i missed to redirect IO). Sorry for the inconvenience.
