### ISSUE TITLE
Identity Requirements in 3.19 for trade functionality.

### ISSUE THREAD

**Issue by mpawlowski** [SnosMe/awakened-poe-trade#691]
I'm pretty sure the upcoming patch is going to break trade functionality.

https://www.pathofexile.com/forum/view-thread/3293287#tradewebsitechanges

The right way to tackle it is probably going to need some sort of [OAuth flow](https://www.pathofexile.com/developer/docs), or a hacky solution to just add a session cookie / token somewhere.

**Comment by SnosMe** [comment]
This change will not affect API. oauth indeed will be required soon (3.20+ league), but for now no changes.

**Comment by mpawlowski** [comment]
Are you sure this won't be affected? The app makes a request that hits the same API the trade site uses:

https://github.com/SnosMe/awakened-poe-trade/blob/c417fb83318e161f30009eac41d2a9b37234b47b/renderer/src/web/price-check/trade/pathofexile-trade.ts#L554

I would assume that that API would be behind a login per the patch notes.

**Comment by SnosMe** [comment]
Yes, ggg representative said so. And btw you can already login in builtin browser.
