### ISSUE TITLE
Oauth for 3.19 will be needed. 

### ISSUE THREAD

**Issue by zombodotcom** [SnosMe/awakened-poe-trade#692]
https://www.pathofexile.com/forum/view-thread/3293287
https://www.pathofexile.com/forum/view-thread/3293287#tradewebsitechanges

Accessing the Path of Exile: Trade website now requires you to be logged in.

**Comment by SnosMe** [comment]
Thank you for your attention, everything will be fine. Duplicate of #691

**Comment by zombodotcom** [comment]
thanks for looking into this <3
