### ISSUE TITLE
Can download Executable. Executable does nothing. Found workaround

### ISSUE THREAD

**Issue by SormerSensei** [SnosMe/awakened-poe-trade#693]
Skip to step 13 to see more interesting stuff. Just giving as much context as possible so you know what is NOT the problem.

1.- I go to 'https://snosme.github.io/awakened-poe-trade/download'
2.- I click 'Windows 10 (installer)'
3.- Microsoft Bing downloads an application titled 'Awakened-PoE-Trade-Setup-3.18.10004'
4.- Microsoft Bing warns against said download, so I hit 'keep' twice and it finishes the download
5.- I try opening/starting application from downloads folder, desktop, as well as "as an administrator"

Mouse Pointer changes briefly to a loading wheel, after which nothing happens. Can't find anything in Task Manager processes.

6.- I restart my computer
7.- I try step 5 again to no success
8.- I download and install the Google Chrome Browser.
9.- I repeat steps 1 and 2
10.- Used Chrome to download the same application is step 3
11.- No warning was issued upon download, so there was no pause between the unfinished download at %100 becoming recognized as an application.
12.- I repeat steps 5, 6, and 7

Same lack of response.

13.- Searched 'Issues' section and found issue #676 to be very similar if not the same.
14.- Right clicked Icon on desktop and opened 'Properties'
15.- Moved to Compatibility and checked the box to 'Run this program as an administrator' and hit 'Apply'
16.- Hit the button 'Run compatibility troubleshooter' followed by 'Try recommended settings'
17.- Hit 'Test the program' and it just worked. The 'Setup' program finally worked!

Hope you find this helpful!

**Comment by luishrodg** [comment]
This guide solved my problem.
