### ISSUE TITLE
APT wont run on arch (failed to find config files)

### ISSUE THREAD

**Issue by bytooo** [SnosMe/awakened-poe-trade#697]
When I try to run the appimage I get the following erros:
```
➜  Downloads ./Awakened-PoE-Trade-3.18.10004.AppImage
error [game-config]: Failed to find game configuration file in the default location. Default values will be used instead. {"file":"/home/byto/Documents/My Games/Path of Exile/production_Config.ini"}
[26268:0817/182154.584238:ERROR:browser_main_loop.cc(271)] Gdk: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
hook_thread_proc [101]: Could not set thread priority 49 for thread 0x7FB258FF56C0!
```
System Specs:
- OS: EndeavourOS (arch based)
- WM: i3 window manager
- Proton: GE-Proton 7-29

The game runs perfectly fine but when I click the in game button to find my filters folder a different filesystem appears (most likely the virtual container that proton probably creates for the game to run fine) 
I don't know how true the my previous assumptions are but, I'm unable to find the path to poe's config files and so does APT.

**Comment by SnosMe** [comment]
It should run fine without game config file.
> Default values will be used instead

If you happen to find a config file you can set in Awakened: Settings > General

![image](https://user-images.githubusercontent.com/4292308/185351975-a8f44e9e-50ce-4a05-b85f-d6c909188e48.png)
