### ISSUE TITLE
Can´t install on ubuntu 22 (symbol lookup error)

### ISSUE THREAD

**Issue by ginokok1996** [SnosMe/awakened-poe-trade#698]
Trying to install awakened POE on my ubuntu 22 machine.
When running the Appimage the following error occurred
`/tmp/.mount_AwakenyELje2/awakened-poe-trade: symbol lookup error: /lib/x86_64-linux-gnu/libgdk-3.so.0: undefined symbol: wl_proxy_marshal_flags`

Haven´t been able to find a fix for this so far so any help would be appreciated.
I've already tried to reinstall libgtk-3-0 but no luck.

**Comment by SnosMe** [comment]
wl_ prefix is related to wayland, are you trying to run it under wayland, it won't work

**Comment by ginokok1996** [comment]
[daemon]
# Uncomment the line below to force the login screen to use Xorg
WaylandEnable=false

I have wayland disabled.

**Comment by ferrosa** [comment]
Just want to comment that I've been successfully running the 3.18.x and 3.19.x versions of APT on Ubuntu 22.04.
```
~$ loginctl show-session $(awk '/tty/ {print $1}' <(loginctl)) -p Type
Type=wayland
~$ inxi -Gxx | grep compositor
    compositor: gnome-shell v: 42.2 driver: gpu: amdgpu display-ID: 0
```

Not sure if it depends on the the driver or anything, all I did was to clean out `~/.config/awakened-poe-trade/` and it worked.

**Comment by ferrosa** [comment]
On second checking, launching the AppImage also starts a `XWayland` instance. I'm not running XWayland otherwise.
