### ISSUE TITLE
Using price check is opening character panel 50% of the time.

### ISSUE THREAD

**Issue by Brasolis** [SnosMe/awakened-poe-trade#699]
When using my price check hotkey, about half the time it does not open a check, it opens the character panel. My hotkey does not have the character panel keybind in it anywhere. Guessing the application is trying to copy the mods which involves the c key. I did not have this issue last league with an older version.

**Comment by Brasolis** [comment]
Here is an example of it happening. 

https://i.imgur.com/8OoL31a.mp4

Once it fails to copy the info and opens the character panel, I must move the item to a different inventory slot in order for the application to read the mods.

**Comment by SnosMe** [comment]
Close other programs, probably AHK script.
https://snosme.github.io/awakened-poe-trade/nothing-happens
