### ISSUE TITLE
Check influenced base

### ISSUE THREAD

**Issue by vadash** [SnosMe/awakened-poe-trade#7]
It can be an extra hotkey / integrated in CTRL+D
ilvl 86+ should be reduced to 86, ilvl 85 to 84

**Comment by SnosMe** [comment]
Yes, when creating the tool, I planned that all the information should be shown with one shortcut CTRL+D. Display the cost of the base is indeed located on my roadmap. 


> ilvl 85 to 84

I do not understand why this is necessary, can you explain?

**Comment by vadash** [comment]
I double checked poedb and there is indeed some rolls for ilvl 85. Yep, ignore this part
