### ISSUE TITLE
No tray icon on Linux

### ISSUE THREAD

**Issue by zaggynl** [SnosMe/awakened-poe-trade#70]
I play Standard, does this tool only search in Delirium? (at time of writing)

**Comment by SnosMe** [comment]
![image](https://user-images.githubusercontent.com/4292308/78503202-d5c7c080-776d-11ea-8f4d-9173b9c9e153.png)

**Comment by zaggynl** [comment]
Playing on Linux, how does I access the settings? No tray icon appears for me, using XFCE.

**Comment by SnosMe** [comment]
Try to follow this guide https://github.com/electron/electron/issues/21445#issuecomment-565061274
`xfce4-statusnotifier-plugin`

**Comment by zaggynl** [comment]
Appreciate the quick response!

After adding the "Status Notifier Plugin" (was already installed):
![image](https://user-images.githubusercontent.com/5062119/78506444-d36b6380-7779-11ea-91bc-0c35cd3c2339.png)
And restarting the Appimage the icon appeared!
![image](https://user-images.githubusercontent.com/5062119/78506479-0ca3d380-777a-11ea-9c5c-cb31cf6960bc.png)
