### ISSUE TITLE
Adding items for comparisons results in broken numbers (thousands of percent)

### ISSUE THREAD

**Issue by ThirteenEra** [SnosMe/awakened-poe-trade#701]
Steps to reproduce (in my case, at least):

1. Make new profile
2. Import my character (Hjormnir - europe kalandra softcore trade)
3. Assign Righteous Fire as main skill, include all gem links in full dps
4. In Items, copy-paste an item from ingame.

The item (scepter with fire damage) comes with massively inflated numbers - thousands of percent increases. When pasted into notepad, the data appears correct - which means its POB misreading it.

Copy pasting a different scepter results in same issue (so its not related to just one specific item).

See screenshots for information

<img width="1237" alt="bug6" src="https://user-images.githubusercontent.com/111650549/185755121-519462ad-acb5-4f40-a93c-5aa0fbcfad08.png">
<img width="1190" alt="bug5" src="https://user-images.githubusercontent.com/111650549/185755125-e8662ed4-ae99-4425-a63c-f9641ad8d0b3.png">
<img width="969" alt="bug4" src="https://user-images.githubusercontent.com/111650549/185755126-ae9f85c8-997b-4172-a489-b61a699d0076.png">
<img width="961" alt="bug3" src="https://user-images.githubusercontent.com/111650549/185755128-1a284e20-767e-4846-aaa9-ce96aa3e8ec3.png">
<img width="615" alt="bug2" src="https://user-images.githubusercontent.com/111650549/185755129-05df0709-2cbf-4252-800d-970d28640a08.png">
<img width="497" alt="bug1" src="https://user-images.githubusercontent.com/111650549/185755132-63e81830-b3bb-40c5-ade3-a3ffe307beaf.png">

**Comment by Tahakk** [comment]
u sure you didn't wanted to post this on PoB git?

**Comment by ThirteenEra** [comment]
... I did. Fuck me. 

Woops
