### ISSUE TITLE
Incorrect name being whispered, not allowing for stash search

### ISSUE THREAD

**Issue by ThirteenEra** [SnosMe/awakened-poe-trade#703]
When whispering names, it seems website adds a comma after the initial name before item type

For example: [Doedre's Tenure, Velvet Gloves]

The problem is that the comma isnt recognised by the stash. You can find the gloves by searching for [Doedre's Tenure Velvet Gloves], but if you add a comma, it becomes an invalid search. Thus making it impossible to highlight the item.

A fix would be for Awakened POE to remove any "," symbol from the item string before generating a stash search

**Comment by SnosMe** [comment]
awakened-poe-trade doesn't have such feature. You've created issue in the wrong repo.
