### ISSUE TITLE
Using APT causes stuttering in DX12 and Vulcan.

### ISSUE THREAD

**Issue by R1llan** [SnosMe/awakened-poe-trade#709]
Using APT causes severe stuttering in all APIs (cause of it is overlay i think, im not a dev). My thoughts is it just breaks GSync functioning somehow. I think it is GGG to blame, cause of their bad VSync implementation, but i've decided to start here first.
I've recorded a video with APT on and off, its hard to spot these stutters on a video, but i definitely can see if APT launched or not, trust me.
[the video](https://youtu.be/qh9CQwsSio4)
Im really like APT and want to use it, but it won't work right with G-Sync compatible enabled, games becomes really choppy and unsmooth.

**Comment by SnosMe** [comment]
Thank you for taking the effort to film this.
APT is just a simple transparent window that ALWAYS shown on top of the game. I expect it breaks transitioning borderless window into directx Independet flip which is probably required for g-sync.
Since I can't change how APT functions the only option is to disable g-sync and use usual vsync in poe.

**Comment by R1llan** [comment]
i've seen it, sadly this didn't helped

**Comment by R1llan** [comment]
is it possible to make mode that changed behaviour to not always be on top of the game? like only when called by hotkey

**Comment by poroburu** [comment]
I found a workaround my GSYNC APT issue that increased my GSYNC FPS from 75 to 120. Open up APT overlay, move it to another monitor using `win+shift+left/right`.
I play PoE boarderless windowed on my second monitor at 120hz GSYNC. My primary monitor is 75hz non-gsync. 
I spend a bit of time in NVIDIA Profile Inspector, or Windows' Desktop Window Manager (DWM) to disable acceleration to APT. Which did not work. But I highly recommend enabling `GSYNC - Indicator Overlay` as a GSYNC sanity check.

**Comment by nekokind** [comment]
@poroburu These settings in nvidia profile inspector fixed g-sync with APT open for me. On Windows 11. 

<img width="1074" height="445" alt="Image" src="https://github.com/user-attachments/assets/387700ef-648b-429b-a792-11cc60d888f4" />

**Comment by poroburu** [comment]
@nekokind Those settings on APT didn't work for me. But thanks for sharing. It would be great to isolate the cause.
Are you on a multiple monitor setup? I am using an AW3418DW (PoE) secondary and ASUS primary VL279 monitor. 
Moving the APT overlay doesn't have any perceptible delay other than opening it. So, I don't mind this workaround for now when opening PoE.

**Comment by LWoBTbl** [comment]
> I found a workaround my GSYNC APT issue that increased my GSYNC FPS from 75 to 120. Open up APT overlay, move it to another monitor using `win+shift+left/right`. I play PoE boarderless windowed on my second monitor at 120hz GSYNC. My primary monitor is 75hz non-gsync. I spend a bit of time in NVIDIA Profile Inspector, or Windows' Desktop Window Manager (DWM) to disable acceleration to APT. Which did not work. But I highly recommend enabling `GSYNC - Indicator Overlay` as a GSYNC sanity check.

You are my saviour.

**Comment by poroburu** [comment]
I vibed new Auto Hotkey scripts. That move APT, allowing PoE to run with GSYNC:

This AHKv2 script moves APT overlay to my left secondary monitor by default. Importantly, it resizes APT to the monitor size to prevent overlapping between monitors with smaller resolutions than the PoE monitor.
https://gist.github.com/poroburu/d8b624540dc4ce1fa2bd4d0a6b74f366

This AHKv2 script minimizes APT overlay. If you use the APT system tray 'Open in Browser' feature.
https://gist.github.com/poroburu/4411ace08f70e408d42e3cfe1efa1ac1
