### ISSUE TITLE
Using backtick/backquote as a hotkey doesn't seem to work correctly.

### ISSUE THREAD

**Issue by pterolatypus** [SnosMe/awakened-poe-trade#717]
I'm trying to bind the backquote key to /exit. When setting the key bind the UI says "backquote", however pressing said key in-game does nothing and the action is instead bound to the apostrophe key.

**Comment by SnosMe** [comment]
If I remember, this is a problem with Dutch kb, you can:
- bind it to apostrophe and use backquote
- or start app with EN kb layout active

**Comment by SnosMe** [comment]
#447

**Comment by pterolatypus** [comment]
I'm using a UK keyboard and layout. If I bind the action to apostrophe it does work, but it also triggers when pressing the hash `#` key which makes using global chat difficult.
I can work around the issue so not a major problem, would just be nice. Ty for response.
