### ISSUE TITLE
new update messed with my scroll wheel

### ISSUE THREAD

**Issue by gravilensing** [SnosMe/awakened-poe-trade#719]
Hey dev, 

The latest update made my tab scrolling less ideal. I have my scroll down wheel set to left click to quickly dump my inventory into a dump tab. I disable it by enabling the scroll lock on my keyboard. 

When scroll lock is enabled, the usual tab scrolling from awakened trade would function, but now when it's also disabled it is now still scrolling, despite it supposed to be being registered as a left click. 

any possibility to change this back?

**Comment by SnosMe** [comment]
???? I don't interact with your wheel in any way. There were no changes made in latest version.

**Comment by gravilensing** [comment]
Ok, I changed a couple settings that I should've done a while ago on my mouse. Sorry for bothering. 

I had some ghetto way of changing the functions of my mouse, but now just set it via mouse software. 

Sorry for being a nuisance.
