### ISSUE TITLE
Crashes w/o VC 2015-2019

### ISSUE THREAD

**Issue by akoidan** [SnosMe/awakened-poe-trade#72]
![image](https://user-images.githubusercontent.com/1336703/78772459-a4eeb380-7946-11ea-94c3-60c14b444175.png)

This extension fixes the issue. https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads . Thought POE game doesn't it. This could be non-intuitive to a user that doesn't understand anything in coding. 

I suggest we add to to README.md

**Comment by SnosMe** [comment]
@akoidan I have already recompiled iohook lib, so it does not require vcredist. Will be replaced soon.

**Comment by hellwasta** [comment]
@SnosMe Thx have the same issue

**Comment by SnosMe** [comment]
Fixed in v1.0
