### ISSUE TITLE
Allow adding custom mod to search when open prefix/suffix

### ISSUE THREAD

**Issue by melink14** [SnosMe/awakened-poe-trade#721]
Often, it's worth it to craft life/res on a base with good affixes so that it shows up in naive searches. Right now, I open the search in a browser to manually add but it would be nice to be able to quickly add a mod from the UI. Even just life/res would solve 90% of my use cases!

**Comment by SnosMe** [comment]
Unfortunately, too complex to implement.
When I see that item costs 20c I'm okay to spend 4c on craft no matter how much it will boost price.
