### ISSUE TITLE
unable to find league after new update

### ISSUE THREAD

**Issue by ThatDudeThor** [SnosMe/awakened-poe-trade#723]
on windows 11, was working perfectly before the update but since the update its unable to find the league

**Comment by EldritchEevee** [comment]
Private league? You'll need to type it out in the box next to `or Private League` exactly as Path of Exile's site shows it (case-sensitive.)

**Comment by SnosMe** [comment]
Make sure you have Kalandra league selected. If you've used Private League you may need to relogin in builtin browser.
No changes have been made to the "leagues" part of the code, so nothing should break.
