### ISSUE TITLE
cannot click search window - it auto hides when mouse is moved

### ISSUE THREAD

**Issue by btrisler** [SnosMe/awakened-poe-trade#724]
after pushing ctrl + D, when i move my mouse about half an inch, the price search window hides.  previously i was able to enable/disable some of the search criteria by clicking in this window.  i would like to tweak some of the numbers and search again to get a better feel for the price of similar items people might search for by different stats.  Am i doing something wrong?

**Comment by MrPirou** [comment]
having the exact same issue, found anything?

**Comment by EldritchEevee** [comment]
Hold down ctrl while you're moving your mouse.
