### ISSUE TITLE
Doc Enhancement -- add a Linux requirement

### ISSUE THREAD

**Issue by topola888** [SnosMe/awakened-poe-trade#726]
Hello,

I am using APT on Ubuntu 22.04 with PoE through Steam.

What I find, totaly randomly, is that ATP need the lib `libfuse2`
Can you add it to requirement section ?
Is there any other libs needed to launch ATP ?

Before installing this lib, ATP didn't launch, no tray icon, no errors so no clues.
Since you need the tray icon to know where logs are, i was unable to try to debug.

the default log directory is : `~/.config/awakened-poe-trade/apt-data/`

I had to make a symbolic link because ATP was not able to find PoE's `production_Config.ini` and take the default value.
I tried to edit ATP's config.json to put the directory but ATP refuse to launch with this (tried with and without quotes)
`"gameConfig": "/home/<username>/.steam/steam/steamapps/compatdata/238960/pfx/drive_c/users/steamuser/Documents/My\ Games/Path\ of\ Exile/production_Config.ini"`

Now i am trying to figure why i have this issue : 
![Capture d’écran du 2022-08-31 14-11-25](https://user-images.githubusercontent.com/55354551/187681189-0cf4efa1-1a00-4d7c-a434-05914897c18a.png)

before removing the `--no-sandbox` flag, I wasn't able to get hotkey catching by ATP.
But without I have the errors on screenshot
With debug loglevel, I see that ATP catching the hotkey but don't know why I have the js errors.

I hope my debug may help someone and the doc can be updated.

If someone know why I have the js error, feel free to help :)

thank you for the amazing know done on ATP

**Comment by SnosMe** [comment]
> What I find, totaly randomly, is that ATP need the lib libfuse2

I don't use it, and have no idea what can depend on it (probably Electron/Chromium, either they should bundle it or depend on it to be installed but it's not for some reason on your system).

> I tried to edit ATP's config.json

Game config is totally optional, you can change it's location in normal settings rather than editing config, and as I see you broke something in config and need to delete file now.

Regarding --no-sandbox there is issue created already

**Comment by topola888** [comment]
I understand, I will try to delete the config.json
I don't have hotkey working so it's may be my only way to test config change

it may be the appImage launcher that need libfuse2

**Comment by topola888** [comment]
after deleting config.json now all work fine
Thank you a lot
