### ISSUE TITLE
Could Grand Spectrums please have their mod checked by default?

### ISSUE THREAD

**Issue by Xenemros** [SnosMe/awakened-poe-trade#727]
![POEGrandSpectrum](https://user-images.githubusercontent.com/93318071/187770978-4afc4e5d-4a62-45c3-ae58-d2d4eea219c4.png)

Can we please get the box checked by default for Grand Spectrums?
It's a single mod jewel, so it would make sense for the rolled mod to be checked

**Comment by RhapsodySL** [comment]
Similarly, Atlas memories should also have their mod checked by default as the mod heavily influences the pricing of the item. For example, Einhar's memory ranges from 70c all the way to 1.5 divines for the Harvest memory.
