### ISSUE TITLE
zh_CN

### ISSUE THREAD

**Issue by makefilezzds** [SnosMe/awakened-poe-trade#729]
I added zh_ Cn to the current version_ Cn's support, hope to get your authorization! It won't be used in business, just for free sharing and use!

Thank you very much for your open source!

**Comment by leooooooooo** [comment]
> I added zh_ Cn to the current version_ Cn's support, hope to get your authorization! It won't be used in business, just for free sharing and use!
> 
> Thank you very much for your open source!

Have see the zh_CN version released on bbs,maybe pull request the code is better
