### ISSUE TITLE
/hideout hotkey only works every second time.

### ISSUE THREAD

**Issue by majorregal** [SnosMe/awakened-poe-trade#731]
Hello, I have a strange problem.
I have bound F2 to /hideout with "Press Enter" enabled.
However it only executes the command every second time I press the F2 key, when it doesn't work it seems to just paste it into the chat without executing it as if it would open the chat, paste /hideout and then close the chat without pressing enter.
When I open the chat again after it didn't work I can see /hideout in the chat.
My operating system is Windows 11 x64 bit.

I also want to add that I'm having this problem for quite some time now, so it wasn't the recent update that made this happen.

**Comment by SnosMe** [comment]
Sorry, can't help, something on your PC.

**Comment by coreclap** [comment]
hi, im having the same problem actually.
For me it started with this league, have not changed my pc configuration at all.
