### ISSUE TITLE
can't access to settings 

### ISSUE THREAD

**Issue by itdonotwork** [SnosMe/awakened-poe-trade#732]
i canot access to settings using the overlayhotkey (shift + barspace) while the game is launch. 
the only result i get is a "..." bar with those options : "stop watch, stash search, image strip" 
i've tried to fix from the common issues but i'm stuck at this point 
so basically i canot use any shortcuts in the game i dont know why and how to fix this

**Comment by SnosMe** [comment]
Happens for some mysterious reason to some people. You need to remove config file and restart app.

**Comment by itdonotwork** [comment]
"i'll prey to the whispered gods so they'll bless you with their best regards when you'll fight against adversity" :')
