### ISSUE TITLE
fill stat values not correctly applying the proper value when exact roll selected.

### ISSUE THREAD

**Issue by straylightd** [SnosMe/awakened-poe-trade#733]
So i have exact roll selected for fill stat values. Prior to this league it would automaticall put the right roll in the box when i used the tool.Now it tends to give me around a 2-3% (esitmating) lower value instead of the exact roll value on the item. It also does this for item level on certain items. Ive noticed it on my logbooks, blueprints, contracts it puts 81 when the item is 83. while it seems to be working for gear (armour, weapons, jewels)

**Comment by SnosMe** [comment]
> tends to give me around a 2-3% (esitmating) lower value

This is a lower roll of current mod tier.
