### ISSUE TITLE
[request] add quick search via ctrl+f for similar items in stash tab

### ISSUE THREAD

**Issue by eskoONE** [SnosMe/awakened-poe-trade#736]
I don't know which tool had this feature before, but I'd like a feature that searches for an item's base (e.g. currency, fragments, artifacts, oils, incubators, etc.) when you press ctrl+f on it. 

As an example, i wanna look for all scarabs in my dump tab, I'd have to just ctrl+f on a scarab in my inventory or in the stash, which then puts a regex into search that only highlights scarabs. I imagine you would just process the text you get when you ctrl+c on an item and find the relevant string to do this.

If you need help with putting together the regex, I can help with that.

**Comment by NokTham** [comment]
It's PoE Trade Macro
https://github.com/POE-TradeMacro/POE-TradeMacro/wiki/AdditionalMacros#:~:text=minimized%20this%20way).-,HighlightItems,-Ctrl%2BF%20fills

Would be very useful if Awakened PoE Trade could implement something like this.
