### ISSUE TITLE
Chat macros can leak clipboard contents if used in a loading screen

### ISSUE THREAD

**Issue by slaren** [SnosMe/awakened-poe-trade#742]
From a quick glance at the code this seems to be caused by the "copy message to clipboard - send enter - send ctrl v - restore previous clipboard" process. Doing this while in a loading screen will cause the key presses to be queued by the PoE client, and by the time they are executed the clipboard will have the original contents. This specifically can happen when first launching the game and spamming the /hideout hotkey to enter the hideout as quickly as possible.

Obviously this is user error to some degree, but given the consequences of possibly leaking sensitive content from the clipboard to a global channel, I think this should be considered a serious issue.

**Comment by SnosMe** [comment]
https://github.com/SnosMe/awakened-poe-trade/issues/618#issuecomment-1131390002

**Comment by slaren** [comment]
I think the obvious solution here is to send the entire message via key presses, not disabling restoring the clipboard. In the meanwhile or if you're just not interesting in implementing that, it may be a good idea to make that option the default and only allow users to enable restoring the clipboard with a big and very clear warning that enabling the feature can result in leaking sensitive data.

**Comment by SnosMe** [comment]
> I think the obvious solution here is to send the entire message via key presses

Not sure what this means and how different from current implementation.

**Comment by slaren** [comment]
I mean sending every character of the message, ie. the "/hideout" as an individual keypresses, instead of pasting it from the keyboard.

**Comment by SnosMe** [comment]
This will work only if you don't have any keyboard layouts other than english and no usernames other than Latin characters 😄

**Comment by slaren** [comment]
I don't think that's necessarily the case, you don't have to simulate low level keyboard presses, you can send characters to the application. That's the way AHK does it, for example.

**Comment by SnosMe** [comment]
This is not possible with libraries I'm using, and pretty sure not available on Mac (and maybe linux).
So yeah, will disable it by default

**Comment by ContecSafran** [comment]
@SnosMe The above problem is happening to me this season too. How can I solve this?

**Comment by SnosMe** [comment]
@ContecSafran this setting has moved to here

![image](https://github.com/SnosMe/awakened-poe-trade/assets/4292308/09e8ad62-7df9-4778-a4b8-cd120ce10e87)

It cannot randomly start to happen, if you have it disabled.

**Comment by grish333** [comment]
@SnosMe
I'd like to inform you that this setting does not work. I checked it and tried. I unchecked it and tried - it still continues to use the clipboard when the game interface is not active for a split second (as mentioned before - either while in someone else's hideout or right after the game loads a town, etc.)

I highly recommend that you:

Fix the it in a way that this issue won't possibly ever happen again.
Explain to me and in public why would it use the clipboard in any way?
I have read this topic but it isn't a solution for the issue, let alone an explanation why you're using the user's clipboard for this function.
Please excuse my hard tone but the situation is of a serious legal matter.

**Comment by eabemitchell** [comment]
Why was this issue closed?

I don't understand why this tool even uses my clipboard. As I never use it for anything with it. I can close the game and awakened POE for hours. start both up hours later and then when I hit F5 to go to my hideout. I instead whisper someone to trade a trade I made hours ago. Restarting Awakened POE Trade doesn't fix it. Unchecking the default checked load clipboard setting doesn't fix it. I just have to restart the app a few times over and over until the problem goes away.

What else is even more odd. Is I can manually copy something else like "test" to my clipboard and it still uses some old text. Not the new text I just added. Like it has it's own clipboard that never clears itself. I don't understand the purpose of this clipboard. And why the tool even needs it.

The tool is great overall. But it is sad to see this functionality is so buggy. And looks like it has been for a very long time.

**Comment by SnosMe** [comment]
@eabemitchell it's closed because there is no bug. All users that had APT  installed before Oct 2022 need to change this setting manually. Also read this https://github.com/SnosMe/awakened-poe-trade/issues/1139#issuecomment-1783769647

**Comment by eabemitchell** [comment]
I just said changing the setting didn't fix it for me. Neither does restarting the app. I just tried un-installing and re-installing but I doubt it will fix it.

**Comment by Juts2** [comment]
Experiencing this issue on Linux, though it happens even when not used during/close to a loading screen. It will continue to output the clipboard to chat when you press F5 to hideout until you either restart path of exile (restarting awakened poe trade doesnt seem to work) or you do an item lookup (ctrl d).
