### ISSUE TITLE
Add armour percentile as a search option in pricing overlay

### ISSUE THREAD

**Issue by RhapsodySL** [SnosMe/awakened-poe-trade#746]
Some items, especially Ward-based armour, have heavily varying prices depending on the percentile of the armour (for example, Runic Gauntlets range from 102-117 if you hold alt over them). APT doesn't currently offer a way to search for the item with percentile in mind, so I'm suggesting that this feature be added (but not checked by default).

**Comment by SnosMe** [comment]
https://www.pathofexile.com/forum/view-thread/3207890
