### ISSUE TITLE
Content of clipboard pasted in local chat when pressing F5 on game start

### ISSUE THREAD

**Issue by smootise** [SnosMe/awakened-poe-trade#751]
When I press F5 right when I login (in town), it pastes my clipboard in local chat instead of pasting /hideout. 
It has happened twice today, but I can't reproduce 100% of the time (seems to only do it when I first open the game after a long break). 

This is a very serious problem as my clipboard often has important and confidential data in it ! I've pasted a link with a confidential security token to an account for my work in chat and had to change all the security on that account to not compromise it ! 

I can try to capture a video of it next time I open the game tomorrow.

**Comment by SnosMe** [comment]
#742 you can disable this

**Comment by smootise** [comment]
My bad, I searched for an issue about it and didn't find any, I realize now that I was searching with :isopen so I didn't see that. 
Thanks for the fast answer.
