### ISSUE TITLE
[feature request] for list of return trades (or when user is pressing the "Trade" button)

### ISSUE THREAD

**Issue by zaafar** [SnosMe/awakened-poe-trade#753]
Give users the option to set following 2 settings.

* Collapse Listings by Account
* Buyout Price = chaos, divine, exalt

**Comment by SnosMe** [comment]
You can now change currency type, this setting is not reset while you check the same item type.
So if you check another item in between price check of Compasses, it will be reset.

> Collapse Listings by Account

This one was not added because the motivation was not provided in this issue.

**Comment by zaafar** [comment]
Thank you for implementing one part, I will test this tonight! :)

@SnosMe sorry for not providing the motivation for the "collapse listing by account". I normally do this for following reason.

1: to make sure I am not looking at same account posting 1 item multiple times. This will help me reduce some price fixing.

Basically what this (trade-site) feature does is return 1 item per account ( even if that account have listed multiple items ).

**Comment by zaafar** [comment]
@SnosMe Sir, do you concur?

**Comment by SnosMe** [comment]
@zaafar You can enable it permanently since long ago

![image](https://user-images.githubusercontent.com/4292308/197752716-3ba2d809-4a57-480a-a81a-611d9fb5632e.png)

**Comment by zaafar** [comment]
@SnosMe  oh i see, so that's what the ? is about (as shown in the image below). 
![image](https://user-images.githubusercontent.com/5079646/197815738-863e21d0-4582-4fa8-bbfc-d34a2eb3bac2.png)


That is a good feature and solve 90% of the issue but as you can see the image below when I click the "Trade" button, the POE website have set it to false and i have to manually set it to Yes every time i click trade.

![image](https://user-images.githubusercontent.com/5079646/197817706-07190929-d333-4203-8ee3-87a8cd38c30a.png)

**Comment by SnosMe** [comment]
Nope, question mark indicates this https://www.reddit.com/r/pathofexile/comments/wd41mk/comment/iihg6ef/?utm_source=share&utm_medium=web2x&context=3

And the setting I mentioned above will show "x2" "x3" etc label where question mark is for collapsed listings (can easily test it on bestiary orbs, usually bulk selled by one person)

**Comment by zaafar** [comment]
So I did some testing, something doesn't make sense. it shows x5 (as shown in the image below).

![image](https://user-images.githubusercontent.com/5079646/197862511-136f9d6c-330e-4652-b9c4-73b246c5ccc5.png)

but doesn't show x2 (as shown in the image below)

![image](https://user-images.githubusercontent.com/5079646/197863591-ea3df4a8-9770-4775-b8d4-ed0842da8c92.png)

**Comment by SnosMe** [comment]
yes, its >= 3, because there are a lot of valid x2 listings, and showing labels for them will be too noisy

**Comment by zaafar** [comment]
> because there are a lot of valid x2 listings, and showing labels for them will be too noisy

I see, now I have the whole picture. Thank you for taking your time and explaining me everything.

First of all, it would be nice to mention that ( >=3 ) over here (Screen shot below).
![image](https://user-images.githubusercontent.com/5079646/197864204-813874d0-e7d8-4296-8f27-4c305d240d19.png)

Second of all, for the use case of "What should I price this item for?" and "that item with those mods/mods-value is rare" it's good to know if an item is sold by the same person or different person even for x2 scenario.

If you agree with that, I can think of multiple solutions.
* easiest one would be to make >= 3 a configurable option over here (screenshot below)
![image](https://user-images.githubusercontent.com/5079646/197864204-813874d0-e7d8-4296-8f27-4c305d240d19.png)

* another one would be to allow user to set this (screenshot below) to Yes/No
![image](https://user-images.githubusercontent.com/5079646/197866979-935dc543-ae88-4e81-b6aa-e7101f78074a.png)

**Comment by zaafar** [comment]
that being said, 99% of the use-case is solved, it's just for items that are rare to find on the market.

**Comment by zaafar** [comment]
Also, IMO, "Not showing the indication of collapsed listings AND removing that whole item from the list of returned item" is kind of worst choice.
