### ISSUE TITLE
Error: Failed to Fetch

### ISSUE THREAD

**Issue by bjorn1369** [SnosMe/awakened-poe-trade#767]
Failed to get price prediction:
Error: Failed to fetch

Unable to price predict rares ONLY, everything else seems fine. Version is updated to latest, and tried re-installing, still an issue. have tried to run as admin as well. 
![image](https://user-images.githubusercontent.com/115324879/194673928-1a40c960-9b6f-43ad-95ca-b2716e772104.png)

**Comment by SnosMe** [comment]
Press Ctrl+Shift+I when overlay is active and make screenshot of Console tab (after making price-check).
I think your IPs are blocked by Google (where https://poeprices.info/ is hosted)

![image](https://user-images.githubusercontent.com/4292308/194698775-bf07a413-a39d-46e8-8245-05bf46459196.png)

**Comment by sminor** [comment]
Error in console log

www.poeprices.info/api?i=SXRlbSBDbGFzczogSmV3ZWxzDQpSYXJpdHk6IFJhcmUNCkFwb2NhbHlwc2UgSm95DQpWaXJpZGlhbiBKZXdlbA0KLS0tLS0tLS0NCkl0ZW0gTGV2ZWw6IDg0DQotLS0tLS0tLQ0KKzE1JSB0byBDcml0aWNhbCBTdHJpa2UgTXVsdGlwbGllciB3aXRoIE9uZSBIYW5kZWQgTWVsZWUgV2VhcG9ucw0KMTYlIGluY3JlYXNlZCBEYW1hZ2Ugd2l0aCBDbGF3cw0KOCUgaW5jcmVhc2VkIFByb2plY3RpbGUgU3BlZWQNCjE2JSBpbmNyZWFzZWQgRnJlZXplIER1cmF0aW9uIG9uIEVuZW1pZXMKMyUgY2hhbmNlIHRvIEZyZWV6ZQooRnJlZXplIGxvd2VycyBFbmVteSBBY3Rpb24gU3BlZWQgdG8gemVybywgcHJldmVudGluZyB0aGVtIGZyb20gYWN0aW5nLiBEdXJhdGlvbiBpcyBiYXNlZCBvbiB0aGUgQ29sZCBEYW1hZ2Ugb2YgdGhlIEhpdCkNCi0tLS0tLS0tDQpQbGFjZSBpbnRvIGFuIGFsbG9jYXRlZCBKZXdlbCBTb2NrZXQgb24gdGhlIFBhc3NpdmUgU2tpbGwgVHJlZS4gUmlnaHQgY2xpY2sgdG8gcmVtb3ZlIGZyb20gdGhlIFNvY2tldC4NCg%3D%3D&l=Kalandra&s=awakened-poe-trade:1          Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR

**Comment by sminor** [comment]
Tried via VPN and issue went away. I suspect the issue is with Xfinity/Comcast

**Comment by sminor** [comment]
Resolved this for me by going into xfinity app and disabling advanced security as poeprices.info is being flagged as spam/adware/ Hope this helps.
