### ISSUE TITLE
Too many "APT is ready and running" notifications 

### ISSUE THREAD

**Issue by SnosMe** [SnosMe/awakened-poe-trade#772]
This happens because on instance load on **low spec PCs** game window transitions into "Not Responding"

![image](https://user-images.githubusercontent.com/4292308/195569197-993b6e84-c8a6-41c8-af4c-1276460a9f08.png)

![image](https://user-images.githubusercontent.com/4292308/195569197-993b6e84-c8a6-41c8-af4c-1276460a9f08.png)

![image](https://user-images.githubusercontent.com/4292308/195569249-689369dc-a2fa-4bf4-805a-283a097be8c0.png)

**Comment by EldritchEevee** [comment]
This procs off ANY Application (including Explorer menus!) that has "Path of Exile" in its name.

**Comment by EldritchEevee** [comment]
> I know about Windows Explorer, it's expected to happen and not a bug (also not related to this issue).

**That's a bug.**

**Comment by SnosMe** [comment]
The app worked like this for 2 year, you're only aware about it now because of notification 😄

**Comment by SnosMe** [comment]
The fix landed in 3.19.10004

**Comment by EldritchEevee** [comment]
Tried, tested, NOT COMPLETE.

**Comment by SnosMe** [comment]
Can you record small vid using OBS for example.
You can reliably trigger Not responding window state by changing renderer in game options.
