### ISSUE TITLE
APT is attaching itself to Windows Explorer

### ISSUE THREAD

**Issue by JajinderK** [SnosMe/awakened-poe-trade#776]
Last week I came back to play the game a bit and updated ATP. Seems like some new features have been added, like an annoying overlay with names of people. Application is starting to become bloated imo. 

After the update I immediately noticed that I see a message that APT is ready and running in the background. This is nice. However, it seems to attach itself to Windows Explorer (Win10 1806). Screeenshot: https://imgur.com/a/VaJnRiD

This is something unwanted and it also seems to interact with my function keys because I'm using them in my configuration. For example; When I press F2 in Windows Explorer it's suppose to rename a file. This works, but here's the weirdest thing I've ever seen: It won't let me use the F2 on xml-files. It opens the file itself. Can you pls check this behaviour?

Is there a version with only the league updates without all these new features/messages? I really liked the simple approach in previous versions.

Thanks for helping in advance.

**Comment by SnosMe** [comment]
> an annoying overlay with names of people

Are you familiar with such a thing as giving credit people for monetary support? 

> However, it seems to attach itself to Windows Explorer

The app functions like that for 2 years, you're only aware about it now because of notification.
I will not add PoE detection by process name for a lot of reasons.

Also there is bug with too much notifications that will be fixed #772

**Comment by JajinderK** [comment]
I don't mind seeing credits at all, bt this way of implementation is in my opinion an annoyance. It jumps everywhere and it distracts.

> The app functions like that for 2 years, you're only aware about it now because of notification.
> I will not add PoE detection by process name for a lot of reasons.
Fair anough.

**Comment by SnosMe** [comment]
> It jumps everywhere and it distracts.

It should be shown only when Settings are open, I've configured my APT long ago and don't feel the need to open them.
Am I missed something and they show up elsewhere?

**Comment by JajinderK** [comment]
When I click outside of the "settings-screen" and click on a name the overlay with names jumps around annoyingly.

**Comment by SnosMe** [comment]
> I do that often (on accident) to get out of the screen

But how do you get so often to Settings window?
There is no point to get out of Settings without saving them.

**Comment by JajinderK** [comment]
I go to settings often to check commands or change them. I press save only when needed. I don't see the buttons you have. When I press outside of the screen I'm used for it to close or at least not showing that annoying message "press shortcut to continue editing."

https://imgur.com/a/Bm7ihFL

**Comment by SnosMe** [comment]
Ty for explaining.
This message was added to help people, previously if you were to add cheatsheet image
it would open file picker and after selecting file not opening back overlay (can't do this for technical reasons).
Now at least this behavior is not confusing, and you know you can continue editing cheatsheet widget.

![image](https://user-images.githubusercontent.com/4292308/198281797-6cf116b9-c74c-42cb-a6dc-9e17c3d9dcb4.png)

I'll think how to improve parts you have mentioned.

**Comment by JajinderK** [comment]
Thank you for showing what you ment. I don't use the cheatsheet functions. Only use the app for commands and for pricechecking. Like I mentioned before, I don't like all the extra's but am somewhat forced to interact with them. That's why I was asking for a simpler version. Maybe you can add more tabs in the settings windows and implement them in there. That way everything is in 1 place. (just trying to think with you)

**Comment by EldritchEevee** [comment]
**this WILL be fixed, or _it's on its way to Windows to be blocked._**

**Comment by SnosMe** [comment]
> **this WILL be fixed, or _it's on its way to Windows to be blocked at SYSTEM level._**

Do whatever you want. I'm sure you don't even know what "attaching" means. It's not  injecting into process(aka Discord, Overwolf), using shady DLLs etc. For this app "attaching" means find window by title, track it's position using official windows api, move and resize app accordingly.

**Comment by SnosMe** [comment]
@JajinderK I've fixed some annoying parts in v3.19.10004.

If someone wants to change the behavior of attaching by window title,
they can do it in library I use 
https://github.com/SnosMe/electron-overlay-window
