### ISSUE TITLE
3.19.10003 - all sorts of issues?

### ISSUE THREAD

**Issue by 7ekken** [SnosMe/awakened-poe-trade#777]
original issue before i just updated ... divines were showing 1 div = 17c

so i updated app... now i'm seeing all sorts of names all over the place that look like loot drops when i open settings in game with shift+space

also i am not able to remove the blue ( press shift space to continue editing ) with this new release.

![image](https://user-images.githubusercontent.com/104710979/199109155-c0ff6f54-a6cf-4734-a42f-453afac1524f.png)

![image](https://user-images.githubusercontent.com/104710979/199109395-c038920f-0f78-490c-b746-10deb4bcd01d.png)

![image](https://user-images.githubusercontent.com/104710979/199110025-2f15764c-53cb-4748-8b29-c762478c5cdb.png)

**Comment by SnosMe** [comment]
> divines were showing 1 div = 17c

The only source for this info is poe.ninja website, it can be tricked by players sometimes.

![image](https://user-images.githubusercontent.com/4292308/199112455-e53a73c4-b2e9-492d-95e3-3f257d4844f9.png)

---

> i'm seeing all sorts of names all over the place

This is a credit to people for monetary support. I think about grouping labels together, but it's not a critical issue right now.

> also i am not able to remove the blue ( press shift space to continue editing ) with this new release

Just Save or Cancel in the settings window.
Why it's shown here: https://github.com/SnosMe/awakened-poe-trade/issues/776#issuecomment-1293448679

**Comment by 7ekken** [comment]
as far as the Div > Chaos exchange rate ... i was able to fix it by a complete wipe of %appdata%  and  %localappdata%  of both awakened poe trade folders + complete uninstall / reinstall of the app.  the trade div > chaos is fixed.
