### ISSUE TITLE
"Search for app in store?"

### ISSUE THREAD

**Issue by RSNRazor** [SnosMe/awakened-poe-trade#778]
Whenever I launch the setup, it attempts to look for an app on the store that brings up an error.
Is this an individual issue or is this just incompatible with Win11?

![tradeerror](https://user-images.githubusercontent.com/117249445/199391544-059cebd8-b0ee-4c69-9d71-70715631a244.png)

**Comment by SnosMe** [comment]
I don't require anything.
But I wonder what app it will show if you click Yes?

**Comment by RSNRazor** [comment]
https://i.imgur.com/XhyUsu3.png
At first I thought it was a general win11 problem, but it seems specific to this app

**Comment by SnosMe** [comment]
I successfully installed it in clean Windows (Windows Sandbox).
So my response can be only to seek what's different with your windows.

![image](https://user-images.githubusercontent.com/4292308/201203548-239dfd77-31a5-42e8-b914-b85dc3f65088.png)

**Comment by FrancoisMentec** [comment]
> I successfully installed it in clean Windows (Windows Sandbox). So my response can be only to seek what's different with your windows.

Can you send the list of programs installed in your sandbox?

**Comment by SnosMe** [comment]
Each time it's opened starts from clean state

![image](https://user-images.githubusercontent.com/4292308/206426090-293bdcb2-98d0-4f36-b2e0-c7e018ef593a.png)
