### ISSUE TITLE
Sggestions for improvement

### ISSUE THREAD

**Issue by skripterasm** [SnosMe/awakened-poe-trade#78]
1. Is it possible to add the ability to specify the number of links when searching for a rare item?

2. Is it possible to make sure that when scrolling through the tabs with the CTRL button, when the last tab is reached, the camera location in the game does not change?

3. Is it possible to make the prices of cheap currency be displayed in decimal places where the average price and price chart are indicated?

4. Will it be possible to select craft mods instead of pseudo in search?

**Comment by SnosMe** [comment]
1. `5, 6 Linked sockets` already detected. Why would you search for 1-4 link ?

2. This is technically impossible. README has notice `You can also disable "Mousewheel Zoom" in PoE settings (Options -> UI -> 3-rd check mark starting from the bottom)`. You can still zoom by using PgUp PgDown keys.

3. By doing this, you essentially lose the point of showing price. (just a note: this data comes from https://poe.ninja and it is not avg price).

4. What you really want is filter "Has 1 crafted pref/suf or 1 empty pref/suf". I need to do research to find out if this is possible to implement.

**Comment by Slaviator** [comment]
@SnosMe hello, can I kindly ask about the 4 list item (empty pref/suf). Have you done any research? This works somehow on https://poeapp.com, so quite sure it is possible. This feature would save so much time during accessories pre-pricing. Maybe I can help you in terms of research? Code with c# but definitely can make sense of other languages and approaches. Have a nice day.

**Comment by SnosMe** [comment]
poeapp watches https://www.pathofexile.com/api/public-stash-tabs
it returns number of prefs, suffs
![image](https://user-images.githubusercontent.com/4292308/103206956-cc871100-4905-11eb-8a27-69c7aec21a8f.png)
 @Slaviator

**Comment by SnosMe** [comment]
This issue was open for (4) suggestion. It is implemented now https://github.com/SnosMe/awakened-poe-trade/commit/c400c7b8a03636c8e0df05b2c7c1db44c58a8b47
