### ISSUE TITLE
Installer not running

### ISSUE THREAD

**Issue by mwashburn1987** [SnosMe/awakened-poe-trade#789]
Trying to fresh download and install on Win 11
Trying to run the .exe after download forces a request for an app to be found in microsoft store which isn't an option.

**Comment by Meisen1977** [comment]
I just bought a new computer with windows 11 myself. Tried to install awakened poe, but alas, same situation as you :/

After a lot of googling i happened across a person that had had the same issue but had found a workaround;

https://www.reddit.com/r/techsupport/comments/ylaveh/search_for_app_in_store_popup_when_trying_to_run/

It worked for me too, so best of luck to you sir :)

**Comment by SnosMe** [comment]
![image](https://user-images.githubusercontent.com/4292308/206687757-5f9b0f0c-4274-4e89-ad9b-9d5a57051894.png)

**Comment by bl4ckm1st** [comment]
Same thing as OP but resetting Microsoft Store did not fix the issue.
