### ISSUE TITLE
[bug] Unexpected token < in json at position 0

### ISSUE THREAD

**Issue by zaggynl** [SnosMe/awakened-poe-trade#79]
![poe_unexpected_token](https://user-images.githubusercontent.com/5062119/79259755-82502380-7e8d-11ea-82a0-2b615a49c098.png)

**Comment by notwlsn** [comment]
Have the same bug. Repeatable by searching anything on my client. Restarted client to no avail. 

Attached my config, logs, and a screenshot. Log level was Debug.

[logs.txt](https://github.com/SnosMe/awakened-poe-trade/files/4477918/logs.txt)
[config.txt](https://github.com/SnosMe/awakened-poe-trade/files/4477921/config.txt)
![awkaened_poe_bug](https://user-images.githubusercontent.com/12144803/79277354-a0ab2480-7e77-11ea-8e61-eafc0c857ffd.png)

**Comment by notwlsn** [comment]
I figured it out, it's due to the official PoE trading site being down. Just wait for the site to be back up and the problem will likely resolve itself. @zaggynl
