### ISSUE TITLE
Map and Item check duplicate hotkey

### ISSUE THREAD

**Issue by dovry** [SnosMe/awakened-poe-trade#792]
Latest version
![image](https://user-images.githubusercontent.com/15201298/206735766-eaf4460a-d6b5-46c2-935d-8e2701a1ad67.png)

# Issue
![image](https://user-images.githubusercontent.com/15201298/206735440-156a129e-b8b5-47e6-bfea-7a990ab8d81a.png)

---

I've deleted `%appdata%\Roaming\awakened-poe-trade`, but the config isn't generated with a mapCheckKey.

    "configVersion": 12,
	"wikiKey": "Alt + W",
	"craftOfExileKey": null,
	"overlayKey": "Shift + Space",
	"overlayBackground": "rgba(129, 139, 149, 0.15)",
	"overlayBackgroundExclusive": true,
	"overlayBackgroundClose": true,
	"itemCheckKey": "Alt + D",
	"delveGridKey": null,
	"restoreClipboard": false,

Is this intended behaviour now?

**Comment by SnosMe** [comment]
Yes, they share same hotkey
