### ISSUE TITLE
"Running" pop-up outside of the game

### ISSUE THREAD

**Issue by AaStern** [SnosMe/awakened-poe-trade#794]
Honestly, it's a pretty minor issue, but the "app is ready and running" is showing even if you open the folder named "Path of Exile"/
![Annotation 2022-12-10 134855](https://user-images.githubusercontent.com/62376967/206851350-f479ecfd-1e94-4aeb-9d2e-e25443ea7e59.png)

**Comment by SnosMe** [comment]
#776 

> The app functions like that for 2 years, you're only aware about it now because of notification.
I will not add PoE detection by process name for a lot of reasons.
