### ISSUE TITLE
Awakened PoE doesn't show item mods? 

### ISSUE THREAD

**Issue by Emibjr** [SnosMe/awakened-poe-trade#795]
I have problems with Awakened PoE trade since 3.20

**Comment by CodeMG** [comment]
I had the same issue. I fixed it by changing the key bind ingame in the input options for "Show Advanced Item Descriptions" from "Alt" to another key.

**Comment by SnosMe** [comment]
Key detection was fixed in 3.20.10002, you can update now.

https://www.pathofexile.com/forum/view-thread/3323944
> The "Compare Item Descriptions" and "Show Advanced Item Descriptions" behaviour has been split from the "Highlight Items and Objects" keybind into their own dedicated options. These new options default to holding Ctrl and Alt respectfully. These new binds can be configured in the Options panel, under the Input section.
