### ISSUE TITLE
v3.20.10002 download virus

### ISSUE THREAD

**Issue by BooJetz** [SnosMe/awakened-poe-trade#797]
Great job, well done! 
KIS restored OS two times after downloading the latest version of APT. In general, the virus deletes all folders from Windows directory at once. So, how could you explain all this?

P.S. fix it pls, and don't do that again - many people use your application.

**Comment by SnosMe** [comment]
I have no clue what's happening on your PC, but code is public, programmers can verify made changes between versions (if you suspect this tool in breaking your OS).

**Comment by BooJetz** [comment]
Actually what's the problem...

Today after installing this version, I played a little in PoE. Then I decided to check the price with Crtl+D, and after some time application closed and "awakened_poe_trade.exe" from installing directory was removed by KIS. 
Whereat OS started to fail - errors started popping up about memory bugs 0x02024980, for example; explorer was removed and PC went into reboot. 

I can't figure out why this happened, but it is. Maybe it's application problem, i don't know...

**Comment by jasonpanosso** [comment]
> I have no clue what's happening on your PC, but code is public, programmers can verify made changes between versions (if you suspect this tool in breaking your OS).
> 
> It runs on PCs of streamers, so I greatly acknowledge responsibility.

Interestingly 'Awakened PoE Trade.exe' does get flagged by one vendor on [VirusTotal](https://www.virustotal.com/gui/file/16f365bacda5453d941925d5dbaf9dcee2e557c0d3b567ced3a8090ee8099791/detection)

Bit curious why this happens, obviously this is not a virus but if antivirus like Kaspersky are flagging it that would be rather obnoxious!

**Comment by BooJetz** [comment]
About yesterday's incident. 
Here is what gives a report about the executable file (everything was downloaded directly from the link in the repository)
![2022-12-12 202605](https://user-images.githubusercontent.com/120327903/207112815-47aec27a-23ae-4c2a-b322-a4e12d8ac070.png)

For the sake of experiment, I downloaded the portable version of APT from the same link, I check it for performance and trojans too :)
