### ISSUE TITLE
Ctrl + D not working

### ISSUE THREAD

**Issue by SHHamps** [SnosMe/awakened-poe-trade#799]
I was using a really old version, saw a video where they used Ctrl + D and it had support to check oils on annoints on rings, it would be useful for me, so I decided to update, deleted older version and downloaded new one.

Ctrl + D stopped working, I`ve got the "doesn't have a quick fix" problem from FAQ, where log shows **warn [clipboard]: No item text found. {"text":""}** 

Tried downloading all other versions from here https://github.com/SnosMe/awakened-poe-trade/tags
all of them with the same problem

Older versions got me "Imcompatible Configuration - You are trying to use an older version of Awakened Poe Trade with a newer incompatible configuration file. You need to install the latest version to continue using it."

Is there anything that I can do?

**Comment by SnosMe** [comment]
Follow this https://snosme.github.io/awakened-poe-trade/nothing-happens
There is video at the end too, you should get working even when APT is closed.
Also, if you have mentioned key in article bound to mouse, change it to keyboard.

**Comment by SHHamps** [comment]
> Follow this https://snosme.github.io/awakened-poe-trade/nothing-happens

I don't understand how this can help me, my configs are the same from the video

Not even unninstalling AHK worked

I have no idea on how to make Ctrl + Highlight + C work

**Comment by SnosMe** [comment]
So are you able to copy item text from PoE?

**Comment by SHHamps** [comment]
Ctrl + Alt + C doesn't copy for me; only Ctrl + C, but it's not with advanced description, (even though I have advanced descriptions on)

**Comment by SnosMe** [comment]
Yeah, can't help with, this functionality is built into PoE, should work when all programs are closed. You have to find what's conflicting on your PC.

**Comment by jordanadania** [comment]
My AHK script is blocking my Awakened hotkeys.

Is there a hotkey I can use for awakened that won't be blocked by my AHK?
Is there any code I can put in my AHK script to allow awakened hotkeys thru?

I feel like if Awakened allowed me to remove Ctrl or Alt it could be a solution.
