### ISSUE TITLE
Voidstone - applied Sextant price check not working 

### ISSUE THREAD

**Issue by AeonNoeA** [SnosMe/awakened-poe-trade#800]
When you try to check the price directly on the voidstone for the Sextant modifiers does not work.
This is broken since the new league version

**Comment by EldritchEevee** [comment]
You can no longer price check Quest Items.

**Comment by SnosMe** [comment]
@EldritchEevee this is not entirely correct.

GGG has broke something and now on Quest items item name is copied into Rarity.
Waiting for reply.

```
Item Class: Atlas Upgrade Items
Rarity: Ceremonial Voidstone
--------
Item Level: 84
```
