### ISSUE TITLE
Awakened POE Trade causes Faster Sensitivity in Minecraft

### ISSUE THREAD

**Issue by Snailic** [SnosMe/awakened-poe-trade#801]
### Problem
Awakened POE Trade causes Faster Sensitivity/Mouse Acceleration in Minecraft

### Repro:

[Windows 11 22H2]

1. Run Minecraft 1.8.9 in Windowed mode.
2. Compare 360 distance with and without Awakened POE Trade running

### Expected results
360 distance is the same regardless of Awakened POE Trade running

### Notes
Probably caused by it being an overlay?

**Comment by SnosMe** [comment]
I have no idea how it can influence Minecraft.
Can't do anything other than recommend to close APT when you don't paly PoE.
