### ISSUE TITLE
Price conversion to chaos not working both ways

### ISSUE THREAD

**Issue by Aggnog** [SnosMe/awakened-poe-trade#802]
This is regarding the stack size conversion at the bottom of the window. 

Example with scour orb https://i.imgur.com/rGUB9Pa.png

Works correctly, showing  I have 54 scour which is 19c at 1s:3c ratio.

When a currency costs more than a chaos orb, the conversion isn't switched backwards and is thus incorrect

https://i.imgur.com/3BHyaaJ.png

Here it assumes that 2 sextants are 1c, when it is the opposite.

**Comment by SnosMe** [comment]
The prices at the bottom and on the top are from poe.ninja website. You can see on the graph huge drop in price. This can happen due to manipulation by players.
