### ISSUE TITLE
[Request] Alchemy Orb option for price check

### ISSUE THREAD

**Issue by Froochu** [SnosMe/awakened-poe-trade#812]
In Ruthless the popular currency is alchemy orbs instead of divines or chaos, which makes price checking difficult as it shows the prices in chaos which usually has 0 listings while alchs have multiple.

It would be even better if you could choose a custom currency to search for, but even just alchemy orbs would be great 👍

**Comment by SnosMe** [comment]
> it shows the prices in chaos

I by default show in Any currency, not sure where you want the change to be made

**Comment by Froochu** [comment]
That's odd, I can't seem to find any listings in alchs and it instead shows chaos. It says I am on v.3.20.10003
For example this essence, I can only find a listing in chaos. But when I search on the trade site I can find one for an alch there.
![image](https://user-images.githubusercontent.com/60483071/209581779-2ae890c3-c6eb-45ed-ba47-59120054055d.png)
![image](https://user-images.githubusercontent.com/60483071/209581861-b29bdc3a-2a37-44b3-8211-ef34f8c18610.png)

If I try to change currency mode my only options seem to be chaos and divines unless I am missing something.
![image](https://user-images.githubusercontent.com/60483071/209581904-a98a04a8-1314-4b5e-951c-745ffa509a39.png)

**Comment by SnosMe** [comment]
Oh right, bulk exchange is in Chaos 😅

**Comment by SnosMe** [comment]
I'm not interested in supporting ruthless.
