### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by VitalySonko** [SnosMe/awakened-poe-trade#813]
Hi,
I used poe awakening trade long time. Today, advanced price check doesn't work. Ctrl + D works ok, but ctrl + alt + D goes into desktop. Can someone help me? I reinstalled, updated, didn't help.

**Comment by SnosMe** [comment]
> ctrl + alt + D goes into desktop

You have game running in Fullscreen, change to windowed Fullscreen

**Comment by VitalySonko** [comment]
> переключитесь на оконный полноэкранный режим

thanks for helping
