### ISSUE TITLE
Price check window stays open permanently (Win 7)

### ISSUE THREAD

**Issue by aiolos01** [SnosMe/awakened-poe-trade#815]
Since the latest update a few minutes ago the price check window stays open permanently when I press the button to open the search in a browser window. When I return to the game the price check window is in the middle of the screen and doesn't function at all. It just stays there regardless of what I do and the only way to make it close is to press ctrl+space to open the APT config menu,

**Comment by SnosMe** [comment]
Doesn't happen to me. Can you record small video in OBS, drag and drop it here

**Comment by aiolos01** [comment]
I don't have OBS. Here are 2 screenshots, if that helps. As you can see after pressing the trade button the window is permanently overlayed on the game. I can play normally and it just stays there.
![Snap233](https://user-images.githubusercontent.com/6642661/210123399-f27dd472-5660-4ff2-a512-dbddb5374a64.png)
![Snap234](https://user-images.githubusercontent.com/6642661/210123400-5c292f9e-6567-4a22-bd82-056891bff855.png)

**Comment by OneManOneClass** [comment]
Same issue on Win10 for *04 and *05 versions. Not only the PriceCheck window, but the overlay gets stuck too. 

The solution posted in [issue #818](https://github.com/SnosMe/awakened-poe-trade/issues/818) helped me.

**Comment by aiolos01** [comment]
Confirmed, this fixes the issue.
