### ISSUE TITLE
Key detection is broken

### ISSUE THREAD

**Issue by crash0verwr1te** [SnosMe/awakened-poe-trade#816]
Alt is my push to talk and every time i push ctrl+D the tool push alt. 

https://i.imgur.com/Zas1Y01.jpg

**Comment by SnosMe** [comment]
I've checked and it doesn't after setting key to Ctrl. Make sure u've restarted the app after change.

![image](https://user-images.githubusercontent.com/4292308/210112110-2bd83323-9ada-4260-ac48-47cc1b243612.png)

**Comment by SnosMe** [comment]
Hmm, did you set custom path to PoE config file in settings?

**Comment by crash0verwr1te** [comment]
I deletet all i found from awakaned and reinstalled it. Now it works.
