### ISSUE TITLE
 you can now open overlay in your Browser (via an option in tray menu)

### ISSUE THREAD

**Issue by gordo54321** [SnosMe/awakened-poe-trade#817]
How to disable this and go back to open trade search inside Poe instead of opening a browser?

**Comment by SnosMe** [comment]
You need to open Overlay once (Shift+Space). I will make sure this is not required after closing browser tab in next release.

**Comment by vova792** [comment]
Проблема после обновления 0004/5 ! при клике на трейд переходит в браузер а не внитри игры как раньше, как решить?

**Comment by SnosMe** [comment]
@vova792 this is a different issue, and for the reasons see #821

**Comment by vova792** [comment]
спс за ответ,что я могу сделать чтоб дело сдвинулось? куда написать?

**Comment by gordo54321** [comment]
> @vova792 this is a different issue, and for the reasons see [#821 ](https://github.com/SnosMe/awakened-poe-trade/issues/821)

what @vova792 asked was my issue when I wrote this post. Also #821 is what I was trying to ask. I thought the title with the changelog was referring to that
