### ISSUE TITLE
Whole screen goes black in POE except price check overlay 

### ISSUE THREAD

**Issue by scottmudge** [SnosMe/awakened-poe-trade#818]
New version ([3.20.10004](https://github.com/SnosMe/awakened-poe-trade/releases/tag/v3.20.10004) has issue where entire screen goes black except the price check overlay window.

I don't see an option for GPU acceleration anymore, so can't toggle that to see if it fixes it. Can't downgrade without deleting my config, so that's a little annoying. 

POE is using Vulkan.

**Comment by scottmudge** [comment]
When using price check, it also breaks video playback in various websites in Chrome. I believe these issue have to do with the opening the overlay in the browser.

Going to have to downgrade.

**Comment by SnosMe** [comment]
You need to add `--disable-gpu` flag now.

This setting was removed because I cannot apply it in app at launch myself anymore.

**Comment by SnosMe** [comment]
The HW is disabled by default in the latest release.
