### ISSUE TITLE
Map Check not working

### ISSUE THREAD

**Issue by seke1111** [SnosMe/awakened-poe-trade#826]
Something broke for me other than settings not being saved + closing down since the update to 3.20.10004, and that is the Hotkey for Maps (not sure if that's the actual cause of course), in any case i can't see the mods for map rolls, which i then wiped and installed the 3.20.10005 in hopes of it kicking again but it's still the same, don't matter which hotkey i'm using.

**Comment by SnosMe** [comment]
If you don't see mods visit page https://snosme.github.io/awakened-poe-trade/nothing-happens
