### ISSUE TITLE
Failed to load leagues

### ISSUE THREAD

**Issue by Plaggi** [SnosMe/awakened-poe-trade#827]
AFter press "Ctrl+D"  it gives me error "Failed to load leagues". Press "Retry" dont help. Press "Browser"  it gives me this. You also can't select a league in the settings.
![Снимок экрана (91)](https://user-images.githubusercontent.com/79322444/210177078-9f6b7716-c91c-48bf-a7a7-5f24b7e5b002.png)
После нажатия на "Ctrl+D", выскакивает ошибка "Failed to load leagues". Нажатие на "Retry" не помогает  - ничего не происходит. Нажатие на "Browser" выдает то, что изображено на первой картинке.

В настройках также нельзя выбрать лигу и нажатия на "retry" не помогают.
![Снимок экрана (93)](https://user-images.githubusercontent.com/79322444/210189541-5937c71d-5859-476f-b697-919e856eef2e.png)

Удалил версию [3.20.10004]  и папку  'AppData\Roaming\awakened-poe-trade', поставил [3.20.10001] - прайсчек работает и в настройках можно выбирать лигу.
![Снимок экрана (92)](https://user-images.githubusercontent.com/79322444/210188751-2612ff97-40bc-4543-b252-e263407ef9be.png) Но после выхода из  awakened-poe-trade он автоматом обновляется до версии  [3.20.10004], ошибка "Failed to load leagues" повторяется и прайсчек не работает.

В попытке повторить данную ошибку, иногда после открытия настроек "Shift+Space"  появлялась ошибка в ходе которой при нажатии  "Ctrl+D" ничего не происходило, а при наведение в трее на иконку  awakened-poe-trade программа закрывалась. Помогало удаление папки  'AppData\Roaming\awakened-poe-trade' и установка версии [3.20.10001].

**Comment by somwasan** [comment]
same here

**Comment by 0x111BA6FA** [comment]
same

**Comment by wonderczech** [comment]
We have the same issue here - two account.
![image](https://user-images.githubusercontent.com/59936059/210516078-2e9f0241-f539-45b2-bab4-e246615a0d28.png)

**Comment by 13RedFox** [comment]
When I try to find out the price of an item, it gives the same error, when I click on the browser, it shows the text that I do not have access to the site. And it's impossible to choose leagues.

![Screenshot 2023-01-04 at 11 56 25](https://user-images.githubusercontent.com/31631365/210530292-bf01dbca-8acd-49fd-9c34-0e04601fc1c0.png)
![Screenshot 2023-01-04 at 11 57 43](https://user-images.githubusercontent.com/31631365/210530322-68c74c79-437a-4dd5-9ddb-01c459534683.png)

But I'm logged into my account on the website.
I need help with this problem, if you have any ideas, tell me.

**Comment by SnosMe** [comment]
https://github.com/SnosMe/awakened-poe-trade/issues/840#issuecomment-1370632844

**Comment by michaelobr** [comment]
I am having the same exact issue.

**Comment by quamtum** [comment]
Hi SnosMe
I can use awakened-poe-trade after install newest "setup version"
but if use newest "portable version", still can't work like old version

**Comment by 0x111BA6FA** [comment]
As temp workaround for me - i downloaded portable 3.20.10001 (non-setup version) and just run it. It works on old version, no need to delete anything.

**Comment by buzaslan129** [comment]
same here

**Comment by SnosMe** [comment]
The "Retry" button should be working now again. Press it after solving CAPTCHA or if you see that leagues are loaded like on screenshot 

![image](https://user-images.githubusercontent.com/4292308/216207281-8732b6fd-24ac-4a05-918e-4f72aee7c6b5.png)

**Comment by ashoklathwal** [comment]
[Check this detailed article](https://wealthquint.com/fix-awakened-poe-trade-failed-to-load-leagues-62156/) with workaround & fixes in details if Awakened poe trade failed to load leagues
