### ISSUE TITLE
[Bug] Prismatic catalyst wrong price

### ISSUE THREAD

**Issue by porcupince** [SnosMe/awakened-poe-trade#828]
Tried to price check my prismatic catalyst with APT today, got totally supprised when attemp to buy more in web browser

Ingame price check
![image](https://user-images.githubusercontent.com/55292891/210178159-464868b4-1e84-4cf1-b75d-c9ac347fbd97.png)

Trade on web
![image](https://user-images.githubusercontent.com/55292891/210178171-90acd338-3dec-4641-ac00-8459ce45d6c1.png)

Poeninja 
![image](https://user-images.githubusercontent.com/55292891/210178244-676082ae-bfac-44d4-9978-5a7c601fa410.png)

**Comment by SnosMe** [comment]
You even gave screenshot where it says -99% price drop, for 1c you get 10 catalysts.
