### ISSUE TITLE
JavaScript Error

### ISSUE THREAD

**Issue by Spieluhr89** [SnosMe/awakened-poe-trade#83]
Hi....i have this problem when i try to use awakened poe trade

![error](https://user-images.githubusercontent.com/63886393/79623464-d0b22c00-80f2-11ea-9754-2f584b623060.png)

**Comment by ZoR3oL** [comment]
You have to download and install VC 2015-2019, as described in this issue: https://github.com/SnosMe/awakened-poe-trade/issues/72

**Comment by Spieluhr89** [comment]
Thank you!!!! problem resolved

**Comment by SnosMe** [comment]
Fixed in v1.0
