### ISSUE TITLE
How to send POESESSID cookie

### ISSUE THREAD

**Issue by Traveller-hongchen** [SnosMe/awakened-poe-trade#834]
afterv3.20.10004,how can i send POESESSID cookie on every requests?

**Comment by Traveller-hongchen** [comment]
before v3.20.10004, I revise overlay-windows   modifyResponseHeaders's return and add"POESESSID=****" can make send it,but after v3.20.10004,this way is useless

**Comment by SnosMe** [comment]
International API doesn't require it, for CN you will need to modify and pass it here https://github.com/SnosMe/awakened-poe-trade/blob/b2905cbace347e9bde7b93c9248e61b5428790fe/main/src/server.ts#L31-L42

**Comment by Traveller-hongchen** [comment]
thank you very much for your help!!!!!!!!

**Comment by Traveller-hongchen** [comment]
Another question, How can I get poesessid from config on server.ts?

**Comment by Traveller-hongchen** [comment]
I want add poesessid to config, but I don't konw how to get config on server now.

**Comment by SnosMe** [comment]
Config can be received here 

https://github.com/SnosMe/awakened-poe-trade/blob/b2905cbace347e9bde7b93c9248e61b5428790fe/main/src/main.ts#L37-L44

**Comment by Traveller-hongchen** [comment]
But I don't know how to send it to server.ts, And I don't know when server.ts 's code will run

**Comment by SnosMe** [comment]
It's sent for you already, add new field here 

https://github.com/SnosMe/awakened-poe-trade/blob/b2905cbace347e9bde7b93c9248e61b5428790fe/renderer/src/web/Config.ts#L607-L609
