### ISSUE TITLE
Overlay won't load after computer goes to sleep (3.20.10004/5)

### ISSUE THREAD

**Issue by ciceroripi** [SnosMe/awakened-poe-trade#837]
After the upgrade to 3.20.10004 every time I put my computer to sleep, I have to close and open the app for the overlay to work.
I'm now on 3.20.10005, but I tested back and forth both, and it's the same.
I can't test 3.20.10003 back, as the config is not compatible anymore.
Anything I should do?

**Comment by ciceroripi** [comment]
Shift+Space also won't work, only restarting the app can get it to work.

**Comment by fate0521** [comment]
I'm experiencing this also, I'm on 3.20.10004

**Comment by marcelomoreli** [comment]
Same for me

**Comment by Irfy** [comment]
+1

Seems to be affecting many people, seen a lot of in-game reports about APT "not working".

**Comment by OneManOneClass** [comment]
Please try the solution to another problem posted [here](https://github.com/SnosMe/awakened-poe-trade/issues/818) and see if it works as a temp solution.
