### ISSUE TITLE
Incorrect pricing ratios

### ISSUE THREAD

**Issue by joestrach** [SnosMe/awakened-poe-trade#838]
This isn't 1/17th of a chaos, it's 17 chaos.

The individual value and the "You have" total value are both incorrect.

![PxohcgqVRA](https://user-images.githubusercontent.com/5495465/210446243-ba795f0b-4d80-4a05-924d-61aa2ea1a5cd.png)

![image](https://user-images.githubusercontent.com/5495465/210446428-a9d65e1a-5b12-4a56-8e91-e5b6bedfdb6e.png)

**Comment by SnosMe** [comment]
The prices at the bottom and on the top are from poe.ninja website. You can see on the graph huge drop in price. This can happen due to manipulation by players.
