### ISSUE TITLE
Invalid JSON error, unable to enter CAPTCHA

### ISSUE THREAD

**Issue by kysu1313** [SnosMe/awakened-poe-trade#839]
Hi, when I try to price check an item I get the following error:

Error code 1020

![image](https://user-images.githubusercontent.com/38538913/210466643-09da0f04-ad5f-4b0a-b463-765feb18b10f.png)

I tried restarting the app but still getting this issue. I last used it a few days ago when it worked.

Update,

after restarting the app again I see the following message:

![image](https://user-images.githubusercontent.com/38538913/210467230-184c37cb-e74e-4ba9-b228-9329ea1d3412.png)

When I click on "browser" to enter the captcha I see the following. (I didn't see it at first, the text is almost transparent.

![image](https://user-images.githubusercontent.com/38538913/210467119-5c062d39-0c8a-4fe2-a4dd-34d54805ff77.png)

I got an error when visiting www.pathofexile.com/api/leagues?type=main&realm=pc&compact=1.

Error code: 1020
Ray ID: 784020489ae4b0ed
Country: US
Data center: atl06
IP: removed
Timestamp: 2023-01-04 01:15:58 UTC

If you need more info please let me know, thanks! :)

**Comment by aerickson1337** [comment]
updating to 3.20.10004 fixed it for me, maybe give that a try if you haven't: https://github.com/SnosMe/awakened-poe-trade/releases/tag/v3.20.10004

**Comment by kysu1313** [comment]
I thought I was fully up to date but I guess not, that fixed it, thanks!
