### ISSUE TITLE
[solved] error 1020

### ISSUE THREAD

**Issue by gtoilet** [SnosMe/awakened-poe-trade#840]
all of a sudden i get this has been working fine for days of spam searching items
anyone with a quick link to fix or lmk help thanks

**Comment by ghostcodekc** [comment]
I'm getting the 1020 error as well. I am NOT getting the error when visiting the link that @Diabolos posted.

**Comment by ghostcodekc** [comment]
> 

Ope. I misunderstood, my fault!

**Comment by gtoilet** [comment]
i never use the browser version as it usually forgets me and wants me to relog OFTEN
i mainly use it to link my search reqs to the main trade so i can PC items

**Comment by Wisain** [comment]
Getting the same error as well, basically saying the owner has denied me permission then the 1020 error code

**Comment by TEXTTURE** [comment]
also getting an error 1020

**Comment by gtoilet** [comment]
sad to say i find it hard to want to trade when i cant pc items lol
i wont go back to lookin up items on trade to price them

**Comment by SnosMe** [comment]
Older version of the app is blocked by GGG, you need to update the app.
You probably have some v3.19.*** version, they were not auto-updating due to a bug.

**Comment by gtoilet** [comment]
so weird tho it was JUST workin earlier today

**Comment by Diabolos** [comment]
> Older version of the app is blocked by GGG, you need to update the app. You probably have some v3.19.*** version, they were not auto-updating due to a bug.

I see now, yea i had 3.18.10004 
![image](https://user-images.githubusercontent.com/3803306/210561008-a500e77f-2794-464e-bd7a-43906ae23035.png)

Thanks @SnosMe !

**Comment by MansourM** [comment]
Same problem here
![poe0e](https://user-images.githubusercontent.com/22474418/230510728-2dbdf50c-051e-4d7c-98b1-f4916c7c44bd.png)
I'm on win11, using a VPN (vpn works fine)

**Comment by SnosMe** [comment]
Leagues have loaded successfuly in browser, the Retry button should work

**Comment by MansourM** [comment]
> Leagues have loaded successfuly in browser, the Retry button should work

but, it doesn't ;(, im not sure what to do, tried uninstalling, using setup and protable versions

**Comment by Feilzz** [comment]
Same problem, error 1020 blocked by cloudflare. I am using Version 3.21.10001, retry doesn't work, I can access the poe site just fine on any other browser.

**Comment by ashoklathwal** [comment]
Check for detailed understanding and fixes: https://wealthquint.com/fix-awakened-poe-trade-error-code-1020-access-denied-60388/

**Comment by matin0802** [comment]
> Same problem here ![poe0e](https://user-images.githubusercontent.com/22474418/230510728-2dbdf50c-051e-4d7c-98b1-f4916c7c44bd.png) I'm on win11, using a VPN (vpn works fine) using v3.20.10007

Have you found a solotion for this problem?

**Comment by Aphotic** [comment]
> > Same problem here ![poe0e](https://user-images.githubusercontent.com/22474418/230510728-2dbdf50c-051e-4d7c-98b1-f4916c7c44bd.png) I'm on win11, using a VPN (vpn works fine) using v3.20.10007
> 
> Have you found a solotion for this problem?

#1278 This is the same issue i posted from people of my country :}
