### ISSUE TITLE
Can't Add Cheat Sheet

### ISSUE THREAD

**Issue by rubenkruger** [SnosMe/awakened-poe-trade#841]
I'm having trouble adding a new cheat sheet.

I click cheat sheet / Edit / and add the new sheet 
Then nothing happens.

File format is PNG

The same thing happens with the Image strip.

Any help would be appreciated.

**Comment by wlsnbilyb** [comment]
Did you find a solution to this? Having the same issue, I upload the image in the edit widget menu and when I tab back into the game nothing happens.

**Comment by SnosMe** [comment]
https://github.com/SnosMe/awakened-poe-trade/discussions/867#discussioncomment-4740284
