### ISSUE TITLE
Awakened PoE Trade quit unexpectedly

### ISSUE THREAD

**Issue by 13RedFox** [SnosMe/awakened-poe-trade#842]
I updated the program to the latest version 3.20.10005, I ran into a problem that I can not open the program. Although I tried as they wrote on the forum about access, try to switch the input back and forth. Still a pop-up window appears that the program cannot be opened. What could be causing the conflict? Although I granted access to the program (Privacy & Security).

![Screenshot 2023-01-04 at 12 57 40](https://user-images.githubusercontent.com/31631365/210542215-0ebfb820-d137-4efc-a529-16e2ff535257.png)

**Comment by SnosMe** [comment]
@hsource
