### ISSUE TITLE
Update "It will be installed automatically on exit" not userfriendly

### ISSUE THREAD

**Issue by MaxKruse** [SnosMe/awakened-poe-trade#846]
Hello, here my usecase:

1. Boot up PC
2. Either have APT on auto-start, or manually start it
3. In case of an update, it auto-downloads, but waits for an "Exit" context menu to install <- this is where the issue is
4. I Shutdown my PC. The update doesnt gets never applied.

In short, having to boot up APT, just to manually exit it to apply an update seems rather convoluted and not thought out. I accidentally keep going with age old versions at times because my normal work flow doesnt involve manually closing an app that can just as well run in the background without issues.

I suggest a different mechanism to update, either directly on Download, through the overlay it provides, or a hotkey.

**Comment by SnosMe** [comment]
There was a bug that disabled auto-updates for half last year.
You normally see a notification about update available when doing price check

![image](https://user-images.githubusercontent.com/4292308/211041469-d9c3e8c2-fd19-457f-8b19-69170e0c8bc3.png)
