### ISSUE TITLE
Controller bindings for price check

### ISSUE THREAD

**Issue by slvrtrn** [SnosMe/awakened-poe-trade#849]
I wonder if it's even theoretically possible to implement the Xbox controller support for bindings.

As I play on a PC using a controller almost exclusively, one of the few things that I use the keyboard for is the price check feature. 

Implementing the possibility to bind the price check to a controller will improve the user experience a lot. 

Cheers.

**Comment by SnosMe** [comment]
I don't know an easy way to do this.

https://www.electronjs.org/docs/latest/api/global-shortcut
