### ISSUE TITLE
With all these new mods the mods/collapse button goes outside of the screen (lower resolution).

### ISSUE THREAD

**Issue by leet0rz** [SnosMe/awakened-poe-trade#852]
Please let us ctrl -/+ to zoom the window and make it smaller, as of now sometimes when we pricecheck items the window is so full of mods you cant even open  it in the browser or collapse the tab. Allowing us to [ctrl][-] to make the window smaller like lets say skype allows would make it easier to price check some items that can't really be checked right now.

**Comment by SnosMe** [comment]
1. You can click on "Stats" button, it also collapses list 
![image](https://user-images.githubusercontent.com/4292308/211016852-20792eae-a72a-436e-9add-d72020ccbae3.png)

2. You can change font size in settings

![image](https://user-images.githubusercontent.com/4292308/211016918-6e1a00bd-7eca-45dd-8661-85a4466ee98a.png)
