### ISSUE TITLE
Price checks are reversed. i.e. it shows 18/1 chaos/bulk but prices it 1/18 chaos.

### ISSUE THREAD

**Issue by Tadiian** [SnosMe/awakened-poe-trade#858]
Some of the price checks are wrong, you could say they are [reversed?[](url)](url)
![cfec575a-7aa9-4cc3-91c8-d4ed59e3b1c7](https://user-images.githubusercontent.com/51496946/211151444-a72f2e0d-83b5-42c6-98db-918927648906.png)
It's not only on crescent splinter it's also one other currency/fragments. That where it happens most afaik.

**Comment by SnosMe** [comment]
Source of prices is poe.ninja.
You even gave screenshot where it says -99% price drop, for 1c you get 10 catalysts.
