### ISSUE TITLE
Search window bug

### ISSUE THREAD

**Issue by Draw99Gray** [SnosMe/awakened-poe-trade#86]
when you search an item with Ctrl+Alt+D, you need to close the window from the task bar or else all other searches on different items will repeat the one made originally
lets say i search a shavronne with C+A+D, exit from the small red x square in the top right, search screen goes off 
If i decide to search another item with Ctrl+D, it will always repeat the shavronne one
Fix this pls

**Comment by SnosMe** [comment]
Sorry but I can not reproduce your bug. Consider recording a video, also I want to know your OS. Make sure you are using the latest version. For now, I can advise you try to toggle "Hardware Acceleration" On/Off
![image](https://user-images.githubusercontent.com/4292308/80593858-96b62380-8a2a-11ea-9417-0a869aef8f78.png)

**Comment by Draw99Gray** [comment]
It seems it was the hardware acceleration, i had it enabled
Disabled it and it got fixed
I'm using W7
