### ISSUE TITLE
syndicate Widget update to 3.20

### ISSUE THREAD

**Issue by Moubai** [SnosMe/awakened-poe-trade#863]
Hello, is it possible to update the image of syndicate in the widget with new version ?
https://www.reddit.com/r/pathofexile/comments/znc47k/320_updated_betrayal_cheatsheet/

**Comment by SnosMe** [comment]
You can do this without waiting for me by editing that widget.

**Comment by Moubai** [comment]
yes i know, already did it on my side, it's just for all other people, maybe they don't know they can do it

**Comment by EldritchEevee** [comment]
Any update to the app would overwrite it.
