### ISSUE TITLE
[Bitdefender AV] false positive alert for temporary file at startup

### ISSUE THREAD

**Issue by benjaminhenne** [SnosMe/awakened-poe-trade#87]
As of today my antivirus shows this warning when starting the application:
![image](https://user-images.githubusercontent.com/13474968/80595640-6029da00-8a25-11ea-9fc2-2fa09904e52a.png)
Updating to the 1.1.0 release did not fix the issue. It does not appear to be related to the executable but to temporary information downloaded during startup.

**Comment by pawelmalza** [comment]
Same here. Using Bitdefender.

**Comment by SnosMe** [comment]
@benjaminhenne can you apload this file to virustotal and share link here

**Comment by benjaminhenne** [comment]
@SnosMe There's the link: https://www.virustotal.com/gui/file/d9cf459b75c5246219b60fec8398bf5abaf63904124adb6c2ed0c6408cb80dcd/detection

**Comment by SnosMe** [comment]
From VT report I see that was caused by robotjs lib. robotjs is important lib since it sends Ctrl+C key presses to the game.

Also, I triggered file reanalyze, Bitdefender no longer reports this file as malicious, so I think it is no longer problem.
