### ISSUE TITLE
App not working

### ISSUE THREAD

**Issue by Tricslip** [SnosMe/awakened-poe-trade#870]
Whenever I try to use it to price check anything it says, "An error occurred while parsing the item."
It says that every time without fail. I have updated it, reinstalled it, ran it as admin and nothing has worked.

**Comment by SnosMe** [comment]
Screenshot please

**Comment by Tricslip** [comment]
It doesn't allow me bc if the overlay

**Comment by SnosMe** [comment]
printscreen button exists

**Comment by prblylakeman** [comment]
This is happening for me currently @SnosMe 

Details:

User is unable to use manual price check

Repro:

- Sync to Awakened Trade 3.20.10006
- Launch PoE and progress through Character Select
- Open the Overlay (default SHIFT + SPACE)
- In the manual price check string field, begin typing

Observed:
- After typing a single letter, the field will auto progress to display an error and disable any further entry: "An error occurred while parsing the item"

Expected:
- Users to be able to enter string without error

![image](https://user-images.githubusercontent.com/114590329/214402255-b5aabed2-767c-4198-a504-858ff02803db.png)

**Comment by SnosMe** [comment]
@prblylakeman

![image](https://user-images.githubusercontent.com/4292308/214405687-d0501834-ff18-41a8-86d3-fd3d0972eaea.png)

It specifically says Ctrl+V, and expects that you have full item text in clipboard.
This is not a search by item name, like on trade/poe.ninja.
