### ISSUE TITLE
I can't check the price of the item

### ISSUE THREAD

**Issue by FlexAirZ** [SnosMe/awakened-poe-trade#871]
when pressing ctrl+d nothing happens
It gives an error in the logs
error [GameConfig] Failed to read game config
![изображение_2023-01-15_102252026](https://user-images.githubusercontent.com/122710864/212521349-92d09caa-6db8-403d-a46c-43b8911ecbaf.png)
uration file.

**Comment by SnosMe** [comment]
https://snosme.github.io/awakened-poe-trade/nothing-happens
