### ISSUE TITLE
Config File Corruption

### ISSUE THREAD

**Issue by Cornyboob** [SnosMe/awakened-poe-trade#872]
Every other time I try to open the program I get a error message that says I am using a newer config file with an older application which is simply not true.

I have to reinstall from installer to fix and that fixes every time for a few uses then error comes back.

I have no more details sorry. Has happened 5 times to me today alone. I often shut down laptop to do other things then come back to play a little.

**Comment by Cornyboob** [comment]
V 3.20.1006 hope that's right its current version.

**Comment by SnosMe** [comment]
3.20.1006 doesn't even have this message anymore, you're clearly having two files/shortcuts to different versions.
