### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by dcbawden** [SnosMe/awakened-poe-trade#878]
Would love the option to force price checks to Chaos Orb only.

**Comment by SnosMe** [comment]
Can you write explanation why

**Comment by dcbawden** [comment]
When price checking charged compasses there are a lot of listings with price set for awakened sextants. It is difficult to tell what the actual price in chaos is.



    On Saturday, January 21, 2023 at 11:22:22 PM PST, Alexander Drozdov ***@***.***> wrote:  
 
 


Can you write explanation why

**Comment by dcbawden** [comment]
![image](https://user-images.githubusercontent.com/17535802/213906550-942c014a-e64a-41a0-b0a1-2da098d92ded.png)

**Comment by SnosMe** [comment]
This is already possible, put a mouse over "Online" and select Chaos orbs there.
It will stay in Chaos orbs as long as you keep price checking compasses only.
