### ISSUE TITLE
some mods are ignored for unique items when price checking

### ISSUE THREAD

**Issue by rezk2ll** [SnosMe/awakened-poe-trade#88]
unique wand:

![image](https://user-images.githubusercontent.com/6764881/80726174-f7f9f780-8afb-11ea-8de3-1af053ab32f4.png)

when price checking you get a 1c wand because of the max roll attack speed being ignored

![image](https://user-images.githubusercontent.com/6764881/80726007-c4b76880-8afb-11ea-8b71-b0c22d0531b3.png)
![image](https://user-images.githubusercontent.com/6764881/80726324-28419600-8afc-11ea-8d8b-b98a4890c470.png)

manual checking:

![image](https://user-images.githubusercontent.com/6764881/80726404-40191a00-8afc-11ea-958c-829782396ff1.png)

**Comment by SnosMe** [comment]
@rezk2ll Attack speed mod is in "hidden" section. I'll change that in next release.

**Comment by SnosMe** [comment]
Done in v1.2.0
