### ISSUE TITLE
[Request] Information when searching Uniques to indicate extra value if you hit useful Vaal Corruptions

### ISSUE THREAD

**Issue by SirDMZ** [SnosMe/awakened-poe-trade#886]
Hey, not sure how feasible this is.

Some unique items become valuable if and only if they receive the right corruption.
Having this information available would encourage more players to gamble away useless unique items with Vaal orbs in hopes of hitting gold.
It would also help lower the price of said golden targets.

Example, Crown of the Inward Eye. 21% goes for about 70c, but if they see there's a % chance of corrupting it and selling it for 16div. Some people are going to take that shot.

**Comment by SnosMe** [comment]
I can do something, but first someone on Reddit should post data about such uniques. Like for example they got all builds on ladder with corrupted uniques and created excel. Obviously there should be a way to auto update this information each league, otherwise I'm just wasting player's orbs.
