### ISSUE TITLE
Pricing bug

### ISSUE THREAD

**Issue by elskydev** [SnosMe/awakened-poe-trade#89]
```
Rarity: Rare
Ghoul Etcher
Runic Hatchet
--------
One Handed Axe
Physical Damage: 44-79
Elemental Damage: 3-40 (augmented)
Critical Strike Chance: 5.00%
Attacks per Second: 1.35
Weapon Range: 11
--------
Requirements:
Level: 71
Str: 163
Dex: 82
--------
Sockets: G-R B 
--------
Item Level: 83
--------
12% increased Global Physical Damage (implicit)
--------
Adds 3 to 40 Lightning Damage
14% reduced Enemy Stun Threshold
+23% to Cold Resistance
55% increased Lightning Damage (crafted)
10% chance to Shock (crafted)
```

[https://i.imgur.com/luX59lY.png](https://i.imgur.com/luX59lY.png)

**Comment by SnosMe** [comment]
So where is the bug? Please describe it.

**Comment by elskydev** [comment]
> So where is the bug? Please describe it.

Please see attached printscreen, calculation is wrong (overpriced), poeprices shows correct calculation - around 10c.

**Comment by SnosMe** [comment]
This info comes from poprices.info. If you think it is overpriced press appropriate feedback button to improve their pricing algorithm.

![image](https://user-images.githubusercontent.com/4292308/80808148-9010e300-8bc7-11ea-987d-10da1fd75c95.png)

However you don't have this button, because you are using the old version of app.

**Comment by elskydev** [comment]
As I said before, I have checked with poeprices and the price was correct on the website, item was overpriced only on app. Anyway, thank you for your time.

**Comment by SnosMe** [comment]
![image](https://user-images.githubusercontent.com/4292308/80809260-fac31e00-8bc9-11ea-9317-98516719b0ed.png)

"Machine Learning Prediction" is what app getting from poeprices.info

While "Recommended Price" is site exclusive feature.

As you can see it is the same 1.2-1.8 exa on site.

**Comment by elskydev** [comment]
I do regret I have sold that item, I can totally understand your point, and what is recommended price, but poeprice did accurate pricing - if I remember correctly it was between 12 and 18c. Good luck with app, for me it is the best from the market and please remove this issue.
