### ISSUE TITLE
No longer showing the price of Awakened Sextant modifiers on Voidstone.

### ISSUE THREAD

**Issue by TehnoiD** [SnosMe/awakened-poe-trade#892]
No longer showing the price of Awakened Sextant modifiers on Voidstone. Shows a blank display.
Screenshot - https://prnt.sc/zSlNXJxHOLDp

**Comment by anatonokao** [comment]
+1

**Comment by SnosMe** [comment]
GGG finally translated that one string to Russian, so need to update it in the app too.

**Comment by SnosMe** [comment]
Fixed
