### ISSUE TITLE
Price error on replica/gem tool

### ISSUE THREAD

**Issue by sualehumer** [SnosMe/awakened-poe-trade#894]
Divergent Controlled destruction price mentioned 12div when checking with replica/gem tool.. actually worth 20c
![Screenshot 2023-02-22 190345](https://user-images.githubusercontent.com/112756687/220643303-99a3da29-8877-4665-b7a0-958de4829670.png)

**Comment by SnosMe** [comment]
poe.ninja has wrong prices sometimes, I can't do anything about it :(
