### ISSUE TITLE
Mismatch server

### ISSUE THREAD

**Issue by samos667** [SnosMe/awakened-poe-trade#902]
Since today, Awakened can't correctly identify the server I'm connected to. Yesterday, when I was still on sanctum, I didn't have this problem. But today on standard Awakened thinks me on ruthless.

Screenshot from my character on standard:
![image](https://user-images.githubusercontent.com/50653464/230129755-9c65ce7b-856e-48d4-b000-de1836ba88e9.png)

Also, when I click on trade, he redirects me to ruthless market:
![image](https://user-images.githubusercontent.com/50653464/230130059-e8649a3e-193a-4da9-9533-d30b244f7a9b.png)

Can I manually specify the server somewhere ?

**Comment by samos667** [comment]
Note: my perso was on sanctum before the migration

**Comment by SnosMe** [comment]
It should have changed from Sanctum to Standard automatically.
But because of new Ruthless leagues this doesn't work anymore, will fix ty
