### ISSUE TITLE
Not able to use any features.

### ISSUE THREAD

**Issue by Motr27** [SnosMe/awakened-poe-trade#903]
After installing APT, when I launch my game absolutely nothing happens. There's no overlay, none of the hotkeys work, and not even the hideout macro hotkey f5 does anything. I've tried updating my drivers, reinstalling APT multiple times, and everything else I can think of with no success. I'm running the game in windowed fullscreen but I've tried in windowed with the same result. I'm also not using a VPN. When I check the logs this is what I see: 
![image](https://user-images.githubusercontent.com/130122484/230536687-97e0409a-04fb-4640-b495-83a8eb0c01df.png)

Note the logs.txt file was last edited in 2021, not sure if that's normal or another sign that the program isn't working. Let me know if there's anything else I can try, I can't see what could be causing this.

**Comment by SnosMe** [comment]
Do you even see icon in the tray, multiple processes in task manager?

**Comment by Motr27** [comment]
Yes to both:

![image](https://user-images.githubusercontent.com/130122484/230599859-ea105077-8a53-42a6-87ab-f81550f65ed0.png)

![image](https://user-images.githubusercontent.com/130122484/230600027-cd2099e3-a69c-495e-a041-e55bc271d80a.png)

**Comment by Matteyes** [comment]
I also encountered this problem,there's no icon in the tray

**Comment by SnosMe** [comment]
Do you have the latest version? 

If it starts working in the game after opening in the browser, you should download fixed version.
![image](https://user-images.githubusercontent.com/4292308/230632588-c93444b0-0602-46e8-bfa2-46af310b8f78.png)

**Comment by Motr27** [comment]
I do have the lastest version, I just updated and seem to have the same issue. I may have identified the problem though. When I right click the icon in the tray and click "Open in Browser", it opens a webpage with nothing on the screen and this address: 

![image](https://user-images.githubusercontent.com/130122484/230659298-0f117f69-72fd-48af-97b8-b160ec8d8d34.png)

Is this what's supposed to happen? If not how do I fix it? I just tried to allow APT through my firewall but my firewall doesn't seem to even recognize it as an app.

**Comment by SnosMe** [comment]
> opens a webpage with nothing

Nope, what errors do you see in Console F12

**Comment by Motr27** [comment]
These 4 errors: 
![image](https://user-images.githubusercontent.com/130122484/230663792-451b7b54-c1be-4f12-a39c-8d79bb8cddf9.png)

And also 1 "Issue" whatever that means: 
![image](https://user-images.githubusercontent.com/130122484/230663880-dadb5a73-f67b-4b80-9168-2fe858113bc1.png)

**Comment by SnosMe** [comment]
Just noticed config is from 2021, delete it and restart.

**Comment by Motr27** [comment]
Thanks so much! That fixed it, must have been from when I last played poe a couple of years ago, and for some reason persisted on reinstall. Enjoy the league.

**Comment by Rafael-F-Amaral** [comment]
> Acabei de notar que a configuração é de 2021, exclua-a e reinicie.

I don't understand, how to fix this problem? I'm facing the same problem

**Comment by davemo88** [comment]
Open the directory containing your conf.json file and delete it. You can find the directory by right clicking on the app in the taskbar @Rafael-F-Amaral
