### ISSUE TITLE
Error after update (kernel32.dll)

### ISSUE THREAD

**Issue by Simgond** [SnosMe/awakened-poe-trade#904]
win7x64
after 3.21 league update throw error on launch app
Точка входа в процедуру DiscardVirtualMemory не найдена в библиотеке DLL KERNEL32.DLL.
[https://prnt.sc/gxLqsU_oziMR](url)

P.S. Before update app worked perfectly

**Comment by SnosMe** [comment]
Windows 7 is no longer supported
https://www.electronjs.org/blog/windows-7-to-8-1-deprecation-notice

You can download portable version [Awakened-PoE-Trade-3.20.10007.exe](https://github.com/SnosMe/awakened-poe-trade/releases/download/v3.20.10007/Awakened-PoE-Trade-3.20.10007.exe)
but as time passes, you will get more and more unrecognized stats on items when using this outdated version

**Comment by Tallion99** [comment]
similar error on windows 8.1 too.

**Comment by Smake** [comment]
I rebuilt it with an old version of electron for my friend, and it works for him.
https://github.com/Smake/awakened-poe-trade/releases/tag/Latest

**Comment by ealmen** [comment]
If anyone still needs this and found this old issue via Google etc.
I have a Win7 repo with 6 working releases so far, with plans to continue for the next year most likely.
I'm using electron 22.x.x for Win7 compatibility, and I've hopefully got auto-update working as of today's release.

https://github.com/ealmen/awakened-poe-trade-win7/releases

**Comment by SnosMe** [comment]
idk what you guys doing with your life to not upgrade to win10, but Steam stops running on win7 too

**Comment by ealmen** [comment]
I hope the above comment wasn’t seen as a dick move, trying to "steal" users away from you.
I’m new to GitHub, so genuinely not sure how this is seen. I thought it was mostly fine, but also seeing some annoyance there?
Let me know and I’ll delete either comment and/or fork.

And in case you want an actual answer as to why some people stick with old OS for long.
I have a complex time-consuming setup, with custom hardware/drivers, and a bunch of custom services running. I've been changing OS only with new hardware once every 8-10 years.
Win 10 wasn’t out last time I switched, and Win 8/8.1 didn’t look like a good long-term OS at that time. Poor timing, Win10 would have been a good choice.
Win12 is coming this year if rumors are to be believed. AMD Zen5 and new wave of GPU’s this spring/summer. This summer looks like a good time to buy a new computer. And I'm looking in to VMs or multiple physical machines until then as a better way to not have to switch everything at once.
Living with Win7 a while longer is looking like my least bad option currently. And for what I'm doing, this tool not working was honestly my biggest issue, so a quick fix looked better than a long term fix.

**Comment by SnosMe** [comment]
I'm completly fine with you publishing win7 builds.
But as a developer I see that win10 offers a lot of new features. Under all marketing fluff and ui redesign, underneath kernel is still improving, new features, interesting Win32 APIs being added. The same I can say about win11.
I hope win12 gonna be more polished and you migrate to it, good luck :)
