### ISSUE TITLE
Смэрть

### ISSUE THREAD

**Issue by incone53** [SnosMe/awakened-poe-trade#907]
После ласт апдейта, запустилась на 30 секунд и теперь вечная ошибка. Переустановка не помогает. 
![Безымянный](https://user-images.githubusercontent.com/130221170/230717287-8c0e9b47-de4b-484f-98b1-9121622021be.png)

**Comment by SnosMe** [comment]
Duplicate of #904

**Comment by Smake** [comment]
Попробуй [это ](https://github.com/SnosMe/awakened-poe-trade/issues/904#issuecomment-1501137181)
