### ISSUE TITLE
Pricing screen disappears

### ISSUE THREAD

**Issue by LordStorm7** [SnosMe/awakened-poe-trade#909]
When I click "Control D" on an item the price comes up, but as soon as I move my mouse it disappears so I can't select any specific mods? How do you get the price summary to stay on the screen?

**Comment by SnosMe** [comment]
This page explains it https://snosme.github.io/awakened-poe-trade/quick-start

**Comment by tdemarest** [comment]
I think something else has changed in Windows 11. Despite hold down control, as soon as I move the mose to select mods the entire game window minimizes to the desktop. As soon as I move the mouse after this happens, the game raises again.

**Comment by SnosMe** [comment]
@tdemarest 
Your game is running in fullscreen while the tool requires it to be Windowed Fullscreen

**Comment by tdemarest** [comment]
Ah - thank you! I should have checked that first. I have no idea when it got set to from windowed+fullscreen to just fullscreen.
