### ISSUE TITLE
Unexcepted Token '<', <!DOCTYPE" .... is not valid JSON

### ISSUE THREAD

**Issue by davidmelumian** [SnosMe/awakened-poe-trade#914]
Привет. В гитхаб профиле у тебя указано, что ты из Украины как и я. По-этому описываю проблему не на английском. 
Прежде всего спасибо за это приложение, оно очень полезно, но я постоянно сталкиваюсь с ошибкой, которая раздражает. Хочу выяснить в чем проблема. Играю через Steam. После захода в игру и попытке чекнуть прайс, вылезает диалоговое окно, где жалуется на капчу (смотри скрин)
<details><summary>Details</summary>
<p>

![старт](https://user-images.githubusercontent.com/110660428/230730442-ec630977-daa8-4f16-88a4-cd846a57ace8.JPG)

</p>
</details> 
После нажатии кнопки "Браузер", открывается офф.сайт пое, на котором проверяется соединение на безопасность. После этого при нажатии кнопки "Повторить" все работает. Спустя 5-10 мин, при попытке прайсчекнуть предмет,  появляется ошибка  как на скрине.
<details><summary>Details</summary>
<p>

![Capture](https://user-images.githubusercontent.com/110660428/230731120-276d56bc-d2e9-4a82-88bf-801402d5c705.JPG)

</p>
</details> 

далее при нажатии кнопки "Браузер", появляется снова окно, которое проверяет соединение на безопасность, а далее просит авторизоваться. 
<details><summary>Details</summary>
<p>

![проверка](https://user-images.githubusercontent.com/110660428/230731400-6e81314f-e882-4e56-8419-8661d7b51913.png)
![авторизация](https://user-images.githubusercontent.com/110660428/230731395-982a890a-1d41-44ff-bf14-f16b13770b9f.png)

</p>
</details> 
 Если пройти проверку безопасности, дойти до страницы авторизации, а далее закрыть браузер и снова совершить прайс-чек, то снова все работает.Спустя 5-10 мин, опять та же проблема. Бесконечный цикл. Вопрос: в чем проблема и можно ли как то это исправить?  Не использую прокси/впн.

 Мои мнение насчет ошибки: Я прохожу проверку на безопасное соединение, далее имею доступ определенное время, а после сервер снова просит совершить проверку на безопасность из-за чего и триггерит эту ошибку.

**Comment by SnosMe** [comment]
> Если пройти проверку безопасности, дойти до страницы авторизации, а далее закрыть браузер и снова совершить прайс-чек

Да, так и должно быть. GGG включили агрессивную защиту от ботов в cloudflare

> Спустя 5-10 мин, опять та же проблема

По этой же причине это и происходит, это нормально.
Ну разве что можете писать молебные письма GGG
