### ISSUE TITLE
ML prediction error. Report to poeprices forum thread.

### ISSUE THREAD

**Issue by Simrien** [SnosMe/awakened-poe-trade#92]
Getting the above error when pricing rares.
Tested https://www.poeprices.info/ manually with a copy/paste of the item data.
To be fair this looks like an issue at poeprices.info.

![ml prediction error](https://user-images.githubusercontent.com/61622337/80974608-dad56980-8e18-11ea-8d33-8bd55818b681.JPG)
![ml prediction error 2](https://user-images.githubusercontent.com/61622337/80974612-dd37c380-8e18-11ea-8958-79e95f0a8df2.JPG)
![ml prediction error 3](https://user-images.githubusercontent.com/61622337/80974624-e032b400-8e18-11ea-92e7-645a28ac8a2e.JPG)

**Comment by SnosMe** [comment]
![image](https://user-images.githubusercontent.com/4292308/80974845-fac15900-8e29-11ea-94a7-610dd252419d.png)

Indeed, looks like this. Report it here http://www.pathofexile.com/forum/view-thread/1216141 with Ctrl+C item data
