### ISSUE TITLE
Notifications.

### ISSUE THREAD

**Issue by itsxScrubz** [SnosMe/awakened-poe-trade#920]
Linux: Ubuntu 22.10

Whenever tabbing back into poe, it almost always shows the "Awakened PoE Trade is ready" notification.

I'm honestly not sure if this is intended to be the case or not, but I never had the issue on windows 2 seasons ago using this.

**Comment by SnosMe** [comment]
Not sure why it would do it, but you can disable this notification in the settings

**Comment by itsxScrubz** [comment]
I have that disabled. It's hit and miss with it. Sometimes I can just close it down and start it back up for the second time, and it stops with the notifications, but after taking this video it took me 4 trys to get it to stop. 

I should have included a video of it from the start with more information. That's my bad.

https://streamable.com/x44a1v

**Comment by SnosMe** [comment]
Oh, that one... from the GNOME. I have no control of it.

**Comment by itsxScrubz** [comment]
Yeah I'm swapping out to arch here soon. Just wanted to pass it along incase you didn't know about it.

Love the app tho <3

**Comment by BaiRado** [comment]
I'm having the same issue on Ubuntu 22.04. What I found is that when it bugs out either the OS sidebars show up or you cant use your keyboard at all in PoE. If you manage to get it to focus back on the game then the tool stops working for some reason. Also if you swipe through the gnome notification to remove it, it also stops the tool from working.

**Comment by itsxScrubz** [comment]
@SnosMe and esp @BaiRado 

I'm gonna close this issue.

Fixed via the following extension for gnome.
https://extensions.gnome.org/extension/1007/window-is-ready-notification-remover/
