### ISSUE TITLE
entry point not found

### ISSUE THREAD

**Issue by dustondan** [SnosMe/awakened-poe-trade#924]
The procedure entry point DiscardVirtualMemory could nto be located in the dynamic link library KERNEL32.dll

windows 7

**Comment by gambitflash123** [comment]
I am getting the same error on Windows 8.1, it was working for many leagues without issue.But last night after autoupdating it keeps giving me Entry Point Error.

The procedure entry point DiscardVirtualMemory could not be located in the dynamic link library C:\Program Files\Awakened PoE Trade\Awakened PoE Trade.exe

Need help please

**Comment by SnosMe** [comment]
Duplicate of #904

**Comment by Smake** [comment]
Try [this](https://github.com/SnosMe/awakened-poe-trade/issues/904#issuecomment-1501137181)
