### ISSUE TITLE
Hotkey for Map Check & Item info binding together

### ISSUE THREAD

**Issue by Jstraws** [SnosMe/awakened-poe-trade#929]
When I try to set the hotkey for checking a map it also sets the hotkey for item info. I have tried setting one and deleting the other, but it seems like they're both intertwined somehow. Running on version 3.21.10001

**Comment by DygDyg** [comment]
The same problem, it is not possible to change the buttons individually, when trying to enter a key in one field, it is duplicated in the second

**Comment by SnosMe** [comment]
It's intended, there is no need to have them separate as functionality doesn't overlap.
