### ISSUE TITLE
Parsing Error - Ashcaller

### ISSUE THREAD

**Issue by khaganmv** [SnosMe/awakened-poe-trade#931]
![image](https://user-images.githubusercontent.com/70900585/230830988-389e9c97-38c1-4181-8bed-e90544292b22.png)

**Comment by EldritchEevee** [comment]
**Drop-disabled. Won't be added.**

**Comment by khaganmv** [comment]
Apologies, this issue seems to have been fixed by the latest release ([3.21.10001 - Crucible](https://github.com/SnosMe/awakened-poe-trade/releases/tag/v3.21.10001)).
