### ISSUE TITLE
Unable to get Seasons

### ISSUE THREAD

**Issue by Traveller-hongchen** [SnosMe/awakened-poe-trade#935]
Recently, such returns often occur when acquiring Seasons, and Seasons are not obtained

<!DOCTYPE html>
<html lang="en-US">
<head>
    <title>Just a moment...</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="robots" content="noindex,nofollow">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="/cdn-cgi/styles/challenges.css" rel="stylesheet">
    

</head>
<body class="no-js">
    <div class="main-wrapper" role="main">
    <div class="main-content">
        <noscript>
            <div id="challenge-error-title">
                <div class="h2">
                    <span class="icon-wrapper">
                        <div class="heading-icon warning-icon"></div>
                    </span>
                    <span id="challenge-error-text">
                        Enable JavaScript and cookies to continue
                    </span>
                </div>
            </div>
        </noscript>
        <div id="trk_jschal_js" style="display:none;background-image:url('/cdn-cgi/images/trace/managed/nojs/transparent.gif?ray=7b6055d119c8cec9')"></div>
        <form id="challenge-form" action="/api/leagues?type=main&amp;realm=pc&amp;__cf_chl_f_tk=cRu8qtvhr_iFJ5A2QZt9RC1IG4AyhHGsaLVCDuOJ6gE-1681185758-0-gaNycGzNDLs" method="POST" enctype="application/x-www-form-urlencoded">
            <input type="hidden" name="md" value="eHUuQEOvO0wWK.QoCDkufTfUqo8vEF7Gz5.ZgGo0i5g-1681185758-0-AX4botCz2XqJqbCPUsdNzKBqX8Zag8n1G0MQj0Iju5Wh7Cx7CUkoc5jp9SfVyPIyyIWOJ-ltQas3_XFKj5Ej1zA8_R9U3VQQ1zKxPKJUyPUWlhdwW23n8e_BOh_BrU0BPUboUZLa_XoY4enVVl_af1TmFTq4omE3I0krYuuZc5fXN8h5kXsd2c76tyRBfs59xrf79VVChrVO7Oi_Eeniomb65GOYxA0tllENiJhV6eVgXoS5KJFFlzLbnCz84fKHD2XyN-QKP2oeI_aBnGJNKS-6YhhW6vWH-jkRvG06fK2vjcZhIgruhzCzZ5M_-ZPhZjijKuF5Ny21fifGIyslUJbRT_zct_2Fq4BiwJtWn03gTxS5DruqNj-7fJrXoWhPXBOfhF_oiL-eazBlT4MtQPokpEci16yiEi5k_PWGWXqM5HGjus9f7-afs4z6-7Nj9AzMoO2i0vGMdGaiYlLQWvvlAOFHsVNw0r_hhKnhai2CINpC3glkfmF4r2I8we06Zr-hPDJTQA-emQL1hkGhsFLM8UeWzRZD1xP3FP99FvgssQ-dO6ykHGetgPz4EAmw93QZ20y07kB31pUs3Srnlcrfq22_KLiOAlJ8cLtjJgDYt_EpDdY7Vm_BOj9YuL6w3K4p8N9MVlm-q1VoBxNgu4iE2cBHNgB_ol3dycFz3AhvBAENoBU7tqx5jRJGptq06mZkNbLkB9OTde1A-fwsyi6bWkvrdzrxExnvtPA0-8bDNgEUenNEBEs9zkSzsfGA676HffWxJX404diJDD0UQh8SaUrKlcXp-RShec_RK4Xle24tm8SL28PQR4aXr9OGM9OE42XXSGiSYxVrqhKmNokdueQZ7C-gnSoZl1RFAvm8KEhSRFmcy5cmMRV44dzVOpGHd0yVqBkaRK62OauPZpWLtg_NCA5_7kmrkF1L5iWkVP6O9qZYU43WvRTvo2XWMkmHqMdBGX-Bu69jVsZFHaOS9ANRWnXJXkfQQR4vc5jbjK5e4W4C0aO0ne3VNAMkdbIL4kx7u8apOyTWG8qPYGJfdxEgNaJTyVAH_8_Nhczw-EZ6TCcdmeHyscJe-9ONfG29O9Dhzg-_bs6meGsoQClfPG89oQJGDQO5aUtVLXyMOTKscEUkncwhvB5GNC8sfJvboYNYcVcY2q61qIiGXCzTUmt6B5SneJS4rp0PvgBt3y-Oo0hnq_XgaxgQm8zdYX1k2L5UJ16uP8Oaj2iPafvI5pyN5aqhWEdnk5KaKKfd1KYJNZC24-07ilW4L2hOzVP87r1h52jAfiWbUDLbOVu1zlQjhSxxwtyP9l-VhhPP2-O-aqGXb64KILsA_hZaJAPBkuv_RO2lsYErx_JBMtGWLNiAcZdqZiROoffU00tK50kyZAvxanXjNJyx3VoHsX1lgcuzfXEK5zgDomhmASIkLxM-s9dm_-o2Vi9k4Pb_yMeiHnZK20Q6IpYwu9QO6qCxr3FsjdSKPG5Eat47pIMCtMWzXnWL0uEMCqgx0niWrbrdEuVCIuovsoHN_pYaA655qYn6EonAut-7IwXC0yP3uVm_dtA34z0aN_S9qUN5fgn_wNxDXKULHE_iI-IBG-DeYE3HOZRgVlc936xBKTyBEqXh4GEDbCS3IoXKst6nMtQgvwUovhnlvU81UrQIhtBygqC2rTE_32zuq5wbYJcj3utinSYkKn6d2gp9-eGkfBVKUlO6Kx-V8vqArAHWqIZgIOP_nNebG1t0Oatvu6vMP2i7qQt1EMpG47FzwuZZbETzhsojNFMOJ3O-AIILSaAoXjuZ498oJoXP9iNAQMipSila4MMU11P6MZ8aQJN8N9rCg6YZfjOjTHqGcJg_q-hrQp_4cAWyy9SU7V_GnPb0wdWnmPOcV_iYG4wrcb-KcIPOx28zMVN-B-_DBnub4wtKdQFuDevhF8poF-Boy57_lXOFOUxbB-F59K8QTG8CVk8DFWQ8JO_Zw4lgGDLwv2-gk9BXtrPfJNGqt1r0dXnB3gM0XfEO6mxi_CaKZjJAMAfdl52bpxpJCOe8mG1OVQ0jYGB3Zg4hvLbj7UvkKDaMvWE9-ooikykdB8XHnMVw1yCEaXRat-tfBDwwgPxROn_xQmbXmFDRR7Hm1JPtMv-s6BnByQuzmnLamEeF3PXbgH3Mtnni3_7XWBnVVFbvu80IZMaybbcd4shRxGb-wZzHF8SoMtBeq5u1JcfGGvRnyRZ771d5uVOzeiL9D5RJUj_tcn_pT_L8KeerlG6dcRJ2Cyd3Nbb0DRfwBvoA0vyZL-Ulz4qq5K744xy7_FYqYssuZYkPbE48TQs175nwmCTboBor5bb-UAOerEEe30h90Qn7goDcyoqgJzGFhLVPBsAgRJujhpxHUM_OMCeTbp8r_Zcb_kqGdFHS4SkBmJkcS4jG4XNlDBJU91XBlGGtNaUSfO8bIds28VrwMZoq8HYMG7KbxD5PCiHog7m1tm6XGglyg_UILCOjyUkIsLFqDD2vRJHMdIjqYSg0gEOcr5mi6HmRbT1Nj6u0bgfW7eq_bSMGpHq2_ZFlTxZsSh1aYtOhdZwoEwc5WJloOGnPjBNG1bCUf0s2uZOCBXP5zh8yFldMJtZBJ1MQfXiQSzIcyC4nCGFNJNsep4vMLPEkxCquPpZVn5x9c8xOJZbOlpAI__QUYB0AuIuI6fDzHYX_YLtkOaY0jUC8RH0Y7lfY07TuAOikiFZ7agA7f2mYfkS_KAbQ8xRZP56J89NKbAQ3js8r0L9sIz0aIXrxYOd8PJxkqejb-QhECfZfKzclQIwF2v67lgzM4o__GX4SV3j_pzAm27ujlqc2h9Oz0c-EwQ3wlh2Bhx6Uj9QLxeLcILwuCtzDsx6DnEXRzVR2x4y2KDrX0D3FEkV81k_Ax2cA2NbDc0DE9ejwQ00mdBXqt021UPq1ZT9TQv37aw0J9SBHhwvq8nQ6s2AwIphG4dKy8H3DbWgo1Y5FXqtG6qd6igFAUsjupTRpdNhc9qOBIczJqAEtxL0GSCej5L3qpleV61IsjMJ7KIm7GcWvFmmodbeko3pJ7EtOdLJVChw-WP5lXyfGzmrFjw-8ogxumYK_dpRkYXyOm_xsjv3u3DBtwmQCmk-GvX6LqZ20RwQsDLLL_qtORQjgricSYkQvD_MuUeioY_fYfLWvpo_lzn9MArA1xVu37NPr2RhZWaRZot3G6Q">
        </form>
    </div>
</div>
<script>
    (function(){
        window._cf_chl_opt={
            cvId: '2',
            cZone: 'www.pathofexile.com',
            cType: 'managed',
            cNounce: '43299',
            cRay: '7b6055d119c8cec9',
            cHash: 'f1dca7b1b08368c',
            cUPMDTk: "\/api\/leagues?type=main&realm=pc&__cf_chl_tk=cRu8qtvhr_iFJ5A2QZt9RC1IG4AyhHGsaLVCDuOJ6gE-1681185758-0-gaNycGzNDLs",
            cFPWv: 'b',
            cTTimeMs: '1000',
            cMTimeMs: '0',
            cTplV: 5,
            cTplB: 'cf',
            cK: "",
            cRq: {
                ru: 'aHR0cHM6Ly93d3cucGF0aG9mZXhpbGUuY29tL2FwaS9sZWFndWVzP3R5cGU9bWFpbiZyZWFsbT1wYw==',
                ra: 'TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgYXdha2VuZWQtcG9lLXRyYWRlLzMuMjEuMTAwMDEgQ2hyb21lLzExMi4wLjU2MTUuNDkgRWxlY3Ryb24vMjQuMC4wIFNhZmFyaS81MzcuMzY=',
                rm: 'R0VU',
                d: '7+qPVpG1xy4zImNBm7vZHbu/aFQKmPo1rtzOhKZBUgrPqospz6v8+qSGCBTiZrhIyAvbk+4L9xNeuM3Thl5V29aoPB9kcTywyu3Q+6KSHJusKIeci1P6G3A+U+Hf/stFIDfYG7V8K60OLwC/b/WNo3VxFO52nWNbt6CLco9px76Ox8FVKXv6mHUQrrHOX3/JBMNHFBTFBmVt7Ge6DmPM543UI95UR/knTZab2drMLWbIoWwxM469KePahda80JGm+UjGZ6ol1UhNNb/34Tsakl0RJKbk9DH0ETDoDRxR37C82G6rm9z648JUTP0JFdjBKtFFyqEtXR9qbYjjzHSNaQaV15N6L7tNCRFCTVxpiCoXeHjrLvX3shZ52blg4rOyC+Us6tKi/mpVCUCBlVUai4SqO1yUMBWxYUdWhuDrB0TiK5BDh9Dhkr8c9At83IYs/735YWcsAqP9xXlqmzhC61Gu5pQPS95NkQkUbTL6Iwpc7FEmG9/ybgog1aclUwNv6dps3VHb1eRS7nHUx/g5wua8fr7Ih4xfoaJ1Jiyh2JvCX3zWi55+ZYMXVvJvPozt',
                t: 'MTY4MTE4NTc1OC44OTcwMDA=',
                m: '73JxjhvOICKe/iQkvfaGbEBRkGSEMfg4JrEJF+FbDfY=',
                i1: '0fkXYZRhNBcxceBq1rOESg==',
                i2: '3JvcNslG97/8nTMrx7RaIg==',
                zh: 'QQ+lpboEqhGP3khoPw6p3Gs9nAQQkOTv/N0CKT6VSv0=',
                uh: 'yLJG/D+IBoxzyhc2kZxary/TbUEul7swXlTiOK9XliU=',
                hh: 'FSZhbK/t0tnPDIZtJhu6S3S4VAZv/ixDMUDC4lmYyWs=',
            }
        };
        var trkjs = document.createElement('img');
        trkjs.setAttribute('src', '/cdn-cgi/images/trace/managed/js/transparent.gif?ray=7b6055d119c8cec9');
        trkjs.setAttribute('alt', '');
        trkjs.setAttribute('style', 'display: none');
        document.body.appendChild(trkjs);
        var cpo = document.createElement('script');
        cpo.src = '/cdn-cgi/challenge-platform/h/b/orchestrate/managed/v1?ray=7b6055d119c8cec9';
        window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;
        window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;
        if (window.history && window.history.replaceState) {
            var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;
            history.replaceState(null, null, "\/api\/leagues?type=main&realm=pc&__cf_chl_rt_tk=cRu8qtvhr_iFJ5A2QZt9RC1IG4AyhHGsaLVCDuOJ6gE-1681185758-0-gaNycGzNDLs" + window._cf_chl_opt.cOgUHash);
            cpo.onload = function() {
                history.replaceState(null, null, ogU);
            };
        }
        document.getElementsByTagName('head')[0].appendChild(cpo);
    }());
</script>

</body>
</html>

**Comment by Traveller-hongchen** [comment]
The corresponding preview hint is

Enable JavaScript and cookies to continue

**Comment by SnosMe** [comment]
Not possible to fix, unless GGG decides to relax bot protection rules in cloudflare
