### ISSUE TITLE
Invalid request after update : Version 3.21.10001

### ISSUE THREAD

**Issue by Furiouss38** [SnosMe/awakened-poe-trade#949]
Hi,
I'm using AWK poetrade for years, updating frequently, I waited a bit for last update and I just did it, now I can't make a request anymore, 
I have "Trade site request failed
Error: Invalid query"
I'm in a private league "Chat SF (PL38806)" before the update (10min ago) it was working just fine with this league configured in the settings.
Right now it's not anymore (but for regular leagues, like Crucile, my app work)

**Comment by SnosMe** [comment]
You need to login in built-in browser. You will also need to click Browser button every app restart (but without the need of logging in again)
