### ISSUE TITLE
UNEXPECTED TOEKN < IN JSON AT POSITION 0

### ISSUE THREAD

**Issue by saraneth0o** [SnosMe/awakened-poe-trade#95]
Since the latest update this is happening for every single item. I have tried restarting both game and poe trade. Have also tried reinstalling poe trade. Please help.
![000125](https://user-images.githubusercontent.com/38872690/81254273-c4c8e280-907e-11ea-89a7-7a193d6ba7ea.jpg)

**Comment by SnosMe** [comment]
Do you even notice the text "POWERED BY POEPRICES.INFO" ? This means if site goes down, price prediction cannot be made.
