### ISSUE TITLE
Nvidia Geforce Now

### ISSUE THREAD

**Issue by talerzdebi** [SnosMe/awakened-poe-trade#954]
Hey, just checked to be sure. It doesn't work on nvidia geforce now  (It's gaming in cloud)
Very usefull for someone like me who dont have good pc to play and it helps alot.
But awakened doesn't work and makes it hard to play. Would it be possible to make it work? Thanks.

**Comment by r00t-z** [comment]
I dunno the current situation but it seems it would be easier to implement this tool now that gfn supports copying the content and pasting into the host, you don't need the steam trick anymore.

**Comment by SnosMe** [comment]
It supports only one way copy, so hideout shortcut can work, copying item text - no.
You can get the first one working by changing window title in the APT settings.

**Comment by r00t-z** [comment]
You are right, I though it was working for a moment... bummer.

Thanks.

**Comment by avatarisCSN** [comment]
Hi, i have that problem too,  i can still use awakend poe trade if i play poe in geforce now.
How i can do this?

**Comment by SnosMe** [comment]
@isaaclai92 you can try https://github.com/SnosMe/awakened-poe-trade/blob/466b654c0bd05a79973a8eeb36cdc8bf99c81bb2/main/src/server.ts#L109

**Comment by isaaclai92** [comment]
> @isaaclai92 you can try with 0.0.0.0
> 
> https://github.com/SnosMe/awakened-poe-trade/blob/466b654c0bd05a79973a8eeb36cdc8bf99c81bb2/main/src/server.ts#L109

I'm not tech-savvy in regards of programming language... I tried messing with the source code file and package it with Visual Studio Code but couldn't make it work.

I also tried something like ngrok, but the web app page is just blank when I access it through the forwarding address. Sadly I think it's out of my hands.
