### ISSUE TITLE
keyboard not working

### ISSUE THREAD

**Issue by JorySeverijnse** [SnosMe/awakened-poe-trade#956]
Hello, My keyboard stops working when in get the overlay so when pressing for example shift+space or ctrl+alt+d. This only happens for me when using wayland. On x11 i dont have any problem whatsoever. Im using the latest appimage: Awakened-PoE-Trade-3.21.10001.AppImage.

This is the message i get when starting the appimage from terminal:
load_input_helper [1827]: XkbGetKeyboard failed to locate a valid keyboard!

I heard that you can call the XkbGetMap() function instead of XkbGetKeyboard() and it should work fine?

**Comment by SnosMe** [comment]
The code in question is not mine (https://github.com/kwhat/libuiohook).
And even with that, it's not possible to make the app work on Wayland.

**Comment by JorySeverijnse** [comment]
ooh yeah i see thats sad especially because more and more people are switching from X11 to wayland because xorg isn't maintained anymore.
