### ISSUE TITLE
add option to force specific monitor

### ISSUE THREAD

**Issue by muzzol** [SnosMe/awakened-poe-trade#964]
this is a feature request to add an option to use the specified monitor on a multi-screen setup.

I'm on Linux and I'm having a lot of problems with monitor detection (position, black screen) and I see other people complaining about similar situations.
some solutions require external tools to move the overlay. I think the cleanest solution would be to add an option such as

    --use-monitor=X

and also an option on config file and GUI.

thanks for your time.

**Comment by SnosMe** [comment]
APT can be opened in a browser (from tray menu), and there is a [flag to disable the creation of an overlay window](https://snosme.github.io/awakened-poe-trade/cmd-flags.html). These features are useful on all platforms.
I'm not interested in creating the flag you suggested just to fix a mess called Linux Desktop, sorry.
