### ISSUE TITLE
Preview Trade Listing

### ISSUE THREAD

**Issue by Reithan** [SnosMe/awakened-poe-trade#98]
When viewing the search list of trades under an item lookup, it would be useful if we could easily hover or click a line item to view what that specific item is, so that we can compare listed items to the one we're looking for info on.

**Comment by SnosMe** [comment]
Out of app scope, use built-in browser to compare side by side.
![image](https://user-images.githubusercontent.com/4292308/86513373-5ef49f00-be12-11ea-91ad-54733309df0f.png)
