### ISSUE TITLE
Chose the browser?

### ISSUE THREAD

**Issue by exoticfoxz** [SnosMe/awakened-poe-trade#983]
Is there a way to select the browser?
Whenever I look for an item in the trade, Microsoft Edge opens automatically, is there any way to switch it to Chrome?

**Comment by Shawak** [comment]
Set chrome as your default browser

**Comment by exoticfoxz** [comment]
> Set chrome as your default browser

how?

**Comment by exoticfoxz** [comment]
> Set chrome as your default browser

thx very much
