### ISSUE TITLE
Allow toggles between price checking in Divines, in Chaos, and in "Chaos Orb Equivalent"

### ISSUE THREAD

**Issue by JekyllGamer** [SnosMe/awakened-poe-trade#994]
There is a very prevalent issue this league (3.21) with items being priced in awakened sextants, but the Price Check tool does not have a way to filter these listings out in the price check screen-you have to open it in browser and manually change the filter from "Chaos Orb Equivalent" to Divines or Chaos Orbs. 

I am proposing an addition that allows you to click a button in the price check overlay box to toggle between Divines/Chaos/Equivalent when needed to help prevent the overwhelming amount of pricefixing that is enabled by this poor trade etiquette.

**Comment by scottmudge** [comment]
You can hover over the "Online" label and change it:

![image](https://user-images.githubusercontent.com/19617165/236500747-e0bbc31a-cbff-419a-8054-ab7eafdd9c3d.png)

However, you have to manually do this for each price check.

It would be nice to change it to Chaos/Divine by default.

**Comment by JekyllGamer** [comment]
I agree being able to change it to default would be the ideal. However, I totally did not know this was a thing. Thanks for letting me know.

**Comment by SnosMe** [comment]
Added in 3.21.10002

![image](https://github.com/SnosMe/awakened-poe-trade/assets/4292308/2dd053e6-48a7-42e2-a6b3-582800190425)


![image](https://github.com/SnosMe/awakened-poe-trade/assets/4292308/0b2b829b-b864-467f-a8c7-8fa605891dc8)
